In [ ]:
# Install dependencies and connect Google Drive
# Install the latest Hugging Face libraries
!pip install -q transformers datasets accelerate tokenizers

from google.colab import drive
import os

# Mount Drive to save files securely
drive.mount('/content/drive')

# Create the project directory in Drive if it does not exist
PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
os.makedirs(PROJECT_DIR, exist_ok=True)
print(f"Working directory ready at: {PROJECT_DIR}")

Mounted at /content/drive
Working directory ready at: /content/drive/MyDrive/Colab_LLMs/Maia_Lite

## Hugging Face Hub Token Configuration

To avoid unauthenticated request warnings and potentially speed up model and dataset downloads, it is recommended to configure a Hugging Face Hub access token. Follow the steps below:

1.  **Get your Access Token:**
    *   Go to [https://huggingface.co/settings/tokens](https://huggingface.co/settings/tokens).
    *   Create a new token. A token with `read` permission is recommended for most download operations.

2.  **Add the Token to Colab Secrets:**
    *   In the left panel of Google Colab, click on the key icon (🔑) to open the "Secrets" interface.
    *   Click on "Add new secret".
    *   In the "Name" field, type `HF_TOKEN`.
    *   In the "Value" field, paste the token you got from Hugging Face.
    *   Make sure to enable the "Notebook access" toggle so the notebook can use this secret.

3.  **Run the Python cell below:**
    *   This cell will load the token from Colab secrets and set it as an environment variable, which will be used by Hugging Face libraries.

In [ ]:
# Import the necessary libraries
from google.colab import userdata
import os
from huggingface_hub import login # Imports the login function from Hugging Face Hub

# Load the Hugging Face token from Colab secrets
try:
    hf_token = userdata.get('HF_TOKEN')
    if hf_token:
        # Try to login with the Hugging Face token
        login(token=hf_token, add_to_git_credential=False) # 'add_to_git_credential=False' to avoid asking for git credentials
        print("Hugging Face token successfully loaded and configured via huggingface_hub.login().")
    else:
        print("WARNING: The secret 'HF_TOKEN' was found, but it is empty or None. Please check the value in Colab secrets.")
        # If the token is empty/None, still set the environment variable as an empty string to avoid later errors
        os.environ['HF_TOKEN'] = ''
except userdata.SecretNotFoundError:
    print("WARNING: The secret 'HF_TOKEN' was not found. Please add your Hugging Face token to Colab secrets.")
    os.environ['HF_TOKEN'] = '' # Ensure the environment variable is set, even if empty
except Exception as e:
    print(f"An error occurred while loading or configuring the Hugging Face token: {e}")
    os.environ['HF_TOKEN'] = '' # Ensure the environment variable is set, even if empty

Hugging Face token successfully loaded and configured via huggingface_hub.login().

In [ ]:
from datasets import load_dataset, concatenate_datasets
from tokenizers import ByteLevelBPETokenizer
from transformers import GPT2TokenizerFast
import os
import shutil

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
tokenizer_dir = os.path.join(PROJECT_DIR, "tokenizador")

# Checks if the tokenizer already exists and loads it, otherwise trains a new one.
if os.path.exists(tokenizer_dir) and os.path.isdir(tokenizer_dir) and \
   os.path.exists(os.path.join(tokenizer_dir, "vocab.json")) and \
   os.path.exists(os.path.join(tokenizer_dir, "merges.txt")):
    print(f"Tokenizer found at: {tokenizer_dir}. Loading existing tokenizer...")
    tokenizer = GPT2TokenizerFast.from_pretrained(tokenizer_dir, local_files_only=True)
    print("Tokenizer successfully loaded!")
else:
    print(f"Tokenizer not found or incomplete at {tokenizer_dir}. Training a new tokenizer...")

    # 1. Load exact fractions directly to the local Colab cache (WITHOUT streaming=True)
    # Divided proportionally to sum up to 50,000 articles in total (50% EN, 25% PT, 25% ES)
    print("Downloading Wikipedia slices to local memory (This takes about 1-2 minutes)...")
    wiki_en = load_dataset("wikimedia/wikipedia", "20231101.en", split="train[:25000]")
    wiki_pt = load_dataset("wikimedia/wikipedia", "20231101.pt", split="train[:12500]")
    wiki_es = load_dataset("wikimedia/wikipedia", "20231101.es", split="train[:12500]")

    # Merges the locally downloaded datasets and shuffles in RAM
    print("Mixing and preparing the data...")
    mixed_dataset = concatenate_datasets([wiki_en, wiki_pt, wiki_es])
    mixed_dataset = mixed_dataset.shuffle(seed=42)

    # Generator used to feed the tokenizer trainer directly from RAM
    def extract_text():
        for item in mixed_dataset:
            yield item["text"]

    print("Training the tokenizer... This should now take 2 to 3 minutes.")
    tokenizer_raw = ByteLevelBPETokenizer()
    tokenizer_raw.train_from_iterator(
        extract_text(),
        vocab_size=50257, # Classic GPT-2 default
        min_frequency=2,
        special_tokens=["<s>", "<pad>", "</s>", "<unk>", "<mask>"]
    )

    # Saves the tokenizer to Drive
    # REMOVES the existing directory before creating again to force synchronization
    if os.path.exists(tokenizer_dir) and os.path.isdir(tokenizer_dir):
        print(f"Removing existing tokenizer directory: {tokenizer_dir}")
        shutil.rmtree(tokenizer_dir)

    os.makedirs(tokenizer_dir, exist_ok=True) # Creates the directory again
    tokenizer_raw.save_model(tokenizer_dir)

    # Converts to the format usable by Hugging Face Trainer
    tokenizer = GPT2TokenizerFast.from_pretrained(tokenizer_dir, bos_token="<s>", eos_token="</s>", unk_token="<unk>", pad_token="<pad>", mask_token="<mask>")
    tokenizer.save_pretrained(tokenizer_dir)
    print(f"Tokenizer successfully saved at: {tokenizer_dir}")

Tokenizer found at: /content/drive/MyDrive/Colab_LLMs/Maia_Lite/tokenizador. Loading existing tokenizer...
Tokenizer successfully loaded!

In [ ]:
import os

# Set BEFORE importing torch
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import torch
from datasets import load_dataset, interleave_datasets
from transformers import (
    GPT2Config,
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
from transformers.trainer_utils import get_last_checkpoint


# ============================================================
# MAIA LITE PRETRAINING
# Conservative configuration for Google Colab L4 / A100 / V100
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
TOKENIZER_DIR = os.path.join(PROJECT_DIR, "tokenizador")
OUTPUT_DIR = os.path.join(PROJECT_DIR, "checkpoints_pretreino")
FINAL_MODEL_DIR = os.path.join(PROJECT_DIR, "modelo_355M_final")

MAX_LENGTH = 1024
MAX_STEPS = 300_000


# ------------------------------------------------------------
# 1. GPU detection
# ------------------------------------------------------------

if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    device = torch.device("cuda")

    props = torch.cuda.get_device_properties(0)
    gpu_memory_gb = props.total_memory / (1024 ** 3)

    print(f"GPU available: {gpu_name}")
    print(f"GPU memory: {gpu_memory_gb:.1f} GB")
else:
    gpu_name = "CPU"
    device = torch.device("cpu")

    print(
        "WARNING: No CUDA GPU available. "
        "Training will be extremely slow."
    )


# ------------------------------------------------------------
# 2. Tokenizer
# ------------------------------------------------------------

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

# GPT-style causal LM normally uses EOS as padding token.
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(f"Tokenizer vocabulary: {tokenizer.vocab_size:,}")
print(f"EOS token: {tokenizer.eos_token_id}")
print(f"PAD token: {tokenizer.pad_token_id}")


# ------------------------------------------------------------
# 3. Find latest checkpoint
# ------------------------------------------------------------

last_checkpoint = get_last_checkpoint(OUTPUT_DIR)

if last_checkpoint is not None:
    print(f"\nCheckpoint found: {last_checkpoint}")

    model = GPT2LMHeadModel.from_pretrained(
        last_checkpoint,
        local_files_only=True,
    )

else:
    print("\nNo checkpoint found. Creating Maia Lite from scratch.")

    config = GPT2Config(
        vocab_size=tokenizer.vocab_size,
        n_positions=MAX_LENGTH,
        n_ctx=MAX_LENGTH,
        n_embd=1024,
        n_layer=24,
        n_head=16,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
        use_cache=False,
        tie_word_embeddings=True,
    )

    model = GPT2LMHeadModel(config)


# Important when using gradient checkpointing
model.config.use_cache = False

model.to(device)

print(f"Model parameters: {model.num_parameters():,}")


# ------------------------------------------------------------
# 4. Verify tied embeddings
# ------------------------------------------------------------

try:
    tied = (
        model.transformer.wte.weight.data_ptr()
        == model.lm_head.weight.data_ptr()
    )

    print(f"Input/output embeddings tied: {tied}")

except Exception as exc:
    print(f"Could not verify tied embeddings: {exc}")


# ------------------------------------------------------------
# 5. Gradient checkpointing
#
# KEEP ENABLED.
# Maia Lite previously experienced CUDA OOM on Colab.
# Reliability is more important than a small speed gain.
# ------------------------------------------------------------

model.gradient_checkpointing_enable()

print("Gradient checkpointing: ENABLED")


# ------------------------------------------------------------
# 6. Wikipedia streaming datasets
# ------------------------------------------------------------

print("\nLoading Wikipedia streams...")

wiki_en = load_dataset(
    "wikimedia/wikipedia",
    "20231101.en",
    split="train",
    streaming=True,
)

wiki_pt = load_dataset(
    "wikimedia/wikipedia",
    "20231101.pt",
    split="train",
    streaming=True,
)

wiki_es = load_dataset(
    "wikimedia/wikipedia",
    "20231101.es",
    split="train",
    streaming=True,
)

dataset_mixed = interleave_datasets(
    [wiki_en, wiki_pt, wiki_es],
    probabilities=[0.50, 0.25, 0.25],
    seed=42,
)


# ------------------------------------------------------------
# 7. Tokenization
#
# IMPORTANT:
# We deliberately keep the current tokenization strategy while
# resuming this pretraining run.
#
# Changing to document packing halfway through the experiment
# changes the training-data distribution.
#
# Packing should be implemented and benchmarked separately for
# the next Maia pretraining run.
# ------------------------------------------------------------

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=True,
    )


tokenized_dataset = dataset_mixed.map(
    tokenize_function,
    batched=True,
    remove_columns=["id", "url", "title", "text"],
)


# ------------------------------------------------------------
# 8. Causal language-model collator
# ------------------------------------------------------------

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)


# ------------------------------------------------------------
# 9. Conservative GPU profile
# ------------------------------------------------------------

batch_size = 1
gradient_accumulation = 16
use_bf16 = False
use_fp16 = True


if "A100" in gpu_name:

    # Still conservative because the same notebook may receive
    # different A100 memory configurations.
    batch_size = 8
    gradient_accumulation = 4

    use_bf16 = True
    use_fp16 = False


elif "L4" in gpu_name:

    # Known-safe configuration from the current Maia run.
    batch_size = 4
    gradient_accumulation = 8

    use_bf16 = True
    use_fp16 = False


elif "V100" in gpu_name:

    batch_size = 4
    gradient_accumulation = 8

    use_bf16 = False
    use_fp16 = True


elif "T4" in gpu_name:

    batch_size = 1
    gradient_accumulation = 16

    use_bf16 = False
    use_fp16 = True


effective_batch = batch_size * gradient_accumulation

print("\nTraining configuration")
print("----------------------")
print(f"GPU:                   {gpu_name}")
print(f"Micro batch:           {batch_size}")
print(f"Gradient accumulation: {gradient_accumulation}")
print(f"Effective batch:       {effective_batch}")
print(f"Context length:        {MAX_LENGTH}")
print(f"BF16:                  {use_bf16}")
print(f"FP16:                  {use_fp16}")


# ------------------------------------------------------------
# 10. Training arguments
# ------------------------------------------------------------

training_args = TrainingArguments(

    output_dir=OUTPUT_DIR,

    # Total training target
    max_steps=MAX_STEPS,

    # Memory-safe batching
    per_device_train_batch_size=batch_size,
    gradient_accumulation_steps=gradient_accumulation,

    # Precision
    bf16=use_bf16,
    fp16=use_fp16,

    # Optimization
    learning_rate=4e-4,
    weight_decay=0.01,

    # Explicit scheduler
    lr_scheduler_type="linear",
    warmup_steps=3000,

    # Logging
    logging_steps=100,

    # Checkpoints
    save_steps=2000,
    save_total_limit=2,

    # Streaming dataset
    dataloader_num_workers=2,

    # IMPORTANT:
    # Keep this behavior because restarting a huge streaming
    # dataset and skipping tens of thousands of batches can take
    # a very long time in Colab.
    ignore_data_skip=True,

    # Avoid unnecessary integrations
    report_to="none",

    # Reduces CPU -> GPU transfer overhead
    dataloader_pin_memory=True,

    # Let Trainer remove unused dataset columns
    remove_unused_columns=True,
)


# ------------------------------------------------------------
# 11. Trainer
# ------------------------------------------------------------

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
)


# ------------------------------------------------------------
# 12. CUDA diagnostics before training
# ------------------------------------------------------------

if torch.cuda.is_available():

    torch.cuda.empty_cache()

    allocated = torch.cuda.memory_allocated() / (1024 ** 3)
    reserved = torch.cuda.memory_reserved() / (1024 ** 3)

    print("\nCUDA memory before training")
    print("---------------------------")
    print(f"Allocated: {allocated:.2f} GB")
    print(f"Reserved:  {reserved:.2f} GB")


# ------------------------------------------------------------
# 13. Resume training
# ------------------------------------------------------------

print("\nStarting Maia Lite pretraining...")

if last_checkpoint is not None:

    print(f"Resuming Trainer state from:")
    print(last_checkpoint)

    trainer.train(
        resume_from_checkpoint=last_checkpoint
    )

else:

    trainer.train()


# ------------------------------------------------------------
# 14. Save final consolidated model
# ------------------------------------------------------------

trainer.save_model(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)

print("\n========================================")
print("MAIA LITE PRETRAINING COMPLETED")
print("========================================")
print(f"Final model saved to: {FINAL_MODEL_DIR}")

GPU available: NVIDIA L4
GPU memory: 22.0 GB
Tokenizer vocabulary: 50,257
EOS token: 2
PAD token: 1

Checkpoint found: /content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Model parameters: 354,823,168
Input/output embeddings tied: True
Gradient checkpointing: ENABLED

Loading Wikipedia streams...

README.md:   0%|          | 0.00/131k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

Training configuration
----------------------
GPU:                   NVIDIA L4
Micro batch:           4
Gradient accumulation: 8
Effective batch:       32
Context length:        1024
BF16:                  True
FP16:                  False

CUDA memory before training
---------------------------
Allocated: 1.32 GB
Reserved:  1.33 GB

Starting Maia Lite pretraining...
Resuming Trainer state from:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].
[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
import os
import torch
import numpy as np

from datasets import load_dataset, interleave_datasets
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    DataCollatorForLanguageModeling,
)
from torch.utils.data import DataLoader


# ============================================================
# MAIA LITE - STREAM LOSS DIAGNOSTIC
#
# Loads checkpoint-106000 and evaluates the Wikipedia stream
# WITHOUT training or modifying model weights.
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

CHECKPOINT_DIR = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

MAX_LENGTH = 1024

MICRO_BATCH = 4

# Equivalent to Trainer gradient accumulation
GRAD_ACCUM = 8

# Trainer logged every 100 optimizer steps.
LOGGING_STEPS = 100

# Number of equivalent training steps to inspect.
# 3000 steps covers substantially beyond the observed transition.
TEST_STEPS = 3000


# ------------------------------------------------------------
# 1. Device
# ------------------------------------------------------------

assert torch.cuda.is_available(), "CUDA GPU required."

device = torch.device("cuda")

print("GPU:", torch.cuda.get_device_name(0))


# ------------------------------------------------------------
# 2. Tokenizer
# ------------------------------------------------------------

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token


# ------------------------------------------------------------
# 3. Load checkpoint
# ------------------------------------------------------------

print("\nLoading checkpoint:")
print(CHECKPOINT_DIR)

model = GPT2LMHeadModel.from_pretrained(
    CHECKPOINT_DIR,
    local_files_only=True,
)

model.config.use_cache = False

model.to(device)
model.eval()

print(
    f"Parameters: {model.num_parameters():,}"
)


# ------------------------------------------------------------
# 4. Recreate EXACT Wikipedia stream
# ------------------------------------------------------------

print("\nLoading Wikipedia streams...")

wiki_en = load_dataset(
    "wikimedia/wikipedia",
    "20231101.en",
    split="train",
    streaming=True,
)

wiki_pt = load_dataset(
    "wikimedia/wikipedia",
    "20231101.pt",
    split="train",
    streaming=True,
)

wiki_es = load_dataset(
    "wikimedia/wikipedia",
    "20231101.es",
    split="train",
    streaming=True,
)

dataset_mixed = interleave_datasets(
    [wiki_en, wiki_pt, wiki_es],
    probabilities=[0.50, 0.25, 0.25],
    seed=42,
)


# ------------------------------------------------------------
# 5. Tokenization
# ------------------------------------------------------------

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=True,
    )


tokenized_dataset = dataset_mixed.map(
    tokenize_function,
    batched=True,
    remove_columns=[
        "id",
        "url",
        "title",
        "text",
    ],
)


# ------------------------------------------------------------
# 6. Collator / DataLoader
# ------------------------------------------------------------

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)

loader = DataLoader(
    tokenized_dataset,
    batch_size=MICRO_BATCH,
    collate_fn=data_collator,

    # Use zero workers for this diagnostic.
    # This makes stream ordering easier to reason about.
    num_workers=0,
)


# ------------------------------------------------------------
# 7. Frozen evaluation
# ------------------------------------------------------------

micro_losses = []

optimizer_step_losses = []

log_window_losses = []

equivalent_step = 0

print("\n========================================")
print("STARTING FROZEN LOSS TEST")
print("========================================")
print("NO gradients")
print("NO optimizer")
print("NO weight updates")
print()


with torch.inference_mode():

    for micro_step, batch in enumerate(loader, start=1):

        batch = {
            key: value.to(device)
            for key, value in batch.items()
            if isinstance(value, torch.Tensor)
        }

        with torch.autocast(
            device_type="cuda",
            dtype=torch.bfloat16,
        ):

            outputs = model(**batch)

        loss = outputs.loss.item()

        micro_losses.append(loss)


        # ----------------------------------------------------
        # Simulate one Trainer optimizer step
        # ----------------------------------------------------

        if len(micro_losses) == GRAD_ACCUM:

            equivalent_step += 1

            step_loss = float(
                np.mean(micro_losses)
            )

            optimizer_step_losses.append(
                step_loss
            )

            log_window_losses.append(
                step_loss
            )

            micro_losses.clear()


            # ------------------------------------------------
            # Equivalent to logging_steps=100
            # ------------------------------------------------

            if equivalent_step % LOGGING_STEPS == 0:

                window_loss = float(
                    np.mean(log_window_losses)
                )

                minimum = float(
                    np.min(log_window_losses)
                )

                maximum = float(
                    np.max(log_window_losses)
                )

                print(
                    f"Equivalent step "
                    f"{equivalent_step:5d} | "
                    f"mean loss = {window_loss:.6f} | "
                    f"min = {minimum:.4f} | "
                    f"max = {maximum:.4f}"
                )

                log_window_losses.clear()


            if equivalent_step >= TEST_STEPS:
                break


print()
print("========================================")
print("FROZEN LOSS TEST COMPLETED")
print("========================================")

GPU: NVIDIA L4

Loading checkpoint:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters: 354,823,168

Loading Wikipedia streams...

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

========================================
STARTING FROZEN LOSS TEST
========================================
NO gradients
NO optimizer
NO weight updates

Equivalent step   100 | mean loss = 2.752875 | min = 2.2633 | max = 2.9478
Equivalent step   200 | mean loss = 2.686952 | min = 2.2218 | max = 2.9339
Equivalent step   300 | mean loss = 2.511525 | min = 2.1626 | max = 2.7397
Equivalent step   400 | mean loss = 2.541561 | min = 2.0858 | max = 2.8022
Equivalent step   500 | mean loss = 2.572391 | min = 2.2613 | max = 2.8445
Equivalent step   600 | mean loss = 2.630158 | min = 2.3931 | max = 2.8278
Equivalent step   700 | mean loss = 2.520425 | min = 2.1049 | max = 2.7846
Equivalent step   800 | mean loss = 2.542685 | min = 2.1420 | max = 2.7979
Equivalent step   900 | mean loss = 2.602480 | min = 2.1763 | max = 2.9043
Equivalent step  1000 | mean loss = 2.557116 | min = 2.1317 | max = 2.8653
Equivalent step  1100 | mean loss = 2.453954 | min = 2.0883 | max = 2.7592
Equivalent step  1200 | mean loss = 2.361959 | min = 1.7154 | max = 2.6501
Equivalent step  1300 | mean loss = 2.492430 | min = 2.0598 | max = 2.8345
Equivalent step  1400 | mean loss = 2.457747 | min = 1.8156 | max = 2.7391
Equivalent step  1500 | mean loss = 2.559676 | min = 2.1517 | max = 2.8359
Equivalent step  1600 | mean loss = 2.568496 | min = 2.2504 | max = 2.8170
Equivalent step  1700 | mean loss = 2.561844 | min = 2.2561 | max = 2.8079
Equivalent step  1800 | mean loss = 2.500675 | min = 2.1957 | max = 2.7391
Equivalent step  1900 | mean loss = 2.322030 | min = 1.8975 | max = 2.5786
Equivalent step  2000 | mean loss = 2.479232 | min = 2.0080 | max = 2.7583
Equivalent step  2100 | mean loss = 2.552587 | min = 2.1971 | max = 2.8132
Equivalent step  2200 | mean loss = 2.485447 | min = 1.9541 | max = 2.7569
Equivalent step  2300 | mean loss = 2.474164 | min = 2.1908 | max = 2.6749
Equivalent step  2400 | mean loss = 2.486408 | min = 1.9837 | max = 2.6816
Equivalent step  2500 | mean loss = 2.517259 | min = 2.1502 | max = 2.7372
Equivalent step  2600 | mean loss = 2.436102 | min = 2.0465 | max = 2.7162
Equivalent step  2700 | mean loss = 2.551471 | min = 2.2262 | max = 2.7429
Equivalent step  2800 | mean loss = 2.557248 | min = 2.2460 | max = 2.7605
Equivalent step  2900 | mean loss = 2.598815 | min = 2.3247 | max = 2.7767

In [ ]:
import os

# Set BEFORE importing torch
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import torch
from datasets import load_dataset, interleave_datasets
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)


# ============================================================
# MAIA LITE - CHECKPOINT 106000 RECOVERY EXPERIMENT
#
# PURPOSE:
#   Load ONLY the model weights from checkpoint-106000.
#
#   DO NOT restore:
#     - optimizer
#     - scheduler
#     - Trainer state
#     - gradient scaler
#
#   Keep the original data pipeline and L4 batch configuration.
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

RECOVERY_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

# Completely separate directory.
# checkpoint-106000 will NOT be touched.
RECOVERY_OUTPUT_DIR = os.path.join(
    PROJECT_DIR,
    "recovery_test_106000"
)

RECOVERY_FINAL_DIR = os.path.join(
    RECOVERY_OUTPUT_DIR,
    "final"
)

MAX_LENGTH = 1024

# Number of NEW optimizer steps.
MAX_STEPS = 2000

# Conservative LR for the diagnostic experiment.
LEARNING_RATE = 1e-5

# Fresh optimizer gets a short warmup.
WARMUP_STEPS = 200


# ============================================================
# 1. GPU detection
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA GPU not available. "
        "This recovery experiment should run on GPU."
    )

gpu_name = torch.cuda.get_device_name(0)
device = torch.device("cuda")

props = torch.cuda.get_device_properties(0)
gpu_memory_gb = props.total_memory / (1024 ** 3)

print("=" * 70)
print("MAIA LITE - RECOVERY TRAINING EXPERIMENT")
print("=" * 70)
print(f"GPU:            {gpu_name}")
print(f"GPU memory:     {gpu_memory_gb:.1f} GB")
print(f"PyTorch:        {torch.__version__}")
print(f"CUDA:           {torch.version.cuda}")
print()


# ============================================================
# 2. Tokenizer
# ============================================================

print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(f"Tokenizer vocabulary: {tokenizer.vocab_size:,}")
print(f"EOS token:            {tokenizer.eos_token_id}")
print(f"PAD token:            {tokenizer.pad_token_id}")
print()


# ============================================================
# 3. Load ONLY model weights from checkpoint-106000
# ============================================================

print("Loading ONLY model weights from:")
print(RECOVERY_CHECKPOINT)
print()

model = GPT2LMHeadModel.from_pretrained(
    RECOVERY_CHECKPOINT,
    local_files_only=True,
)

model.config.use_cache = False

model.to(device)

print(f"Parameters: {model.num_parameters():,}")


# ============================================================
# 4. Verify tied embeddings
# ============================================================

try:

    tied = (
        model.transformer.wte.weight.data_ptr()
        == model.lm_head.weight.data_ptr()
    )

    print(f"Input/output embeddings tied: {tied}")

except Exception as exc:

    print(f"Could not verify tied embeddings: {exc}")


# ============================================================
# 5. Gradient checkpointing
# ============================================================

model.gradient_checkpointing_enable()

print("Gradient checkpointing: ENABLED")


# ============================================================
# 6. Wikipedia streams
#
# IDENTICAL TO ORIGINAL TRAINING.
# ============================================================

print("\nLoading Wikipedia streams...")

wiki_en = load_dataset(
    "wikimedia/wikipedia",
    "20231101.en",
    split="train",
    streaming=True,
)

wiki_pt = load_dataset(
    "wikimedia/wikipedia",
    "20231101.pt",
    split="train",
    streaming=True,
)

wiki_es = load_dataset(
    "wikimedia/wikipedia",
    "20231101.es",
    split="train",
    streaming=True,
)

dataset_mixed = interleave_datasets(
    [wiki_en, wiki_pt, wiki_es],
    probabilities=[0.50, 0.25, 0.25],
    seed=42,
)


# ============================================================
# 7. Tokenization
#
# IDENTICAL TO ORIGINAL TRAINING.
# ============================================================

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=True,
    )


tokenized_dataset = dataset_mixed.map(
    tokenize_function,
    batched=True,
    remove_columns=["id", "url", "title", "text"],
)


# ============================================================
# 8. Causal LM collator
#
# IDENTICAL TO ORIGINAL TRAINING.
# ============================================================

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)


# ============================================================
# 9. ORIGINAL L4 batch configuration
# ============================================================

# We deliberately preserve the configuration used during
# the original Maia Lite run.
#
# L4:
#
#   micro batch          = 4
#   gradient accumulation = 8
#   effective batch       = 32

if "L4" in gpu_name:

    batch_size = 4
    gradient_accumulation = 8

    use_bf16 = True
    use_fp16 = False

else:

    # Conservative fallback if Colab unexpectedly assigns
    # another GPU.

    batch_size = 1
    gradient_accumulation = 16

    use_bf16 = False
    use_fp16 = True


effective_batch = batch_size * gradient_accumulation


# ============================================================
# 10. Experiment summary
# ============================================================

print()
print("=" * 70)
print("RECOVERY EXPERIMENT CONFIGURATION")
print("=" * 70)

print(f"Checkpoint weights:      checkpoint-106000")
print()
print("RESTORED:")
print("  Model weights:         YES")
print()
print("NOT RESTORED:")
print("  Optimizer:             NEW")
print("  LR scheduler:          NEW")
print("  Trainer state:         NEW")
print("  Gradient scaler:       NEW")
print()

print("DATA:")
print("  Wikipedia EN:          50%")
print("  Wikipedia PT:          25%")
print("  Wikipedia ES:          25%")
print(f"  Context length:        {MAX_LENGTH}")
print()

print("BATCH:")
print(f"  Micro batch:           {batch_size}")
print(f"  Gradient accumulation: {gradient_accumulation}")
print(f"  Effective batch:       {effective_batch}")
print()

print("OPTIMIZATION:")
print(f"  Learning rate:         {LEARNING_RATE:.2e}")
print(f"  Warmup steps:          {WARMUP_STEPS}")
print("  Scheduler:             linear")
print("  Weight decay:          0.01")
print()

print(f"Recovery steps:          {MAX_STEPS}")
print(f"BF16:                    {use_bf16}")
print(f"FP16:                    {use_fp16}")

print("=" * 70)


# ============================================================
# 11. Training arguments
# ============================================================

training_args = TrainingArguments(

    # IMPORTANT:
    # Separate from the production checkpoint directory.
    output_dir=RECOVERY_OUTPUT_DIR,

    # These are NEW steps, starting logically from zero.
    max_steps=MAX_STEPS,

    # Preserve original L4 batching.
    per_device_train_batch_size=batch_size,
    gradient_accumulation_steps=gradient_accumulation,

    # Precision.
    bf16=use_bf16,
    fp16=use_fp16,

    # --------------------------------------------------------
    # NEW OPTIMIZATION STATE
    # --------------------------------------------------------

    learning_rate=LEARNING_RATE,

    weight_decay=0.01,

    lr_scheduler_type="linear",

    warmup_steps=WARMUP_STEPS,

    # Gradient clipping provides another safety barrier.
    max_grad_norm=1.0,

    # --------------------------------------------------------
    # LOGGING
    # --------------------------------------------------------

    logging_strategy="steps",

    logging_steps=100,

    logging_first_step=True,

    # --------------------------------------------------------
    # CHECKPOINTS
    # --------------------------------------------------------

    # Save frequently because this is a diagnostic experiment.
    save_strategy="steps",

    save_steps=500,

    # Keep all four diagnostic checkpoints.
    save_total_limit=4,

    # --------------------------------------------------------
    # STREAMING DATASET
    # --------------------------------------------------------

    dataloader_num_workers=2,

    dataloader_pin_memory=True,

    remove_unused_columns=True,

    # There is no previous Trainer state to skip.
    # Still harmless and consistent with streaming behavior.
    ignore_data_skip=True,

    # --------------------------------------------------------
    # OTHER
    # --------------------------------------------------------

    report_to="none",

    seed=42,
)


# ============================================================
# 12. Trainer
# ============================================================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
)


# ============================================================
# 13. CUDA diagnostics
# ============================================================

torch.cuda.empty_cache()

allocated = torch.cuda.memory_allocated() / (1024 ** 3)
reserved = torch.cuda.memory_reserved() / (1024 ** 3)

print()
print("CUDA memory before training")
print("---------------------------")
print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved:  {reserved:.2f} GB")


# ============================================================
# 14. START RECOVERY TRAINING
#
# CRITICAL:
#
# DO NOT USE:
#
# trainer.train(
#     resume_from_checkpoint=RECOVERY_CHECKPOINT
# )
#
# We intentionally call train() WITHOUT a checkpoint.
#
# This forces Trainer to create:
#
#   NEW AdamW optimizer
#   NEW LR scheduler
#   NEW training state
#
# while keeping the loaded checkpoint-106000 weights.
# ============================================================

print()
print("=" * 70)
print("STARTING RECOVERY TRAINING")
print("=" * 70)

print()
print("Checkpoint-106000 provides ONLY the model weights.")
print()

print("Watch the following columns:")
print()
print("  Step")
print("  Training Loss")
print("  Learning Rate")
print()

print("The experiment is successful if loss remains stable")
print("around the checkpoint's healthy region.")
print()

print("WARNING:")
print("If loss shows sustained monotonic growth toward 3.0,")
print("stop the experiment.")
print()

print("=" * 70)
print()


train_result = trainer.train()


# ============================================================
# 15. Save final recovery model
# ============================================================

trainer.save_model(RECOVERY_FINAL_DIR)

tokenizer.save_pretrained(
    RECOVERY_FINAL_DIR
)


# ============================================================
# 16. Print log history
# ============================================================

print()
print("=" * 70)
print("RECOVERY TRAINING LOG")
print("=" * 70)

for entry in trainer.state.log_history:

    if "loss" in entry:

        step = entry.get("step", "?")
        loss = entry.get("loss", None)
        lr = entry.get("learning_rate", None)

        if loss is not None:

            if lr is not None:

                print(
                    f"Step {step:5} | "
                    f"loss = {loss:.6f} | "
                    f"LR = {lr:.8e}"
                )

            else:

                print(
                    f"Step {step:5} | "
                    f"loss = {loss:.6f}"
                )


print()
print("=" * 70)
print("RECOVERY EXPERIMENT COMPLETED")
print("=" * 70)
print(f"Final recovery model:")
print(RECOVERY_FINAL_DIR)
print()
print("Original checkpoint-106000 was NOT modified.")
print("=" * 70)

======================================================================
MAIA LITE - RECOVERY TRAINING EXPERIMENT
======================================================================
GPU:            NVIDIA L4
GPU memory:     22.0 GB
PyTorch:        2.11.0+cu128
CUDA:           12.8

Loading tokenizer...
Tokenizer vocabulary: 50,257
EOS token:            2
PAD token:            1

Loading ONLY model weights from:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters: 354,823,168
Input/output embeddings tied: True
Gradient checkpointing: ENABLED

Loading Wikipedia streams...

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

======================================================================
RECOVERY EXPERIMENT CONFIGURATION
======================================================================
Checkpoint weights:      checkpoint-106000

RESTORED:
  Model weights:         YES

NOT RESTORED:
  Optimizer:             NEW
  LR scheduler:          NEW
  Trainer state:         NEW
  Gradient scaler:       NEW

DATA:
  Wikipedia EN:          50%
  Wikipedia PT:          25%
  Wikipedia ES:          25%
  Context length:        1024

BATCH:
  Micro batch:           4
  Gradient accumulation: 8
  Effective batch:       32

OPTIMIZATION:
  Learning rate:         1.00e-05
  Warmup steps:          200
  Scheduler:             linear
  Weight decay:          0.01

Recovery steps:          2000
BF16:                    True
FP16:                    False
======================================================================

CUDA memory before training
---------------------------
Allocated: 4.25 GB
Reserved:  4.42 GB

======================================================================
STARTING RECOVERY TRAINING
======================================================================

Checkpoint-106000 provides ONLY the model weights.

Watch the following columns:

  Step
  Training Loss
  Learning Rate

The experiment is successful if loss remains stable
around the checkpoint's healthy region.

WARNING:
If loss shows sustained monotonic growth toward 3.0,
stop the experiment.

======================================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
RECOVERY TRAINING LOG
======================================================================
Step     1 | loss = 2.799536 | LR = 0.00000000e+00
Step   100 | loss = 2.745501 | LR = 4.95000000e-06
Step   200 | loss = 2.785903 | LR = 9.95000000e-06
Step   300 | loss = 2.757358 | LR = 9.45000000e-06
Step   400 | loss = 2.635333 | LR = 8.89444444e-06
Step   500 | loss = 2.558901 | LR = 8.33888889e-06
Step   600 | loss = 2.585332 | LR = 7.78333333e-06
Step   700 | loss = 2.613076 | LR = 7.22777778e-06
Step   800 | loss = 2.557166 | LR = 6.67222222e-06
Step   900 | loss = 2.628467 | LR = 6.11666667e-06
Step  1000 | loss = 2.667072 | LR = 5.56111111e-06
Step  1100 | loss = 2.703328 | LR = 5.00555556e-06
Step  1200 | loss = 2.686302 | LR = 4.45000000e-06
Step  1300 | loss = 2.656910 | LR = 3.89444444e-06
Step  1400 | loss = 2.622562 | LR = 3.33888889e-06
Step  1500 | loss = 2.649464 | LR = 2.78333333e-06
Step  1600 | loss = 2.632236 | LR = 2.22777778e-06
Step  1700 | loss = 2.659712 | LR = 1.67222222e-06
Step  1800 | loss = 2.690224 | LR = 1.11666667e-06
Step  1900 | loss = 2.652272 | LR = 5.61111111e-07
Step  2000 | loss = 2.539832 | LR = 5.55555556e-09

======================================================================
RECOVERY EXPERIMENT COMPLETED
======================================================================
Final recovery model:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/recovery_test_106000/final

Original checkpoint-106000 was NOT modified.
======================================================================

In [ ]:
import os

# ============================================================
# MAIA LITE - DEFINITIVE A100 PRETRAINING CONTINUATION
# ============================================================
#
# FIRST EXECUTION:
#   - Load ONLY model weights from checkpoint-106000
#   - NEW optimizer
#   - NEW scheduler
#   - NEW Trainer state
#
# SUBSEQUENT COLAB SESSIONS:
#   - Resume latest checkpoint created by THIS continuation
#   - Restore model + optimizer + scheduler + Trainer state
#
# DATA PIPELINE:
#   IDENTICAL to the successful recovery experiment.
#
# ============================================================

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import math
import torch

from datasets import load_dataset, interleave_datasets

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    DataCollatorForLanguageModeling,
)

from transformers.trainer_utils import get_last_checkpoint


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

# GOLDEN checkpoint.
# This directory is NEVER used as output_dir.
GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

# New independent continuation.
CONTINUATION_DIR = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuacao_a100"
)

CURRENT_MODEL_DIR = os.path.join(
    CONTINUATION_DIR,
    "current_model"
)

os.makedirs(
    CONTINUATION_DIR,
    exist_ok=True
)


# ============================================================
# 2. LONG-TERM TRAINING PLAN
# ============================================================

ORIGINAL_STEP = 106_000

TARGET_ORIGINAL_STEP = 300_000

CONTINUATION_STEPS = (
    TARGET_ORIGINAL_STEP
    - ORIGINAL_STEP
)

assert CONTINUATION_STEPS == 194_000


# ============================================================
# 3. DATA
# ============================================================

MAX_LENGTH = 1024

SEED = 42


# ============================================================
# 4. A100 BATCH CONFIGURATION
# ============================================================
#
# Successful L4 recovery:
#
#   micro batch           = 4
#   gradient accumulation = 8
#   effective batch       = 32
#
# A100:
#
#   micro batch           = 8
#   gradient accumulation = 4
#   effective batch       = 32
#
# Therefore the effective batch remains unchanged.
# ============================================================

BATCH_SIZE = 8

GRADIENT_ACCUMULATION = 4

EFFECTIVE_BATCH = (
    BATCH_SIZE
    * GRADIENT_ACCUMULATION
)

assert EFFECTIVE_BATCH == 32


# ============================================================
# 5. OPTIMIZATION
# ============================================================

LEARNING_RATE = 1.0e-5

WARMUP_STEPS = 500

WEIGHT_DECAY = 0.01

MAX_GRAD_NORM = 1.0


# ============================================================
# 6. LOGGING / CHECKPOINTS
# ============================================================

LOGGING_STEPS = 100

SAVE_STEPS = 1000

SAVE_TOTAL_LIMIT = 3


# ============================================================
# 7. GPU DETECTION
# ============================================================

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


gpu_name = torch.cuda.get_device_name(0)

device = torch.device("cuda")

props = torch.cuda.get_device_properties(0)

gpu_memory_gb = (
    props.total_memory
    / (1024 ** 3)
)


print("=" * 74)

print(
    "MAIA LITE - DEFINITIVE A100 "
    "PRETRAINING CONTINUATION"
)

print("=" * 74)

print(f"GPU:                 {gpu_name}")
print(f"GPU memory:          {gpu_memory_gb:.1f} GB")
print(f"PyTorch:             {torch.__version__}")
print(f"CUDA:                {torch.version.cuda}")

print()


if "A100" not in gpu_name.upper():

    print("WARNING:")
    print(
        "This configuration was designed "
        "for NVIDIA A100."
    )

    print(
        f"Detected GPU: {gpu_name}"
    )

    print()


# ============================================================
# 8. TOKENIZER
# ============================================================

print("Loading tokenizer...")


tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)


if tokenizer.pad_token is None:

    tokenizer.pad_token = tokenizer.eos_token


print(
    f"Tokenizer vocabulary: "
    f"{tokenizer.vocab_size:,}"
)

print(
    f"EOS token:            "
    f"{tokenizer.eos_token_id}"
)

print(
    f"PAD token:            "
    f"{tokenizer.pad_token_id}"
)

print()


# ============================================================
# 9. DETECT EXISTING CONTINUATION
# ============================================================

resume_checkpoint = get_last_checkpoint(
    CONTINUATION_DIR
)


# ============================================================
# 10. LOAD MODEL
# ============================================================

if resume_checkpoint is None:

    # --------------------------------------------------------
    # FIRST EXECUTION
    # --------------------------------------------------------

    print("=" * 74)
    print("NEW A100 CONTINUATION")
    print("=" * 74)

    print()

    print(
        "Loading ONLY model weights from:"
    )

    print(GOLDEN_CHECKPOINT)

    print()


    model = GPT2LMHeadModel.from_pretrained(
        GOLDEN_CHECKPOINT,
        local_files_only=True,
    )


    print("RESTORED:")
    print("  Model weights:         YES")

    print()

    print("NOT RESTORED:")
    print("  Optimizer:             NEW")
    print("  LR scheduler:          NEW")
    print("  Trainer state:         NEW")
    print("  Gradient scaler:       NEW")


else:

    # --------------------------------------------------------
    # SUBSEQUENT COLAB SESSION
    # --------------------------------------------------------

    print("=" * 74)
    print("RESUMING A100 CONTINUATION")
    print("=" * 74)

    print()

    print(
        "Latest continuation checkpoint:"
    )

    print(resume_checkpoint)

    print()


    model = GPT2LMHeadModel.from_pretrained(
        resume_checkpoint,
        local_files_only=True,
    )


    print("RESTORING:")
    print("  Model weights")
    print("  Optimizer")
    print("  LR scheduler")
    print("  Trainer state")


# ============================================================
# 11. MODEL CONFIGURATION
# ============================================================

model.config.use_cache = False

model.to(device)

model.gradient_checkpointing_enable()


print()

print(
    f"Parameters:            "
    f"{model.num_parameters():,}"
)


# Verify tied embeddings.

try:

    tied = (
        model.transformer.wte.weight.data_ptr()
        ==
        model.lm_head.weight.data_ptr()
    )

    print(
        f"Input/output embeddings tied: "
        f"{tied}"
    )

except Exception as exc:

    print(
        "Could not verify tied embeddings:",
        exc
    )


print(
    "Gradient checkpointing: ENABLED"
)

print()


# ============================================================
# 12. WIKIPEDIA STREAMS
#
# EXACTLY THE SAME PIPELINE AS THE SUCCESSFUL RECOVERY TEST.
# ============================================================

print(
    "Loading Wikipedia streams..."
)


wiki_en = load_dataset(
    "wikimedia/wikipedia",
    "20231101.en",
    split="train",
    streaming=True,
)


wiki_pt = load_dataset(
    "wikimedia/wikipedia",
    "20231101.pt",
    split="train",
    streaming=True,
)


wiki_es = load_dataset(
    "wikimedia/wikipedia",
    "20231101.es",
    split="train",
    streaming=True,
)


dataset_mixed = interleave_datasets(

    [
        wiki_en,
        wiki_pt,
        wiki_es
    ],

    probabilities=[
        0.50,
        0.25,
        0.25
    ],

    seed=SEED,
)


# ============================================================
# 13. TOKENIZATION
#
# EXACTLY THE SAME AS THE SUCCESSFUL RECOVERY TEST.
# ============================================================

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=True,
    )


tokenized_dataset = dataset_mixed.map(

    tokenize_function,

    batched=True,

    remove_columns=[
        "id",
        "url",
        "title",
        "text"
    ],
)


# ============================================================
# 14. DATA COLLATOR
#
# IDENTICAL TO SUCCESSFUL RECOVERY.
# ============================================================

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)


# ============================================================
# 15. TRAINING MONITOR
# ============================================================

class MaiaTrainingMonitor(
    TrainerCallback
):

    def __init__(self):

        self.recent_losses = []


    def on_log(
        self,
        args,
        state,
        control,
        logs=None,
        **kwargs
    ):

        if not logs:
            return

        loss = logs.get("loss")

        lr = logs.get(
            "learning_rate"
        )

        grad_norm = logs.get(
            "grad_norm"
        )


        if loss is None:
            return


        continuation_step = (
            state.global_step
        )

        equivalent_step = (
            ORIGINAL_STEP
            + continuation_step
        )


        self.recent_losses.append(
            float(loss)
        )


        if len(
            self.recent_losses
        ) > 10:

            self.recent_losses.pop(0)


        message = (

            f"[MAIA] "
            f"continuation="
            f"{continuation_step:6d} | "

            f"equivalent="
            f"{equivalent_step:6d} | "

            f"loss="
            f"{loss:.6f}"
        )


        if lr is not None:

            message += (
                f" | LR="
                f"{lr:.3e}"
            )


        if grad_norm is not None:

            message += (
                f" | grad_norm="
                f"{grad_norm:.4f}"
            )


        print()
        print(message)


        # ----------------------------------------------------
        # NON-FINITE LOSS
        # ----------------------------------------------------

        if not math.isfinite(
            float(loss)
        ):

            print()
            print("!" * 60)

            print(
                "NON-FINITE LOSS DETECTED."
            )

            print(
                "TRAINING WILL STOP."
            )

            print("!" * 60)


            control.should_training_stop = True

            return


        # ----------------------------------------------------
        # SUSTAINED HIGH LOSS PROTECTION
        #
        # Stop only if FIVE consecutive 100-step averages
        # exceed 3.20.
        # ----------------------------------------------------

        if len(
            self.recent_losses
        ) >= 5:

            last5 = (
                self.recent_losses[-5:]
            )


            if all(
                x > 3.20
                for x in last5
            ):

                print()
                print("!" * 60)

                print(
                    "SUSTAINED HIGH LOSS DETECTED."
                )

                print(
                    "Last five logged losses:",
                    [
                        round(x, 4)
                        for x in last5
                    ]
                )

                print(
                    "TRAINING WILL STOP."
                )

                print("!" * 60)


                control.should_training_stop = True


# ============================================================
# 16. TRAINING ARGUMENTS
# ============================================================

training_args = TrainingArguments(

    # --------------------------------------------------------
    # OUTPUT
    # --------------------------------------------------------

    output_dir=CONTINUATION_DIR,


    # --------------------------------------------------------
    # LONG-TERM TRAINING
    # --------------------------------------------------------

    max_steps=CONTINUATION_STEPS,


    # --------------------------------------------------------
    # A100 BATCH
    # --------------------------------------------------------

    per_device_train_batch_size=(
        BATCH_SIZE
    ),

    gradient_accumulation_steps=(
        GRADIENT_ACCUMULATION
    ),


    # --------------------------------------------------------
    # PRECISION
    # --------------------------------------------------------

    bf16=True,

    fp16=False,


    # --------------------------------------------------------
    # OPTIMIZATION
    # --------------------------------------------------------

    learning_rate=LEARNING_RATE,

    weight_decay=WEIGHT_DECAY,

    lr_scheduler_type="cosine",

    warmup_steps=WARMUP_STEPS,

    max_grad_norm=MAX_GRAD_NORM,

    optim="adamw_torch",


    # --------------------------------------------------------
    # MEMORY
    # --------------------------------------------------------

    gradient_checkpointing=True,


    # --------------------------------------------------------
    # LOGGING
    # --------------------------------------------------------

    logging_strategy="steps",

    logging_steps=LOGGING_STEPS,

    logging_first_step=True,


    # --------------------------------------------------------
    # CHECKPOINTS
    # --------------------------------------------------------

    save_strategy="steps",

    save_steps=SAVE_STEPS,

    save_total_limit=SAVE_TOTAL_LIMIT,


    # --------------------------------------------------------
    # STREAMING DATASET
    #
    # SAME AS SUCCESSFUL RECOVERY.
    # --------------------------------------------------------

    dataloader_num_workers=2,

    dataloader_pin_memory=True,

    remove_unused_columns=True,

    ignore_data_skip=True,


    # --------------------------------------------------------
    # OTHER
    # --------------------------------------------------------

    report_to="none",

    seed=SEED,
)


# ============================================================
# 17. TRAINER
# ============================================================

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_dataset,

    data_collator=data_collator,

    callbacks=[
        MaiaTrainingMonitor()
    ],
)


# ============================================================
# 18. CONFIGURATION SUMMARY
# ============================================================

print()
print("=" * 74)

print(
    "MAIA LITE - A100 TRAINING CONFIGURATION"
)

print("=" * 74)

print()


print("TRAINING PLAN:")

print(
    f"  Golden checkpoint:      "
    f"{ORIGINAL_STEP:,}"
)

print(
    f"  Target equivalent:      "
    f"{TARGET_ORIGINAL_STEP:,}"
)

print(
    f"  New optimizer steps:    "
    f"{CONTINUATION_STEPS:,}"
)

print()


print("DATA:")

print(
    "  Wikipedia EN:           50%"
)

print(
    "  Wikipedia PT:           25%"
)

print(
    "  Wikipedia ES:           25%"
)

print(
    f"  Context length:         "
    f"{MAX_LENGTH}"
)

print()


print("A100 BATCH:")

print(
    f"  Micro batch:            "
    f"{BATCH_SIZE}"
)

print(
    f"  Gradient accumulation:  "
    f"{GRADIENT_ACCUMULATION}"
)

print(
    f"  Effective batch:        "
    f"{EFFECTIVE_BATCH}"
)

print()


print("OPTIMIZATION:")

print(
    f"  Peak learning rate:     "
    f"{LEARNING_RATE:.2e}"
)

print(
    f"  Warmup steps:           "
    f"{WARMUP_STEPS}"
)

print(
    "  Scheduler:              cosine"
)

print(
    f"  Weight decay:           "
    f"{WEIGHT_DECAY}"
)

print(
    f"  Max gradient norm:      "
    f"{MAX_GRAD_NORM}"
)

print()


print("CHECKPOINTS:")

print(
    f"  Directory:              "
    f"{CONTINUATION_DIR}"
)

print(
    f"  Save every:             "
    f"{SAVE_STEPS:,} steps"
)

print(
    f"  Keep latest:            "
    f"{SAVE_TOTAL_LIMIT}"
)

print()


if resume_checkpoint is None:

    print("MODE:")
    print(
        "  GOLDEN checkpoint weights ONLY"
    )

    print(
        "  NEW optimizer"
    )

    print(
        "  NEW scheduler"
    )

    print(
        "  NEW Trainer state"
    )

else:

    print("MODE:")

    print(
        "  RESUME HEALTHY CONTINUATION"
    )

    print(
        f"  {resume_checkpoint}"
    )


print()
print("=" * 74)


# ============================================================
# 19. CUDA MEMORY
# ============================================================

torch.cuda.empty_cache()


allocated = (
    torch.cuda.memory_allocated()
    / (1024 ** 3)
)

reserved = (
    torch.cuda.memory_reserved()
    / (1024 ** 3)
)


print()

print(
    "CUDA memory before training"
)

print(
    "---------------------------"
)

print(
    f"Allocated: {allocated:.2f} GB"
)

print(
    f"Reserved:  {reserved:.2f} GB"
)

print()


# ============================================================
# 20. START TRAINING
# ============================================================

print("=" * 74)

print(
    "STARTING MAIA LITE A100 TRAINING"
)

print("=" * 74)

print()


if resume_checkpoint is None:

    print(
        "Starting from checkpoint-106000 "
        "MODEL WEIGHTS ONLY."
    )

    print()

    print(
        "Optimizer and scheduler are NEW."
    )

else:

    print(
        "Restoring complete healthy "
        "continuation state from:"
    )

    print()

    print(
        resume_checkpoint
    )


print()

print(
    "Monitor:"
)

print(
    "  loss"
)

print(
    "  learning rate"
)

print(
    "  gradient norm"
)

print()

print(
    "Golden checkpoint-106000 "
    "will NOT be modified."
)

print()

print("=" * 74)

print()


# ============================================================
# 21. TRAIN
# ============================================================

if resume_checkpoint is None:

    # --------------------------------------------------------
    # FIRST RUN
    #
    # CRITICAL:
    #
    # Do NOT use resume_from_checkpoint here.
    #
    # This creates a NEW optimizer and scheduler.
    # --------------------------------------------------------

    train_result = trainer.train()


else:

    # --------------------------------------------------------
    # FUTURE COLAB SESSIONS
    #
    # Restore optimizer/scheduler/state generated by this
    # healthy continuation.
    # --------------------------------------------------------

    train_result = trainer.train(
        resume_from_checkpoint=(
            resume_checkpoint
        )
    )


# ============================================================
# 22. SAVE CURRENT MODEL
# ============================================================

trainer.save_model(
    CURRENT_MODEL_DIR
)

tokenizer.save_pretrained(
    CURRENT_MODEL_DIR
)


# ============================================================
# 23. SESSION SUMMARY
# ============================================================

continuation_step = (
    trainer.state.global_step
)

equivalent_step = (
    ORIGINAL_STEP
    + continuation_step
)


print()
print("=" * 74)

print(
    "MAIA LITE A100 SESSION COMPLETED"
)

print("=" * 74)

print()


print(
    f"Continuation step:        "
    f"{continuation_step:,}"
)

print(
    f"Equivalent original step: "
    f"{equivalent_step:,}"
)

print()


print(
    "Current model:"
)

print(
    CURRENT_MODEL_DIR
)

print()


print(
    "Golden checkpoint-106000 "
    "remains untouched."
)

print("=" * 74)

==========================================================================
MAIA LITE - DEFINITIVE A100 PRETRAINING CONTINUATION
==========================================================================
GPU:                 NVIDIA A100-SXM4-80GB
GPU memory:          79.3 GB
PyTorch:             2.11.0+cu128
CUDA:                12.8

Loading tokenizer...
Tokenizer vocabulary: 50,257
EOS token:            2
PAD token:            1

==========================================================================
RESUMING A100 CONTINUATION
==========================================================================

Latest continuation checkpoint:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuacao_a100/checkpoint-51000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

RESTORING:
  Model weights
  Optimizer
  LR scheduler
  Trainer state

Parameters:            354,823,168
Input/output embeddings tied: True
Gradient checkpointing: ENABLED

Loading Wikipedia streams...

README.md:   0%|          | 0.00/131k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

==========================================================================
MAIA LITE - A100 TRAINING CONFIGURATION
==========================================================================

TRAINING PLAN:
  Golden checkpoint:      106,000
  Target equivalent:      300,000
  New optimizer steps:    194,000

DATA:
  Wikipedia EN:           50%
  Wikipedia PT:           25%
  Wikipedia ES:           25%
  Context length:         1024

A100 BATCH:
  Micro batch:            8
  Gradient accumulation:  4
  Effective batch:        32

OPTIMIZATION:
  Peak learning rate:     1.00e-05
  Warmup steps:           500
  Scheduler:              cosine
  Weight decay:           0.01
  Max gradient norm:      1.0

CHECKPOINTS:
  Directory:              /content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuacao_a100
  Save every:             1,000 steps
  Keep latest:            3

MODE:
  RESUME HEALTHY CONTINUATION
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuacao_a100/checkpoint-51000

==========================================================================

CUDA memory before training
---------------------------
Allocated: 1.32 GB
Reserved:  1.33 GB

==========================================================================
STARTING MAIA LITE A100 TRAINING
==========================================================================

Restoring complete healthy continuation state from:

/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuacao_a100/checkpoint-51000

Monitor:
  loss
  learning rate
  gradient norm

Golden checkpoint-106000 will NOT be modified.

==========================================================================

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].
[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

[MAIA] continuation= 51100 | equivalent=157100 | loss=2.900024 | LR=8.406e-06 | grad_norm=2.2957

[MAIA] continuation= 51200 | equivalent=157200 | loss=2.931596 | LR=8.400e-06 | grad_norm=1.2956

[MAIA] continuation= 51300 | equivalent=157300 | loss=2.909729 | LR=8.394e-06 | grad_norm=1.5069

[MAIA] continuation= 51400 | equivalent=157400 | loss=2.792738 | LR=8.388e-06 | grad_norm=1.5015

[MAIA] continuation= 51500 | equivalent=157500 | loss=2.719987 | LR=8.382e-06 | grad_norm=0.8435

[MAIA] continuation= 51600 | equivalent=157600 | loss=2.750173 | LR=8.376e-06 | grad_norm=1.1910

[MAIA] continuation= 51700 | equivalent=157700 | loss=2.773105 | LR=8.370e-06 | grad_norm=0.9272

[MAIA] continuation= 51800 | equivalent=157800 | loss=2.724689 | LR=8.364e-06 | grad_norm=1.0577

[MAIA] continuation= 51900 | equivalent=157900 | loss=2.791362 | LR=8.358e-06 | grad_norm=1.6656

[MAIA] continuation= 52000 | equivalent=158000 | loss=2.831927 | LR=8.352e-06 | grad_norm=1.6110

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 52100 | equivalent=158100 | loss=2.871678 | LR=8.346e-06 | grad_norm=2.0960

[MAIA] continuation= 52200 | equivalent=158200 | loss=2.853086 | LR=8.340e-06 | grad_norm=1.0243

[MAIA] continuation= 52300 | equivalent=158300 | loss=2.827015 | LR=8.334e-06 | grad_norm=1.3074

[MAIA] continuation= 52400 | equivalent=158400 | loss=2.795183 | LR=8.328e-06 | grad_norm=0.9391

[MAIA] continuation= 52500 | equivalent=158500 | loss=2.816833 | LR=8.322e-06 | grad_norm=2.4862

[MAIA] continuation= 52600 | equivalent=158600 | loss=2.805462 | LR=8.315e-06 | grad_norm=0.9144

[MAIA] continuation= 52700 | equivalent=158700 | loss=2.830313 | LR=8.309e-06 | grad_norm=1.6144

[MAIA] continuation= 52800 | equivalent=158800 | loss=2.861116 | LR=8.303e-06 | grad_norm=1.4108

[MAIA] continuation= 52900 | equivalent=158900 | loss=2.823889 | LR=8.297e-06 | grad_norm=1.1870

[MAIA] continuation= 53000 | equivalent=159000 | loss=2.711277 | LR=8.291e-06 | grad_norm=1.2967

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 53100 | equivalent=159100 | loss=2.748506 | LR=8.285e-06 | grad_norm=1.0304

[MAIA] continuation= 53200 | equivalent=159200 | loss=2.700916 | LR=8.279e-06 | grad_norm=1.0595

[MAIA] continuation= 53300 | equivalent=159300 | loss=2.693654 | LR=8.273e-06 | grad_norm=2.0078

[MAIA] continuation= 53400 | equivalent=159400 | loss=2.659478 | LR=8.267e-06 | grad_norm=1.0328

[MAIA] continuation= 53500 | equivalent=159500 | loss=2.744168 | LR=8.260e-06 | grad_norm=1.6922

[MAIA] continuation= 53600 | equivalent=159600 | loss=2.776143 | LR=8.254e-06 | grad_norm=1.2351

[MAIA] continuation= 53700 | equivalent=159700 | loss=2.690193 | LR=8.248e-06 | grad_norm=3.1861

[MAIA] continuation= 53800 | equivalent=159800 | loss=2.760208 | LR=8.242e-06 | grad_norm=1.2477

[MAIA] continuation= 53900 | equivalent=159900 | loss=2.800730 | LR=8.236e-06 | grad_norm=1.1978

[MAIA] continuation= 54000 | equivalent=160000 | loss=2.826568 | LR=8.230e-06 | grad_norm=1.5421

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 54100 | equivalent=160100 | loss=2.805252 | LR=8.223e-06 | grad_norm=1.2920

[MAIA] continuation= 54200 | equivalent=160200 | loss=2.823400 | LR=8.217e-06 | grad_norm=1.7667

[MAIA] continuation= 54300 | equivalent=160300 | loss=2.830349 | LR=8.211e-06 | grad_norm=1.1016

[MAIA] continuation= 54400 | equivalent=160400 | loss=2.778276 | LR=8.205e-06 | grad_norm=1.3881

[MAIA] continuation= 54500 | equivalent=160500 | loss=2.806448 | LR=8.198e-06 | grad_norm=1.0455

[MAIA] continuation= 54600 | equivalent=160600 | loss=2.729705 | LR=8.192e-06 | grad_norm=1.3147

[MAIA] continuation= 54700 | equivalent=160700 | loss=2.665284 | LR=8.186e-06 | grad_norm=1.2906

[MAIA] continuation= 54800 | equivalent=160800 | loss=2.728614 | LR=8.180e-06 | grad_norm=1.4120

[MAIA] continuation= 54900 | equivalent=160900 | loss=2.720280 | LR=8.173e-06 | grad_norm=1.6491

[MAIA] continuation= 55000 | equivalent=161000 | loss=2.784381 | LR=8.167e-06 | grad_norm=1.9253

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 55100 | equivalent=161100 | loss=2.802251 | LR=8.161e-06 | grad_norm=1.1585

[MAIA] continuation= 55200 | equivalent=161200 | loss=2.788845 | LR=8.155e-06 | grad_norm=1.3339

[MAIA] continuation= 55300 | equivalent=161300 | loss=2.792686 | LR=8.148e-06 | grad_norm=1.5287

[MAIA] continuation= 55400 | equivalent=161400 | loss=2.758246 | LR=8.142e-06 | grad_norm=2.2165

[MAIA] continuation= 55500 | equivalent=161500 | loss=2.782055 | LR=8.136e-06 | grad_norm=1.3519

[MAIA] continuation= 55600 | equivalent=161600 | loss=2.772829 | LR=8.129e-06 | grad_norm=1.2501

[MAIA] continuation= 55700 | equivalent=161700 | loss=2.741012 | LR=8.123e-06 | grad_norm=1.2687

[MAIA] continuation= 55800 | equivalent=161800 | loss=2.780713 | LR=8.117e-06 | grad_norm=1.3935

[MAIA] continuation= 55900 | equivalent=161900 | loss=2.743961 | LR=8.110e-06 | grad_norm=0.9962

[MAIA] continuation= 56000 | equivalent=162000 | loss=2.779396 | LR=8.104e-06 | grad_norm=1.6303

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 56100 | equivalent=162100 | loss=2.768152 | LR=8.098e-06 | grad_norm=1.4182

[MAIA] continuation= 56200 | equivalent=162200 | loss=2.749178 | LR=8.091e-06 | grad_norm=1.4179

[MAIA] continuation= 56300 | equivalent=162300 | loss=2.774980 | LR=8.085e-06 | grad_norm=1.8913

[MAIA] continuation= 56400 | equivalent=162400 | loss=2.790583 | LR=8.078e-06 | grad_norm=2.0959

[MAIA] continuation= 56500 | equivalent=162500 | loss=2.773816 | LR=8.072e-06 | grad_norm=3.7843

[MAIA] continuation= 56600 | equivalent=162600 | loss=2.791335 | LR=8.066e-06 | grad_norm=11.0008

[MAIA] continuation= 56700 | equivalent=162700 | loss=2.809896 | LR=8.059e-06 | grad_norm=3.2476

[MAIA] continuation= 56800 | equivalent=162800 | loss=2.849104 | LR=8.053e-06 | grad_norm=1.0456

[MAIA] continuation= 56900 | equivalent=162900 | loss=2.789135 | LR=8.046e-06 | grad_norm=2.6242

[MAIA] continuation= 57000 | equivalent=163000 | loss=2.766065 | LR=8.040e-06 | grad_norm=1.5677

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 57100 | equivalent=163100 | loss=2.774941 | LR=8.033e-06 | grad_norm=3.2463

[MAIA] continuation= 57200 | equivalent=163200 | loss=2.833459 | LR=8.027e-06 | grad_norm=2.0112

[MAIA] continuation= 57300 | equivalent=163300 | loss=2.818446 | LR=8.020e-06 | grad_norm=1.4558

[MAIA] continuation= 57400 | equivalent=163400 | loss=2.821377 | LR=8.014e-06 | grad_norm=7.3668

[MAIA] continuation= 57500 | equivalent=163500 | loss=2.808432 | LR=8.008e-06 | grad_norm=1.5950

[MAIA] continuation= 57600 | equivalent=163600 | loss=2.743942 | LR=8.001e-06 | grad_norm=4.6760

[MAIA] continuation= 57700 | equivalent=163700 | loss=2.768091 | LR=7.995e-06 | grad_norm=1.4121

[MAIA] continuation= 57800 | equivalent=163800 | loss=2.815712 | LR=7.988e-06 | grad_norm=1.4914

[MAIA] continuation= 57900 | equivalent=163900 | loss=2.732158 | LR=7.982e-06 | grad_norm=1.1523

[MAIA] continuation= 58000 | equivalent=164000 | loss=2.775010 | LR=7.975e-06 | grad_norm=3.5356

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 58100 | equivalent=164100 | loss=2.821919 | LR=7.968e-06 | grad_norm=2.5036

[MAIA] continuation= 58200 | equivalent=164200 | loss=2.814555 | LR=7.962e-06 | grad_norm=1.5362

[MAIA] continuation= 58300 | equivalent=164300 | loss=2.811343 | LR=7.955e-06 | grad_norm=37.4314

[MAIA] continuation= 58400 | equivalent=164400 | loss=2.842195 | LR=7.949e-06 | grad_norm=1.5621

[MAIA] continuation= 58500 | equivalent=164500 | loss=2.829832 | LR=7.942e-06 | grad_norm=1.4778

[MAIA] continuation= 58600 | equivalent=164600 | loss=2.850721 | LR=7.936e-06 | grad_norm=1.0576

[MAIA] continuation= 58700 | equivalent=164700 | loss=2.851087 | LR=7.929e-06 | grad_norm=3.5950

[MAIA] continuation= 58800 | equivalent=164800 | loss=2.822296 | LR=7.923e-06 | grad_norm=2.3016

[MAIA] continuation= 58900 | equivalent=164900 | loss=2.834857 | LR=7.916e-06 | grad_norm=1.5356

[MAIA] continuation= 59000 | equivalent=165000 | loss=2.748608 | LR=7.909e-06 | grad_norm=0.9047

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 59100 | equivalent=165100 | loss=2.716362 | LR=7.903e-06 | grad_norm=7.8554

[MAIA] continuation= 59200 | equivalent=165200 | loss=2.754499 | LR=7.896e-06 | grad_norm=3.2753

[MAIA] continuation= 59300 | equivalent=165300 | loss=2.734242 | LR=7.890e-06 | grad_norm=1.5258

[MAIA] continuation= 59400 | equivalent=165400 | loss=2.832740 | LR=7.883e-06 | grad_norm=2.5099

[MAIA] continuation= 59500 | equivalent=165500 | loss=2.724918 | LR=7.876e-06 | grad_norm=1.0627

[MAIA] continuation= 59600 | equivalent=165600 | loss=2.706254 | LR=7.870e-06 | grad_norm=1.0996

[MAIA] continuation= 59700 | equivalent=165700 | loss=2.777731 | LR=7.863e-06 | grad_norm=2.8582

[MAIA] continuation= 59800 | equivalent=165800 | loss=2.781661 | LR=7.856e-06 | grad_norm=2.5050

[MAIA] continuation= 59900 | equivalent=165900 | loss=2.755110 | LR=7.850e-06 | grad_norm=4.6195

[MAIA] continuation= 60000 | equivalent=166000 | loss=2.791452 | LR=7.843e-06 | grad_norm=5.2190

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 60100 | equivalent=166100 | loss=2.779951 | LR=7.836e-06 | grad_norm=2.3800

[MAIA] continuation= 60200 | equivalent=166200 | loss=2.698795 | LR=7.830e-06 | grad_norm=1.1579

[MAIA] continuation= 60300 | equivalent=166300 | loss=2.711817 | LR=7.823e-06 | grad_norm=6.4709

[MAIA] continuation= 60400 | equivalent=166400 | loss=2.710044 | LR=7.816e-06 | grad_norm=8.1233

[MAIA] continuation= 60500 | equivalent=166500 | loss=2.654721 | LR=7.809e-06 | grad_norm=1.1949

[MAIA] continuation= 60600 | equivalent=166600 | loss=2.696505 | LR=7.803e-06 | grad_norm=3.4409

[MAIA] continuation= 60700 | equivalent=166700 | loss=2.680619 | LR=7.796e-06 | grad_norm=3.2300

[MAIA] continuation= 60800 | equivalent=166800 | loss=2.649268 | LR=7.789e-06 | grad_norm=8.5417

[MAIA] continuation= 60900 | equivalent=166900 | loss=2.713854 | LR=7.783e-06 | grad_norm=2.5434

[MAIA] continuation= 61000 | equivalent=167000 | loss=2.716602 | LR=7.776e-06 | grad_norm=10.8282

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 61100 | equivalent=167100 | loss=2.733628 | LR=7.769e-06 | grad_norm=1.3074

[MAIA] continuation= 61200 | equivalent=167200 | loss=2.740701 | LR=7.762e-06 | grad_norm=4.9689

[MAIA] continuation= 61300 | equivalent=167300 | loss=2.685902 | LR=7.756e-06 | grad_norm=12.7551

[MAIA] continuation= 61400 | equivalent=167400 | loss=2.674129 | LR=7.749e-06 | grad_norm=1.9038

[MAIA] continuation= 61500 | equivalent=167500 | loss=2.709008 | LR=7.742e-06 | grad_norm=2.0684

[MAIA] continuation= 61600 | equivalent=167600 | loss=2.703260 | LR=7.735e-06 | grad_norm=2.5623

[MAIA] continuation= 61700 | equivalent=167700 | loss=2.671886 | LR=7.728e-06 | grad_norm=3.0757

[MAIA] continuation= 61800 | equivalent=167800 | loss=2.634924 | LR=7.722e-06 | grad_norm=8.6479

[MAIA] continuation= 61900 | equivalent=167900 | loss=2.683706 | LR=7.715e-06 | grad_norm=2.1540

[MAIA] continuation= 62000 | equivalent=168000 | loss=2.695706 | LR=7.708e-06 | grad_norm=1.2971

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 62100 | equivalent=168100 | loss=2.688014 | LR=7.701e-06 | grad_norm=1.7402

[MAIA] continuation= 62200 | equivalent=168200 | loss=2.639033 | LR=7.694e-06 | grad_norm=7.4319

[MAIA] continuation= 62300 | equivalent=168300 | loss=2.673771 | LR=7.687e-06 | grad_norm=2.5229

[MAIA] continuation= 62400 | equivalent=168400 | loss=2.677424 | LR=7.681e-06 | grad_norm=4.2951

[MAIA] continuation= 62500 | equivalent=168500 | loss=2.657163 | LR=7.674e-06 | grad_norm=11.8519

[MAIA] continuation= 62600 | equivalent=168600 | loss=2.750117 | LR=7.667e-06 | grad_norm=1.3243

[MAIA] continuation= 62700 | equivalent=168700 | loss=2.732401 | LR=7.660e-06 | grad_norm=2.1066

[MAIA] continuation= 62800 | equivalent=168800 | loss=2.750244 | LR=7.653e-06 | grad_norm=6.2964

[MAIA] continuation= 62900 | equivalent=168900 | loss=2.740709 | LR=7.646e-06 | grad_norm=3.9972

[MAIA] continuation= 63000 | equivalent=169000 | loss=2.759992 | LR=7.639e-06 | grad_norm=1.2298

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 63100 | equivalent=169100 | loss=3.094330 | LR=7.632e-06 | grad_norm=9.9293

[MAIA] continuation= 63200 | equivalent=169200 | loss=3.059889 | LR=7.626e-06 | grad_norm=1.8388

[MAIA] continuation= 63300 | equivalent=169300 | loss=3.055454 | LR=7.619e-06 | grad_norm=1.4185

[MAIA] continuation= 63400 | equivalent=169400 | loss=3.028492 | LR=7.612e-06 | grad_norm=2.7900

[MAIA] continuation= 63500 | equivalent=169500 | loss=3.050508 | LR=7.605e-06 | grad_norm=1.6723

[MAIA] continuation= 63600 | equivalent=169600 | loss=3.074196 | LR=7.598e-06 | grad_norm=1.3862

[MAIA] continuation= 63700 | equivalent=169700 | loss=3.079589 | LR=7.591e-06 | grad_norm=2.3994

[MAIA] continuation= 63800 | equivalent=169800 | loss=3.061305 | LR=7.584e-06 | grad_norm=2.6774

[MAIA] continuation= 63900 | equivalent=169900 | loss=3.059344 | LR=7.577e-06 | grad_norm=0.9891

[MAIA] continuation= 64000 | equivalent=170000 | loss=3.066783 | LR=7.570e-06 | grad_norm=1.5709

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 64100 | equivalent=170100 | loss=3.051201 | LR=7.563e-06 | grad_norm=1.5474

[MAIA] continuation= 64200 | equivalent=170200 | loss=3.048619 | LR=7.556e-06 | grad_norm=6.1128

[MAIA] continuation= 64300 | equivalent=170300 | loss=3.054863 | LR=7.549e-06 | grad_norm=1.3399

[MAIA] continuation= 64400 | equivalent=170400 | loss=2.956943 | LR=7.542e-06 | grad_norm=1.5216

[MAIA] continuation= 64500 | equivalent=170500 | loss=3.059013 | LR=7.535e-06 | grad_norm=1.2886

[MAIA] continuation= 64600 | equivalent=170600 | loss=3.064587 | LR=7.528e-06 | grad_norm=1.8513

[MAIA] continuation= 64700 | equivalent=170700 | loss=3.042592 | LR=7.521e-06 | grad_norm=5.6762

[MAIA] continuation= 64800 | equivalent=170800 | loss=3.051483 | LR=7.514e-06 | grad_norm=1.8722

[MAIA] continuation= 64900 | equivalent=170900 | loss=3.017512 | LR=7.507e-06 | grad_norm=3.4698

[MAIA] continuation= 65000 | equivalent=171000 | loss=3.066121 | LR=7.500e-06 | grad_norm=1.9934

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 65100 | equivalent=171100 | loss=3.059065 | LR=7.493e-06 | grad_norm=2.6725

[MAIA] continuation= 65200 | equivalent=171200 | loss=3.045133 | LR=7.486e-06 | grad_norm=2.2248

[MAIA] continuation= 65300 | equivalent=171300 | loss=3.042964 | LR=7.479e-06 | grad_norm=4.5517

[MAIA] continuation= 65400 | equivalent=171400 | loss=3.031592 | LR=7.472e-06 | grad_norm=1.8381

[MAIA] continuation= 65500 | equivalent=171500 | loss=3.076363 | LR=7.465e-06 | grad_norm=1.5253

[MAIA] continuation= 65600 | equivalent=171600 | loss=3.052117 | LR=7.458e-06 | grad_norm=4.1417

[MAIA] continuation= 65700 | equivalent=171700 | loss=3.039446 | LR=7.451e-06 | grad_norm=1.4637

[MAIA] continuation= 65800 | equivalent=171800 | loss=3.046040 | LR=7.444e-06 | grad_norm=1.2387

[MAIA] continuation= 65900 | equivalent=171900 | loss=3.077258 | LR=7.437e-06 | grad_norm=5.0515

[MAIA] continuation= 66000 | equivalent=172000 | loss=3.007699 | LR=7.429e-06 | grad_norm=2.0951

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 66100 | equivalent=172100 | loss=3.014052 | LR=7.422e-06 | grad_norm=2.9271

[MAIA] continuation= 66200 | equivalent=172200 | loss=2.971240 | LR=7.415e-06 | grad_norm=1.6434

[MAIA] continuation= 66300 | equivalent=172300 | loss=2.972679 | LR=7.408e-06 | grad_norm=2.1170

[MAIA] continuation= 66400 | equivalent=172400 | loss=3.007803 | LR=7.401e-06 | grad_norm=1.6461

[MAIA] continuation= 66500 | equivalent=172500 | loss=2.974708 | LR=7.394e-06 | grad_norm=5.4208

[MAIA] continuation= 66600 | equivalent=172600 | loss=2.974921 | LR=7.387e-06 | grad_norm=3.3901

[MAIA] continuation= 66700 | equivalent=172700 | loss=3.017002 | LR=7.380e-06 | grad_norm=2.7917

[MAIA] continuation= 66800 | equivalent=172800 | loss=3.043129 | LR=7.372e-06 | grad_norm=1.1270

[MAIA] continuation= 66900 | equivalent=172900 | loss=2.962794 | LR=7.365e-06 | grad_norm=6.4084

[MAIA] continuation= 67000 | equivalent=173000 | loss=2.924252 | LR=7.358e-06 | grad_norm=5.3360

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[MAIA] continuation= 67100 | equivalent=173100 | loss=2.886105 | LR=7.351e-06 | grad_norm=2.2058

KeyboardInterrupt:

In [ ]:
# ============================================================
# MAIA LITE - FIXED FROZEN LOSS CHECKPOINT DIAGNOSTIC
#
# PURPOSE:
#   Compare checkpoint-106000 (golden) against checkpoint-67000
#   using EXACTLY THE SAME fixed evaluation samples.
#
# IMPORTANT:
#   - NO gradients
#   - NO optimizer
#   - NO scheduler
#   - NO weight updates
#   - NO Trainer
#   - Checkpoints are NEVER modified
# ============================================================

import os
import gc
import math
import json
import statistics

import torch

from datasets import load_dataset, interleave_datasets
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    DataCollatorForLanguageModeling,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

CONTINUATION_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuacao_a100",
    "checkpoint-67000"
)

DIAGNOSTIC_DIR = os.path.join(
    PROJECT_DIR,
    "diagnostics"
)

os.makedirs(
    DIAGNOSTIC_DIR,
    exist_ok=True
)

FIXED_DATA_FILE = os.path.join(
    DIAGNOSTIC_DIR,
    "fixed_validation_samples.pt"
)

RESULTS_FILE = os.path.join(
    DIAGNOSTIC_DIR,
    "checkpoint_106000_vs_continuation_67000.json"
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

MAX_LENGTH = 1024

SEED = 42

# Number of individual Wikipedia examples to freeze.
#
# 1024 examples gives us a reasonably large diagnostic sample
# while keeping the evaluation inexpensive.
NUM_FIXED_SAMPLES = 1024

# Evaluation batch size.
# A100 80 GB can handle this comfortably in inference mode.
EVAL_BATCH_SIZE = 16


# ============================================================
# 3. DEVICE
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU not available.")

device = torch.device("cuda")

gpu_name = torch.cuda.get_device_name(0)

print("=" * 74)
print("MAIA LITE - FIXED FROZEN LOSS DIAGNOSTIC")
print("=" * 74)

print()
print(f"GPU:                  {gpu_name}")
print(f"PyTorch:              {torch.__version__}")
print(f"CUDA:                 {torch.version.cuda}")

print()


# ============================================================
# 4. VERIFY CHECKPOINTS
# ============================================================

for path in [
    GOLDEN_CHECKPOINT,
    CONTINUATION_CHECKPOINT
]:
    if not os.path.isdir(path):
        raise RuntimeError(
            f"Checkpoint not found:\n{path}"
        )

print("Golden checkpoint:")
print(GOLDEN_CHECKPOINT)

print()

print("Continuation checkpoint:")
print(CONTINUATION_CHECKPOINT)

print()


# ============================================================
# 5. TOKENIZER
# ============================================================

print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(
    f"Tokenizer vocabulary: {tokenizer.vocab_size:,}"
)

print(
    f"EOS token:            {tokenizer.eos_token_id}"
)

print(
    f"PAD token:            {tokenizer.pad_token_id}"
)

print()


# ============================================================
# 6. BUILD OR LOAD FIXED DIAGNOSTIC DATASET
#
# IMPORTANT:
#
# Once created, this file is reused forever.
#
# Future checkpoints can therefore be compared against
# EXACTLY the same token sequences.
# ============================================================

if os.path.exists(FIXED_DATA_FILE):

    print("Loading EXISTING fixed diagnostic dataset:")
    print(FIXED_DATA_FILE)

    fixed_samples = torch.load(
        FIXED_DATA_FILE,
        map_location="cpu",
        weights_only=False,
    )

    print(
        f"Loaded {len(fixed_samples):,} fixed samples."
    )

else:

    print("Creating NEW fixed diagnostic dataset...")

    print()
    print("Loading Wikipedia streams...")

    wiki_en = load_dataset(
        "wikimedia/wikipedia",
        "20231101.en",
        split="train",
        streaming=True,
    )

    wiki_pt = load_dataset(
        "wikimedia/wikipedia",
        "20231101.pt",
        split="train",
        streaming=True,
    )

    wiki_es = load_dataset(
        "wikimedia/wikipedia",
        "20231101.es",
        split="train",
        streaming=True,
    )

    dataset_mixed = interleave_datasets(
        [
            wiki_en,
            wiki_pt,
            wiki_es,
        ],
        probabilities=[
            0.50,
            0.25,
            0.25,
        ],
        seed=SEED,
    )

    fixed_samples = []

    print()
    print(
        f"Collecting {NUM_FIXED_SAMPLES:,} "
        "fixed Wikipedia samples..."
    )

    for example in dataset_mixed:

        encoded = tokenizer(
            example["text"],
            truncation=True,
            max_length=MAX_LENGTH,
            add_special_tokens=True,
        )

        input_ids = encoded["input_ids"]

        # Ignore extremely short entries.
        # They provide little useful LM diagnostic signal.
        if len(input_ids) < 32:
            continue

        fixed_samples.append({
            "input_ids": torch.tensor(
                input_ids,
                dtype=torch.long
            )
        })

        if len(fixed_samples) >= NUM_FIXED_SAMPLES:
            break

    if len(fixed_samples) != NUM_FIXED_SAMPLES:
        raise RuntimeError(
            "Could not collect the requested "
            "number of diagnostic samples."
        )

    torch.save(
        fixed_samples,
        FIXED_DATA_FILE
    )

    print()
    print("Fixed diagnostic dataset SAVED:")
    print(FIXED_DATA_FILE)


print()

print(
    f"Diagnostic samples:    "
    f"{len(fixed_samples):,}"
)

lengths = [
    len(x["input_ids"])
    for x in fixed_samples
]

print(
    f"Mean token length:     "
    f"{statistics.mean(lengths):.1f}"
)

print(
    f"Median token length:   "
    f"{statistics.median(lengths):.1f}"
)

print(
    f"Min token length:      "
    f"{min(lengths)}"
)

print(
    f"Max token length:      "
    f"{max(lengths)}"
)

print()


# ============================================================
# 7. COLLATOR
#
# IDENTICAL LM COLLATOR USED DURING TRAINING.
# ============================================================

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)


# ============================================================
# 8. EVALUATION FUNCTION
# ============================================================

def evaluate_checkpoint(
    checkpoint_path,
    checkpoint_name
):

    print()
    print("=" * 74)
    print(
        f"EVALUATING: {checkpoint_name}"
    )
    print("=" * 74)

    print()
    print(checkpoint_path)
    print()

    # Clean GPU before loading next model.
    gc.collect()
    torch.cuda.empty_cache()

    model = GPT2LMHeadModel.from_pretrained(
        checkpoint_path,
        local_files_only=True,
        torch_dtype=torch.bfloat16,
    )

    model.config.use_cache = False

    model.to(device)

    model.eval()

    batch_losses = []

    weighted_loss_sum = 0.0
    total_prediction_tokens = 0

    num_samples = len(fixed_samples)

    num_batches = math.ceil(
        num_samples / EVAL_BATCH_SIZE
    )

    print(
        f"Samples:              {num_samples:,}"
    )

    print(
        f"Batch size:           {EVAL_BATCH_SIZE}"
    )

    print(
        f"Batches:              {num_batches:,}"
    )

    print()

    with torch.inference_mode():

        for batch_index, start in enumerate(
            range(
                0,
                num_samples,
                EVAL_BATCH_SIZE
            ),
            start=1
        ):

            end = min(
                start + EVAL_BATCH_SIZE,
                num_samples
            )

            samples = fixed_samples[
                start:end
            ]

            batch = data_collator(
                samples
            )

            input_ids = batch[
                "input_ids"
            ].to(device)

            attention_mask = batch[
                "attention_mask"
            ].to(device)

            labels = batch[
                "labels"
            ].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )

            loss = float(
                outputs.loss.detach().float().cpu()
            )

            batch_losses.append(loss)

            # For causal LM, token t predicts token t+1.
            # Count valid target tokens after shifting.
            valid_tokens = int(
                (
                    labels[:, 1:] != -100
                ).sum().item()
            )

            weighted_loss_sum += (
                loss * valid_tokens
            )

            total_prediction_tokens += (
                valid_tokens
            )

            if (
                batch_index % 10 == 0
                or
                batch_index == num_batches
            ):

                running_loss = (
                    weighted_loss_sum
                    / total_prediction_tokens
                )

                print(
                    f"Batch "
                    f"{batch_index:4d}/"
                    f"{num_batches:4d}"
                    f" | running loss = "
                    f"{running_loss:.6f}"
                )


    # --------------------------------------------------------
    # Statistics
    # --------------------------------------------------------

    token_weighted_mean_loss = (
        weighted_loss_sum
        / total_prediction_tokens
    )

    mean_batch_loss = statistics.mean(
        batch_losses
    )

    median_batch_loss = statistics.median(
        batch_losses
    )

    std_batch_loss = statistics.stdev(
        batch_losses
    ) if len(batch_losses) > 1 else 0.0

    min_batch_loss = min(
        batch_losses
    )

    max_batch_loss = max(
        batch_losses
    )

    perplexity = math.exp(
        token_weighted_mean_loss
    )


    print()
    print("-" * 74)

    print(
        f"Token-weighted loss:  "
        f"{token_weighted_mean_loss:.6f}"
    )

    print(
        f"Mean batch loss:      "
        f"{mean_batch_loss:.6f}"
    )

    print(
        f"Median batch loss:    "
        f"{median_batch_loss:.6f}"
    )

    print(
        f"Std batch loss:       "
        f"{std_batch_loss:.6f}"
    )

    print(
        f"Min batch loss:       "
        f"{min_batch_loss:.6f}"
    )

    print(
        f"Max batch loss:       "
        f"{max_batch_loss:.6f}"
    )

    print(
        f"Prediction tokens:    "
        f"{total_prediction_tokens:,}"
    )

    print(
        f"Perplexity:           "
        f"{perplexity:.6f}"
    )

    print("-" * 74)


    result = {
        "checkpoint": checkpoint_name,
        "path": checkpoint_path,
        "samples": num_samples,
        "prediction_tokens": total_prediction_tokens,
        "token_weighted_loss": (
            token_weighted_mean_loss
        ),
        "mean_batch_loss": mean_batch_loss,
        "median_batch_loss": median_batch_loss,
        "std_batch_loss": std_batch_loss,
        "min_batch_loss": min_batch_loss,
        "max_batch_loss": max_batch_loss,
        "perplexity": perplexity,
    }


    # --------------------------------------------------------
    # Release model completely before next checkpoint.
    # --------------------------------------------------------

    del outputs
    del model

    gc.collect()

    torch.cuda.empty_cache()

    return result


# ============================================================
# 9. RUN EXACTLY THE SAME TEST ON BOTH CHECKPOINTS
# ============================================================

golden_result = evaluate_checkpoint(
    GOLDEN_CHECKPOINT,
    "golden-original-106000"
)

continuation_result = evaluate_checkpoint(
    CONTINUATION_CHECKPOINT,
    "continuation-67000-equivalent-173000"
)


# ============================================================
# 10. COMPARISON
# ============================================================

golden_loss = (
    golden_result[
        "token_weighted_loss"
    ]
)

continuation_loss = (
    continuation_result[
        "token_weighted_loss"
    ]
)

absolute_change = (
    continuation_loss
    - golden_loss
)

percent_change = (
    absolute_change
    / golden_loss
    * 100.0
)


print()
print()
print("=" * 74)
print("MAIA LITE - CHECKPOINT COMPARISON")
print("=" * 74)

print()

print(
    f"Golden 106000 loss:       "
    f"{golden_loss:.6f}"
)

print(
    f"Continuation 67000 loss:  "
    f"{continuation_loss:.6f}"
)

print()

print(
    f"Absolute change:           "
    f"{absolute_change:+.6f}"
)

print(
    f"Relative change:           "
    f"{percent_change:+.3f}%"
)

print()

print(
    f"Golden perplexity:         "
    f"{golden_result['perplexity']:.6f}"
)

print(
    f"Continuation perplexity:   "
    f"{continuation_result['perplexity']:.6f}"
)

print()


# ============================================================
# 11. INTERPRETATION
# ============================================================

if continuation_loss < golden_loss:

    print(
        "RESULT: continuation checkpoint has "
        "LOWER frozen loss than the golden checkpoint."
    )

    print(
        "The model improved on the fixed diagnostic set."
    )

elif continuation_loss > golden_loss:

    print(
        "RESULT: continuation checkpoint has "
        "HIGHER frozen loss than the golden checkpoint."
    )

    print(
        "This requires investigation before "
        "continuing long-term training."
    )

else:

    print(
        "RESULT: losses are identical."
    )


# ============================================================
# 12. SAVE RESULTS
# ============================================================

results = {
    "configuration": {
        "seed": SEED,
        "max_length": MAX_LENGTH,
        "num_fixed_samples": NUM_FIXED_SAMPLES,
        "eval_batch_size": EVAL_BATCH_SIZE,
        "dataset": {
            "source": "wikimedia/wikipedia",
            "en": "20231101.en",
            "pt": "20231101.pt",
            "es": "20231101.es",
            "probabilities": [
                0.50,
                0.25,
                0.25
            ],
        },
        "fixed_data_file": (
            FIXED_DATA_FILE
        ),
    },
    "golden": golden_result,
    "continuation": continuation_result,
    "comparison": {
        "absolute_loss_change": (
            absolute_change
        ),
        "relative_loss_change_percent": (
            percent_change
        ),
    },
}

with open(
    RESULTS_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        results,
        f,
        indent=2,
        ensure_ascii=False,
    )


print()
print(
    "Results saved to:"
)

print(
    RESULTS_FILE
)

print()

print(
    "Fixed diagnostic dataset:"
)

print(
    FIXED_DATA_FILE
)

print()

print("=" * 74)
print("DIAGNOSTIC COMPLETE")
print("=" * 74)

==========================================================================
MAIA LITE - FIXED FROZEN LOSS DIAGNOSTIC
==========================================================================

GPU:                  NVIDIA A100-SXM4-80GB
PyTorch:              2.11.0+cu128
CUDA:                 12.8

Golden checkpoint:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Continuation checkpoint:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuacao_a100/checkpoint-67000

Loading tokenizer...
Tokenizer vocabulary: 50,257
EOS token:            2
PAD token:            1

Creating NEW fixed diagnostic dataset...

Loading Wikipedia streams...

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

Collecting 1,024 fixed Wikipedia samples...

Fixed diagnostic dataset SAVED:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/diagnostics/fixed_validation_samples.pt

Diagnostic samples:    1,024
Mean token length:     887.5
Median token length:   1024.0
Min token length:      32
Max token length:      1024


==========================================================================
EVALUATING: golden-original-106000
==========================================================================

/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Samples:              1,024
Batch size:           16
Batches:              64

Batch   10/  64 | running loss = 2.769387
Batch   20/  64 | running loss = 2.721659
Batch   30/  64 | running loss = 2.701241
Batch   40/  64 | running loss = 2.722818
Batch   50/  64 | running loss = 2.740855
Batch   60/  64 | running loss = 2.743709
Batch   64/  64 | running loss = 2.746445

--------------------------------------------------------------------------
Token-weighted loss:  2.746445
Mean batch loss:      2.745051
Median batch loss:    2.758717
Std batch loss:       0.146005
Min batch loss:       2.163710
Max batch loss:       2.989947
Prediction tokens:    907,778
Perplexity:           15.587114
--------------------------------------------------------------------------

==========================================================================
EVALUATING: continuation-67000-equivalent-173000
==========================================================================

/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuacao_a100/checkpoint-67000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Samples:              1,024
Batch size:           16
Batches:              64

Batch   10/  64 | running loss = 2.845064
Batch   20/  64 | running loss = 2.802996
Batch   30/  64 | running loss = 2.781911
Batch   40/  64 | running loss = 2.800170
Batch   50/  64 | running loss = 2.814443
Batch   60/  64 | running loss = 2.815316
Batch   64/  64 | running loss = 2.817412

--------------------------------------------------------------------------
Token-weighted loss:  2.817412
Mean batch loss:      2.815972
Median batch loss:    2.817804
Std batch loss:       0.142178
Min batch loss:       2.264682
Max batch loss:       3.060543
Prediction tokens:    907,778
Perplexity:           16.733495
--------------------------------------------------------------------------


==========================================================================
MAIA LITE - CHECKPOINT COMPARISON
==========================================================================

Golden 106000 loss:       2.746445
Continuation 67000 loss:  2.817412

Absolute change:           +0.070968
Relative change:           +2.584%

Golden perplexity:         15.587114
Continuation perplexity:   16.733495

RESULT: continuation checkpoint has HIGHER frozen loss than the golden checkpoint.
This requires investigation before continuing long-term training.

Results saved to:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/diagnostics/checkpoint_106000_vs_continuation_67000.json

Fixed diagnostic dataset:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/diagnostics/fixed_validation_samples.pt

==========================================================================
DIAGNOSTIC COMPLETE
==========================================================================

In [ ]:
# ============================================================
# MAIA LITE - MULTI-CHECKPOINT FROZEN LOSS COMPARISON
#
# Compares:
#   Golden checkpoint-106000
#   Continuation checkpoint-65000  -> equivalent 171000
#   Continuation checkpoint-66000  -> equivalent 172000
#   Continuation checkpoint-67000  -> equivalent 173000
#
# Uses the ALREADY SAVED fixed diagnostic dataset.
#
# NO gradients
# NO optimizer
# NO scheduler
# NO Trainer
# NO weight updates
# ============================================================

import os
import gc
import math
import statistics
import torch

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    DataCollatorForLanguageModeling,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

CONTINUATION_DIR = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuacao_a100"
)

FIXED_DATA_FILE = os.path.join(
    PROJECT_DIR,
    "diagnostics",
    "fixed_validation_samples.pt"
)


# ============================================================
# 2. CHECKPOINTS
# ============================================================

CHECKPOINTS = [
    (
        "golden-106000",
        GOLDEN_CHECKPOINT,
        106000,
    ),
    (
        "continuation-65000",
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-65000"
        ),
        171000,
    ),
    (
        "continuation-66000",
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-66000"
        ),
        172000,
    ),
    (
        "continuation-67000",
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-67000"
        ),
        173000,
    ),
]


# ============================================================
# 3. CONFIGURATION
# ============================================================

EVAL_BATCH_SIZE = 16


# ============================================================
# 4. GPU
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU not available.")

device = torch.device("cuda")

print("=" * 78)
print("MAIA LITE - MULTI-CHECKPOINT FROZEN LOSS TEST")
print("=" * 78)

print()
print(
    f"GPU:     {torch.cuda.get_device_name(0)}"
)

print(
    f"PyTorch: {torch.__version__}"
)

print(
    f"CUDA:    {torch.version.cuda}"
)

print()


# ============================================================
# 5. VERIFY FILES
# ============================================================

if not os.path.exists(FIXED_DATA_FILE):

    raise RuntimeError(
        "Fixed diagnostic dataset not found:\n"
        + FIXED_DATA_FILE
    )


valid_checkpoints = []

for name, path, equivalent_step in CHECKPOINTS:

    if os.path.isdir(path):

        valid_checkpoints.append(
            (
                name,
                path,
                equivalent_step,
            )
        )

        print(
            f"FOUND:   {name}"
        )

    else:

        print(
            f"MISSING: {name}"
        )


if len(valid_checkpoints) < 2:

    raise RuntimeError(
        "Not enough checkpoints available "
        "for comparison."
    )


# ============================================================
# 6. TOKENIZER
# ============================================================

print()
print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token


# ============================================================
# 7. LOAD EXACT SAME FROZEN DATA
# ============================================================

print()
print("Loading FIXED diagnostic dataset...")

fixed_samples = torch.load(
    FIXED_DATA_FILE,
    map_location="cpu",
    weights_only=False,
)

print(
    f"Samples: {len(fixed_samples):,}"
)


# ============================================================
# 8. DATA COLLATOR
# ============================================================

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)


# ============================================================
# 9. EVALUATION
# ============================================================

def evaluate_checkpoint(
    name,
    path,
    equivalent_step,
):

    print()
    print("=" * 78)
    print(f"EVALUATING: {name}")
    print(
        f"EQUIVALENT STEP: {equivalent_step:,}"
    )
    print("=" * 78)

    gc.collect()
    torch.cuda.empty_cache()

    model = GPT2LMHeadModel.from_pretrained(
        path,
        local_files_only=True,
        torch_dtype=torch.bfloat16,
    )

    model.config.use_cache = False

    model.to(device)
    model.eval()

    losses = []

    weighted_loss_sum = 0.0
    total_prediction_tokens = 0

    total_samples = len(fixed_samples)

    total_batches = math.ceil(
        total_samples / EVAL_BATCH_SIZE
    )


    with torch.inference_mode():

        for batch_number, start in enumerate(
            range(
                0,
                total_samples,
                EVAL_BATCH_SIZE
            ),
            start=1,
        ):

            end = min(
                start + EVAL_BATCH_SIZE,
                total_samples
            )

            samples = fixed_samples[
                start:end
            ]

            batch = data_collator(
                samples
            )

            input_ids = batch[
                "input_ids"
            ].to(device)

            attention_mask = batch[
                "attention_mask"
            ].to(device)

            labels = batch[
                "labels"
            ].to(device)


            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )


            loss = float(
                outputs.loss
                .detach()
                .float()
                .cpu()
            )

            losses.append(loss)


            valid_tokens = int(
                (
                    labels[:, 1:] != -100
                )
                .sum()
                .item()
            )


            weighted_loss_sum += (
                loss * valid_tokens
            )

            total_prediction_tokens += (
                valid_tokens
            )


            if (
                batch_number % 16 == 0
                or
                batch_number == total_batches
            ):

                running_loss = (
                    weighted_loss_sum
                    / total_prediction_tokens
                )

                print(
                    f"Batch "
                    f"{batch_number:3d}/"
                    f"{total_batches:3d}"
                    f" | loss="
                    f"{running_loss:.6f}"
                )


    frozen_loss = (
        weighted_loss_sum
        / total_prediction_tokens
    )

    perplexity = math.exp(
        frozen_loss
    )

    mean_loss = statistics.mean(
        losses
    )

    median_loss = statistics.median(
        losses
    )

    std_loss = statistics.stdev(
        losses
    )


    result = {
        "name": name,
        "equivalent_step": equivalent_step,
        "loss": frozen_loss,
        "perplexity": perplexity,
        "mean": mean_loss,
        "median": median_loss,
        "std": std_loss,
        "min": min(losses),
        "max": max(losses),
        "tokens": total_prediction_tokens,
    }


    print()
    print(
        f"Frozen loss: {frozen_loss:.6f}"
    )

    print(
        f"Perplexity:  {perplexity:.6f}"
    )


    del outputs
    del model

    gc.collect()
    torch.cuda.empty_cache()

    return result


# ============================================================
# 10. RUN ALL CHECKPOINTS
# ============================================================

results = []

for name, path, equivalent_step in valid_checkpoints:

    result = evaluate_checkpoint(
        name,
        path,
        equivalent_step,
    )

    results.append(result)


# ============================================================
# 11. FINAL COMPARISON
# ============================================================

print()
print()
print("=" * 92)
print("FINAL FROZEN LOSS COMPARISON")
print("=" * 92)

print(
    f"{'CHECKPOINT':<25}"
    f"{'EQUIV STEP':>12}"
    f"{'LOSS':>12}"
    f"{'PPL':>12}"
    f"{'VS GOLDEN':>14}"
)

print("-" * 92)


golden_loss = None

for r in results:

    if r["name"] == "golden-106000":
        golden_loss = r["loss"]
        break


for r in results:

    if golden_loss is not None:

        delta_percent = (
            (
                r["loss"]
                - golden_loss
            )
            / golden_loss
            * 100.0
        )

    else:

        delta_percent = float("nan")


    print(
        f"{r['name']:<25}"
        f"{r['equivalent_step']:>12,}"
        f"{r['loss']:>12.6f}"
        f"{r['perplexity']:>12.4f}"
        f"{delta_percent:>+13.3f}%"
    )


# ============================================================
# 12. FIND LOWEST FROZEN LOSS
# ============================================================

best = min(
    results,
    key=lambda x: x["loss"]
)


print()
print("=" * 92)

print(
    "LOWEST FROZEN LOSS:"
)

print(
    f"  Checkpoint:      {best['name']}"
)

print(
    f"  Equivalent step: {best['equivalent_step']:,}"
)

print(
    f"  Frozen loss:     {best['loss']:.6f}"
)

print(
    f"  Perplexity:      {best['perplexity']:.6f}"
)

print("=" * 92)

==============================================================================
MAIA LITE - MULTI-CHECKPOINT FROZEN LOSS TEST
==============================================================================

GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA:    12.8

FOUND:   golden-106000
FOUND:   continuation-65000
FOUND:   continuation-66000
FOUND:   continuation-67000

Loading tokenizer...

Loading FIXED diagnostic dataset...
Samples: 1,024

==============================================================================
EVALUATING: golden-106000
EQUIVALENT STEP: 106,000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Batch  16/ 64 | loss=2.757594
Batch  32/ 64 | loss=2.703455
Batch  48/ 64 | loss=2.737303
Batch  64/ 64 | loss=2.746445

Frozen loss: 2.746445
Perplexity:  15.587114

==============================================================================
EVALUATING: continuation-65000
EQUIVALENT STEP: 171,000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Batch  16/ 64 | loss=2.822682
Batch  32/ 64 | loss=2.771604
Batch  48/ 64 | loss=2.800434
Batch  64/ 64 | loss=2.806730

Frozen loss: 2.806730
Perplexity:  16.555697

==============================================================================
EVALUATING: continuation-66000
EQUIVALENT STEP: 172,000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Batch  16/ 64 | loss=2.827038
Batch  32/ 64 | loss=2.776231
Batch  48/ 64 | loss=2.804904
Batch  64/ 64 | loss=2.810927

Frozen loss: 2.810927
Perplexity:  16.625327

==============================================================================
EVALUATING: continuation-67000
EQUIVALENT STEP: 173,000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Batch  16/ 64 | loss=2.834384
Batch  32/ 64 | loss=2.783465
Batch  48/ 64 | loss=2.811575
Batch  64/ 64 | loss=2.817412

Frozen loss: 2.817412
Perplexity:  16.733495


============================================================================================
FINAL FROZEN LOSS COMPARISON
============================================================================================
CHECKPOINT                 EQUIV STEP        LOSS         PPL     VS GOLDEN
--------------------------------------------------------------------------------------------
golden-106000                 106,000    2.746445     15.5871       +0.000%
continuation-65000            171,000    2.806730     16.5557       +2.195%
continuation-66000            172,000    2.810927     16.6253       +2.348%
continuation-67000            173,000    2.817412     16.7335       +2.584%

============================================================================================
LOWEST FROZEN LOSS:
  Checkpoint:      golden-106000
  Equivalent step: 106,000
  Frozen loss:     2.746445
  Perplexity:      15.587114
============================================================================================

In [ ]:
# ============================================================
# MAIA LITE - BASE MODEL CAPABILITY BENCHMARK
#
# Compare:
#   Golden checkpoint-106000
#   Continuation checkpoint-67000 (equivalent 173000)
#
# PURPOSE:
#   Evaluate what the BASE model can already do BEFORE SFT.
#
# IMPORTANT:
#   - NO training
#   - NO gradients
#   - NO optimizer
#   - NO Trainer
#   - NO checkpoint modifications
#
# Tests:
#   - English / Portuguese / Spanish
#   - factual completion
#   - semantic completion
#   - simple reasoning
#   - mathematics
#   - Python
#   - structured patterns
#   - few-shot behavior
#   - multiple-choice log probabilities
# ============================================================

import os
import gc
import math
import json
import torch

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

CONTINUATION_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuacao_a100",
    "checkpoint-67000"
)

DIAGNOSTIC_DIR = os.path.join(
    PROJECT_DIR,
    "diagnostics"
)

os.makedirs(
    DIAGNOSTIC_DIR,
    exist_ok=True
)

RESULT_FILE = os.path.join(
    DIAGNOSTIC_DIR,
    "base_capability_106k_vs_173k.json"
)


# ============================================================
# 2. GENERATION CONFIGURATION
# ============================================================

MAX_NEW_TOKENS = 80

# Greedy decoding is deliberate.
#
# Both checkpoints receive exactly the same deterministic
# generation conditions.
DO_SAMPLE = False


# ============================================================
# 3. DEVICE
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU not available.")

device = torch.device("cuda")

print("=" * 78)
print("MAIA LITE - BASE MODEL CAPABILITY BENCHMARK")
print("=" * 78)

print()
print(f"GPU:     {torch.cuda.get_device_name(0)}")
print(f"PyTorch: {torch.__version__}")
print(f"CUDA:    {torch.version.cuda}")
print()


# ============================================================
# 4. CHECKPOINT VERIFICATION
# ============================================================

for path in [
    GOLDEN_CHECKPOINT,
    CONTINUATION_CHECKPOINT,
]:
    if not os.path.isdir(path):
        raise RuntimeError(
            f"Checkpoint not found:\n{path}"
        )


# ============================================================
# 5. TOKENIZER
# ============================================================

print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(
    f"Vocabulary: {tokenizer.vocab_size:,}"
)

print()


# ============================================================
# 6. GENERATION TESTS
#
# These are BASE MODEL completions.
# They are intentionally NOT chat/instruction prompts.
# ============================================================

TESTS = [

    # --------------------------------------------------------
    # ENGLISH - LANGUAGE / FACTUAL
    # --------------------------------------------------------

    {
        "id": "EN01",
        "category": "English factual",
        "prompt":
            "The capital of France is",
    },

    {
        "id": "EN02",
        "category": "English factual",
        "prompt":
            "The largest planet in the Solar System is",
    },

    {
        "id": "EN03",
        "category": "English factual",
        "prompt":
            "Water freezes at a temperature of",
    },

    {
        "id": "EN04",
        "category": "English semantic",
        "prompt":
            "A dog is an animal and a rose is a",
    },

    {
        "id": "EN05",
        "category": "English continuation",
        "prompt":
            "Artificial intelligence is a field of computer science that",
    },


    # --------------------------------------------------------
    # PORTUGUESE
    # --------------------------------------------------------

    {
        "id": "PT01",
        "category": "Portuguese factual",
        "prompt":
            "A capital do Brasil é",
    },

    {
        "id": "PT02",
        "category": "Portuguese factual",
        "prompt":
            "O maior planeta do Sistema Solar é",
    },

    {
        "id": "PT03",
        "category": "Portuguese semantic",
        "prompt":
            "Um cachorro é um animal e uma rosa é uma",
    },

    {
        "id": "PT04",
        "category": "Portuguese continuation",
        "prompt":
            "A inteligência artificial é uma área da computação que",
    },

    {
        "id": "PT05",
        "category": "Portuguese science",
        "prompt":
            "A água é composta pelos elementos químicos",
    },


    # --------------------------------------------------------
    # SPANISH
    # --------------------------------------------------------

    {
        "id": "ES01",
        "category": "Spanish factual",
        "prompt":
            "La capital de España es",
    },

    {
        "id": "ES02",
        "category": "Spanish factual",
        "prompt":
            "El planeta más grande del Sistema Solar es",
    },

    {
        "id": "ES03",
        "category": "Spanish semantic",
        "prompt":
            "Un perro es un animal y una rosa es una",
    },

    {
        "id": "ES04",
        "category": "Spanish continuation",
        "prompt":
            "La inteligencia artificial es un área de la informática que",
    },


    # --------------------------------------------------------
    # SIMPLE REASONING / PATTERNS
    # --------------------------------------------------------

    {
        "id": "RE01",
        "category": "Sequence",
        "prompt":
            "1, 2, 3, 4, 5,",
    },

    {
        "id": "RE02",
        "category": "Sequence",
        "prompt":
            "2, 4, 6, 8, 10,",
    },

    {
        "id": "RE03",
        "category": "Analogy",
        "prompt":
            "Bird is to sky as fish is to",
    },

    {
        "id": "RE04",
        "category": "Semantic relation",
        "prompt":
            "Paris is in France. Rome is in Italy. Madrid is in",
    },


    # --------------------------------------------------------
    # MATHEMATICS
    # --------------------------------------------------------

    {
        "id": "MA01",
        "category": "Arithmetic",
        "prompt":
            "2 + 2 =",
    },

    {
        "id": "MA02",
        "category": "Arithmetic",
        "prompt":
            "10 * 5 =",
    },

    {
        "id": "MA03",
        "category": "Mathematics",
        "prompt":
            "The square root of 81 is",
    },

    {
        "id": "MA04",
        "category": "Mathematics",
        "prompt":
            "If x + 3 = 7, then x =",
    },


    # --------------------------------------------------------
    # PYTHON
    # --------------------------------------------------------

    {
        "id": "PY01",
        "category": "Python",
        "prompt":
            "def add(a, b):\n    return",
    },

    {
        "id": "PY02",
        "category": "Python",
        "prompt":
            "for i in range(10):\n    print(",
    },

    {
        "id": "PY03",
        "category": "Python",
        "prompt":
            "def square(x):\n    return x",
    },


    # --------------------------------------------------------
    # FEW-SHOT
    # --------------------------------------------------------

    {
        "id": "FS01",
        "category": "Few-shot factual",
        "prompt":
            "Question: What is the capital of Germany?\n"
            "Answer: Berlin.\n\n"
            "Question: What is the capital of Italy?\n"
            "Answer: Rome.\n\n"
            "Question: What is the capital of France?\n"
            "Answer:",
    },

    {
        "id": "FS02",
        "category": "Few-shot Portuguese",
        "prompt":
            "Pergunta: Qual é a capital da Argentina?\n"
            "Resposta: Buenos Aires.\n\n"
            "Pergunta: Qual é a capital de Portugal?\n"
            "Resposta: Lisboa.\n\n"
            "Pergunta: Qual é a capital do Brasil?\n"
            "Resposta:",
    },

    {
        "id": "FS03",
        "category": "Few-shot arithmetic",
        "prompt":
            "2 + 3 = 5\n"
            "4 + 5 = 9\n"
            "7 + 8 =",
    },

    {
        "id": "FS04",
        "category": "Few-shot pattern",
        "prompt":
            "cat -> animal\n"
            "rose -> plant\n"
            "car -> vehicle\n"
            "dog ->",
    },


    # --------------------------------------------------------
    # SCIENTIFIC LANGUAGE
    # --------------------------------------------------------

    {
        "id": "SC01",
        "category": "Scientific continuation",
        "prompt":
            "A neural network consists of",
    },

    {
        "id": "SC02",
        "category": "Scientific continuation",
        "prompt":
            "Machine learning models are trained using",
    },

]


# ============================================================
# 7. MULTIPLE-CHOICE TESTS
#
# Here we calculate conditional log probability.
# This is often more informative than free generation
# for a pretrained base model.
# ============================================================

CHOICE_TESTS = [

    {
        "id": "MC01",
        "prompt":
            "The capital of France is",
        "choices": [
            " Paris",
            " London",
            " Berlin",
            " Madrid",
        ],
        "expected": " Paris",
    },

    {
        "id": "MC02",
        "prompt":
            "A capital do Brasil é",
        "choices": [
            " Brasília",
            " Lisboa",
            " Buenos Aires",
            " Madrid",
        ],
        "expected": " Brasília",
    },

    {
        "id": "MC03",
        "prompt":
            "La capital de España es",
        "choices": [
            " Madrid",
            " Barcelona",
            " Lisboa",
            " Roma",
        ],
        "expected": " Madrid",
    },

    {
        "id": "MC04",
        "prompt":
            "The largest planet in the Solar System is",
        "choices": [
            " Jupiter",
            " Mars",
            " Earth",
            " Venus",
        ],
        "expected": " Jupiter",
    },

    {
        "id": "MC05",
        "prompt":
            "2 + 2 =",
        "choices": [
            " 4",
            " 3",
            " 5",
            " 6",
        ],
        "expected": " 4",
    },

    {
        "id": "MC06",
        "prompt":
            "Bird is to sky as fish is to",
        "choices": [
            " water",
            " forest",
            " desert",
            " mountain",
        ],
        "expected": " water",
    },
]


# ============================================================
# 8. LOAD MODEL
# ============================================================

def load_model(path):

    gc.collect()
    torch.cuda.empty_cache()

    model = GPT2LMHeadModel.from_pretrained(
        path,
        local_files_only=True,
        torch_dtype=torch.bfloat16,
    )

    model.to(device)
    model.eval()

    model.config.use_cache = True

    return model


# ============================================================
# 9. GENERATE
# ============================================================

def generate_completion(model, prompt):

    encoded = tokenizer(
        prompt,
        return_tensors="pt",
    )

    input_ids = encoded[
        "input_ids"
    ].to(device)

    attention_mask = encoded[
        "attention_mask"
    ].to(device)

    prompt_length = input_ids.shape[1]

    with torch.inference_mode():

        output = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=DO_SAMPLE,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=True,
        )

    generated_ids = output[
        0,
        prompt_length:
    ]

    text = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    )

    return text


# ============================================================
# 10. CONDITIONAL LOG PROBABILITY
# ============================================================

def choice_log_probability(
    model,
    prompt,
    choice,
):

    prompt_ids = tokenizer(
        prompt,
        add_special_tokens=False,
    )["input_ids"]

    full_ids = tokenizer(
        prompt + choice,
        add_special_tokens=False,
    )["input_ids"]

    # Number of tokens belonging to the answer.
    choice_length = (
        len(full_ids)
        - len(prompt_ids)
    )

    input_ids = torch.tensor(
        [full_ids],
        dtype=torch.long,
        device=device,
    )

    with torch.inference_mode():

        outputs = model(
            input_ids=input_ids
        )

        logits = outputs.logits

    log_probs = torch.log_softmax(
        logits,
        dim=-1
    )

    # Token at position i predicts token i+1.
    start = len(prompt_ids) - 1

    total_log_prob = 0.0

    for offset in range(choice_length):

        target_position = (
            len(prompt_ids)
            + offset
        )

        prediction_position = (
            target_position - 1
        )

        target_token = full_ids[
            target_position
        ]

        token_log_prob = log_probs[
            0,
            prediction_position,
            target_token
        ]

        total_log_prob += float(
            token_log_prob.cpu()
        )

    # Normalize by answer token count so longer tokenizations
    # are not automatically penalized.
    mean_log_prob = (
        total_log_prob
        / max(choice_length, 1)
    )

    return mean_log_prob


# ============================================================
# 11. TEST ONE MODEL
# ============================================================

def benchmark_model(
    name,
    path,
):

    print()
    print("=" * 78)
    print(f"LOADING {name}")
    print("=" * 78)

    model = load_model(path)

    results = {
        "generation": [],
        "multiple_choice": [],
    }


    # --------------------------------------------------------
    # GENERATION TESTS
    # --------------------------------------------------------

    for index, test in enumerate(
        TESTS,
        start=1,
    ):

        print()
        print("-" * 78)

        print(
            f"{test['id']} | "
            f"{test['category']}"
        )

        print("-" * 78)

        print("PROMPT:")
        print(test["prompt"])

        print()
        print("COMPLETION:")

        completion = generate_completion(
            model,
            test["prompt"],
        )

        print(completion)

        results["generation"].append({
            "id": test["id"],
            "category": test["category"],
            "prompt": test["prompt"],
            "completion": completion,
        })


    # --------------------------------------------------------
    # MULTIPLE CHOICE
    # --------------------------------------------------------

    print()
    print()
    print("=" * 78)
    print("MULTIPLE-CHOICE LOG-PROBABILITY TESTS")
    print("=" * 78)


    for test in CHOICE_TESTS:

        scores = []

        for choice in test["choices"]:

            score = choice_log_probability(
                model,
                test["prompt"],
                choice,
            )

            scores.append({
                "choice": choice,
                "score": score,
            })


        scores.sort(
            key=lambda x: x["score"],
            reverse=True,
        )

        selected = scores[0]["choice"]

        correct = (
            selected
            == test["expected"]
        )


        print()
        print(
            f"{test['id']} | "
            f"{test['prompt']}"
        )

        for item in scores:

            marker = (
                " <-- SELECTED"
                if item["choice"] == selected
                else ""
            )

            print(
                f"  {item['choice']!r:<20}"
                f"{item['score']:>10.4f}"
                f"{marker}"
            )

        print(
            f"Expected: {test['expected']!r}"
        )

        print(
            f"Correct:  {correct}"
        )


        results[
            "multiple_choice"
        ].append({
            "id": test["id"],
            "prompt": test["prompt"],
            "expected": test["expected"],
            "selected": selected,
            "correct": correct,
            "scores": scores,
        })


    del model

    gc.collect()
    torch.cuda.empty_cache()

    return results


# ============================================================
# 12. RUN GOLDEN 106K
# ============================================================

golden_results = benchmark_model(
    "GOLDEN 106K",
    GOLDEN_CHECKPOINT,
)


# ============================================================
# 13. RUN CONTINUATION 67K
# ============================================================

continuation_results = benchmark_model(
    "CONTINUATION 67K / EQUIVALENT 173K",
    CONTINUATION_CHECKPOINT,
)


# ============================================================
# 14. MULTIPLE-CHOICE SUMMARY
# ============================================================

def count_correct(results):

    return sum(
        1
        for x in results["multiple_choice"]
        if x["correct"]
    )


golden_correct = count_correct(
    golden_results
)

continuation_correct = count_correct(
    continuation_results
)


print()
print()
print("=" * 78)
print("MULTIPLE-CHOICE SUMMARY")
print("=" * 78)

print()

print(
    f"Golden 106K:       "
    f"{golden_correct}/"
    f"{len(CHOICE_TESTS)}"
)

print(
    f"Continuation 173K: "
    f"{continuation_correct}/"
    f"{len(CHOICE_TESTS)}"
)


# ============================================================
# 15. SIDE-BY-SIDE GENERATION RESULTS
# ============================================================

print()
print()
print("=" * 78)
print("SIDE-BY-SIDE GENERATION COMPARISON")
print("=" * 78)


for i, test in enumerate(TESTS):

    golden_text = (
        golden_results[
            "generation"
        ][i]["completion"]
    )

    continuation_text = (
        continuation_results[
            "generation"
        ][i]["completion"]
    )

    print()
    print("#" * 78)

    print(
        f"{test['id']} | "
        f"{test['category']}"
    )

    print("#" * 78)

    print()
    print("PROMPT:")
    print(test["prompt"])

    print()
    print("--- GOLDEN 106K ---")
    print(golden_text)

    print()
    print("--- CONTINUATION 173K ---")
    print(continuation_text)


# ============================================================
# 16. SAVE EVERYTHING
# ============================================================

all_results = {

    "configuration": {
        "max_new_tokens": MAX_NEW_TOKENS,
        "do_sample": DO_SAMPLE,
    },

    "golden_106000": (
        golden_results
    ),

    "continuation_67000_equivalent_173000": (
        continuation_results
    ),

    "multiple_choice_summary": {
        "golden_correct": golden_correct,
        "continuation_correct": (
            continuation_correct
        ),
        "total": len(CHOICE_TESTS),
    },
}


with open(
    RESULT_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        all_results,
        f,
        indent=2,
        ensure_ascii=False,
    )


print()
print()
print("=" * 78)
print("BENCHMARK COMPLETE")
print("=" * 78)

print()
print("Results saved to:")
print(RESULT_FILE)

==============================================================================
MAIA LITE - BASE MODEL CAPABILITY BENCHMARK
==============================================================================

GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA:    12.8

Loading tokenizer...
Vocabulary: 50,257


==============================================================================
LOADING GOLDEN 106K
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
EN01 | English factual
------------------------------------------------------------------------------
PROMPT:
The capital of France is

COMPLETION:
 the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel of the Channel of the Sable.

The capital is located on the island of Brittany, on the southern shore of the Channel of the Sable. The island is the largest island in the Channel of the Sable, and is

------------------------------------------------------------------------------
EN02 | English factual
------------------------------------------------------------------------------
PROMPT:
The largest planet in the Solar System is

COMPLETION:
 the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the

------------------------------------------------------------------------------
EN03 | English factual
------------------------------------------------------------------------------
PROMPT:
Water freezes at a temperature of

COMPLETION:
 , or , are a series of freezes that are formed by the precipitation of water. The freezes are formed by the precipitation of water, such as snow, snow, or snow. The water freezes are formed by the precipitation of water, such as snow, snow, or snow.

The water freezes are formed by the precipitation of snow, snow, or snow. The water

------------------------------------------------------------------------------
EN04 | English semantic
------------------------------------------------------------------------------
PROMPT:
A dog is an animal and a rose is a

COMPLETION:
 type of rose.

Buddhism

Buddhism is a type of vegetarianism that involves the use of a variety of vegetarian or veganical techniques. The most common method of vegetarianism is to use a variety of vegetarian or veganical techniques. The most common method of vegetarianism is to use a variety of vegetarian or vegan

------------------------------------------------------------------------------
EN05 | English continuation
------------------------------------------------------------------------------
PROMPT:
Artificial intelligence is a field of computer science that

COMPLETION:
 focuses on the application of artificial intelligence to the study of artificial intelligence.

History

The field of artificial intelligence was founded in the early 1970s by the American computer programmer and computer programmer John C. Allen. Allen was the first to develop artificial intelligence, and the first to use artificial intelligence to study the application of artificial intelligence. Allen's work was the first to use artificial intelligence

------------------------------------------------------------------------------
PT01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
A capital do Brasil é

COMPLETION:
 a capital do estado do Brasil, sendo também a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo, fundada em 1545, foi fundada por Pedro Álvares Cabral, que se instalou na margem direita do rio Uruguai, em 1545.

A cidade foi fundada em 1545, por Pedro Álvares Cabral, que se

------------------------------------------------------------------------------
PT02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
O maior planeta do Sistema Solar é

COMPLETION:
 o planeta que orbita o planeta Terra, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com

------------------------------------------------------------------------------
PT03 | Portuguese semantic
------------------------------------------------------------------------------
PROMPT:
Um cachorro é um animal e uma rosa é uma

COMPLETION:
 espécie de animal que se alimenta de frutas e legumes.

Cães
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domesticadas
Cães domestic

------------------------------------------------------------------------------
PT04 | Portuguese continuation
------------------------------------------------------------------------------
PROMPT:
A inteligência artificial é uma área da computação que

COMPLETION:
 estuda a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial, a inteligência artificial

------------------------------------------------------------------------------
PT05 | Portuguese science
------------------------------------------------------------------------------
PROMPT:
A água é composta pelos elementos químicos

COMPLETION:
 constituintes da água. A água é composta por água e sais minerais, sendo o restante composto por minerais. A água é composta por minerais, como o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro, o ferro,

------------------------------------------------------------------------------
ES01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
La capital de España es

COMPLETION:
 la ciudad más poblada de la República de España, con una población de  habitantes (2022). Es la capital de la provincia homónima, en la región de Castilla-La Mancha.

La ciudad se encuentra en el centro de la provincia, en la región de Castilla-La Mancha, a orillas del río Guadiana, a unos  al oeste de Madrid. Es la capital de la provincia homónima,

------------------------------------------------------------------------------
ES02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
El planeta más grande del Sistema Solar es

COMPLETION:
 el planeta más grande del sistema solar, con una superficie de aproximadamente  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km².

El

------------------------------------------------------------------------------
ES03 | Spanish semantic
------------------------------------------------------------------------------
PROMPT:
Un perro es un animal y una rosa es una

COMPLETION:
 rosa que se puede encontrar en los gatos.

El término "lechero" se refiere a un perro que se puede encontrar en los gatos, pero no es un perro salvaje.

El perro es un animal doméstico, pero no es un perro salvaje.

El perro es un animal doméstico, pero no es un perro salvaje.

El perro es un animal doméstico, pero

------------------------------------------------------------------------------
ES04 | Spanish continuation
------------------------------------------------------------------------------
PROMPT:
La inteligencia artificial es un área de la informática que

COMPLETION:
 se ocupa de la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la inteligencia artificial, la

------------------------------------------------------------------------------
RE01 | Sequence
------------------------------------------------------------------------------
PROMPT:
1, 2, 3, 4, 5,

COMPLETION:
 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 13, 14, 14, 15, 16, 17, 17, 17, 18, 18, 19, 20, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,

------------------------------------------------------------------------------
RE02 | Sequence
------------------------------------------------------------------------------
PROMPT:
2, 4, 6, 8, 10,

COMPLETION:
 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,

------------------------------------------------------------------------------
RE03 | Analogy
------------------------------------------------------------------------------
PROMPT:
Bird is to sky as fish is to

COMPLETION:
 be found in the sky.

Bird may also refer to:

Places

United States
 Bird, Alabama, a city in Alabama
 Bird, Illinois, a city in Illinois
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri

------------------------------------------------------------------------------
RE04 | Semantic relation
------------------------------------------------------------------------------
PROMPT:
Paris is in France. Rome is in Italy. Madrid is in

COMPLETION:
 Spain.

Paris may also refer to:

Places

United States
 Paris, Texas, a city in the United States
 Paris, Illinois, a city in the United States
 Paris, Missouri, a city in the United States
 Paris, Missouri, a city in the United States
 Paris, Missouri, a city in the United States
 Paris, Missouri, a city in

------------------------------------------------------------------------------
MA01 | Arithmetic
------------------------------------------------------------------------------
PROMPT:
2 + 2 =

COMPLETION:
 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2

------------------------------------------------------------------------------
MA02 | Arithmetic
------------------------------------------------------------------------------
PROMPT:
10 * 5 =

COMPLETION:
 5

4 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5

------------------------------------------------------------------------------
MA03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
The square root of 81 is

COMPLETION:
 a major component of the median nerve of the median nerve. It is a branch of the median nerve.

Anatomy

Origin
The square root of 81 is a branch of the median nerve of median nerve. It is a branch of the median nerve of median nerve.

Course and relations
It is distributed to the median nerve and the median nerve.


------------------------------------------------------------------------------
MA04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
If x + 3 = 7, then x =

COMPLETION:
 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x =

------------------------------------------------------------------------------
PY01 | Python
------------------------------------------------------------------------------
PROMPT:
def add(a, b):
    return

COMPLETION:
 (a, b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):

------------------------------------------------------------------------------
PY02 | Python
------------------------------------------------------------------------------
PROMPT:
for i in range(10):
    print(

COMPLETION:
x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(x)
    print(

------------------------------------------------------------------------------
PY03 | Python
------------------------------------------------------------------------------
PROMPT:
def square(x):
    return x

COMPLETION:
 :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x

------------------------------------------------------------------------------
FS01 | Few-shot factual
------------------------------------------------------------------------------
PROMPT:
Question: What is the capital of Germany?
Answer: Berlin.

Question: What is the capital of Italy?
Answer: Rome.

Question: What is the capital of France?
Answer:

COMPLETION:
 Berlin.

External links
Official website

Geography of Berlin
Germany–France relations
Germany–France relations
Germany–France relations
Germany–France relations
Germany–France relations
Germany–Germany relations
Germany–France relations
Germany–Germany relations
Germany–Germany relations
Germany–Germany relations
Germany–Germany relations
Germany–Germany relations
Germany–Germany relations


------------------------------------------------------------------------------
FS02 | Few-shot Portuguese
------------------------------------------------------------------------------
PROMPT:
Pergunta: Qual é a capital da Argentina?
Resposta: Buenos Aires.

Pergunta: Qual é a capital de Portugal?
Resposta: Lisboa.

Pergunta: Qual é a capital do Brasil?
Resposta:

COMPLETION:
 Lisboa.

Pergunta: Qual é a capital de Portugal?

Pergunta: Qual é a capital de Portugal?

Pergunta: Qual é a capital de Portugal?

Pergunta: Qual é a capital de Portugal?

Pergunta: Qual é a capital de Portugal?

Pergunta: Qual é a capital de Portugal?

Pergunta: Qual

------------------------------------------------------------------------------
FS03 | Few-shot arithmetic
------------------------------------------------------------------------------
PROMPT:
2 + 3 = 5
4 + 5 = 9
7 + 8 =

COMPLETION:
 9

4 + 5 = 9 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5 + 5

------------------------------------------------------------------------------
FS04 | Few-shot pattern
------------------------------------------------------------------------------
PROMPT:
cat -> animal
rose -> plant
car -> vehicle
dog ->

COMPLETION:
 animal

Desambiguação
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal

------------------------------------------------------------------------------
SC01 | Scientific continuation
------------------------------------------------------------------------------
PROMPT:
A neural network consists of

COMPLETION:
 a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected by a network of neurons that are interconnected

------------------------------------------------------------------------------
SC02 | Scientific continuation
------------------------------------------------------------------------------
PROMPT:
Machine learning models are trained using

COMPLETION:
 the principles of the mind to teach the mind to learn about the mind. Machines are used to teach the mind to learn about the mind, and to teach the mind to learn about the mind to learn about the mind. Machines are used to teach the mind to learn about the mind to learn about the mind to learn about the mind to learn about the mind to learn about the mind to learn


==============================================================================
MULTIPLE-CHOICE LOG-PROBABILITY TESTS
==============================================================================

MC01 | The capital of France is
  ' Paris'               -4.8438 <-- SELECTED
  ' London'              -7.4375
  ' Berlin'             -10.6250
  ' Madrid'             -10.6250
Expected: ' Paris'
Correct:  True

MC02 | A capital do Brasil é
  ' Brasília'            -6.3750 <-- SELECTED
  ' Buenos Aires'        -6.4375
  ' Lisboa'             -11.9375
  ' Madrid'             -14.0000
Expected: ' Brasília'
Correct:  True

MC03 | La capital de España es
  ' Madrid'              -4.9688 <-- SELECTED
  ' Barcelona'           -6.0312
  ' Roma'                -8.5625
  ' Lisboa'              -9.0625
Expected: ' Madrid'
Correct:  True

MC04 | The largest planet in the Solar System is
  ' Earth'               -3.5781 <-- SELECTED
  ' Mars'                -3.7031
  ' Venus'               -4.8438
  ' Jupiter'             -5.0312
Expected: ' Jupiter'
Correct:  False

MC05 | 2 + 2 =
  ' 4'                   -2.1094 <-- SELECTED
  ' 3'                   -2.2969
  ' 5'                   -2.9219
  ' 6'                   -4.1875
Expected: ' 4'
Correct:  True

MC06 | Bird is to sky as fish is to
  ' water'               -6.5938 <-- SELECTED
  ' forest'              -8.5000
  ' desert'              -9.7500
  ' mountain'           -10.4375
Expected: ' water'
Correct:  True

==============================================================================
LOADING CONTINUATION 67K / EQUIVALENT 173K
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
EN01 | English factual
------------------------------------------------------------------------------
PROMPT:
The capital of France is

COMPLETION:
 the capital of the French overseas department of Brittany. It is located in the south-east of France, in the region of Brittany.

History

The capital of France was founded in the 12th century by the French king Louis IX of France. The capital was built on the site of the former royal residence of the Château de Saint-Germain-en-

------------------------------------------------------------------------------
EN02 | English factual
------------------------------------------------------------------------------
PROMPT:
The largest planet in the Solar System is

COMPLETION:
 the Sun's largest planet, the Sun's largest planet. The Sun's largest planet is the Sun's largest planet, the Sun's largest planet. The Sun's largest planet is the Sun's largest planet, the Sun's largest planet. The Sun's largest planet is the Sun's largest planet, the Sun's largest planet. The Sun's largest planet is the Sun's largest planet, the Sun

------------------------------------------------------------------------------
EN03 | English factual
------------------------------------------------------------------------------
PROMPT:
Water freezes at a temperature of

COMPLETION:
  is a temperature of  in the atmosphere. It is a temperature of  in the atmosphere. It is a temperature of  in the atmosphere.

Water freezes at a temperature of  in the atmosphere are often called "water freezes".

Water freezes at a temperature of  in the atmosphere are called "water freezes".

Water freezes at a temperature of

------------------------------------------------------------------------------
EN04 | English semantic
------------------------------------------------------------------------------
PROMPT:
A dog is an animal and a rose is a

COMPLETION:
 type of rose.

The dog is a type of rose, a type of rose. It is a type of rose that is a type of rose.

The dog is a type of rose that is a type of rose. It is a type of rose that is a type of rose that is a type of rose. It is a type of rose that is a type of rose that

------------------------------------------------------------------------------
EN05 | English continuation
------------------------------------------------------------------------------
PROMPT:
Artificial intelligence is a field of computer science that

COMPLETION:
 studies the interaction of a computer with a computer.

History
The concept of artificial intelligence was first proposed by John C. D. McIntyre in the early 1980s.

In the early 1980s, the concept of artificial intelligence was first proposed by John C. D. McIntyre, who was working at the University of California, Berkeley. He was working at

------------------------------------------------------------------------------
PT01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
A capital do Brasil é

COMPLETION:
 a capital do país, e a capital federal do Brasil.

A capital do Brasil é a capital do país, e a capital federal do Brasil.

História
A capital do Brasil foi fundada em 15 de agosto de 1563, por Dom João III, com o nome de Vila de Nossa Senhora da Conceição de Belém.

A cidade foi fundada em 1563, por Dom

------------------------------------------------------------------------------
PT02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
O maior planeta do Sistema Solar é

COMPLETION:
 um planeta que orbita a Terra, com uma massa de aproximadamente 1,5 milhões de massas solares. O planeta é o mais massivo planeta do Sistema Solar, com uma massa de aproximadamente 1,5 milhões de massas solares. O planeta é o mais massivo planeta do Sistema Solar, com uma massa de aproximadamente 1,5 milhões de massas solares.

O planeta foi descoberto em 16 de

------------------------------------------------------------------------------
PT03 | Portuguese semantic
------------------------------------------------------------------------------
PROMPT:
Um cachorro é um animal e uma rosa é uma

COMPLETION:
 espécie de roedor da família dos roedores.

Etimologia
"Chorro" é um termo originário do tupi kûrâ, que significa "pequena cabeça".

Características
Os cachorros são animais de pequeno porte, com uma cabeça grande e cabeça grande. Os cachorros são geralmente de tamanho médio, com uma cabeça grande e cabeça grande. Os cach

------------------------------------------------------------------------------
PT04 | Portuguese continuation
------------------------------------------------------------------------------
PROMPT:
A inteligência artificial é uma área da computação que

COMPLETION:
 estuda a inteligência artificial.

A inteligência artificial é um campo de estudo que estuda a inteligência artificial, a inteligência artificial e a inteligência artificial.

A inteligência artificial é um campo de estudo que estuda a inteligência artificial, a inteligência artificial e a inteligência artificial.

A inteligência artificial é um campo de estudo que estuda a inteligência artificial, a inteligência artificial e a inteligência artificial.

A

------------------------------------------------------------------------------
PT05 | Portuguese science
------------------------------------------------------------------------------
PROMPT:
A água é composta pelos elementos químicos

COMPLETION:
 dissolvidos em água, como o sódio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio, o potássio

------------------------------------------------------------------------------
ES01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
La capital de España es

COMPLETION:
 la capital de España, y la ciudad más poblada de España. La capital de España es la ciudad más poblada de España, con una población de  habitantes (INE 2022). La capital de España es la segunda ciudad más poblada de Europa, después de Madrid, con una población de  habitantes (INE 2022).

La capital de España es la capital de España, y la segunda más poblada de

------------------------------------------------------------------------------
ES02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
El planeta más grande del Sistema Solar es

COMPLETION:
 el más grande de los planetas del sistema solar. El planeta más grande del sistema solar es el más grande de los planetas del sistema solar. El planeta más grande del sistema solar es el más grande de los planetas del sistema solar. El planeta más grande del sistema solar es el más grande de los planetas del sistema solar. El planeta más grande del sistema solar es el más grande de los planetas del sistema

------------------------------------------------------------------------------
ES03 | Spanish semantic
------------------------------------------------------------------------------
PROMPT:
Un perro es un animal y una rosa es una

COMPLETION:
 especie de perro de la familia de los gatos.

Características
Es un perro de tamaño mediano, de tamaño mediano, de tamaño mediano, de color blanco, con una cola corta y una cola corta. Su cuerpo es de color blanco, con una cola corta y una cola corta. Su cuerpo es de color blanco, con una cola corta y una cola corta. Su cola

------------------------------------------------------------------------------
ES04 | Spanish continuation
------------------------------------------------------------------------------
PROMPT:
La inteligencia artificial es un área de la informática que

COMPLETION:
 estudia la inteligencia artificial y la inteligencia artificial.

La inteligencia artificial es una disciplina que estudia la inteligencia artificial y la inteligencia artificial. La inteligencia artificial es una disciplina que estudia la inteligencia artificial y la inteligencia artificial. La inteligencia artificial es una disciplina que estudia la inteligencia artificial y la inteligencia artificial. La inteligencia artificial es una disciplina que estudia la inteligencia artificial y la inteligencia artificial. La inteligencia artificial es una

------------------------------------------------------------------------------
RE01 | Sequence
------------------------------------------------------------------------------
PROMPT:
1, 2, 3, 4, 5,

COMPLETION:
 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,

------------------------------------------------------------------------------
RE02 | Sequence
------------------------------------------------------------------------------
PROMPT:
2, 4, 6, 8, 10,

COMPLETION:
 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,

------------------------------------------------------------------------------
RE03 | Analogy
------------------------------------------------------------------------------
PROMPT:
Bird is to sky as fish is to

COMPLETION:
 be found in the waters of the Atlantic Ocean.

Bird may also refer to:

Places
Bird, New South Wales, a suburb of Sydney, Australia
Bird, Queensland, a suburb of Brisbane, Australia
Bird, New South Wales, a suburb of Sydney, Australia
Bird, New South Wales, a suburb of Sydney, Australia
Bird,

------------------------------------------------------------------------------
RE04 | Semantic relation
------------------------------------------------------------------------------
PROMPT:
Paris is in France. Rome is in Italy. Madrid is in

COMPLETION:
 Spain.

Paris may also refer to:

Places
Paris, France, a commune in the department of Alpes-Maritimes
Paris, France, a commune in the department of Alpes-Maritimes
Paris, France, a commune in the department of Alpes-Maritimes
Paris, France, a commune in the department of Alpes-Maritimes
Paris,

------------------------------------------------------------------------------
MA01 | Arithmetic
------------------------------------------------------------------------------
PROMPT:
2 + 2 =

COMPLETION:
 2 (2 + 2 + 2) is a British television series that aired on ITV from 6 September to 7 October 2006. It was written by David A. McIntyre and directed by David McIntyre.

The series was produced by the BBC and broadcast on ITV from 6 September to 7 October 2006.

Plot
The series revolves around the lives of two young

------------------------------------------------------------------------------
MA02 | Arithmetic
------------------------------------------------------------------------------
PROMPT:
10 * 5 =

COMPLETION:
 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 = 5 =

------------------------------------------------------------------------------
MA03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
The square root of 81 is

COMPLETION:
 a type of seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed seed

------------------------------------------------------------------------------
MA04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
If x + 3 = 7, then x =

COMPLETION:
 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x =

------------------------------------------------------------------------------
PY01 | Python
------------------------------------------------------------------------------
PROMPT:
def add(a, b):
    return

COMPLETION:
 (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return

------------------------------------------------------------------------------
PY02 | Python
------------------------------------------------------------------------------
PROMPT:
for i in range(10):
    print(

COMPLETION:
10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1)
    print(10:1

------------------------------------------------------------------------------
PY03 | Python
------------------------------------------------------------------------------
PROMPT:
def square(x):
    return x

COMPLETION:
:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x:
    return x

------------------------------------------------------------------------------
FS01 | Few-shot factual
------------------------------------------------------------------------------
PROMPT:
Question: What is the capital of Germany?
Answer: Berlin.

Question: What is the capital of Italy?
Answer: Rome.

Question: What is the capital of France?
Answer:

COMPLETION:
 Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.
Answer: Paris.


------------------------------------------------------------------------------
FS02 | Few-shot Portuguese
------------------------------------------------------------------------------
PROMPT:
Pergunta: Qual é a capital da Argentina?
Resposta: Buenos Aires.

Pergunta: Qual é a capital de Portugal?
Resposta: Lisboa.

Pergunta: Qual é a capital do Brasil?
Resposta:

COMPLETION:
 Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.
Resposta: Buenos Aires.

------------------------------------------------------------------------------
FS03 | Few-shot arithmetic
------------------------------------------------------------------------------
PROMPT:
2 + 3 = 5
4 + 5 = 9
7 + 8 =

COMPLETION:
 9
9 + 8 = 9
10 + 8 = 9
11 + 8 = 9
11 + 8 = 9
12 + 8 = 9
13 + 8 = 9
14 + 8 = 9
15 + 8 = 9
16 + 8 = 9
17 + 8 = 9
18 + 8 = 9
19 + 8 = 9
20 + 8 = 9


------------------------------------------------------------------------------
FS04 | Few-shot pattern
------------------------------------------------------------------------------
PROMPT:
cat -> animal
rose -> plant
car -> vehicle
dog ->

COMPLETION:
 animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal -> animal ->

------------------------------------------------------------------------------
SC01 | Scientific continuation
------------------------------------------------------------------------------
PROMPT:
A neural network consists of

COMPLETION:
 a network of neuronal cells that are located in the brain.

The neural network consists of a network of neuronal cells that are located in the brain. The neural network consists of a network of neuronal cells that are located in the brain. The neural network consists of a network of neuronal cells that are located in the brain. The neural network consists of a network of neuronal cells

------------------------------------------------------------------------------
SC02 | Scientific continuation
------------------------------------------------------------------------------
PROMPT:
Machine learning models are trained using

COMPLETION:
 a computer model.

Machine

Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
Machine
M


==============================================================================
MULTIPLE-CHOICE LOG-PROBABILITY TESTS
==============================================================================

MC01 | The capital of France is
  ' Paris'               -5.7812 <-- SELECTED
  ' London'              -7.5625
  ' Berlin'             -10.4375
  ' Madrid'             -10.8125
Expected: ' Paris'
Correct:  True

MC02 | A capital do Brasil é
  ' Brasília'            -6.4375 <-- SELECTED
  ' Buenos Aires'        -6.5314
  ' Lisboa'             -11.1250
  ' Madrid'             -13.3750
Expected: ' Brasília'
Correct:  True

MC03 | La capital de España es
  ' Madrid'              -5.9375 <-- SELECTED
  ' Barcelona'           -6.4375
  ' Roma'                -8.5000
  ' Lisboa'              -9.6875
Expected: ' Madrid'
Correct:  True

MC04 | The largest planet in the Solar System is
  ' Earth'               -3.3594 <-- SELECTED
  ' Jupiter'             -4.5625
  ' Venus'               -4.8750
  ' Mars'                -5.0625
Expected: ' Jupiter'
Correct:  False

MC05 | 2 + 2 =
  ' 3'                   -2.2656 <-- SELECTED
  ' 4'                   -2.4531
  ' 5'                   -3.1406
  ' 6'                   -3.5156
Expected: ' 4'
Correct:  False

MC06 | Bird is to sky as fish is to
  ' water'               -6.9062 <-- SELECTED
  ' forest'              -8.8750
  ' mountain'           -10.0625
  ' desert'             -11.0000
Expected: ' water'
Correct:  True


==============================================================================
MULTIPLE-CHOICE SUMMARY
==============================================================================

Golden 106K:       5/6
Continuation 173K: 4/6


==============================================================================
SIDE-BY-SIDE GENERATION COMPARISON
==============================================================================

##############################################################################
EN01 | English factual
##############################################################################

PROMPT:
The capital of France is

--- GOLDEN 106K ---
 the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel of the Channel of the Sable.

The capital is located on the island of Brittany, on the southern shore of the Channel of the Sable. The island is the largest island in the Channel of the Sable, and is

--- CONTINUATION 173K ---
 the capital of the French overseas department of Brittany. It is located in the south-east of France, in the region of Brittany.

History

The capital of France was founded in the 12th century by the French king Louis IX of France. The capital was built on the site of the former royal residence of the Château de Saint-Germain-en-

##############################################################################
EN02 | English factual
##############################################################################

PROMPT:
The largest planet in the Solar System is

--- GOLDEN 106K ---

In [ ]:
# ============================================================
# MAIA LITE - EXPERIMENTAL SFT FROM GOLDEN 106K
#
# PURPOSE:
#   Determine whether checkpoint-106000 already contains
#   enough pretrained capability to become useful after a
#   relatively small supervised instruction fine-tuning.
#
# THIS IS NOT THE FINAL MAIA LITE FINE-TUNING.
#
# Base:
#   golden checkpoint-106000
#
# Languages:
#   English     40%
#   Portuguese  30%
#   Spanish     30%
#
# Training:
#   3,000 optimizer steps
#   checkpoints every 500 steps
#
# IMPORTANT:
#   - Does NOT modify checkpoint-106000
#   - Uses a completely separate output directory
#   - Can be safely discarded after the experiment
# ============================================================


# ============================================================
# 0. ENVIRONMENT
# ============================================================

import os

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import gc
import json
import torch

from datasets import (
    load_dataset,
    interleave_datasets,
)

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador",
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000",
)

OUTPUT_DIR = os.path.join(
    PROJECT_DIR,
    "experiments",
    "sft_from_106k",
)

FINAL_MODEL_DIR = os.path.join(
    OUTPUT_DIR,
    "maia_lite_106k_sft_3000",
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True,
)


# ============================================================
# 2. VERIFY GOLDEN CHECKPOINT
# ============================================================

if not os.path.isdir(GOLDEN_CHECKPOINT):
    raise RuntimeError(
        "Golden checkpoint not found:\n"
        + GOLDEN_CHECKPOINT
    )


print("=" * 78)
print("MAIA LITE - EXPERIMENTAL SFT")
print("=" * 78)

print()
print("Base checkpoint:")
print(GOLDEN_CHECKPOINT)

print()
print("Output directory:")
print(OUTPUT_DIR)


# ============================================================
# 3. GPU
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA GPU is required for this experiment."
    )

device = torch.device("cuda")

gpu_name = torch.cuda.get_device_name(0)

print()
print(f"GPU:     {gpu_name}")
print(f"PyTorch: {torch.__version__}")
print(f"CUDA:    {torch.version.cuda}")


# ============================================================
# 4. TOKENIZER
# ============================================================

print()
print("Loading Maia Lite tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(
    f"Vocabulary: {tokenizer.vocab_size:,}"
)

print(
    f"EOS token:  {tokenizer.eos_token_id}"
)

print(
    f"PAD token:  {tokenizer.pad_token_id}"
)


# ============================================================
# 5. LOAD GOLDEN MODEL
#
# IMPORTANT:
# We load ONLY checkpoint-106000.
#
# No automatic "latest checkpoint" detection.
# ============================================================

print()
print("=" * 78)
print("LOADING GOLDEN 106K")
print("=" * 78)

model = GPT2LMHeadModel.from_pretrained(
    GOLDEN_CHECKPOINT,
    local_files_only=True,
    torch_dtype=torch.bfloat16,
)

model.to(device)

model.gradient_checkpointing_enable()

model.config.use_cache = False

print()
print(
    f"Parameters: "
    f"{sum(p.numel() for p in model.parameters()):,}"
)


# ============================================================
# 6. DATASETS
# ============================================================

print()
print("=" * 78)
print("LOADING INSTRUCTION DATASETS")
print("=" * 78)


# ------------------------------------------------------------
# ENGLISH
#
# Schema:
#   instruction
#   input
#   output
# ------------------------------------------------------------

print()
print("Loading English Alpaca...")

ds_en = load_dataset(
    "tatsu-lab/alpaca",
    split="train",
    streaming=True,
)


# ------------------------------------------------------------
# PORTUGUESE
#
# Alpaca
#
# We preserve the dataset already selected for the Maia
# project. Schema is detected defensively below.
# ------------------------------------------------------------

print("Loading Portuguese Alpaca...")

ds_pt = load_dataset(
    "pinzhenchen/alpaca-cleaned-pt",
    split="train",
    streaming=True,
)


# ------------------------------------------------------------
# SPANISH
#
# Schema:
#   instruction
#   input
#   output
# ------------------------------------------------------------

print("Loading Spanish Alpaca...")

ds_es = load_dataset(
    "bertin-project/alpaca-spanish",
    split="train",
    streaming=True,
)


# ============================================================
# 7. SHOW DATASET SCHEMAS
# ============================================================

print()
print("Dataset schemas:")

print(
    "EN:",
    list(ds_en.features.keys())
)

print(
    "PT:",
    list(ds_pt.features.keys())
)

print(
    "ES:",
    list(ds_es.features.keys())
)


# ============================================================
# 8. COMMON CHAT FORMAT
#
# We deliberately use a very simple format:
#
# User: ...
# Assistant: ...
# <EOS>
#
# Maia Chat can later use exactly this template.
# ============================================================

def format_alpaca(example):

    instruction = (
        example.get("instruction", "")
        or ""
    ).strip()

    input_text = (
        example.get("input", "")
        or ""
    ).strip()

    output = (
        example.get("output", "")
        or ""
    ).strip()

    if input_text:

        user_text = (
            instruction
            + "\n\n"
            + input_text
        )

    else:

        user_text = instruction

    text = (
        "User: "
        + user_text
        + "\nAssistant: "
        + output
        + tokenizer.eos_token
    )

    return {
        "text_formatted": text
    }


# ============================================================
# 9. NORMALIZE DATASETS
# ============================================================

print()
print("Normalizing datasets...")


ds_en = ds_en.map(
    format_alpaca,
    remove_columns=list(
        ds_en.features.keys()
    ),
)


ds_pt = ds_pt.map(
    format_alpaca,
    remove_columns=list(
        ds_pt.features.keys()
    ),
)


ds_es = ds_es.map(
    format_alpaca,
    remove_columns=list(
        ds_es.features.keys()
    ),
)


# ============================================================
# 10. REMOVE EMPTY / BROKEN EXAMPLES
# ============================================================

def valid_example(example):

    text = example.get(
        "text_formatted",
        ""
    )

    if not text:
        return False

    # Require meaningful User and Assistant sections.
    if "User:" not in text:
        return False

    if "Assistant:" not in text:
        return False

    # Avoid pathological empty samples.
    return len(text.strip()) >= 20


ds_en = ds_en.filter(valid_example)
ds_pt = ds_pt.filter(valid_example)
ds_es = ds_es.filter(valid_example)


# ============================================================
# 11. INTERLEAVE LANGUAGES
#
# EN = 40%
# PT = 30%
# ES = 30%
# ============================================================

print()
print(
    "Interleaving languages: "
    "EN=40%, PT=30%, ES=30%"
)

conversation_dataset = interleave_datasets(
    [
        ds_en,
        ds_pt,
        ds_es,
    ],
    probabilities=[
        0.40,
        0.30,
        0.30,
    ],
    seed=42,
    stopping_strategy="all_exhausted",
)


# ============================================================
# 12. TOKENIZATION
# ============================================================

MAX_LENGTH = 1024


def tokenize_function(examples):

    return tokenizer(
        examples["text_formatted"],
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=True,
    )


print()
print("Tokenizing stream...")

tokenized_dataset = conversation_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=[
        "text_formatted"
    ],
)


# ============================================================
# 13. DATA COLLATOR
# ============================================================

data_collator = (
    DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
    )
)


# ============================================================
# 14. TRAINING CONFIGURATION
#
# Experimental SFT:
#
# 3,000 steps.
#
# This is intentionally much shorter than the original
# 20,000-step proposal.
# ============================================================

MAX_STEPS = 3000

PER_DEVICE_BATCH_SIZE = 8

GRADIENT_ACCUMULATION_STEPS = 4

EFFECTIVE_BATCH_SIZE = (
    PER_DEVICE_BATCH_SIZE
    * GRADIENT_ACCUMULATION_STEPS
)


# Conservative LR for full-model SFT.
LEARNING_RATE = 1.0e-5

WARMUP_STEPS = 100

SAVE_STEPS = 500

LOGGING_STEPS = 25


# ============================================================
# 15. PRECISION
# ============================================================

use_bf16 = torch.cuda.is_bf16_supported()

use_fp16 = not use_bf16


print()
print("=" * 78)
print("EXPERIMENT CONFIGURATION")
print("=" * 78)

print(
    f"Max steps:             {MAX_STEPS:,}"
)

print(
    f"Micro batch:           {PER_DEVICE_BATCH_SIZE}"
)

print(
    f"Gradient accumulation: {GRADIENT_ACCUMULATION_STEPS}"
)

print(
    f"Effective batch:       {EFFECTIVE_BATCH_SIZE}"
)

print(
    f"Learning rate:         {LEARNING_RATE:.2e}"
)

print(
    f"Warmup:                {WARMUP_STEPS}"
)

print(
    f"Checkpoint interval:   {SAVE_STEPS}"
)

print(
    f"BF16:                   {use_bf16}"
)

print(
    f"FP16:                   {use_fp16}"
)


# ============================================================
# 16. TRAINING ARGUMENTS
# ============================================================

training_args = TrainingArguments(

    output_dir=OUTPUT_DIR,

    # --------------------------------------------------------
    # Duration
    # --------------------------------------------------------

    max_steps=MAX_STEPS,

    # --------------------------------------------------------
    # Batch
    # --------------------------------------------------------

    per_device_train_batch_size=(
        PER_DEVICE_BATCH_SIZE
    ),

    gradient_accumulation_steps=(
        GRADIENT_ACCUMULATION_STEPS
    ),

    # --------------------------------------------------------
    # Optimization
    # --------------------------------------------------------

    learning_rate=LEARNING_RATE,

    lr_scheduler_type="cosine",

    warmup_steps=WARMUP_STEPS,

    weight_decay=0.01,

    max_grad_norm=1.0,

    optim="adamw_torch",

    # --------------------------------------------------------
    # Precision
    # --------------------------------------------------------

    bf16=use_bf16,

    fp16=use_fp16,

    # --------------------------------------------------------
    # Checkpointing
    # --------------------------------------------------------

    save_strategy="steps",

    save_steps=SAVE_STEPS,

    # Keep all six experimental checkpoints:
    #
    # 500
    # 1000
    # 1500
    # 2000
    # 2500
    # 3000
    save_total_limit=6,

    # --------------------------------------------------------
    # Logging
    # --------------------------------------------------------

    logging_strategy="steps",

    logging_steps=LOGGING_STEPS,

    report_to="none",

    # --------------------------------------------------------
    # Streaming
    # --------------------------------------------------------

    dataloader_num_workers=0,

    # --------------------------------------------------------
    # Misc
    # --------------------------------------------------------

    remove_unused_columns=False,

    seed=42,

    data_seed=42,
)


# ============================================================
# 17. TRAINER
# ============================================================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
)


# ============================================================
# 18. TRAIN
# ============================================================

print()
print("=" * 78)
print("STARTING EXPERIMENTAL SFT")
print("=" * 78)

print()
print(
    "Golden checkpoint-106000 remains untouched."
)

print()

train_result = trainer.train()


# ============================================================
# 19. SAVE FINAL EXPERIMENTAL MODEL
# ============================================================

print()
print("=" * 78)
print("SAVING EXPERIMENTAL MODEL")
print("=" * 78)

trainer.save_model(
    FINAL_MODEL_DIR
)

tokenizer.save_pretrained(
    FINAL_MODEL_DIR
)


# ============================================================
# 20. SAVE EXPERIMENT METADATA
# ============================================================

metadata = {

    "experiment": (
        "Maia Lite experimental SFT "
        "from golden checkpoint-106000"
    ),

    "base_checkpoint": (
        GOLDEN_CHECKPOINT
    ),

    "output_directory": (
        OUTPUT_DIR
    ),

    "final_model": (
        FINAL_MODEL_DIR
    ),

    "datasets": {

        "english": (
            "tatsu-lab/alpaca"
        ),

        "portuguese": (
            "pinzhenchen/alpaca-cleaned-pt"
        ),

        "spanish": (
            "bertin-project/alpaca-spanish"
        ),
    },

    "language_probabilities": {

        "english": 0.40,

        "portuguese": 0.30,

        "spanish": 0.30,
    },

    "max_steps": (
        MAX_STEPS
    ),

    "learning_rate": (
        LEARNING_RATE
    ),

    "effective_batch_size": (
        EFFECTIVE_BATCH_SIZE
    ),

    "max_length": (
        MAX_LENGTH
    ),
}


metadata_file = os.path.join(
    OUTPUT_DIR,
    "experiment_metadata.json",
)

with open(
    metadata_file,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        metadata,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 21. COMPLETE
# ============================================================

print()
print("=" * 78)
print("EXPERIMENTAL SFT COMPLETE")
print("=" * 78)

print()
print("Base preserved:")
print(GOLDEN_CHECKPOINT)

print()
print("Checkpoints:")
print(OUTPUT_DIR)

print()
print("Final experimental model:")
print(FINAL_MODEL_DIR)

print()
print(
    "NEXT STEP:"
)

print(
    "Evaluate checkpoints 500 / 1000 / 1500 / "
    "2000 / 2500 / 3000 against the original "
    "golden-106000 capability benchmark."
)

==============================================================================
MAIA LITE - EXPERIMENTAL SFT
==============================================================================

Base checkpoint:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Output directory:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k

GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA:    12.8

Loading Maia Lite tokenizer...
Vocabulary: 50,257
EOS token:  2
PAD token:  1

==============================================================================
LOADING GOLDEN 106K
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters: 354,823,168

==============================================================================
LOADING INSTRUCTION DATASETS
==============================================================================

Loading English Alpaca...
Loading Portuguese Alpaca...

README.md:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

Loading Spanish Alpaca...

README.md:   0%|          | 0.00/1.03k [00:00<?, ?B/s]

Dataset schemas:
EN: ['instruction', 'input', 'output', 'text']
PT: ['instruction', 'input', 'output']
ES: ['instruction', 'input', 'output']

Normalizing datasets...

Interleaving languages: EN=40%, PT=30%, ES=30%

Tokenizing stream...

==============================================================================
EXPERIMENT CONFIGURATION
==============================================================================
Max steps:             3,000
Micro batch:           8
Gradient accumulation: 4
Effective batch:       32
Learning rate:         1.00e-05
Warmup:                100
Checkpoint interval:   500
BF16:                   True
FP16:                   False

==============================================================================
STARTING EXPERIMENTAL SFT
==============================================================================

Golden checkpoint-106000 remains untouched.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================================
SAVING EXPERIMENTAL MODEL
==============================================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================================
EXPERIMENTAL SFT COMPLETE
==============================================================================

Base preserved:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Checkpoints:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k

Final experimental model:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/maia_lite_106k_sft_3000

NEXT STEP:
Evaluate checkpoints 500 / 1000 / 1500 / 2000 / 2500 / 3000 against the original golden-106000 capability benchmark.

In [ ]:
# ============================================================
# MAIA LITE - SFT EVOLUTION BENCHMARK
#
# Compare:
#
#   Golden 106K base
#   SFT 500
#   SFT 1000
#   SFT 1500
#   SFT 2000
#   SFT 2500
#   SFT 3000
#
# PURPOSE:
#
#   Observe when instruction-following behavior emerges
#   and whether later SFT checkpoints improve or degrade it.
#
# IMPORTANT:
#
#   - NO training
#   - NO gradients
#   - NO checkpoint modification
#   - Deterministic greedy decoding
#   - One model loaded at a time
#
# ============================================================

import os
import gc
import json
import math
import re
import torch

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

SFT_DIR = os.path.join(
    PROJECT_DIR,
    "experiments",
    "sft_from_106k"
)

DIAGNOSTIC_DIR = os.path.join(
    PROJECT_DIR,
    "diagnostics"
)

os.makedirs(
    DIAGNOSTIC_DIR,
    exist_ok=True
)

RESULT_FILE = os.path.join(
    DIAGNOSTIC_DIR,
    "sft_evolution_106k_500_1000_1500_2000_2500_3000.json"
)


# ============================================================
# 2. MODELS
# ============================================================

MODELS = [
    {
        "name": "base-106000",
        "path": GOLDEN_CHECKPOINT,
        "sft": False,
        "step": 0,
    },
    {
        "name": "sft-500",
        "path": os.path.join(SFT_DIR, "checkpoint-500"),
        "sft": True,
        "step": 500,
    },
    {
        "name": "sft-1000",
        "path": os.path.join(SFT_DIR, "checkpoint-1000"),
        "sft": True,
        "step": 1000,
    },
    {
        "name": "sft-1500",
        "path": os.path.join(SFT_DIR, "checkpoint-1500"),
        "sft": True,
        "step": 1500,
    },
    {
        "name": "sft-2000",
        "path": os.path.join(SFT_DIR, "checkpoint-2000"),
        "sft": True,
        "step": 2000,
    },
    {
        "name": "sft-2500",
        "path": os.path.join(SFT_DIR, "checkpoint-2500"),
        "sft": True,
        "step": 2500,
    },
    {
        "name": "sft-3000",
        "path": os.path.join(SFT_DIR, "checkpoint-3000"),
        "sft": True,
        "step": 3000,
    },
]


# ============================================================
# 3. VERIFY CHECKPOINTS
# ============================================================

print("=" * 78)
print("MAIA LITE - SFT EVOLUTION BENCHMARK")
print("=" * 78)

print()

for item in MODELS:

    exists = os.path.isdir(
        item["path"]
    )

    print(
        f"{item['name']:<15} "
        f"{'OK' if exists else 'MISSING'}"
    )

    if not exists:
        raise RuntimeError(
            f"Checkpoint not found:\n{item['path']}"
        )


# ============================================================
# 4. GPU
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA GPU required."
    )

device = torch.device("cuda")

print()
print(
    "GPU:",
    torch.cuda.get_device_name(0)
)

print(
    "PyTorch:",
    torch.__version__
)

print(
    "CUDA:",
    torch.version.cuda
)


# ============================================================
# 5. TOKENIZER
# ============================================================

print()
print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(
    f"Vocabulary: {tokenizer.vocab_size:,}"
)

print(
    f"EOS: {tokenizer.eos_token_id}"
)

print(
    f"PAD: {tokenizer.pad_token_id}"
)


# ============================================================
# 6. TESTS
#
# "base_prompt":
#     natural completion suitable for pretrained base model
#
# "instruction":
#     instruction used for SFT models
#
# ============================================================

TESTS = [

    # --------------------------------------------------------
    # ENGLISH FACTUAL
    # --------------------------------------------------------

    {
        "id": "EN_FACT_01",
        "category": "English factual",
        "base_prompt":
            "The capital of France is",
        "instruction":
            "What is the capital of France?",
        "expected_terms": [
            "paris"
        ],
    },

    {
        "id": "EN_FACT_02",
        "category": "English factual",
        "base_prompt":
            "The largest planet in the Solar System is",
        "instruction":
            "What is the largest planet in the Solar System?",
        "expected_terms": [
            "jupiter"
        ],
    },


    # --------------------------------------------------------
    # PORTUGUESE FACTUAL
    # --------------------------------------------------------

    {
        "id": "PT_FACT_01",
        "category": "Portuguese factual",
        "base_prompt":
            "A capital do Brasil é",
        "instruction":
            "Qual é a capital do Brasil?",
        "expected_terms": [
            "brasília",
            "brasilia",
        ],
    },

    {
        "id": "PT_FACT_02",
        "category": "Portuguese factual",
        "base_prompt":
            "O maior planeta do Sistema Solar é",
        "instruction":
            "Qual é o maior planeta do Sistema Solar?",
        "expected_terms": [
            "júpiter",
            "jupiter",
        ],
    },


    # --------------------------------------------------------
    # SPANISH FACTUAL
    # --------------------------------------------------------

    {
        "id": "ES_FACT_01",
        "category": "Spanish factual",
        "base_prompt":
            "La capital de España es",
        "instruction":
            "¿Cuál es la capital de España?",
        "expected_terms": [
            "madrid"
        ],
    },

    {
        "id": "ES_FACT_02",
        "category": "Spanish factual",
        "base_prompt":
            "El planeta más grande del Sistema Solar es",
        "instruction":
            "¿Cuál es el planeta más grande del Sistema Solar?",
        "expected_terms": [
            "júpiter",
            "jupiter",
        ],
    },


    # --------------------------------------------------------
    # MATHEMATICS
    # --------------------------------------------------------

    {
        "id": "MATH_01",
        "category": "Mathematics",
        "base_prompt":
            "2 + 2 =",
        "instruction":
            "What is 2 + 2?",
        "expected_terms": [
            "4"
        ],
    },

    {
        "id": "MATH_02",
        "category": "Mathematics",
        "base_prompt":
            "10 * 5 =",
        "instruction":
            "What is 10 multiplied by 5?",
        "expected_terms": [
            "50"
        ],
    },

    {
        "id": "MATH_03",
        "category": "Mathematics",
        "base_prompt":
            "The square root of 81 is",
        "instruction":
            "What is the square root of 81?",
        "expected_terms": [
            "9"
        ],
    },

    {
        "id": "MATH_04",
        "category": "Mathematics",
        "base_prompt":
            "If x + 3 = 7, then x =",
        "instruction":
            "Solve x + 3 = 7. What is x?",
        "expected_terms": [
            "4"
        ],
    },


    # --------------------------------------------------------
    # SEMANTIC / SIMPLE REASONING
    # --------------------------------------------------------

    {
        "id": "SEM_01",
        "category": "Semantic",
        "base_prompt":
            "Paris is in France. Rome is in Italy. Madrid is in",
        "instruction":
            "Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?",
        "expected_terms": [
            "spain"
        ],
    },

    {
        "id": "SEM_02",
        "category": "Semantic",
        "base_prompt":
            "Bird is to sky as fish is to",
        "instruction":
            "Complete the analogy: bird is to sky as fish is to what?",
        "expected_terms": [
            "water"
        ],
    },

    {
        "id": "SEM_03",
        "category": "Classification",
        "base_prompt":
            "A dog is an animal and a rose is a",
        "instruction":
            "A dog is an animal. What kind of thing is a rose?",
        "expected_terms": [
            "plant",
            "flower",
        ],
    },


    # --------------------------------------------------------
    # TRANSLATION
    # --------------------------------------------------------

    {
        "id": "TRANS_01",
        "category": "Translation",
        "base_prompt":
            "English: The house is beautiful.\nPortuguese:",
        "instruction":
            "Translate into Portuguese: The house is beautiful.",
        "expected_terms": [
            "casa",
            "bonita",
            "bela",
        ],
    },

    {
        "id": "TRANS_02",
        "category": "Translation",
        "base_prompt":
            "Portuguese: O livro está sobre a mesa.\nEnglish:",
        "instruction":
            "Translate into English: O livro está sobre a mesa.",
        "expected_terms": [
            "book",
            "table",
        ],
    },

    {
        "id": "TRANS_03",
        "category": "Translation",
        "base_prompt":
            "English: Good morning.\nSpanish:",
        "instruction":
            "Translate into Spanish: Good morning.",
        "expected_terms": [
            "buenos",
            "días",
            "dias",
        ],
    },


    # --------------------------------------------------------
    # EXPLANATION
    # --------------------------------------------------------

    {
        "id": "EXPLAIN_01",
        "category": "Explanation",
        "base_prompt":
            "Artificial intelligence is",
        "instruction":
            "Explain artificial intelligence in one short sentence.",
        "expected_terms": [],
    },

    {
        "id": "EXPLAIN_02",
        "category": "Explanation",
        "base_prompt":
            "A neural network is",
        "instruction":
            "Explain what a neural network is in one short sentence.",
        "expected_terms": [],
    },

    {
        "id": "EXPLAIN_03",
        "category": "Explanation Portuguese",
        "base_prompt":
            "Aprendizado de máquina é",
        "instruction":
            "Explique em uma frase curta o que é aprendizado de máquina.",
        "expected_terms": [],
    },


    # --------------------------------------------------------
    # SIMPLE INSTRUCTION FOLLOWING
    # --------------------------------------------------------

    {
        "id": "INST_01",
        "category": "Instruction",
        "base_prompt":
            "The colors red, green and blue are",
        "instruction":
            "List exactly three colors.",
        "expected_terms": [],
    },

    {
        "id": "INST_02",
        "category": "Instruction",
        "base_prompt":
            "The numbers from one to five are",
        "instruction":
            "List the numbers from 1 to 5.",
        "expected_terms": [
            "1",
            "2",
            "3",
            "4",
            "5",
        ],
    },

    {
        "id": "INST_03",
        "category": "Instruction Portuguese",
        "base_prompt":
            "Três animais são",
        "instruction":
            "Liste exatamente três animais.",
        "expected_terms": [],
    },


    # --------------------------------------------------------
    # PYTHON
    #
    # We know the SFT corpus is not code-focused.
    # This is mainly a preservation test.
    # --------------------------------------------------------

    {
        "id": "PY_01",
        "category": "Python",
        "base_prompt":
            "def add(a, b):\n    return",
        "instruction":
            "Write a Python function called add that returns the sum of a and b.",
        "expected_terms": [
            "def",
            "return",
        ],
    },

    {
        "id": "PY_02",
        "category": "Python",
        "base_prompt":
            "def square(x):\n    return",
        "instruction":
            "Write a Python function called square that returns x squared.",
        "expected_terms": [
            "def",
            "return",
        ],
    },


    # --------------------------------------------------------
    # OPEN LANGUAGE GENERATION
    # --------------------------------------------------------

    {
        "id": "OPEN_EN",
        "category": "Open English",
        "base_prompt":
            "The importance of science is",
        "instruction":
            "Write one short sentence about the importance of science.",
        "expected_terms": [],
    },

    {
        "id": "OPEN_PT",
        "category": "Open Portuguese",
        "base_prompt":
            "A importância da ciência é",
        "instruction":
            "Escreva uma frase curta sobre a importância da ciência.",
        "expected_terms": [],
    },

    {
        "id": "OPEN_ES",
        "category": "Open Spanish",
        "base_prompt":
            "La importancia de la ciencia es",
        "instruction":
            "Escribe una frase corta sobre la importancia de la ciencia.",
        "expected_terms": [],
    },
]


# ============================================================
# 7. GENERATION PARAMETERS
# ============================================================

MAX_NEW_TOKENS = 64

# Intentionally no anti-repetition mechanisms.
#
# We WANT to observe whether repetition is present.
#
# repetition_penalty = 1.0
# no_repeat_ngram_size = 0

GENERATION_CONFIG = {
    "max_new_tokens": MAX_NEW_TOKENS,
    "do_sample": False,
    "num_beams": 1,
}


# ============================================================
# 8. LOAD MODEL
# ============================================================

def load_model(path):

    gc.collect()
    torch.cuda.empty_cache()

    model = GPT2LMHeadModel.from_pretrained(
        path,
        local_files_only=True,
        torch_dtype=torch.bfloat16,
    )

    model.to(device)

    model.eval()

    # Enable KV cache for inference.
    model.config.use_cache = True

    return model


# ============================================================
# 9. BUILD PROMPT
# ============================================================

def build_prompt(test, is_sft):

    if is_sft:

        return (
            "User: "
            + test["instruction"]
            + "\nAssistant:"
        )

    return test["base_prompt"]


# ============================================================
# 10. GENERATE
# ============================================================

def generate(model, prompt):

    encoded = tokenizer(
        prompt,
        return_tensors="pt",
    )

    input_ids = (
        encoded["input_ids"]
        .to(device)
    )

    attention_mask = (
        encoded["attention_mask"]
        .to(device)
    )

    prompt_length = input_ids.shape[1]

    with torch.inference_mode():

        output = model.generate(

            input_ids=input_ids,

            attention_mask=attention_mask,

            max_new_tokens=(
                GENERATION_CONFIG[
                    "max_new_tokens"
                ]
            ),

            do_sample=False,

            num_beams=1,

            pad_token_id=(
                tokenizer.pad_token_id
            ),

            eos_token_id=(
                tokenizer.eos_token_id
            ),

            use_cache=True,
        )

    generated_ids = output[
        0,
        prompt_length:
    ]

    text = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    )

    return text.strip()


# ============================================================
# 11. NORMALIZATION
# ============================================================

def normalize_text(text):

    text = text.lower()

    # Normalize a few accented characters for simple matching.
    replacements = {
        "á": "a",
        "à": "a",
        "ã": "a",
        "â": "a",
        "é": "e",
        "ê": "e",
        "í": "i",
        "ó": "o",
        "ô": "o",
        "õ": "o",
        "ú": "u",
        "ü": "u",
        "ç": "c",
        "ñ": "n",
    }

    for old, new in replacements.items():
        text = text.replace(
            old,
            new
        )

    return text


# ============================================================
# 12. EXPECTED TERM SCORE
# ============================================================

def expected_score(
    text,
    expected_terms
):

    if not expected_terms:
        return None

    normalized = normalize_text(text)

    normalized_terms = [
        normalize_text(x)
        for x in expected_terms
    ]

    found = 0

    for term in normalized_terms:

        if term in normalized:
            found += 1

    return (
        found
        / len(normalized_terms)
    )


# ============================================================
# 13. REPETITION METRICS
# ============================================================

def repetition_metrics(text):

    words = re.findall(
        r"\b\w+\b",
        text.lower()
    )

    if len(words) == 0:

        return {
            "word_count": 0,
            "unique_word_ratio": 0.0,
            "repeated_bigram_ratio": 0.0,
        }

    unique_word_ratio = (
        len(set(words))
        / len(words)
    )

    if len(words) < 2:

        repeated_bigram_ratio = 0.0

    else:

        bigrams = [
            (
                words[i],
                words[i + 1]
            )
            for i in range(
                len(words) - 1
            )
        ]

        unique_bigrams = set(
            bigrams
        )

        repeated_bigram_ratio = (
            1.0
            - (
                len(unique_bigrams)
                / len(bigrams)
            )
        )

    return {
        "word_count":
            len(words),

        "unique_word_ratio":
            unique_word_ratio,

        "repeated_bigram_ratio":
            repeated_bigram_ratio,
    }


# ============================================================
# 14. BENCHMARK ONE MODEL
# ============================================================

def benchmark_model(model_info):

    name = model_info["name"]

    path = model_info["path"]

    is_sft = model_info["sft"]

    print()
    print()
    print("=" * 78)
    print(f"TESTING: {name}")
    print("=" * 78)

    model = load_model(path)

    results = []

    expected_scores = []

    repetition_scores = []

    for index, test in enumerate(
        TESTS,
        start=1,
    ):

        prompt = build_prompt(
            test,
            is_sft,
        )

        completion = generate(
            model,
            prompt,
        )

        score = expected_score(
            completion,
            test["expected_terms"],
        )

        repetition = repetition_metrics(
            completion
        )

        if score is not None:
            expected_scores.append(
                score
            )

        repetition_scores.append(
            repetition[
                "repeated_bigram_ratio"
            ]
        )

        result = {

            "id":
                test["id"],

            "category":
                test["category"],

            "prompt":
                prompt,

            "completion":
                completion,

            "expected_terms":
                test["expected_terms"],

            "expected_score":
                score,

            "word_count":
                repetition[
                    "word_count"
                ],

            "unique_word_ratio":
                repetition[
                    "unique_word_ratio"
                ],

            "repeated_bigram_ratio":
                repetition[
                    "repeated_bigram_ratio"
                ],
        }

        results.append(
            result
        )

        print()
        print("-" * 78)

        print(
            f"{index:02d}/"
            f"{len(TESTS):02d} "
            f"{test['id']} | "
            f"{test['category']}"
        )

        print("-" * 78)

        print("PROMPT:")
        print(prompt)

        print()

        print("RESPONSE:")
        print(completion)

        if score is not None:

            print()

            print(
                f"Expected score: "
                f"{score:.3f}"
            )

        print()

        print(
            "Repeated bigram ratio: "
            f"{repetition['repeated_bigram_ratio']:.3f}"
        )


    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    mean_expected = (

        sum(expected_scores)
        / len(expected_scores)

        if expected_scores
        else 0.0
    )

    mean_repetition = (

        sum(repetition_scores)
        / len(repetition_scores)

        if repetition_scores
        else 0.0
    )


    summary = {

        "name":
            name,

        "step":
            model_info["step"],

        "is_sft":
            is_sft,

        "mean_expected_score":
            mean_expected,

        "mean_repeated_bigram_ratio":
            mean_repetition,

        "tests":
            len(TESTS),
    }


    # --------------------------------------------------------
    # FREE MODEL
    # --------------------------------------------------------

    del model

    gc.collect()

    torch.cuda.empty_cache()

    return {
        "summary":
            summary,

        "results":
            results,
    }


# ============================================================
# 15. RUN ALL MODELS
# ============================================================

all_results = {}

summaries = []


for model_info in MODELS:

    result = benchmark_model(
        model_info
    )

    all_results[
        model_info["name"]
    ] = result

    summaries.append(
        result["summary"]
    )


# ============================================================
# 16. SUMMARY TABLE
# ============================================================

print()
print()
print("=" * 78)
print("SUMMARY")
print("=" * 78)

print()

print(
    f"{'MODEL':<16}"
    f"{'STEP':>8}"
    f"{'EXPECTED':>14}"
    f"{'REPETITION':>14}"
)

print("-" * 52)


for summary in summaries:

    print(
        f"{summary['name']:<16}"
        f"{summary['step']:>8}"
        f"{summary['mean_expected_score']:>14.3f}"
        f"{summary['mean_repeated_bigram_ratio']:>14.3f}"
    )


# ============================================================
# 17. TEST-BY-TEST COMPARISON
# ============================================================

print()
print()
print("=" * 78)
print("TEST-BY-TEST COMPARISON")
print("=" * 78)


for test_index, test in enumerate(TESTS):

    print()
    print()
    print("#" * 78)

    print(
        f"{test['id']} | "
        f"{test['category']}"
    )

    print("#" * 78)


    for model_info in MODELS:

        name = model_info["name"]

        result = (
            all_results[
                name
            ]["results"][
                test_index
            ]
        )

        print()
        print(
            f"--- {name} ---"
        )

        print(
            result["completion"]
        )


# ============================================================
# 18. SAVE JSON
# ============================================================

output = {

    "benchmark": (
        "Maia Lite SFT evolution"
    ),

    "models": [
        {
            "name":
                x["name"],

            "path":
                x["path"],

            "step":
                x["step"],

            "sft":
                x["sft"],
        }
        for x in MODELS
    ],

    "generation": {
        "max_new_tokens":
            MAX_NEW_TOKENS,

        "do_sample":
            False,

        "num_beams":
            1,

        "repetition_penalty":
            1.0,

        "no_repeat_ngram_size":
            0,
    },

    "summaries":
        summaries,

    "results":
        all_results,
}


with open(
    RESULT_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        output,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 19. FINAL
# ============================================================

print()
print()
print("=" * 78)
print("BENCHMARK COMPLETE")
print("=" * 78)

print()

print("Results saved to:")

print(
    RESULT_FILE
)

print()

print(
    "Please send this JSON for analysis."
)

==============================================================================
MAIA LITE - SFT EVOLUTION BENCHMARK
==============================================================================

base-106000     OK
sft-500         OK
sft-1000        OK
sft-1500        OK
sft-2000        OK
sft-2500        OK
sft-3000        OK

GPU: NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA: 12.8

Loading tokenizer...
Vocabulary: 50,257
EOS: 2
PAD: 1


==============================================================================
TESTING: base-106000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
The capital of France is

RESPONSE:
the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel of the Channel of the Sable.

The capital is located on the island of Brittany, on the southern shore of the Channel of the Sable.

Expected score: 0.000

Repeated bigram ratio: 0.417

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
The largest planet in the Solar System is

RESPONSE:
the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in

Expected score: 0.000

Repeated bigram ratio: 0.750

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
A capital do Brasil é

RESPONSE:
a capital do estado do Brasil, sendo também a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo, fundada em 1545, foi fundada por Pedro Álvares Cabral, que se instalou na margem direita do rio Uruguai, em 1545.

Expected score: 0.000

Repeated bigram ratio: 0.149

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
O maior planeta do Sistema Solar é

RESPONSE:
o planeta que orbita o planeta Terra, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica, com uma órbita excêntrica

Expected score: 0.000

Repeated bigram ratio: 0.737

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
La capital de España es

RESPONSE:
la ciudad más poblada de la República de España, con una población de  habitantes (2022). Es la capital de la provincia homónima, en la región de Castilla-La Mancha.

La ciudad se encuentra en el centro de la provincia, en la región de Castilla-La Mancha, a orillas del río Guadiana,

Expected score: 0.000

Repeated bigram ratio: 0.200

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
El planeta más grande del Sistema Solar es

RESPONSE:
el planeta más grande del sistema solar, con una superficie de aproximadamente  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar

Expected score: 0.000

Repeated bigram ratio: 0.647

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
2 + 2 =

RESPONSE:
4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4

Expected score: 1.000

Repeated bigram ratio: 0.857

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
10 * 5 =

RESPONSE:
5

4 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * =

Expected score: 0.000

Repeated bigram ratio: 0.870

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
The square root of 81 is

RESPONSE:
a major component of the median nerve of the median nerve. It is a branch of the median nerve.

Anatomy

Origin
The square root of 81 is a branch of the median nerve of median nerve. It is a branch of the median nerve of median nerve.

Course and

Expected score: 0.000

Repeated bigram ratio: 0.521

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
If x + 3 = 7, then x =

RESPONSE:
7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x

Expected score: 0.000

Repeated bigram ratio: 0.921

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
Paris is in France. Rome is in Italy. Madrid is in

RESPONSE:
Spain.

Paris may also refer to:

Places

United States
 Paris, Texas, a city in the United States
 Paris, Illinois, a city in the United States
 Paris, Missouri, a city in the United States
 Paris, Missouri, a city in the United States
 Paris,

Expected score: 1.000

Repeated bigram ratio: 0.537

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
Bird is to sky as fish is to

RESPONSE:
be found in the sky.

Bird may also refer to:

Places

United States
 Bird, Alabama, a city in Alabama
 Bird, Illinois, a city in Illinois
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a

Expected score: 0.000

Repeated bigram ratio: 0.308

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
A dog is an animal and a rose is a

RESPONSE:
type of rose.

Buddhism

Buddhism is a type of vegetarianism that involves the use of a variety of vegetarian or veganical techniques. The most common method of vegetarianism is to use a variety of vegetarian or veganical techniques. The most common

Expected score: 0.000

Repeated bigram ratio: 0.275

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
English: The house is beautiful.
Portuguese:

RESPONSE:
"The house" (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song) (song)

Expected score: 0.000

Repeated bigram ratio: 0.857

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
Portuguese: O livro está sobre a mesa.
English:

RESPONSE:
The Book is about the book.

The book is a collection of essays by the Portuguese poet Manuel Bandeira, published in 1889.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book is a collection of essays,

Expected score: 0.500

Repeated bigram ratio: 0.489

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
English: Good morning.
Spanish:

RESPONSE:
La hora de la gloria
Spanish: La hora de la gloria
Spanish: The day of the Victory
Spanish: La hora de la gloria

Desambiguações de siglas
Desambiguações de topônimos
Desambiguações de história
Desambiguações de cinema
Desambiguações de música
Desambiguações de música
Desambiguações de música
Desambiguações de música
Desambiguações

Expected score: 0.000

Repeated bigram ratio: 0.489

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
Artificial intelligence is

RESPONSE:
a field of artificial intelligence that involves the use of artificial intelligence to manipulate and manipulate artificial intelligence.

History

The field of artificial intelligence was founded in the early 1970s by the American psychologist and psychologist Dr. Robert A. Lee, who was the first to develop artificial intelligence. Lee was

Repeated bigram ratio: 0.143

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
A neural network is

RESPONSE:
a network of neurons that is composed of neurons that are located in the brain.

The term "snagocyte" is also used for the term "snagocyte" in the context of the brain.

The term "snagocyte" is also used for the term

Repeated bigram ratio: 0.385

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
Aprendizado de máquina é

RESPONSE:
um programa de computador que permite que um computador de computador se torne um computador de máquina.

O programa é executado em um computador de máquina, geralmente um computador de computador, ou um computador de computador. O programa é executado em um computador de máquina, geralmente um computador de computador, ou um computador de computador.

Repeated bigram ratio: 0.556

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
The colors red, green and blue are

RESPONSE:
the official colors of the United States government. The official color of the United States government is blue, the official state color of the United States. The official state color of the United States government is blue, the official state color of the United States. The official state color of the United States government is blue, the official

Repeated bigram ratio: 0.719

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
The numbers from one to five are

RESPONSE:
the following:

The numbers from the United States to the United States are:

The numbers from the United States to the United States are:

The numbers from the United States to the United States are:

The numbers from the United States to the United States are:

The numbers from

Expected score: 0.000

Repeated bigram ratio: 0.771

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
Três animais são

RESPONSE:
animais que possuem um sistema de locomoção e/ou locomoção.

Os animais que possuem um sistema de locomoção são chamados animais de locomoção.

Os animais que possuem um sistema de locomoção são chamados de animais de locomoção.

Os animais que possuem um

Repeated bigram ratio: 0.585

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
def add(a, b):
    return

RESPONSE:
(a, b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b

Expected score: 0.500

Repeated bigram ratio: 0.880

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
def square(x):
    return

RESPONSE:
x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return

Expected score: 0.500

Repeated bigram ratio: 0.935

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
The importance of science is

RESPONSE:
the importance of science to the general public.

The importance of science is the importance of science to the general public. The importance of science is the importance of science to the general public.

The importance of science is the importance of science to the general public. The importance of science is the importance of science

Repeated bigram ratio: 0.818

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
A importância da ciência é

RESPONSE:
a importância da ciência para a compreensão da natureza.

A ciência é uma das áreas mais antigas da filosofia, sendo a mais antiga a filosofia grega, fundada por Aristóteles. A filosofia grega é uma das áreas mais antigas da filosofia, sendo a mais antiga a filosofia grega.

A filosofia grega é uma das áreas

Repeated bigram ratio: 0.415

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
La importancia de la ciencia es

RESPONSE:
la importancia de la ciencia en la sociedad.

La ciencia es una disciplina científica que se ocupa de la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la

Repeated bigram ratio: 0.630


==============================================================================
TESTING: sft-500
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the capital of France?
Assistant:

RESPONSE:
What is the capital of France?

The city of User is the capital of the department of User.

History

The city was founded in the 12th century by the French king Louis IX of France. The city was founded in 1250 by the French king Louis IX of France. The

Expected score: 0.000

Repeated bigram ratio: 0.388

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:

RESPONSE:
What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User:

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é a capital do Brasil?
Assistant:

RESPONSE:
User: O nome da cidade é uma homenagem ao presidente Getúlio Vargas.

História

A cidade foi fundada em 15 de agosto de 1934, por Getúlio Vargas, como capital do país.

A cidade foi fundada em 15 de agosto de 1934, por Getúlio Vargas, como capital do país.

Expected score: 0.000

Repeated bigram ratio: 0.370

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:

RESPONSE:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2006, por um telescópio espacial Hubble.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta foi nomeado em homenagem ao planeta User,

Expected score: 0.000

Repeated bigram ratio: 0.375

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:

RESPONSE:
¿Cuándo es la capital de España?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo. En el año 912, el rey visigodo Leovigildo entregó a su hijo Al-Mutadid, el castillo de Uxir,

Expected score: 0.000

Repeated bigram ratio: 0.135

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:

RESPONSE:
¿Cuál es el planeta más grande del sistema solar?

Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas

Expected score: 0.000

Repeated bigram ratio: 0.732

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 2 + 2?
Assistant:

RESPONSE:
What is the first part of the third album, The Best of User, released in 2006.

Track listing
"The Best of User" (User) – 3:57
"The Best of User" (User) – 3:57
"The Best of User"

Expected score: 0.000

Repeated bigram ratio: 0.371

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 10 multiplied by 5?
Assistant:

RESPONSE:
What is the number of times that a given number is in the range of 0 to 1.

The first two digits of the first digits are the first digit, and the second digit is the first digit.

The second digit is the first digit, and the second digit is the first digit.

Expected score: 0.000

Repeated bigram ratio: 0.365

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is the square root of 81?
Assistant:

RESPONSE:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:

RESPONSE:
The User: Solve x + 3 = 7. What is x?

User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Sol

Expected score: 0.000

Repeated bigram ratio: 0.600

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:

RESPONSE:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book was first published in Paris in the French edition of the book in the French edition of the book in the French

Expected score: 1.000

Repeated bigram ratio: 0.412

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:

RESPONSE:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is

Expected score: 0.000

Repeated bigram ratio: 0.790

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:

RESPONSE:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a

Expected score: 0.000

Repeated bigram ratio: 0.807

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:

RESPONSE:
The house is beautiful, and the house is beautiful.

The house is a beautiful place, and the house is beautiful. The house is beautiful, and the house is beautiful. The house is beautiful, and the house is beautiful. The house is beautiful, and the house is beautiful. The house is beautiful,

Expected score: 0.000

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:

RESPONSE:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre

Expected score: 0.000

Repeated bigram ratio: 0.816

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:

RESPONSE:
The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for

Expected score: 0.000

Repeated bigram ratio: 0.818

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:

RESPONSE:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial

Repeated bigram ratio: 0.758

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:

RESPONSE:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one

Repeated bigram ratio: 0.725

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:

RESPONSE:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em

Repeated bigram ratio: 0.676

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List exactly three colors.
Assistant:

RESPONSE:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List the numbers from 1 to 5.
Assistant:

RESPONSE:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers

Expected score: 0.400

Repeated bigram ratio: 0.837

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Liste exatamente três animais.
Assistant:

RESPONSE:
Liste tudo o que é.

Liste tudo o que é.

Liste tudo o que é.

Liste tudo o que é.

Liste tudo o que é.

Liste tudo o que é.

Liste tudo o que é.

L

Repeated bigram ratio: 0.829

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:

RESPONSE:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of

Expected score: 0.000

Repeated bigram ratio: 0.733

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:

RESPONSE:
Write a function that returns x squared.

The square is a function that returns x squared.

The square is a function that returns x squared.

The square is a function that returns x squared.

The square is a function that returns x squared.

Expected score: 0.500

Repeated bigram ratio: 0.762

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:

RESPONSE:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science

Repeated bigram ratio: 0.952

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:

RESPONSE:
O ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano,

Repeated bigram ratio: 0.909

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:

RESPONSE:
El nombre de la ciencia que se ocupa de la ciencia.
Assistant: El nombre de la ciencia que se ocupa de la ciencia.
Assistant: El nombre de la ciencia que se ocupa de la ciencia.
Assistant: El nombre de la ciencia que se ocupa de la ciencia.

Repeated bigram ratio: 0.783


==============================================================================
TESTING: sft-1000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the capital of France?
Assistant:

RESPONSE:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

Expected score: 1.000

Repeated bigram ratio: 0.792

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:

RESPONSE:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

Expected score: 0.000

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é a capital do Brasil?
Assistant:

RESPONSE:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um

Expected score: 0.000

Repeated bigram ratio: 0.767

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:

RESPONSE:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta

Expected score: 0.000

Repeated bigram ratio: 0.234

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:

RESPONSE:
¿Cuándo es la capital de España?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo, que la convirtió en capital del reino visigodo de Toledo.

En el año 912, el rey visigodo Leovigildo trasladó la capitalidad de

Expected score: 0.000

Repeated bigram ratio: 0.122

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:

RESPONSE:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

Expected score: 0.000

Repeated bigram ratio: 0.565

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 2 + 2?
Assistant:

RESPONSE:
What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the second time that a person can change

Expected score: 0.000

Repeated bigram ratio: 0.688

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 10 multiplied by 5?
Assistant:

RESPONSE:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is the square root of 81?
Assistant:

RESPONSE:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:

RESPONSE:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:

RESPONSE:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book was first published in Paris in the French edition of the book in the French edition of the book in the French

Expected score: 1.000

Repeated bigram ratio: 0.412

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:

RESPONSE:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is

Expected score: 0.000

Repeated bigram ratio: 0.790

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:

RESPONSE:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a

Expected score: 0.000

Repeated bigram ratio: 0.807

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:

RESPONSE:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:

Expected score: 0.000

Repeated bigram ratio: 0.821

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:

RESPONSE:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre

Expected score: 0.000

Repeated bigram ratio: 0.816

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:

RESPONSE:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used

Expected score: 0.000

Repeated bigram ratio: 0.531

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:

RESPONSE:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial

Repeated bigram ratio: 0.758

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:

RESPONSE:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one

Repeated bigram ratio: 0.725

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:

RESPONSE:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em

Repeated bigram ratio: 0.676

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List exactly three colors.
Assistant:

RESPONSE:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List the numbers from 1 to 5.
Assistant:

RESPONSE:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers

Expected score: 0.400

Repeated bigram ratio: 0.837

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Liste exatamente três animais.
Assistant:

RESPONSE:
Liste tudo o que é?

Ou seja, o animal é um animal que não é um animal, mas sim um animal que não é um animal.

O animal é um animal que não é um animal, mas sim um animal que não é um animal.

O animal é um animal

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:

RESPONSE:
Add that the sum of a and b is a function of the sum of b and b.
Assistant: Add that the sum of b and b is a function of the sum of b and b.
Assistant: Add that the sum of b and b is a function of the sum of b

Expected score: 0.000

Repeated bigram ratio: 0.698

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:

RESPONSE:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function

Expected score: 0.500

Repeated bigram ratio: 0.765

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:

RESPONSE:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science

Repeated bigram ratio: 0.952

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:

RESPONSE:
O que é o que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O

Repeated bigram ratio: 0.909

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:

RESPONSE:
El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la

Repeated bigram ratio: 0.791


==============================================================================
TESTING: sft-1500
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the capital of France?
Assistant:

RESPONSE:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

Expected score: 1.000

Repeated bigram ratio: 0.792

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:

RESPONSE:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

Expected score: 0.000

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é a capital do Brasil?
Assistant:

RESPONSE:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um

Expected score: 0.000

Repeated bigram ratio: 0.767

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:

RESPONSE:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta

Expected score: 0.000

Repeated bigram ratio: 0.234

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:

RESPONSE:
¿Cuándo es la capital de España?

La ciudad de User es la capital de España, y la segunda ciudad más poblada de España, después de Madrid.

La ciudad de User es la capital de España, y la cuarta ciudad más poblada de España, después de Madrid y Barcelona.

Expected score: 1.000

Repeated bigram ratio: 0.468

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:

RESPONSE:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

Expected score: 0.000

Repeated bigram ratio: 0.565

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 2 + 2?
Assistant:

RESPONSE:
What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the second time that a person can change

Expected score: 0.000

Repeated bigram ratio: 0.688

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 10 multiplied by 5?
Assistant:

RESPONSE:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is the square root of 81?
Assistant:

RESPONSE:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:

RESPONSE:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:

RESPONSE:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book was first published in Paris in the French edition of the book in the French edition of the book in the French

Expected score: 1.000

Repeated bigram ratio: 0.412

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:

RESPONSE:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is

Expected score: 0.000

Repeated bigram ratio: 0.790

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:

RESPONSE:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a

Expected score: 0.000

Repeated bigram ratio: 0.807

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:

RESPONSE:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:

Expected score: 0.000

Repeated bigram ratio: 0.821

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:

RESPONSE:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre

Expected score: 0.000

Repeated bigram ratio: 0.816

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:

RESPONSE:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a synonym for the Spanish word "Spanish".

The word is used in Spanish as a synonym for the Spanish word "Spanish".

The word is used

Expected score: 0.000

Repeated bigram ratio: 0.468

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:

RESPONSE:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial

Repeated bigram ratio: 0.758

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:

RESPONSE:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one

Repeated bigram ratio: 0.725

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:

RESPONSE:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em

Repeated bigram ratio: 0.676

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List exactly three colors.
Assistant:

RESPONSE:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List the numbers from 1 to 5.
Assistant:

RESPONSE:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers

Expected score: 0.400

Repeated bigram ratio: 0.837

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Liste exatamente três animais.
Assistant:

RESPONSE:
Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assist

Repeated bigram ratio: 0.793

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:

RESPONSE:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of

Expected score: 0.000

Repeated bigram ratio: 0.733

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:

RESPONSE:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function

Expected score: 0.500

Repeated bigram ratio: 0.765

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:

RESPONSE:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science

Repeated bigram ratio: 0.952

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:

RESPONSE:
O ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano,

Repeated bigram ratio: 0.909

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:

RESPONSE:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist

Repeated bigram ratio: 0.800


==============================================================================
TESTING: sft-2000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the capital of France?
Assistant:

RESPONSE:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

Expected score: 1.000

Repeated bigram ratio: 0.792

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:

RESPONSE:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

Expected score: 0.000

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é a capital do Brasil?
Assistant:

RESPONSE:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um

Expected score: 0.000

Repeated bigram ratio: 0.767

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:

RESPONSE:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta

Expected score: 0.000

Repeated bigram ratio: 0.234

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:

RESPONSE:
¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo

Expected score: 0.000

Repeated bigram ratio: 0.750

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:

RESPONSE:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

Expected score: 0.000

Repeated bigram ratio: 0.565

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 2 + 2?
Assistant:

RESPONSE:
What is the first time that a person can talk about the situation.

The first time that someone can talk about the situation is when someone can talk about the situation.

The second time that someone can talk about the situation is when someone can talk about the situation.

The third time that someone can

Expected score: 0.000

Repeated bigram ratio: 0.593

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 10 multiplied by 5?
Assistant:

RESPONSE:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is the square root of 81?
Assistant:

RESPONSE:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:

RESPONSE:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:

RESPONSE:
Paris is in Spain, and the relationship between Paris and the Spanish capital Madrid is in the same way.

The relationship between Paris and the Spanish capital Madrid is in the same way as the relationship between the two cities.

Paris is in Spain, and the relationship between the two cities is in Madrid.

Expected score: 1.000

Repeated bigram ratio: 0.528

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:

RESPONSE:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is

Expected score: 0.000

Repeated bigram ratio: 0.790

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:

RESPONSE:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a

Expected score: 0.000

Repeated bigram ratio: 0.807

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:

RESPONSE:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:

Expected score: 0.000

Repeated bigram ratio: 0.821

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:

RESPONSE:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre

Expected score: 0.000

Repeated bigram ratio: 0.816

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:

RESPONSE:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used

Expected score: 0.000

Repeated bigram ratio: 0.531

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:

RESPONSE:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial

Repeated bigram ratio: 0.758

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:

RESPONSE:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one

Repeated bigram ratio: 0.725

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:

RESPONSE:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em

Repeated bigram ratio: 0.676

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List exactly three colors.
Assistant:

RESPONSE:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List the numbers from 1 to 5.
Assistant:

RESPONSE:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers

Expected score: 0.400

Repeated bigram ratio: 0.837

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Liste exatamente três animais.
Assistant:

RESPONSE:
Liste tudo o que é?

Ou seja, o animal é um animal que não é um animal, mas sim um animal que não é um animal.

O animal é um animal que não é um animal, mas sim um animal que não é um animal.

O animal é um animal

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:

RESPONSE:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of

Expected score: 0.000

Repeated bigram ratio: 0.733

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:

RESPONSE:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function

Expected score: 0.500

Repeated bigram ratio: 0.765

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:

RESPONSE:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science

Repeated bigram ratio: 0.952

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:

RESPONSE:
O que você sabe?

Ou seja:

"O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O

Repeated bigram ratio: 0.794

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:

RESPONSE:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist

Repeated bigram ratio: 0.800


==============================================================================
TESTING: sft-2500
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the capital of France?
Assistant:

RESPONSE:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

Expected score: 1.000

Repeated bigram ratio: 0.792

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:

RESPONSE:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

Expected score: 0.000

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é a capital do Brasil?
Assistant:

RESPONSE:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um

Expected score: 0.000

Repeated bigram ratio: 0.767

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:

RESPONSE:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2006, por um telescópio da NASA, que detectou um planeta extrasolar orbitando o planeta. O planeta foi nomeado em homenagem ao planeta User, o planeta da mitologia grega.

O planeta foi

Expected score: 0.000

Repeated bigram ratio: 0.146

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:

RESPONSE:
¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo

Expected score: 0.000

Repeated bigram ratio: 0.750

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:

RESPONSE:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

Expected score: 0.000

Repeated bigram ratio: 0.565

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 2 + 2?
Assistant:

RESPONSE:
What is the first time you have a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a

Expected score: 0.000

Repeated bigram ratio: 0.825

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 10 multiplied by 5?
Assistant:

RESPONSE:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is the square root of 81?
Assistant:

RESPONSE:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:

RESPONSE:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:

RESPONSE:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays

Expected score: 1.000

Repeated bigram ratio: 0.609

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:

RESPONSE:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is

Expected score: 0.000

Repeated bigram ratio: 0.790

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:

RESPONSE:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a

Expected score: 0.000

Repeated bigram ratio: 0.807

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:

RESPONSE:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:

Expected score: 0.000

Repeated bigram ratio: 0.821

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:

RESPONSE:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre

Expected score: 0.000

Repeated bigram ratio: 0.816

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:

RESPONSE:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used

Expected score: 0.000

Repeated bigram ratio: 0.531

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:

RESPONSE:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial

Repeated bigram ratio: 0.758

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:

RESPONSE:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one

Repeated bigram ratio: 0.725

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:

RESPONSE:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em

Repeated bigram ratio: 0.676

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List exactly three colors.
Assistant:

RESPONSE:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List the numbers from 1 to 5.
Assistant:

RESPONSE:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers

Expected score: 0.400

Repeated bigram ratio: 0.837

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Liste exatamente três animais.
Assistant:

RESPONSE:
Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura

Repeated bigram ratio: 0.763

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:

RESPONSE:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of

Expected score: 0.000

Repeated bigram ratio: 0.733

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:

RESPONSE:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function

Expected score: 0.500

Repeated bigram ratio: 0.765

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:

RESPONSE:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science

Repeated bigram ratio: 0.952

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:

RESPONSE:
O que é?

Ou seja: O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

Repeated bigram ratio: 0.806

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:

RESPONSE:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist

Repeated bigram ratio: 0.800


==============================================================================
TESTING: sft-3000
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
01/27 EN_FACT_01 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the capital of France?
Assistant:

RESPONSE:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

Expected score: 1.000

Repeated bigram ratio: 0.792

------------------------------------------------------------------------------
02/27 EN_FACT_02 | English factual
------------------------------------------------------------------------------
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:

RESPONSE:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

Expected score: 0.000

Repeated bigram ratio: 0.633

------------------------------------------------------------------------------
03/27 PT_FACT_01 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é a capital do Brasil?
Assistant:

RESPONSE:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um

Expected score: 0.000

Repeated bigram ratio: 0.767

------------------------------------------------------------------------------
04/27 PT_FACT_02 | Portuguese factual
------------------------------------------------------------------------------
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:

RESPONSE:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe liderada por David C. Brown, que descobriu o planeta a partir de um buraco de água.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema

Expected score: 0.000

Repeated bigram ratio: 0.173

------------------------------------------------------------------------------
05/27 ES_FACT_01 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:

RESPONSE:
¿Cuándo es la capital de España?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo. En el año 912, el rey visigodo Leovigildo trasladó la capitalidad de la provincia a la ciudad de Toledo.

En el año

Expected score: 0.000

Repeated bigram ratio: 0.195

------------------------------------------------------------------------------
06/27 ES_FACT_02 | Spanish factual
------------------------------------------------------------------------------
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:

RESPONSE:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

Expected score: 0.000

Repeated bigram ratio: 0.565

------------------------------------------------------------------------------
07/27 MATH_01 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 2 + 2?
Assistant:

RESPONSE:
What is the first time you have a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a

Expected score: 0.000

Repeated bigram ratio: 0.825

------------------------------------------------------------------------------
08/27 MATH_02 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is 10 multiplied by 5?
Assistant:

RESPONSE:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
09/27 MATH_03 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: What is the square root of 81?
Assistant:

RESPONSE:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant

Expected score: 0.000

Repeated bigram ratio: 0.744

------------------------------------------------------------------------------
10/27 MATH_04 | Mathematics
------------------------------------------------------------------------------
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:

RESPONSE:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The

Expected score: 0.000

Repeated bigram ratio: 0.667

------------------------------------------------------------------------------
11/27 SEM_01 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:

RESPONSE:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays. It is a collection of essays, essays, and essays.

The book was first published in Paris in the French edition of

Expected score: 1.000

Repeated bigram ratio: 0.375

------------------------------------------------------------------------------
12/27 SEM_02 | Semantic
------------------------------------------------------------------------------
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:

RESPONSE:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is

Expected score: 0.000

Repeated bigram ratio: 0.790

------------------------------------------------------------------------------
13/27 SEM_03 | Classification
------------------------------------------------------------------------------
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:

RESPONSE:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a

Expected score: 0.000

Repeated bigram ratio: 0.807

------------------------------------------------------------------------------
14/27 TRANS_01 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:

RESPONSE:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:

Expected score: 0.000

Repeated bigram ratio: 0.821

------------------------------------------------------------------------------
15/27 TRANS_02 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:

RESPONSE:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre

Expected score: 0.000

Repeated bigram ratio: 0.816

------------------------------------------------------------------------------
16/27 TRANS_03 | Translation
------------------------------------------------------------------------------
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:

RESPONSE:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used

Expected score: 0.000

Repeated bigram ratio: 0.531

------------------------------------------------------------------------------
17/27 EXPLAIN_01 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:

RESPONSE:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial

Repeated bigram ratio: 0.758

------------------------------------------------------------------------------
18/27 EXPLAIN_02 | Explanation
------------------------------------------------------------------------------
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:

RESPONSE:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one

Repeated bigram ratio: 0.725

------------------------------------------------------------------------------
19/27 EXPLAIN_03 | Explanation Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:

RESPONSE:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em

Repeated bigram ratio: 0.676

------------------------------------------------------------------------------
20/27 INST_01 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List exactly three colors.
Assistant:

RESPONSE:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist

Repeated bigram ratio: 0.800

------------------------------------------------------------------------------
21/27 INST_02 | Instruction
------------------------------------------------------------------------------
PROMPT:
User: List the numbers from 1 to 5.
Assistant:

RESPONSE:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers

Expected score: 0.400

Repeated bigram ratio: 0.837

------------------------------------------------------------------------------
22/27 INST_03 | Instruction Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Liste exatamente três animais.
Assistant:

RESPONSE:
Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

L

Repeated bigram ratio: 0.829

------------------------------------------------------------------------------
23/27 PY_01 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:

RESPONSE:
Add that the sum of a and b is a function of the form

The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of

Expected score: 0.000

Repeated bigram ratio: 0.721

------------------------------------------------------------------------------
24/27 PY_02 | Python
------------------------------------------------------------------------------
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:

RESPONSE:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function

Expected score: 0.500

Repeated bigram ratio: 0.765

------------------------------------------------------------------------------
25/27 OPEN_EN | Open English
------------------------------------------------------------------------------
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:

RESPONSE:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science

Repeated bigram ratio: 0.952

------------------------------------------------------------------------------
26/27 OPEN_PT | Open Portuguese
------------------------------------------------------------------------------
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:

RESPONSE:
O que você sabe?

Ou seja:

"O que você sabe?

"O que você sabe?

"O que você sabe?

"O que você sabe?

"O que você sabe?

"O que você sabe?

"O que

Repeated bigram ratio: 0.774

------------------------------------------------------------------------------
27/27 OPEN_ES | Open Spanish
------------------------------------------------------------------------------
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:

RESPONSE:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist

Repeated bigram ratio: 0.800


==============================================================================
SUMMARY
==============================================================================

MODEL               STEP      EXPECTED    REPETITION
----------------------------------------------------
base-106000            0         0.184         0.587
sft-500              500         0.100         0.668
sft-1000            1000         0.153         0.689
sft-1500            1500         0.205         0.707
sft-2000            2000         0.153         0.710
sft-2500            2500         0.153         0.724
sft-3000            3000         0.153         0.696


==============================================================================
TEST-BY-TEST COMPARISON
==============================================================================


##############################################################################
EN_FACT_01 | English factual
##############################################################################

--- base-106000 ---
the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel of the Channel of the Sable.

The capital is located on the island of Brittany, on the southern shore of the Channel of the Sable.

--- sft-500 ---
What is the capital of France?

The city of User is the capital of the department of User.

History

The city was founded in the 12th century by the French king Louis IX of France. The city was founded in 1250 by the French king Louis IX of France. The

--- sft-1000 ---
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

--- sft-1500 ---
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

--- sft-2000 ---
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

--- sft-2500 ---
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital

--- sft-3000 ---
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital


##############################################################################
EN_FACT_02 | English factual
##############################################################################

--- base-106000 ---
the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in

--- sft-500 ---
What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User:

--- sft-1000 ---
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

--- sft-1500 ---
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

--- sft-2000 ---
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

--- sft-2500 ---
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in

--- sft-3000 ---
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in


##############################################################################
PT_FACT_01 | Portuguese factual
##############################################################################

--- base-106000 ---

In [ ]:
# ============================================================
# MAIA LITE - EXPERIMENTAL SFT #2
# RESPONSE-ONLY / ASSISTANT-ONLY LOSS
#
# PURPOSE:
#   Determine whether the Golden 106K checkpoint already
#   contains enough pretrained knowledge to become an
#   instruction-following model through SFT.
#
# CONTROLLED COMPARISON WITH SFT #1:
#
#   SAME:
#     - Golden checkpoint-106000
#     - EN/PT/ES Alpaca datasets
#     - Language mix: 40/30/30
#     - Effective batch size: 32
#     - Learning rate: 1e-5
#     - 3000 steps
#     - Checkpoint every 500 steps
#     - BF16
#
#   CHANGED:
#     - Loss ONLY on Assistant response
#     - max_length: 512
#
# IMPORTANT:
#   Golden checkpoint-106000 is NEVER modified.
# ============================================================

import os

# Set BEFORE importing torch
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import gc
import json
import torch

from datasets import load_dataset, interleave_datasets
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    TrainingArguments,
    Trainer,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

OUTPUT_DIR = os.path.join(
    PROJECT_DIR,
    "experiments",
    "sft_response_only_from_106k"
)

FINAL_DIR = os.path.join(
    OUTPUT_DIR,
    "maia_lite_106k_sft_response_only_3000"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

MAX_LENGTH = 512

MAX_STEPS = 3000

MICRO_BATCH = 8

GRAD_ACCUM = 4

LEARNING_RATE = 1e-5

WARMUP_STEPS = 100

SAVE_STEPS = 500

LOGGING_STEPS = 25

WEIGHT_DECAY = 0.01

MAX_GRAD_NORM = 1.0

SEED = 42


# ============================================================
# 3. GPU
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA GPU required."
    )

device = torch.device("cuda")

print("=" * 78)
print("MAIA LITE - EXPERIMENTAL SFT #2")
print("RESPONSE-ONLY LOSS")
print("=" * 78)

print()

print(
    "Base checkpoint:"
)

print(
    GOLDEN_CHECKPOINT
)

print()

print(
    "Output directory:"
)

print(
    OUTPUT_DIR
)

print()

print(
    "GPU:    ",
    torch.cuda.get_device_name(0)
)

print(
    "PyTorch:",
    torch.__version__
)

print(
    "CUDA:   ",
    torch.version.cuda
)


# ============================================================
# 4. TOKENIZER
# ============================================================

print()
print("Loading Maia Lite tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(
    f"Vocabulary: {tokenizer.vocab_size:,}"
)

print(
    f"EOS token:  {tokenizer.eos_token_id}"
)

print(
    f"PAD token:  {tokenizer.pad_token_id}"
)


# ============================================================
# 5. LOAD GOLDEN 106K
# ============================================================

print()
print("=" * 78)
print("LOADING GOLDEN 106K")
print("=" * 78)

model = GPT2LMHeadModel.from_pretrained(
    GOLDEN_CHECKPOINT,
    local_files_only=True,
    torch_dtype=torch.bfloat16,
)

model.config.use_cache = False

print(
    f"Parameters: "
    f"{sum(p.numel() for p in model.parameters()):,}"
)


# ============================================================
# 6. LOAD DATASETS
# ============================================================

print()
print("=" * 78)
print("LOADING INSTRUCTION DATASETS")
print("=" * 78)

print()
print("Loading English Alpaca...")

dataset_en = load_dataset(
    "tatsu-lab/alpaca",
    split="train",
    streaming=True,
)

print("Loading Portuguese Alpaca...")

dataset_pt = load_dataset(
    "pinzhenchen/alpaca-cleaned-pt",
    split="train",
    streaming=True,
)

print("Loading Spanish Alpaca...")

dataset_es = load_dataset(
    "bertin-project/alpaca-spanish",
    split="train",
    streaming=True,
)


# ============================================================
# 7. FORMAT DATA
# ============================================================

def normalize_example(example):

    instruction = str(
        example.get(
            "instruction",
            ""
        )
    ).strip()

    input_text = str(
        example.get(
            "input",
            ""
        )
    ).strip()

    output_text = str(
        example.get(
            "output",
            ""
        )
    ).strip()

    # Preserve the same basic User / Assistant format
    # used in SFT experiment #1.

    if input_text:

        user_text = (
            instruction
            + "\n"
            + input_text
        )

    else:

        user_text = instruction

    prompt = (
        "User: "
        + user_text
        + "\nAssistant:"
    )

    return {
        "prompt": prompt,
        "response": output_text,
    }


print()
print("Normalizing datasets...")

dataset_en = dataset_en.map(
    normalize_example
)

dataset_pt = dataset_pt.map(
    normalize_example
)

dataset_es = dataset_es.map(
    normalize_example
)


# ============================================================
# 8. INTERLEAVE LANGUAGES
# ============================================================

print()
print(
    "Interleaving languages: "
    "EN=40%, PT=30%, ES=30%"
)

dataset = interleave_datasets(
    [
        dataset_en,
        dataset_pt,
        dataset_es,
    ],
    probabilities=[
        0.40,
        0.30,
        0.30,
    ],
    seed=SEED,
    stopping_strategy="all_exhausted",
)


# ============================================================
# 9. RESPONSE-ONLY TOKENIZATION
#
# IMPORTANT:
#
# input_ids:
#
#   User: instruction
#   Assistant: response <EOS>
#
# labels:
#
#   -100 -100 -100 ... response_tokens EOS
#
# Therefore:
#
#   prompt participates in attention
#   prompt DOES NOT participate in loss
#   assistant response DOES participate in loss
#
# ============================================================

def tokenize_response_only(example):

    prompt = example["prompt"]

    response = example["response"]

    # --------------------------------------------------------
    # Tokenize separately.
    #
    # Do NOT add special tokens automatically.
    # --------------------------------------------------------

    prompt_ids = tokenizer.encode(
        prompt,
        add_special_tokens=False,
    )

    response_ids = tokenizer.encode(
        response,
        add_special_tokens=False,
    )

    # --------------------------------------------------------
    # Explicit EOS after Assistant response.
    # This teaches the model when to stop.
    # --------------------------------------------------------

    response_ids = (
        response_ids
        + [tokenizer.eos_token_id]
    )

    # --------------------------------------------------------
    # Reserve space for the response.
    #
    # If prompt + response exceeds MAX_LENGTH,
    # truncate the prompt FIRST.
    #
    # We want to preserve the Assistant answer.
    # --------------------------------------------------------

    if len(response_ids) >= MAX_LENGTH:

        # Extremely long response:
        # preserve response up to MAX_LENGTH.
        #
        # Keep EOS as final token.

        response_ids = (
            response_ids[
                :MAX_LENGTH - 1
            ]
            + [
                tokenizer.eos_token_id
            ]
        )

        prompt_ids = []

    else:

        max_prompt_length = (
            MAX_LENGTH
            - len(response_ids)
        )

        if len(prompt_ids) > max_prompt_length:

            # Keep the end of the prompt because
            # Assistant: is located there.

            prompt_ids = prompt_ids[
                -max_prompt_length:
            ]


    # --------------------------------------------------------
    # Full model input
    # --------------------------------------------------------

    input_ids = (
        prompt_ids
        + response_ids
    )

    attention_mask = [
        1
    ] * len(input_ids)


    # --------------------------------------------------------
    # RESPONSE-ONLY LABELS
    #
    # -100 tells PyTorch CrossEntropyLoss to ignore
    # those positions.
    # --------------------------------------------------------

    labels = (
        [-100] * len(prompt_ids)
        + response_ids.copy()
    )


    # --------------------------------------------------------
    # Sanity check
    # --------------------------------------------------------

    assert (
        len(input_ids)
        == len(attention_mask)
        == len(labels)
    )

    assert (
        len(input_ids)
        <= MAX_LENGTH
    )


    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }


print()
print("Tokenizing stream with RESPONSE-ONLY labels...")

tokenized_dataset = dataset.map(
    tokenize_response_only,
    remove_columns=[
        "instruction",
        "input",
        "output",
        "text",
        "prompt",
        "response",
    ],
)


# ============================================================
# 10. CUSTOM COLLATOR
#
# Dynamic padding.
#
# IMPORTANT:
#   input_ids padding -> PAD token
#   attention_mask    -> 0
#   labels padding    -> -100
#
# ============================================================

class ResponseOnlyCollator:

    def __init__(
        self,
        tokenizer,
    ):

        self.tokenizer = tokenizer


    def __call__(
        self,
        features,
    ):

        max_len = max(
            len(
                item["input_ids"]
            )
            for item in features
        )

        batch_input_ids = []

        batch_attention_mask = []

        batch_labels = []


        for item in features:

            length = len(
                item["input_ids"]
            )

            padding = (
                max_len
                - length
            )


            input_ids = (
                item["input_ids"]
                + [
                    self.tokenizer.pad_token_id
                ] * padding
            )


            attention_mask = (
                item["attention_mask"]
                + [0] * padding
            )


            labels = (
                item["labels"]
                + [-100] * padding
            )


            batch_input_ids.append(
                input_ids
            )

            batch_attention_mask.append(
                attention_mask
            )

            batch_labels.append(
                labels
            )


        return {

            "input_ids":
                torch.tensor(
                    batch_input_ids,
                    dtype=torch.long,
                ),

            "attention_mask":
                torch.tensor(
                    batch_attention_mask,
                    dtype=torch.long,
                ),

            "labels":
                torch.tensor(
                    batch_labels,
                    dtype=torch.long,
                ),
        }


data_collator = ResponseOnlyCollator(
    tokenizer
)


# ============================================================
# 11. SANITY CHECK
#
# Inspect one example BEFORE training.
#
# We want to prove that:
#
#   prompt labels = -100
#   response labels = real token IDs
#
# ============================================================

print()
print("=" * 78)
print("RESPONSE-ONLY LABEL SANITY CHECK")
print("=" * 78)

sample = next(
    iter(tokenized_dataset)
)

sample_input_ids = (
    sample["input_ids"]
)

sample_labels = (
    sample["labels"]
)

first_trainable_index = next(
    (
        i
        for i, label
        in enumerate(sample_labels)
        if label != -100
    ),
    None,
)

if first_trainable_index is None:

    raise RuntimeError(
        "Sanity check failed: "
        "no trainable Assistant tokens."
    )


prompt_part = tokenizer.decode(
    sample_input_ids[
        :first_trainable_index
    ],
    skip_special_tokens=False,
)

response_part = tokenizer.decode(
    sample_input_ids[
        first_trainable_index:
    ],
    skip_special_tokens=False,
)


print()
print("PROMPT / LOSS MASKED:")
print("-" * 78)

print(
    prompt_part
)

print()
print("ASSISTANT RESPONSE / TRAINED:")
print("-" * 78)

print(
    response_part
)

print()
print(
    "Masked prompt tokens:",
    first_trainable_index
)

print(
    "Trainable response tokens:",
    len(sample_labels)
    - first_trainable_index
)


# ============================================================
# 12. TRAINING ARGUMENTS
# ============================================================

training_args = TrainingArguments(

    output_dir=OUTPUT_DIR,

    max_steps=MAX_STEPS,

    per_device_train_batch_size=(
        MICRO_BATCH
    ),

    gradient_accumulation_steps=(
        GRAD_ACCUM
    ),

    learning_rate=(
        LEARNING_RATE
    ),

    lr_scheduler_type="cosine",

    warmup_steps=(
        WARMUP_STEPS
    ),

    weight_decay=(
        WEIGHT_DECAY
    ),

    max_grad_norm=(
        MAX_GRAD_NORM
    ),

    optim="adamw_torch",

    bf16=True,

    fp16=False,

    logging_steps=(
        LOGGING_STEPS
    ),

    logging_strategy="steps",

    save_strategy="steps",

    save_steps=(
        SAVE_STEPS
    ),

    save_total_limit=6,

    report_to="none",

    dataloader_num_workers=0,

    remove_unused_columns=False,

    seed=SEED,

    data_seed=SEED,
)


# ============================================================
# 13. TRAINER
# ============================================================

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=(
        tokenized_dataset
    ),

    data_collator=(
        data_collator
    ),
)


# ============================================================
# 14. EXPERIMENT METADATA
# ============================================================

metadata = {

    "experiment":
        "Maia Lite SFT #2 - response-only",

    "base_checkpoint":
        GOLDEN_CHECKPOINT,

    "objective":
        "Assistant response tokens only",

    "prompt_labels":
        -100,

    "max_length":
        MAX_LENGTH,

    "max_steps":
        MAX_STEPS,

    "micro_batch":
        MICRO_BATCH,

    "gradient_accumulation":
        GRAD_ACCUM,

    "effective_batch":
        (
            MICRO_BATCH
            * GRAD_ACCUM
        ),

    "learning_rate":
        LEARNING_RATE,

    "warmup_steps":
        WARMUP_STEPS,

    "language_probabilities": {
        "en": 0.40,
        "pt": 0.30,
        "es": 0.30,
    },

    "datasets": {
        "en":
            "tatsu-lab/alpaca",

        "pt":
            "pinzhenchen/alpaca-cleaned-pt",

        "es":
            "bertin-project/alpaca-spanish",
    },

    "seed":
        SEED,
}


with open(
    os.path.join(
        OUTPUT_DIR,
        "experiment_metadata.json",
    ),
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        metadata,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 15. PRINT CONFIGURATION
# ============================================================

print()
print("=" * 78)
print("EXPERIMENT CONFIGURATION")
print("=" * 78)

print(
    f"Max length:            "
    f"{MAX_LENGTH}"
)

print(
    f"Max steps:             "
    f"{MAX_STEPS:,}"
)

print(
    f"Micro batch:           "
    f"{MICRO_BATCH}"
)

print(
    f"Gradient accumulation: "
    f"{GRAD_ACCUM}"
)

print(
    f"Effective batch:       "
    f"{MICRO_BATCH * GRAD_ACCUM}"
)

print(
    f"Learning rate:         "
    f"{LEARNING_RATE:.2e}"
)

print(
    f"Warmup:                "
    f"{WARMUP_STEPS}"
)

print(
    f"Checkpoint interval:   "
    f"{SAVE_STEPS}"
)

print(
    "Loss objective:        "
    "ASSISTANT RESPONSE ONLY"
)

print(
    "Prompt loss:           "
    "MASKED (-100)"
)

print(
    "BF16:                  "
    "True"
)


# ============================================================
# 16. TRAIN
# ============================================================

print()
print("=" * 78)
print("STARTING RESPONSE-ONLY SFT")
print("=" * 78)

print()
print(
    "Golden checkpoint-106000 "
    "remains untouched."
)

print()

trainer.train()


# ============================================================
# 17. SAVE FINAL MODEL
# ============================================================

print()
print("=" * 78)
print("SAVING EXPERIMENTAL MODEL")
print("=" * 78)

trainer.save_model(
    FINAL_DIR
)

tokenizer.save_pretrained(
    FINAL_DIR
)


# ============================================================
# 18. CLEANUP
# ============================================================

model.config.use_cache = True

gc.collect()

torch.cuda.empty_cache()


# ============================================================
# 19. COMPLETE
# ============================================================

print()
print("=" * 78)
print("RESPONSE-ONLY SFT COMPLETE")
print("=" * 78)

print()

print("Base preserved:")
print(
    GOLDEN_CHECKPOINT
)

print()

print("Checkpoints:")
print(
    OUTPUT_DIR
)

print()

print("Final experimental model:")
print(
    FINAL_DIR
)

print()

print("NEXT STEP:")
print(
    "Benchmark response-only checkpoints "
    "500 / 1000 / 1500 / 2000 / 2500 / 3000 "
    "against Golden 106K and SFT #1."
)

==============================================================================
MAIA LITE - EXPERIMENTAL SFT #2
RESPONSE-ONLY LOSS
==============================================================================

Base checkpoint:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Output directory:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k

GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA:    12.8

Loading Maia Lite tokenizer...
Vocabulary: 50,257
EOS token:  2
PAD token:  1

==============================================================================
LOADING GOLDEN 106K
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters: 354,823,168

==============================================================================
LOADING INSTRUCTION DATASETS
==============================================================================

Loading English Alpaca...
Loading Portuguese Alpaca...
Loading Spanish Alpaca...

Normalizing datasets...

Interleaving languages: EN=40%, PT=30%, ES=30%

Tokenizing stream with RESPONSE-ONLY labels...

==============================================================================
RESPONSE-ONLY LABEL SANITY CHECK
==============================================================================

PROMPT / LOSS MASKED:
------------------------------------------------------------------------------
User: ¿Qué significa DNA?
Assistant:

ASSISTANT RESPONSE / TRAINED:
------------------------------------------------------------------------------
DNA significa ácido desoxirribonucleico.</s>

Masked prompt tokens: 13
Trainable response tokens: 11

==============================================================================
EXPERIMENT CONFIGURATION
==============================================================================
Max length:            512
Max steps:             3,000
Micro batch:           8
Gradient accumulation: 4
Effective batch:       32
Learning rate:         1.00e-05
Warmup:                100
Checkpoint interval:   500
Loss objective:        ASSISTANT RESPONSE ONLY
Prompt loss:           MASKED (-100)
BF16:                  True

==============================================================================
STARTING RESPONSE-ONLY SFT
==============================================================================

Golden checkpoint-106000 remains untouched.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================================
SAVING EXPERIMENTAL MODEL
==============================================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================================
RESPONSE-ONLY SFT COMPLETE
==============================================================================

Base preserved:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Checkpoints:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k

Final experimental model:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/maia_lite_106k_sft_response_only_3000

NEXT STEP:
Benchmark response-only checkpoints 500 / 1000 / 1500 / 2000 / 2500 / 3000 against Golden 106K and SFT #1.

In [ ]:
# ============================================================
# MAIA LITE - DECISIVE SFT BENCHMARK
#
# Compare:
#
#   1. Golden Base 106K
#
#   2. SFT #1 - FULL-SEQUENCE LOSS
#      500 / 1000 / 1500 / 2000 / 2500 / 3000
#
#   3. SFT #2 - RESPONSE-ONLY LOSS
#      500 / 1000 / 1500 / 2000 / 2500 / 3000
#
# PURPOSE:
#
#   Determine whether Golden 106K already contains enough
#   pretrained capability to become a useful instruction model
#   without continuing pretraining toward 300K.
#
# IMPORTANT:
#
#   - NO TRAINING
#   - NO WEIGHT CHANGES
#   - deterministic greedy decoding
#   - no repetition penalty
#   - no no-repeat-ngram constraint
#   - same tests for both SFT experiments
#
# ============================================================

import os
import gc
import json
import re
import math
import torch

from collections import Counter

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

BASE_106K = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

SFT1_DIR = os.path.join(
    PROJECT_DIR,
    "experiments",
    "sft_from_106k"
)

SFT2_DIR = os.path.join(
    PROJECT_DIR,
    "experiments",
    "sft_response_only_from_106k"
)

DIAGNOSTICS_DIR = os.path.join(
    PROJECT_DIR,
    "diagnostics"
)

os.makedirs(
    DIAGNOSTICS_DIR,
    exist_ok=True
)

OUTPUT_JSON = os.path.join(
    DIAGNOSTICS_DIR,
    "decisive_sft_full_vs_response_only.json"
)


# ============================================================
# 2. GENERATION CONFIGURATION
# ============================================================

MAX_NEW_TOKENS = 64

GENERATION_CONFIG = {
    "max_new_tokens": MAX_NEW_TOKENS,
    "do_sample": False,
    "num_beams": 1,
    "repetition_penalty": 1.0,
    "no_repeat_ngram_size": 0,
}


# ============================================================
# 3. LOAD TOKENIZER
# ============================================================

print("=" * 78)
print("MAIA LITE - DECISIVE SFT BENCHMARK")
print("=" * 78)

print()
print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(
    f"Vocabulary: {tokenizer.vocab_size:,}"
)

print(
    f"EOS:        {tokenizer.eos_token_id}"
)

print(
    f"PAD:        {tokenizer.pad_token_id}"
)


# ============================================================
# 4. MODEL DEFINITIONS
# ============================================================

models = [
    {
        "name": "base-106000",
        "family": "base",
        "step": 0,
        "path": BASE_106K,
        "sft": False,
    }
]


for step in [
    500,
    1000,
    1500,
    2000,
    2500,
    3000,
]:

    models.append({
        "name": f"sft1-full-{step}",
        "family": "full-sequence",
        "step": step,
        "path": os.path.join(
            SFT1_DIR,
            f"checkpoint-{step}",
        ),
        "sft": True,
    })


for step in [
    500,
    1000,
    1500,
    2000,
    2500,
    3000,
]:

    models.append({
        "name": f"sft2-response-{step}",
        "family": "response-only",
        "step": step,
        "path": os.path.join(
            SFT2_DIR,
            f"checkpoint-{step}",
        ),
        "sft": True,
    })


# ============================================================
# 5. VERIFY CHECKPOINTS
# ============================================================

print()
print("=" * 78)
print("CHECKPOINT VERIFICATION")
print("=" * 78)

missing = []

for info in models:

    exists = os.path.isdir(
        info["path"]
    )

    status = (
        "OK"
        if exists
        else "MISSING"
    )

    print(
        f"{info['name']:<24} "
        f"{status}"
    )

    if not exists:
        missing.append(
            info["path"]
        )


if missing:

    print()
    print("Missing checkpoints:")

    for path in missing:
        print(path)

    raise RuntimeError(
        "One or more checkpoints are missing."
    )


# ============================================================
# 6. TEST DEFINITIONS
#
# For BASE:
#   natural completion prompts
#
# For SFT:
#   User: instruction
#   Assistant:
#
# expected_terms:
#   terms used for simple objective scoring.
#
# Empty expected_terms means qualitative-only test.
# ============================================================

tests = [

    # --------------------------------------------------------
    # FACTUAL - ENGLISH
    # --------------------------------------------------------

    {
        "id": "EN_FACT_01",
        "category": "English factual",

        "base_prompt":
            "The capital of France is",

        "instruction":
            "What is the capital of France?",

        "expected_terms": [
            "paris",
        ],
    },

    {
        "id": "EN_FACT_02",
        "category": "English factual",

        "base_prompt":
            "The largest planet in the Solar System is",

        "instruction":
            "What is the largest planet in the Solar System?",

        "expected_terms": [
            "jupiter",
        ],
    },


    # --------------------------------------------------------
    # FACTUAL - PORTUGUESE
    # --------------------------------------------------------

    {
        "id": "PT_FACT_01",
        "category": "Portuguese factual",

        "base_prompt":
            "A capital do Brasil é",

        "instruction":
            "Qual é a capital do Brasil?",

        "expected_terms": [
            "brasília",
            "brasilia",
        ],
    },

    {
        "id": "PT_FACT_02",
        "category": "Portuguese factual",

        "base_prompt":
            "O maior planeta do Sistema Solar é",

        "instruction":
            "Qual é o maior planeta do Sistema Solar?",

        "expected_terms": [
            "júpiter",
            "jupiter",
        ],
    },


    # --------------------------------------------------------
    # FACTUAL - SPANISH
    # --------------------------------------------------------

    {
        "id": "ES_FACT_01",
        "category": "Spanish factual",

        "base_prompt":
            "La capital de España es",

        "instruction":
            "¿Cuál es la capital de España?",

        "expected_terms": [
            "madrid",
        ],
    },

    {
        "id": "ES_FACT_02",
        "category": "Spanish factual",

        "base_prompt":
            "El planeta más grande del Sistema Solar es",

        "instruction":
            "¿Cuál es el planeta más grande del Sistema Solar?",

        "expected_terms": [
            "júpiter",
            "jupiter",
        ],
    },


    # --------------------------------------------------------
    # MATHEMATICS
    # --------------------------------------------------------

    {
        "id": "MATH_01",
        "category": "Mathematics",

        "base_prompt":
            "2 + 2 =",

        "instruction":
            "What is 2 + 2?",

        "expected_terms": [
            "4",
        ],
    },

    {
        "id": "MATH_02",
        "category": "Mathematics",

        "base_prompt":
            "10 * 5 =",

        "instruction":
            "What is 10 multiplied by 5?",

        "expected_terms": [
            "50",
        ],
    },

    {
        "id": "MATH_03",
        "category": "Mathematics",

        "base_prompt":
            "The square root of 81 is",

        "instruction":
            "What is the square root of 81?",

        "expected_terms": [
            "9",
        ],
    },

    {
        "id": "MATH_04",
        "category": "Mathematics",

        "base_prompt":
            "If x + 3 = 7, then x =",

        "instruction":
            "Solve x + 3 = 7. What is x?",

        "expected_terms": [
            "4",
        ],
    },


    # --------------------------------------------------------
    # SEMANTIC RELATION
    # --------------------------------------------------------

    {
        "id": "SEM_01",
        "category": "Semantic",

        "base_prompt":
            "Paris is in France. Rome is in Italy. Madrid is in",

        "instruction":
            (
                "Complete the relation: "
                "Paris is in France, "
                "Rome is in Italy, "
                "and Madrid is in what country?"
            ),

        "expected_terms": [
            "spain",
        ],
    },

    {
        "id": "SEM_02",
        "category": "Semantic",

        "base_prompt":
            "Bird is to sky as fish is to",

        "instruction":
            (
                "Complete the analogy: "
                "bird is to sky as fish is to what?"
            ),

        "expected_terms": [
            "water",
        ],
    },

    {
        "id": "SEM_03",
        "category": "Classification",

        "base_prompt":
            "A dog is an animal and a rose is a",

        "instruction":
            (
                "A dog is an animal. "
                "What kind of thing is a rose?"
            ),

        "expected_terms": [
            "plant",
            "flower",
        ],
    },


    # --------------------------------------------------------
    # TRANSLATION
    # --------------------------------------------------------

    {
        "id": "TRANS_01",
        "category": "Translation",

        "base_prompt":
            (
                "English: The house is beautiful.\n"
                "Portuguese:"
            ),

        "instruction":
            (
                "Translate into Portuguese: "
                "The house is beautiful."
            ),

        "expected_terms": [
            "casa",
            "bonita",
            "bela",
        ],
    },

    {
        "id": "TRANS_02",
        "category": "Translation",

        "base_prompt":
            (
                "Portuguese: O livro está sobre a mesa.\n"
                "English:"
            ),

        "instruction":
            (
                "Translate into English: "
                "O livro está sobre a mesa."
            ),

        "expected_terms": [
            "book",
            "table",
        ],
    },

    {
        "id": "TRANS_03",
        "category": "Translation",

        "base_prompt":
            (
                "English: Good morning.\n"
                "Spanish:"
            ),

        "instruction":
            (
                "Translate into Spanish: "
                "Good morning."
            ),

        "expected_terms": [
            "buenos",
            "días",
            "dias",
        ],
    },


    # --------------------------------------------------------
    # EXPLANATION
    # --------------------------------------------------------

    {
        "id": "EXPLAIN_01",
        "category": "Explanation",

        "base_prompt":
            "Artificial intelligence is",

        "instruction":
            (
                "Explain artificial intelligence "
                "in one short sentence."
            ),

        "expected_terms": [],
    },

    {
        "id": "EXPLAIN_02",
        "category": "Explanation",

        "base_prompt":
            "A neural network is",

        "instruction":
            (
                "Explain what a neural network is "
                "in one short sentence."
            ),

        "expected_terms": [],
    },

    {
        "id": "EXPLAIN_03",
        "category": "Explanation Portuguese",

        "base_prompt":
            "Aprendizado de máquina é",

        "instruction":
            (
                "Explique em uma frase curta "
                "o que é aprendizado de máquina."
            ),

        "expected_terms": [],
    },


    # --------------------------------------------------------
    # SIMPLE INSTRUCTIONS
    # --------------------------------------------------------

    {
        "id": "INST_01",
        "category": "Instruction",

        "base_prompt":
            "The colors red, green and blue are",

        "instruction":
            "List exactly three colors.",

        "expected_terms": [],
    },

    {
        "id": "INST_02",
        "category": "Instruction",

        "base_prompt":
            "The numbers from one to five are",

        "instruction":
            "List the numbers from 1 to 5.",

        "expected_terms": [
            "1",
            "2",
            "3",
            "4",
            "5",
        ],
    },

    {
        "id": "INST_03",
        "category": "Instruction Portuguese",

        "base_prompt":
            "Três animais são",

        "instruction":
            "Liste exatamente três animais.",

        "expected_terms": [],
    },


    # --------------------------------------------------------
    # PYTHON
    # --------------------------------------------------------

    {
        "id": "PY_01",
        "category": "Python",

        "base_prompt":
            (
                "def add(a, b):\n"
                "    return"
            ),

        "instruction":
            (
                "Write a Python function called add "
                "that returns the sum of a and b."
            ),

        "expected_terms": [
            "def",
            "return",
        ],
    },

    {
        "id": "PY_02",
        "category": "Python",

        "base_prompt":
            (
                "def square(x):\n"
                "    return"
            ),

        "instruction":
            (
                "Write a Python function called square "
                "that returns x squared."
            ),

        "expected_terms": [
            "def",
            "return",
        ],
    },


    # --------------------------------------------------------
    # OPEN GENERATION
    # --------------------------------------------------------

    {
        "id": "OPEN_EN",
        "category": "Open English",

        "base_prompt":
            "The importance of science is",

        "instruction":
            (
                "Write one short sentence "
                "about the importance of science."
            ),

        "expected_terms": [],
    },

    {
        "id": "OPEN_PT",
        "category": "Open Portuguese",

        "base_prompt":
            "A importância da ciência é",

        "instruction":
            (
                "Escreva uma frase curta "
                "sobre a importância da ciência."
            ),

        "expected_terms": [],
    },

    {
        "id": "OPEN_ES",
        "category": "Open Spanish",

        "base_prompt":
            "La importancia de la ciencia es",

        "instruction":
            (
                "Escribe una frase corta "
                "sobre la importancia de la ciencia."
            ),

        "expected_terms": [],
    },
]


print()
print(
    f"Tests: {len(tests)}"
)


# ============================================================
# 7. TEXT NORMALIZATION
# ============================================================

def normalize_text(text):

    text = text.lower()

    # Preserve accented letters and digits.

    text = re.sub(
        r"[^\wáéíóúüñçãõâêôàèìòùäëïöü]+",
        " ",
        text,
        flags=re.UNICODE,
    )

    return " ".join(
        text.split()
    )


# ============================================================
# 8. EXPECTED TERM SCORE
#
# Example:
#
# expected = ["book", "table"]
#
# both found -> 1.0
# one found  -> 0.5
# none       -> 0.0
#
# Alternative spellings are handled imperfectly by this
# simple metric, exactly as in the previous benchmark.
# ============================================================

def expected_score(
    completion,
    expected_terms,
):

    if not expected_terms:
        return None

    normalized = normalize_text(
        completion
    )

    hits = 0

    for term in expected_terms:

        term_norm = normalize_text(
            term
        )

        if term_norm in normalized:
            hits += 1

    return (
        hits
        / len(expected_terms)
    )


# ============================================================
# 9. REPETITION METRICS
# ============================================================

def word_list(text):

    normalized = normalize_text(
        text
    )

    if not normalized:
        return []

    return normalized.split()


def unique_word_ratio(text):

    words = word_list(
        text
    )

    if not words:
        return 0.0

    return (
        len(set(words))
        / len(words)
    )


def repeated_bigram_ratio(text):

    words = word_list(
        text
    )

    if len(words) < 2:
        return 0.0

    bigrams = list(
        zip(
            words[:-1],
            words[1:],
        )
    )

    if not bigrams:
        return 0.0

    unique_bigrams = len(
        set(bigrams)
    )

    return (
        1.0
        - (
            unique_bigrams
            / len(bigrams)
        )
    )


# ============================================================
# 10. PROMPT ECHO METRIC
#
# Measures how many instruction words appear in the
# beginning of the generated answer.
#
# This is intentionally simple and diagnostic.
# ============================================================

def prompt_echo_ratio(
    instruction,
    completion,
):

    instruction_words = word_list(
        instruction
    )

    completion_words = word_list(
        completion
    )

    if not instruction_words:
        return 0.0

    if not completion_words:
        return 0.0

    # Compare against beginning of generated answer.
    #
    # Limit to instruction length so long completions
    # do not artificially inflate the result.

    beginning = completion_words[
        :len(instruction_words)
    ]

    instruction_counter = Counter(
        instruction_words
    )

    beginning_counter = Counter(
        beginning
    )

    overlap = 0

    for word, count in instruction_counter.items():

        overlap += min(
            count,
            beginning_counter.get(
                word,
                0,
            ),
        )

    return (
        overlap
        / len(instruction_words)
    )


# ============================================================
# 11. CHAT MARKER LEAKAGE
#
# Detect whether generated answer itself starts generating
# User: / Assistant: dialogue markers.
# ============================================================

def chat_marker_count(text):

    lower = text.lower()

    return (
        lower.count("user:")
        + lower.count("assistant:")
    )


# ============================================================
# 12. BUILD PROMPT
# ============================================================

def build_prompt(
    test,
    is_sft,
):

    if not is_sft:

        return test[
            "base_prompt"
        ]

    return (
        "User: "
        + test["instruction"]
        + "\nAssistant:"
    )


# ============================================================
# 13. GENERATION
# ============================================================

@torch.inference_mode()
def generate_completion(
    model,
    prompt,
):

    encoded = tokenizer(
        prompt,
        return_tensors="pt",
        add_special_tokens=False,
    )

    input_ids = encoded[
        "input_ids"
    ].to("cuda")

    attention_mask = encoded[
        "attention_mask"
    ].to("cuda")


    input_length = (
        input_ids.shape[1]
    )


    output = model.generate(

        input_ids=input_ids,

        attention_mask=attention_mask,

        max_new_tokens=MAX_NEW_TOKENS,

        do_sample=False,

        num_beams=1,

        repetition_penalty=1.0,

        no_repeat_ngram_size=0,

        pad_token_id=(
            tokenizer.pad_token_id
        ),

        eos_token_id=(
            tokenizer.eos_token_id
        ),
    )


    generated_ids = output[
        0,
        input_length:
    ]


    completion = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    )


    return completion.strip()


# ============================================================
# 14. BENCHMARK ONE MODEL
# ============================================================

def benchmark_model(info):

    print()
    print("=" * 78)

    print(
        f"MODEL: {info['name']}"
    )

    print(
        f"FAMILY: {info['family']}"
    )

    print("=" * 78)

    print(
        info["path"]
    )

    print()


    model = GPT2LMHeadModel.from_pretrained(

        info["path"],

        local_files_only=True,

        torch_dtype=torch.bfloat16,

    ).to("cuda")


    model.eval()

    model.config.use_cache = True


    results = []


    for index, test in enumerate(
        tests,
        start=1,
    ):

        prompt = build_prompt(
            test,
            info["sft"],
        )


        completion = generate_completion(
            model,
            prompt,
        )


        score = expected_score(
            completion,
            test["expected_terms"],
        )


        repeat_ratio = (
            repeated_bigram_ratio(
                completion
            )
        )


        unique_ratio = (
            unique_word_ratio(
                completion
            )
        )


        echo_ratio = 0.0

        if info["sft"]:

            echo_ratio = (
                prompt_echo_ratio(
                    test["instruction"],
                    completion,
                )
            )


        markers = chat_marker_count(
            completion
        )


        result = {

            "id":
                test["id"],

            "category":
                test["category"],

            "prompt":
                prompt,

            "completion":
                completion,

            "expected_terms":
                test["expected_terms"],

            "expected_score":
                score,

            "word_count":
                len(
                    word_list(
                        completion
                    )
                ),

            "unique_word_ratio":
                unique_ratio,

            "repeated_bigram_ratio":
                repeat_ratio,

            "prompt_echo_ratio":
                echo_ratio,

            "chat_marker_count":
                markers,
        }


        results.append(
            result
        )


        print(
            f"[{index:02d}/{len(tests):02d}] "
            f"{test['id']:<12}"
        )

        print(
            "PROMPT:"
        )

        print(
            prompt
        )

        print(
            "COMPLETION:"
        )

        print(
            completion
        )

        print(
            f"Expected score: "
            f"{score}"
        )

        print(
            f"Repeated bigram: "
            f"{repeat_ratio:.3f}"
        )

        if info["sft"]:

            print(
                f"Prompt echo: "
                f"{echo_ratio:.3f}"
            )

        print(
            f"Chat markers: "
            f"{markers}"
        )

        print("-" * 78)


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    scored = [
        item["expected_score"]
        for item in results
        if item["expected_score"]
        is not None
    ]


    repetitions = [
        item[
            "repeated_bigram_ratio"
        ]
        for item in results
    ]


    unique_ratios = [
        item[
            "unique_word_ratio"
        ]
        for item in results
    ]


    echoes = [
        item[
            "prompt_echo_ratio"
        ]
        for item in results
    ]


    marker_counts = [
        item[
            "chat_marker_count"
        ]
        for item in results
    ]


    mean_score = (
        sum(scored)
        / len(scored)
        if scored
        else None
    )


    mean_repetition = (
        sum(repetitions)
        / len(repetitions)
    )


    mean_unique = (
        sum(unique_ratios)
        / len(unique_ratios)
    )


    mean_echo = (
        sum(echoes)
        / len(echoes)
    )


    total_markers = sum(
        marker_counts
    )


    marker_tests = sum(
        1
        for value in marker_counts
        if value > 0
    )


    summary = {

        "name":
            info["name"],

        "family":
            info["family"],

        "step":
            info["step"],

        "is_sft":
            info["sft"],

        "mean_expected_score":
            mean_score,

        "mean_repeated_bigram_ratio":
            mean_repetition,

        "mean_unique_word_ratio":
            mean_unique,

        "mean_prompt_echo_ratio":
            mean_echo,

        "total_generated_chat_markers":
            total_markers,

        "tests_with_chat_markers":
            marker_tests,

        "tests":
            len(results),
    }


    print()
    print("SUMMARY")

    print(
        json.dumps(
            summary,
            indent=2,
            ensure_ascii=False,
        )
    )


    # --------------------------------------------------------
    # Free GPU before loading next model.
    # --------------------------------------------------------

    del model

    gc.collect()

    torch.cuda.empty_cache()


    return {
        "summary": summary,
        "results": results,
    }


# ============================================================
# 15. RUN ALL MODELS
# ============================================================

all_results = {}

summaries = []


print()
print("=" * 78)
print("STARTING BENCHMARK")
print("=" * 78)

print(
    f"Models: {len(models)}"
)

print(
    f"Tests per model: {len(tests)}"
)

print(
    f"Total generations: "
    f"{len(models) * len(tests)}"
)


for model_info in models:

    result = benchmark_model(
        model_info
    )

    all_results[
        model_info["name"]
    ] = result

    summaries.append(
        result["summary"]
    )


# ============================================================
# 16. FINAL SUMMARY TABLE
# ============================================================

print()
print("=" * 110)
print("FINAL COMPARISON")
print("=" * 110)

header = (
    f"{'MODEL':<24}"
    f"{'FAMILY':<16}"
    f"{'STEP':>7}"
    f"{'EXPECTED':>12}"
    f"{'REPEAT':>12}"
    f"{'UNIQUE':>12}"
    f"{'ECHO':>12}"
    f"{'MARKERS':>10}"
)

print(header)

print("-" * 110)


for summary in summaries:

    expected = (
        "N/A"
        if summary[
            "mean_expected_score"
        ] is None
        else (
            f"{summary['mean_expected_score']:.4f}"
        )
    )


    print(
        f"{summary['name']:<24}"
        f"{summary['family']:<16}"
        f"{summary['step']:>7}"
        f"{expected:>12}"
        f"{summary['mean_repeated_bigram_ratio']:>12.4f}"
        f"{summary['mean_unique_word_ratio']:>12.4f}"
        f"{summary['mean_prompt_echo_ratio']:>12.4f}"
        f"{summary['total_generated_chat_markers']:>10}"
    )


# ============================================================
# 17. FAMILY-SPECIFIC COMPARISON
# ============================================================

print()
print("=" * 78)
print("SFT #1 FULL-SEQUENCE VS SFT #2 RESPONSE-ONLY")
print("=" * 78)


for step in [
    500,
    1000,
    1500,
    2000,
    2500,
    3000,
]:

    full = next(
        x
        for x in summaries
        if (
            x["family"]
            == "full-sequence"
            and x["step"]
            == step
        )
    )


    response = next(
        x
        for x in summaries
        if (
            x["family"]
            == "response-only"
            and x["step"]
            == step
        )
    )


    print()
    print(
        f"STEP {step}"
    )

    print(
        f"  Full sequence:"
        f" expected={full['mean_expected_score']:.4f}"
        f" repeat={full['mean_repeated_bigram_ratio']:.4f}"
        f" echo={full['mean_prompt_echo_ratio']:.4f}"
        f" markers={full['total_generated_chat_markers']}"
    )

    print(
        f"  Response-only:"
        f" expected={response['mean_expected_score']:.4f}"
        f" repeat={response['mean_repeated_bigram_ratio']:.4f}"
        f" echo={response['mean_prompt_echo_ratio']:.4f}"
        f" markers={response['total_generated_chat_markers']}"
    )


# ============================================================
# 18. SAVE JSON
# ============================================================

output = {

    "benchmark":
        "Maia Lite decisive SFT benchmark",

    "purpose":
        (
            "Compare Golden 106K, "
            "full-sequence SFT, and "
            "response-only SFT."
        ),

    "generation":
        GENERATION_CONFIG,

    "models":
        models,

    "summaries":
        summaries,

    "results":
        all_results,
}


with open(
    OUTPUT_JSON,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        output,
        f,
        indent=2,
        ensure_ascii=False,
    )


print()
print("=" * 78)
print("BENCHMARK COMPLETE")
print("=" * 78)

print()
print(
    "Results saved to:"
)

print(
    OUTPUT_JSON
)

print()
print(
    "NO model weights were modified."
)

==============================================================================
MAIA LITE - DECISIVE SFT BENCHMARK
==============================================================================

Loading tokenizer...
Vocabulary: 50,257
EOS:        2
PAD:        1

==============================================================================
CHECKPOINT VERIFICATION
==============================================================================
base-106000              OK
sft1-full-500            OK
sft1-full-1000           OK
sft1-full-1500           OK
sft1-full-2000           OK
sft1-full-2500           OK
sft1-full-3000           OK
sft2-response-500        OK
sft2-response-1000       OK
sft2-response-1500       OK
sft2-response-2000       OK
sft2-response-2500       OK
sft2-response-3000       OK

Tests: 27

==============================================================================
STARTING BENCHMARK
==============================================================================
Models: 13
Tests per model: 27
Total generations: 351

==============================================================================
MODEL: base-106000
FAMILY: base
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
The capital of France is
COMPLETION:
the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel Islands.

The capital is located in the centre of the island, on the island of Brittany, in the Channel Islands. The island is the largest island
Expected score: 0.0
Repeated bigram: 0.449
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
The largest planet in the Solar System is
COMPLETION:
the Sun, which is the largest in the Solar System. The largest planet in the Solar System is the Sun, which is the largest in the Solar System. The largest planet in the Solar System is the Sun, which is the largest in the Solar System. The largest planet in the Solar System is the Sun, which
Expected score: 0.0
Repeated bigram: 0.768
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
A capital do Brasil é
COMPLETION:
a capital do estado do Brasil, sendo também a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo, fundada em 1545, foi fundada por Pedro Álvares Cabral, que se instalou na margem direita do rio Uruguai, em 1545.
Expected score: 0.0
Repeated bigram: 0.149
Chat markers: 0
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
O maior planeta do Sistema Solar é
COMPLETION:
o planeta que orbita o planeta Terra, com uma órbita de aproximadamente  km de diâmetro. O planeta tem uma massa de cerca de  kg e é o mais massivo planeta do sistema solar. O planeta tem uma massa de cerca de  kg e é o mais massivo planeta do sistema solar.

O
Expected score: 0.0
Repeated bigram: 0.392
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
La capital de España es
COMPLETION:
la ciudad más poblada de la República de España, con una población de  habitantes (2022). Es la capital de la provincia homónima, en la región de Castilla-La Mancha.

La ciudad se encuentra en el centro de la provincia, en la región de Castilla-La Mancha, a orillas del río Guadiana,
Expected score: 0.0
Repeated bigram: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
El planeta más grande del Sistema Solar es
COMPLETION:
el planeta más grande del sistema solar, con una superficie de aproximadamente  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km².

El planeta más grande del
Expected score: 0.0
Repeated bigram: 0.633
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
2 + 2 =
COMPLETION:
4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4
Expected score: 1.0
Repeated bigram: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
10 * 5 =
COMPLETION:
5

4 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5
Expected score: 0.0
Repeated bigram: 0.870
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
The square root of 81 is
COMPLETION:
a square root of the genus Platyprocta, a genus of flowering plants in the family Rosaceae. It is native to Europe, the Middle East, and the Caucasus.

The genus name is derived from the Latin word "con" meaning "tooth", and refers to the shape of the root.
Expected score: 0.0
Repeated bigram: 0.043
Chat markers: 0
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
If x + 3 = 7, then x =
COMPLETION:
7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x
Expected score: 0.0
Repeated bigram: 0.921
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
Paris is in France. Rome is in Italy. Madrid is in
COMPLETION:
Spain.

Paris may also refer to:

Places

United States
 Paris, Texas, a city in the United States
 Paris, Illinois, a city in the United States
 Paris, Missouri, a city in the United States
 Paris, Missouri, a city in the United States
 Paris,
Expected score: 1.0
Repeated bigram: 0.537
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
Bird is to sky as fish is to
COMPLETION:
be found in the sky.

Bird may also refer to:

Places

United States
 Bird, Alabama, a city in Alabama
 Bird, Illinois, a city in Illinois
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a
Expected score: 0.0
Repeated bigram: 0.308
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
A dog is an animal and a rose is a
COMPLETION:
type of rose.

Buddhism

Buddhism is a type of vegetarianism that involves the use of a variety of vegetarian or veganic ingredients. The vegetarian diet consists of a variety of vegetarian preparations, including a variety of vegetables, fruits, vegetables, and a
Expected score: 0.0
Repeated bigram: 0.175
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
English: The house is beautiful.
Portuguese:
COMPLETION:
"The house" (song), a song by the band Legião Urbana.

See also
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
 House (disambiguation)
Expected score: 0.0
Repeated bigram: 0.517
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
Portuguese: O livro está sobre a mesa.
English:
COMPLETION:
The Book is about the book.

The book is a collection of essays by the Portuguese poet Manuel Bandeira, published in 1889.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book is a collection of essays,
Expected score: 0.5
Repeated bigram: 0.489
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
English: Good morning.
Spanish:
COMPLETION:
La hora de la gloria
Spanish: La hora de la gloria
Spanish: The day of the Victory
Spanish: La hora de la gloria

Desambiguações de siglas
Desambiguações de topônimos
Desambiguações de história
Desambiguações de cinema
Desambiguações de música
Desambiguações de música
Desambiguações de música
Desambiguações de música
Desambiguações
Expected score: 0.0
Repeated bigram: 0.489
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
Artificial intelligence is
COMPLETION:
a field of artificial intelligence that involves the use of artificial intelligence to manipulate the environment.

History

The field of artificial intelligence was first developed by the United States Army in the early 1950s. The United States Army's first artificial intelligence unit, the U.S. Army's Artificial Intelligence Unit, was
Expected score: None
Repeated bigram: 0.235
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
A neural network is
COMPLETION:
a network of neurons that is composed of neurons that are located in the brain.

The term "snagocyte" is also used for the term "snagocyte" in the context of the brain.

The term "snagocyte" is also used for the term
Expected score: None
Repeated bigram: 0.385
Chat markers: 0
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
Aprendizado de máquina é
COMPLETION:
um programa de computador que permite que um computador de computador se torne um computador de máquina.

O programa é executado em um computador de máquina, geralmente um computador de computador, ou um computador de computador. O programa é executado em um computador de máquina, geralmente um computador de computador, ou um computador de computador.
Expected score: None
Repeated bigram: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
The colors red, green and blue are
COMPLETION:
the official colors of the United States government. The official color of the United States government is blue, the official state color of the United States. The official state color of the United States government is blue, the official state color of the United States. The official state color of the United States government is blue, the official
Expected score: None
Repeated bigram: 0.719
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
The numbers from one to five are
COMPLETION:
the following:

The numbers from the United States to the United States are:

The numbers from the United States to the United States are:

The numbers from the United States to the United States are:

The numbers from the United States to the United States are:

The numbers from
Expected score: 0.0
Repeated bigram: 0.771
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
Três animais são
COMPLETION:
animais que possuem um sistema de locomoção e/ou locomoção.

Os animais que possuem um sistema de locomoção são:

Os animais que possuem um sistema de locomoção são:

Os animais que possuem um sistema de locomoção são:

Os animais que possuem
Expected score: None
Repeated bigram: 0.675
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
def add(a, b):
    return
COMPLETION:
(a, b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b):
    return (b
Expected score: 0.5
Repeated bigram: 0.880
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
def square(x):
    return
COMPLETION:
x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return x :
    return
Expected score: 0.5
Repeated bigram: 0.935
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
The importance of science is
COMPLETION:
the importance of science to the general public.

The importance of science is the importance of science to the general public. The importance of science is the importance of science to the general public.

The importance of science is the importance of science to the general public. The importance of science is the importance of science
Expected score: None
Repeated bigram: 0.818
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
A importância da ciência é
COMPLETION:
a importância da ciência para a compreensão da natureza.

A ciência é uma das áreas mais importantes da ciência, sendo a ciência que se ocupa de todas as questões científicas.

A ciência é uma das áreas mais importantes da ciência, sendo a ciência que se ocupa de todas as questões científicas.

A ciência
Expected score: None
Repeated bigram: 0.462
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
La importancia de la ciencia es
COMPLETION:
la importancia de la ciencia en la sociedad. La ciencia es una disciplina científica que se ocupa de la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de la vida cotidiana, la ciencia de
Expected score: None
Repeated bigram: 0.643
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "base-106000",
  "family": "base",
  "step": 0,
  "is_sft": false,
  "mean_expected_score": 0.18421052631578946,
  "mean_repeated_bigram_ratio": 0.5509526734548543,
  "mean_unique_word_ratio": 0.32102980685804344,
  "mean_prompt_echo_ratio": 0.0,
  "total_generated_chat_markers": 0,
  "tests_with_chat_markers": 0,
  "tests": 27
}

==============================================================================
MODEL: sft1-full-500
FAMILY: full-sequence
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/checkpoint-500

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the capital of France?

The city of User is the capital of the department of User.

History

The city was founded in the 12th century by the French king Louis IX of France. The city was founded in 1250 by the French king Louis IX of France. The
Expected score: 0.0
Repeated bigram: 0.388
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User: What is the planet that is closest to the Sun?

User:
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 0.556
Chat markers: 4
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: O nome da cidade é uma homenagem ao presidente Getúlio Vargas.

História

A cidade foi fundada em 15 de agosto de 1934, por Getúlio Vargas, como capital do país.

A cidade foi fundada em 15 de agosto de 1934, por Getúlio Vargas, como capital do país.
Expected score: 0.0
Repeated bigram: 0.370
Prompt echo: 0.167
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta
Expected score: 0.0
Repeated bigram: 0.234
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuándo es la capital de España?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo. En el año 912, el rey visigodo Leovigildo entregó a su hijo, el rey visigodo Leovigildo, la ciudad de Ux
Expected score: 0.0
Repeated bigram: 0.231
Prompt echo: 0.833
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
¿Cuál es el planeta más grande del sistema solar?

Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas
Expected score: 0.0
Repeated bigram: 0.732
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the first part of the second part of the third part of the third part of the third part of the third part of the third part of the third part of the fourth part of the fourth part of the fourth part of the fourth part of the fourth part of the seventh part of the seventh part of the seventh
Expected score: 0.0
Repeated bigram: 0.778
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times that a given number is in the range of 0 to 1.

The first two digits of the first digits are the first digit, the second digit, and the third digit.

The second digit is the first digit, the second digit, and the third digit is the second
Expected score: 0.0
Repeated bigram: 0.340
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The User: Solve x + 3 = 7. What is x?

User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Sol
Expected score: 0.0
Repeated bigram: 0.600
Prompt echo: 0.714
Chat markers: 6
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in Spain, and the relationship between Paris and the Spanish capital Madrid is in the same way.

The relationship between Paris and the Spanish capital Madrid is in the same way that the relationship between the two cities is in the same way.

Paris is in Spain, and the relationship between the two cities
Expected score: 1.0
Repeated bigram: 0.564
Prompt echo: 0.471
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is
Expected score: 0.0
Repeated bigram: 0.790
Prompt echo: 0.583
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is beautiful, and the house is beautiful.

The house is a beautiful place, and the house is beautiful. The house is beautiful, and the house is beautiful. The house is beautiful, and the house is beautiful. The house is beautiful, and the house is beautiful. The house is beautiful,
Expected score: 0.0
Repeated bigram: 0.800
Prompt echo: 0.571
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre
Expected score: 0.0
Repeated bigram: 0.816
Prompt echo: 0.667
Chat markers: 5
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for "Spanish"
Assistant: The Spanish word for
Expected score: 0.0
Repeated bigram: 0.818
Prompt echo: 0.200
Chat markers: 5
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial
Expected score: None
Repeated bigram: 0.758
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one
Expected score: None
Repeated bigram: 0.725
Prompt echo: 1.000
Chat markers: 3
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em
Expected score: None
Repeated bigram: 0.676
Prompt echo: 0.909
Chat markers: 3
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the moon.
Assistant: The color of the moon.
Assistant: The color of the moon.
Assistant: The color of the moon.
Assist
Expected score: None
Repeated bigram: 0.743
Prompt echo: 0.000
Chat markers: 5
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assist
Expected score: None
Repeated bigram: 0.793
Prompt echo: 0.250
Chat markers: 5
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
Add that the sum of a and b is a function of the same size.
Assistant: Add that the sum of a and b is a function of the same size.
Assistant: Add that the sum of a and b is a function of the same size.
Assistant: Add
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.714
Chat markers: 3
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
Write a function that returns x squared.

The square is a function that returns x squared.

The square is a function that returns x squared.

The square is a function that returns x squared.

The square is a function that returns x squared.
Expected score: 0.5
Repeated bigram: 0.762
Prompt echo: 0.800
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science
Expected score: None
Repeated bigram: 0.952
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano, o ser humano é o ser humano,
Expected score: None
Repeated bigram: 0.909
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.400
Chat markers: 5
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft1-full-500",
  "family": "full-sequence",
  "step": 500,
  "is_sft": true,
  "mean_expected_score": 0.09999999999999999,
  "mean_repeated_bigram_ratio": 0.6805714083931521,
  "mean_unique_word_ratio": 0.2566962587439074,
  "mean_prompt_echo_ratio": 0.5966312675463002,
  "total_generated_chat_markers": 53,
  "tests_with_chat_markers": 13,
  "tests": 27
}

==============================================================================
MODEL: sft1-full-1000
FAMILY: full-sequence
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/checkpoint-1000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital
Expected score: 1.0
Repeated bigram: 0.792
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in
Expected score: 0.0
Repeated bigram: 0.633
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um
Expected score: 0.0
Repeated bigram: 0.767
Prompt echo: 0.333
Chat markers: 4
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe liderada por David C. Brown, que descobriu o planeta a partir de um buraco de água.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema
Expected score: 0.0
Repeated bigram: 0.173
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuándo es la capital de España?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo. En el año 912, el rey visigodo Leovigildo trasladó la capitalidad de la provincia a la ciudad de Toledo.

En el año
Expected score: 0.0
Repeated bigram: 0.195
Prompt echo: 0.833
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².
Expected score: 0.0
Repeated bigram: 0.565
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the first time you have to change the color of the sun.

The first time you have to change the color of the sun is when you change the color of the sun.

The second time you change the color of the sun is when you change the color of the sun.

The
Expected score: 0.0
Repeated bigram: 0.630
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.714
Chat markers: 6
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book was first published in Paris in the French edition of the book in the French edition of the book in the French
Expected score: 1.0
Repeated bigram: 0.412
Prompt echo: 0.529
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is
Expected score: 0.0
Repeated bigram: 0.790
Prompt echo: 0.583
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:
Expected score: 0.0
Repeated bigram: 0.821
Prompt echo: 0.571
Chat markers: 4
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre
Expected score: 0.0
Repeated bigram: 0.816
Prompt echo: 0.667
Chat markers: 5
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a synonym for the Spanish word "Spanish".

The word is used in Spanish as a synonym for the Spanish word "Spanish".

The word is used
Expected score: 0.0
Repeated bigram: 0.468
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial
Expected score: None
Repeated bigram: 0.758
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one
Expected score: None
Repeated bigram: 0.725
Prompt echo: 1.000
Chat markers: 3
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em
Expected score: None
Repeated bigram: 0.676
Prompt echo: 0.909
Chat markers: 3
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.000
Chat markers: 5
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

Liste tudo o que é?

L
Expected score: None
Repeated bigram: 0.829
Prompt echo: 0.250
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
Add that the sum of a and b is a function of the sum of b and b.
Assistant: Add that the sum of b and b is a function of the sum of b and b.
Assistant: Add that the sum of b and b is a function of the sum of b
Expected score: 0.0
Repeated bigram: 0.698
Prompt echo: 0.714
Chat markers: 2
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function
Expected score: 0.5
Repeated bigram: 0.765
Prompt echo: 0.700
Chat markers: 4
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science
Expected score: None
Repeated bigram: 0.952
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O que é o que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O que é?

O
Expected score: None
Repeated bigram: 0.909
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.400
Chat markers: 5
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft1-full-1000",
  "family": "full-sequence",
  "step": 1000,
  "is_sft": true,
  "mean_expected_score": 0.15263157894736842,
  "mean_repeated_bigram_ratio": 0.692353552111013,
  "mean_unique_word_ratio": 0.24233171171673168,
  "mean_prompt_echo_ratio": 0.6012790525862421,
  "total_generated_chat_markers": 49,
  "tests_with_chat_markers": 12,
  "tests": 27
}

==============================================================================
MODEL: sft1-full-1500
FAMILY: full-sequence
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/checkpoint-1500

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital
Expected score: 1.0
Repeated bigram: 0.792
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in
Expected score: 0.0
Repeated bigram: 0.633
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um
Expected score: 0.0
Repeated bigram: 0.767
Prompt echo: 0.333
Chat markers: 4
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe liderada por David C. Brown, que descobriu o planeta a partir de um buraco de água.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema
Expected score: 0.0
Repeated bigram: 0.173
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuándo es la capital de España?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo. En el año 912, el rey visigodo Leovigildo trasladó la capitalidad de la provincia a la ciudad de Toledo.

En el año
Expected score: 0.0
Repeated bigram: 0.195
Prompt echo: 0.833
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
¿Cuál es el planeta más grande del sistema solar?

Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas de Planetas
Expected score: 0.0
Repeated bigram: 0.732
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the second time that a person can change
Expected score: 0.0
Repeated bigram: 0.688
Prompt echo: 0.500
Chat markers: 3
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.714
Chat markers: 6
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays by French writers, and is a collection of essays, essays, and essays.

The book was first published in Paris in the French edition of the book in the French edition of the book
Expected score: 1.0
Repeated bigram: 0.333
Prompt echo: 0.529
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is
Expected score: 0.0
Repeated bigram: 0.790
Prompt echo: 0.583
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:
Expected score: 0.0
Repeated bigram: 0.821
Prompt echo: 0.571
Chat markers: 4
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre
Expected score: 0.0
Repeated bigram: 0.816
Prompt echo: 0.667
Chat markers: 5
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used
Expected score: 0.0
Repeated bigram: 0.531
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial
Expected score: None
Repeated bigram: 0.758
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one
Expected score: None
Repeated bigram: 0.725
Prompt echo: 1.000
Chat markers: 3
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em
Expected score: None
Repeated bigram: 0.676
Prompt echo: 0.909
Chat markers: 3
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.000
Chat markers: 5
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assistant: Liste de um animal.
Assist
Expected score: None
Repeated bigram: 0.793
Prompt echo: 0.250
Chat markers: 5
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of
Expected score: 0.0
Repeated bigram: 0.733
Prompt echo: 0.714
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function
Expected score: 0.5
Repeated bigram: 0.765
Prompt echo: 0.700
Chat markers: 4
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science
Expected score: None
Repeated bigram: 0.952
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O que você sabe?

Ou seja:

"O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O
Expected score: None
Repeated bigram: 0.794
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.400
Chat markers: 5
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft1-full-1500",
  "family": "full-sequence",
  "step": 1500,
  "is_sft": true,
  "mean_expected_score": 0.15263157894736842,
  "mean_repeated_bigram_ratio": 0.6958066982430006,
  "mean_unique_word_ratio": 0.24479222874933068,
  "mean_prompt_echo_ratio": 0.6012790525862421,
  "total_generated_chat_markers": 55,
  "tests_with_chat_markers": 13,
  "tests": 27
}

==============================================================================
MODEL: sft1-full-2000
FAMILY: full-sequence
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/checkpoint-2000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital
Expected score: 1.0
Repeated bigram: 0.792
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in
Expected score: 0.0
Repeated bigram: 0.633
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um
Expected score: 0.0
Repeated bigram: 0.767
Prompt echo: 0.333
Chat markers: 4
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta
Expected score: 0.0
Repeated bigram: 0.234
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.833
Chat markers: 4
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².
Expected score: 0.0
Repeated bigram: 0.565
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the first time that a person can change their behavior.

User: What is the second time that a person can change
Expected score: 0.0
Repeated bigram: 0.688
Prompt echo: 0.500
Chat markers: 3
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.714
Chat markers: 6
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays
Expected score: 1.0
Repeated bigram: 0.609
Prompt echo: 0.529
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is
Expected score: 0.0
Repeated bigram: 0.790
Prompt echo: 0.583
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:
Expected score: 0.0
Repeated bigram: 0.821
Prompt echo: 0.571
Chat markers: 4
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre
Expected score: 0.0
Repeated bigram: 0.816
Prompt echo: 0.667
Chat markers: 5
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used
Expected score: 0.0
Repeated bigram: 0.531
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial
Expected score: None
Repeated bigram: 0.758
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one
Expected score: None
Repeated bigram: 0.725
Prompt echo: 1.000
Chat markers: 3
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em
Expected score: None
Repeated bigram: 0.676
Prompt echo: 0.909
Chat markers: 3
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.000
Chat markers: 5
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura
Expected score: None
Repeated bigram: 0.763
Prompt echo: 0.250
Chat markers: 4
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of
Expected score: 0.0
Repeated bigram: 0.733
Prompt echo: 0.714
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function
Expected score: 0.5
Repeated bigram: 0.765
Prompt echo: 0.700
Chat markers: 4
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science
Expected score: None
Repeated bigram: 0.952
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O que você sabe?

Ou seja:

"O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O
Expected score: None
Repeated bigram: 0.794
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
El término se refiere a un tipo de frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que se refiere a una frase que
Expected score: None
Repeated bigram: 0.810
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft1-full-2000",
  "family": "full-sequence",
  "step": 2000,
  "is_sft": true,
  "mean_expected_score": 0.15263157894736842,
  "mean_repeated_bigram_ratio": 0.7218916733523192,
  "mean_unique_word_ratio": 0.23112492947759586,
  "mean_prompt_echo_ratio": 0.5938716451788347,
  "total_generated_chat_markers": 53,
  "tests_with_chat_markers": 13,
  "tests": 27
}

==============================================================================
MODEL: sft1-full-2500
FAMILY: full-sequence
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/checkpoint-2500

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital
Expected score: 1.0
Repeated bigram: 0.792
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in
Expected score: 0.0
Repeated bigram: 0.633
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um
Expected score: 0.0
Repeated bigram: 0.767
Prompt echo: 0.333
Chat markers: 4
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália.

O planeta foi nomeado em homenagem ao planeta User, o planeta mais brilhante do Sistema Solar?

O planeta
Expected score: 0.0
Repeated bigram: 0.234
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.833
Chat markers: 4
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².
Expected score: 0.0
Repeated bigram: 0.565
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the first time you have a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a
Expected score: 0.0
Repeated bigram: 0.825
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.714
Chat markers: 6
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in Spain, and the relationship between Paris and the Spanish capital Madrid is in the same way.

The relationship between Paris and the Spanish capital Madrid is in the same way as the relationship between the two cities.

Paris is in Spain, and the relationship between Paris and the Spanish capital Madrid is in
Expected score: 1.0
Repeated bigram: 0.582
Prompt echo: 0.471
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is
Expected score: 0.0
Repeated bigram: 0.790
Prompt echo: 0.583
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:
Expected score: 0.0
Repeated bigram: 0.821
Prompt echo: 0.571
Chat markers: 4
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre
Expected score: 0.0
Repeated bigram: 0.816
Prompt echo: 0.667
Chat markers: 5
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used in Spanish as a verb meaning "to be a Spanish word".

The word is used
Expected score: 0.0
Repeated bigram: 0.531
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial
Expected score: None
Repeated bigram: 0.758
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one
Expected score: None
Repeated bigram: 0.725
Prompt echo: 1.000
Chat markers: 3
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em
Expected score: None
Repeated bigram: 0.676
Prompt echo: 0.909
Chat markers: 3
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.000
Chat markers: 5
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura que se alimenta de animais.
Assistant: Liste a criatura
Expected score: None
Repeated bigram: 0.763
Prompt echo: 0.250
Chat markers: 4
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of
Expected score: 0.0
Repeated bigram: 0.733
Prompt echo: 0.714
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function
Expected score: 0.5
Repeated bigram: 0.765
Prompt echo: 0.700
Chat markers: 4
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science
Expected score: None
Repeated bigram: 0.952
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O que você sabe?

Ou seja:

"O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O
Expected score: None
Repeated bigram: 0.794
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assistant: El nombre de la ciencia.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.400
Chat markers: 5
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft1-full-2500",
  "family": "full-sequence",
  "step": 2500,
  "is_sft": true,
  "mean_expected_score": 0.15263157894736842,
  "mean_repeated_bigram_ratio": 0.7256507676307371,
  "mean_unique_word_ratio": 0.22887031079271714,
  "mean_prompt_echo_ratio": 0.5991004033487694,
  "total_generated_chat_markers": 55,
  "tests_with_chat_markers": 13,
  "tests": 27
}

==============================================================================
MODEL: sft1-full-3000
FAMILY: full-sequence
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_from_106k/checkpoint-3000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital of France?

The city of Paris is the capital
Expected score: 1.0
Repeated bigram: 0.792
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun?

The planet is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in diameter. It is about  in diameter and is about  in
Expected score: 0.0
Repeated bigram: 0.633
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um dos mais importantes do país.
Assistant: A cidade é um
Expected score: 0.0
Repeated bigram: 0.767
Prompt echo: 0.333
Chat markers: 4
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de agosto de 2006, por um telescópio espacial Hubble. O planeta foi nomeado em homenagem ao planeta User, o planeta da mitologia grega.

O planeta foi nomeado em homenagem ao planeta User, o planeta da mitologia
Expected score: 0.0
Repeated bigram: 0.320
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo es la capital de España?
Assistant: ¿Cuándo
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.833
Chat markers: 4
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
¿Cuál es el planeta más grande del sistema solar?

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de aproximadamente 1.000 km².
Expected score: 0.0
Repeated bigram: 0.565
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the first time you have a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a chance to get a
Expected score: 0.0
Repeated bigram: 0.825
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times that a given number is in the range of 0 to 1.

The number of times that a given number is in the range of 0 to 1 is the number of times that a given number is in the range of 0 to 1.

The number of times that a given
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant: What is the square root of 81?
Assistant
Expected score: 0.0
Repeated bigram: 0.744
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The User: Solve x + 3 = 7. What is x?
Assistant: The
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.714
Chat markers: 6
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in Spain, and Madrid is in Spain.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays.

The book is a collection of essays, essays, and essays, and is a collection of essays, essays, and essays
Expected score: 1.0
Repeated bigram: 0.609
Prompt echo: 0.529
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The analogy is to say that the bird is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is to be a bird that is
Expected score: 0.0
Repeated bigram: 0.790
Prompt echo: 0.583
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant: The house is beautiful, and the house is beautiful.
Assistant:
Expected score: 0.0
Repeated bigram: 0.821
Prompt echo: 0.571
Chat markers: 4
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre a mesa.
Assistant: O livro está sobre
Expected score: 0.0
Repeated bigram: 0.816
Prompt echo: 0.667
Chat markers: 5
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word for "Spanish" is a Spanish word that means "to be a Spanish word".

The word is used in Spanish as a synonym for the Spanish word "Spanish".

The word is used in Spanish as a synonym for the Spanish word "Spanish".

The word is used
Expected score: 0.0
Repeated bigram: 0.468
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial intelligence in one short sentence.
Assistant: Explain artificial
Expected score: None
Repeated bigram: 0.758
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one short sentence.
Assistant: Explain what a neural network is in one
Expected score: None
Repeated bigram: 0.725
Prompt echo: 1.000
Chat markers: 3
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em uma frase curta o que é aprendido de máquina.
Assistant: Explique em
Expected score: None
Repeated bigram: 0.676
Prompt echo: 0.909
Chat markers: 3
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assistant: The color of the sun.
Assist
Expected score: None
Repeated bigram: 0.800
Prompt echo: 0.000
Chat markers: 5
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste tudo o que é?

Ou seja, o animal é um animal que não é um animal, mas sim um animal que não é um animal.

O animal é um animal que não é um animal, mas sim um animal que não é um animal.

O animal é um animal
Expected score: None
Repeated bigram: 0.633
Prompt echo: 0.250
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
Add that the sum of a and b is a function of the form

where  is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of
Expected score: 0.0
Repeated bigram: 0.733
Prompt echo: 0.714
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function that returns x squared.
Assistant: Write a function
Expected score: 0.5
Repeated bigram: 0.765
Prompt echo: 0.700
Chat markers: 4
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
The science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science of science
Expected score: None
Repeated bigram: 0.952
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O que você sabe?

Ou seja:

"O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O que você sabe?

O
Expected score: None
Repeated bigram: 0.794
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la ciencia que estudia la ciencia.
Assistant: El nombre de la
Expected score: None
Repeated bigram: 0.791
Prompt echo: 0.400
Chat markers: 4
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft1-full-3000",
  "family": "full-sequence",
  "step": 3000,
  "is_sft": true,
  "mean_expected_score": 0.15263157894736842,
  "mean_repeated_bigram_ratio": 0.7223359757624228,
  "mean_unique_word_ratio": 0.22603928527430459,
  "mean_prompt_echo_ratio": 0.6012790525862421,
  "total_generated_chat_markers": 50,
  "tests_with_chat_markers": 12,
  "tests": 27
}

==============================================================================
MODEL: sft2-response-500
FAMILY: response-only
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/checkpoint-500

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the city?

The city is the capital of the department of Aisne.

History

The city was founded in the 12th century by the French king Louis IX of France. It was the capital of the department of Aisne from 1631 to 1790.

The city
Expected score: 0.0
Repeated bigram: 0.222
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: Qual é a cidade mais populosa do estado de São Paulo.

História

A cidade foi fundada em 15 de agosto de 1563, por Martim Afonso de Sousa, como cidade de São Sebastião do Rio Pardo.

A cidade foi fundada em 1563, por Martim Afonso de Sousa, como
Expected score: 0.0
Repeated bigram: 0.255
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de novembro de 2006, por uma equipe de astrônomos do Observatório de Arecibo, na Itália. O planeta foi nomeado em homenagem ao planeta-americano U.S.A.

O planeta foi descoberto em 16 de
Expected score: 0.0
Repeated bigram: 0.188
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuál es la capital?

Historia
La ciudad fue fundada en el año 899 por el rey visigodo Leovigildo, que la convirtió en capital del reino visigodo de Toledo. En el año 912, el rey visigodo Leovigildo trasladó la capitalidad de Toledo a la ciudad de
Expected score: 0.0
Repeated bigram: 0.159
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
El planeta más grande del sistema solar.

Planetas de Júpiter
Planetas de Júpiter
Planetas de Júpiter del siglo XXI
Planetas de Júpiter del siglo XXI

sv:Topoplanet#Planetary system#Planetary system#Planetary system#Planetary system#Plan
Expected score: 0.5
Repeated bigram: 0.429
Prompt echo: 0.778
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the second studio album by the Scottish hard rock band Nazareth, released in 1980. It was the first album to feature guitarist Pete Agnew, who would later join the band.

Track listing

Credits

Nazareth
 Pete Agnew – vocals
 Pete Agnew – guitar
Expected score: 0.0
Repeated bigram: 0.049
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the name of the first chapter of the book.

The book is a collection of essays by the author, including:

"What is the name of the first chapter of the book?"
"What is the name of the second chapter of the book?"
"What is the name of the
Expected score: 0.0
Repeated bigram: 0.531
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the number of times we have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have to have
Expected score: 0.0
Repeated bigram: 0.857
Prompt echo: 0.571
Chat markers: 0
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The Final Conflict is the third installment in the series of Final Conflict. It was released in 2006.

Plot
The series follows the lives of the two protagonists, the two survivors of the previous series, and the two survivors of the previous series, the survivors of the previous series, and the
Expected score: 0.0
Repeated bigram: 0.320
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as
Expected score: 0.0
Repeated bigram: 0.719
Prompt echo: 0.353
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The first two pages of the book are devoted to the history of the bird. The first page describes the history of the bird, the history of the bird, and the history of the bird. The second page describes the history of the bird, the history of the bird, and the history of the bird. The third
Expected score: 0.0
Repeated bigram: 0.607
Prompt echo: 0.167
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a
Expected score: 0.0
Repeated bigram: 0.787
Prompt echo: 0.429
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa,
Expected score: 0.0
Repeated bigram: 0.833
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish Revolution.

The Spanish Revolution is a book written by the Spanish writer Juan Pérez de Montalbán. It was published in Madrid in 1693. The book is a collection of essays, essays, and essays. The book is a collection of essays, essays, and essays. The book is a collection
Expected score: 0.0
Repeated bigram: 0.367
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.

Explain artificial intelligence is a psychological concept that is used to explain the situation in which a person is able to learn about the situation in which they are based.

Explain artificial intelligence is a psychological concept that is used to explain the situation in
Expected score: None
Repeated bigram: 0.373
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
User: Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.
Expected score: None
Repeated bigram: 0.725
Prompt echo: 0.900
Chat markers: 1
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de
Expected score: None
Repeated bigram: 0.738
Prompt echo: 0.909
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A
Expected score: None
Repeated bigram: 0.950
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The number of numbers from 1 to 5.

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from
Expected score: 0.4
Repeated bigram: 0.756
Prompt echo: 0.714
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
Liste, o animal que se alimenta de animais.

Ou seja, o animal que se alimenta de animais, ou seja, que se alimenta de animais, ou seja, que se alimenta de animais, ou seja, que se alimenta de animais, ou seja, que se alimenta de animais, ou seja,
Expected score: None
Repeated bigram: 0.761
Prompt echo: 0.250
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum
Expected score: 0.0
Repeated bigram: 0.902
Prompt echo: 0.286
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
The square is a function that returns x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x
Expected score: 0.5
Repeated bigram: 0.791
Prompt echo: 0.700
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
User: Write one short sentence about the importance of science to science.

User: Write one short sentence about the importance of science to science.

User: Write one short sentence about the importance of science to science.

User: Write one short sentence
Expected score: None
Repeated bigram: 0.700
Prompt echo: 0.889
Chat markers: 4
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
"O que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você sabe é que você
Expected score: None
Repeated bigram: 0.919
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
"¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es
Expected score: None
Repeated bigram: 0.902
Prompt echo: 0.300
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft2-response-500",
  "family": "response-only",
  "step": 500,
  "is_sft": true,
  "mean_expected_score": 0.07368421052631578,
  "mean_repeated_bigram_ratio": 0.6072893526000684,
  "mean_unique_word_ratio": 0.30250212820702305,
  "mean_prompt_echo_ratio": 0.4898930166904023,
  "total_generated_chat_markers": 6,
  "tests_with_chat_markers": 3,
  "tests": 27
}

==============================================================================
MODEL: sft2-response-1000
FAMILY: response-only
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/checkpoint-1000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the city?

The city is the capital of the department of Aisne.

History

The city was founded in the 12th century by the Normans. It was the capital of the department of Aisne from 1415 to 1631.

The city was the capital
Expected score: 0.0
Repeated bigram: 0.302
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun, and is the closest to the Sun. It is the closest to
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: Qual é a cidade mais populosa do estado de São Paulo.

História

A cidade foi fundada em 15 de agosto de 1563, por Martim Afonso de Sousa, como cidade de São Sebastião do Rio Pardo.

A cidade foi fundada em 1563, por Martim Afonso de Sousa, como
Expected score: 0.0
Repeated bigram: 0.255
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de novembro de 2006, por uma equipe de astrônomos do Observatório de Arecibo, na Itália. O planeta foi nomeado em homenagem ao planeta-anão e ao planeta-anão que o habitava.

O
Expected score: 0.0
Repeated bigram: 0.109
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuál es la capital?

La ciudad de User es la capital de la provincia de Barcelona, en Cataluña.

Historia
La ciudad fue fundada en el año 999 por el conde de Barcelona Berenguer I, quien la convirtió en capital de la provincia de Barcelona.

En el
Expected score: 0.0
Repeated bigram: 0.244
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
El planeta más grande del sistema solar.

El planeta fue descubierto por el astrónomo japonés Kiyoshi Katsura en el año 2000.

El planeta tiene una superficie de unos 5.000 km² y una temperatura superficial de unos 10.000 K.

El planeta tiene una temperatura superficial de unos
Expected score: 0.0
Repeated bigram: 0.213
Prompt echo: 0.778
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the second studio album by the Scottish hard rock band Nazareth, released in 1982. It was the first album to feature guitarist Pete Agnew, who would later join the band.

Track listing

Personnel
Nazareth
Dan McCafferty - vocals
Pete Agnew - guitar
Expected score: 0.0
Repeated bigram: 0.024
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number
Expected score: 0.0
Repeated bigram: 0.810
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User
Expected score: 0.0
Repeated bigram: 0.795
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The Final Conflict is the second studio album by the band. It was released on May 11, 2006.

Track listing

Personnel

Band members

Matthew "Matt" Thomas – vocals
Matthew "Matt" Thomas – guitar
Matthew "Matt" Thomas – bass guitar
Matt
Expected score: 0.0
Repeated bigram: 0.111
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in the same city as Paris, but the city is in the same city. Paris is in the same city as Paris, but the city is in the same city. Paris is in the same city as Paris, but the city is in the same city. Paris is in the same city as Paris, but
Expected score: 0.0
Repeated bigram: 0.786
Prompt echo: 0.353
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The first two pages of the book are devoted to the history of the bird, and the first two pages of the book are devoted to the history of the bird.

The book is written by the German zoologist Ludwig von Kölner. The book is divided into three sections:

The first section is
Expected score: 0.0
Repeated bigram: 0.365
Prompt echo: 0.167
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture.

The house is a
Expected score: 0.0
Repeated bigram: 0.787
Prompt echo: 0.429
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa,
Expected score: 0.0
Repeated bigram: 0.833
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word "Spanish" is a Spanish word that means "to be a Spanish" or "to be a Spanish". It is a Spanish word that means "to be a Spanish" or "to be a Spanish". It is also used as a Spanish word for "Spanish" or "Spanish".

The
Expected score: 0.0
Repeated bigram: 0.511
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.

Explain artificial intelligence is a type of artificial intelligence that is used to help solve the problem of artificial intelligence.

Explain artificial intelligence is a type of artificial intelligence that is used to solve the problem of artificial intelligence.

Explain
Expected score: None
Repeated bigram: 0.500
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
User: Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.
Expected score: None
Repeated bigram: 0.725
Prompt echo: 0.900
Chat markers: 1
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de
Expected score: None
Repeated bigram: 0.738
Prompt echo: 0.909
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A
Expected score: None
Repeated bigram: 0.950
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
O Ursinho de Ouro é um filme de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de com
Expected score: None
Repeated bigram: 0.773
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum
Expected score: 0.0
Repeated bigram: 0.902
Prompt echo: 0.286
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
The square is a function that returns x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x
Expected score: 0.5
Repeated bigram: 0.791
Prompt echo: 0.700
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short
Expected score: None
Repeated bigram: 0.842
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
Escreva um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um
Expected score: None
Repeated bigram: 0.882
Prompt echo: 0.111
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
"¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es
Expected score: None
Repeated bigram: 0.902
Prompt echo: 0.300
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft2-response-1000",
  "family": "response-only",
  "step": 1000,
  "is_sft": true,
  "mean_expected_score": 0.04736842105263158,
  "mean_repeated_bigram_ratio": 0.6127791082621058,
  "mean_unique_word_ratio": 0.305322855930331,
  "mean_prompt_echo_ratio": 0.4976825522577157,
  "total_generated_chat_markers": 6,
  "tests_with_chat_markers": 3,
  "tests": 27
}

==============================================================================
MODEL: sft2-response-1500
FAMILY: response-only
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/checkpoint-1500

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the city?

The city is the site of the famous "User: What is the city?".

History

The city was founded in the 12th century by the Normans. It was the capital of the county of User from the 13th century until the French Revolution.
Expected score: 0.0
Repeated bigram: 0.156
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun, and is the closest to the Sun. It is the closest to
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: Qual é a cidade mais populosa do estado de São Paulo.

História

A cidade foi fundada em 15 de agosto de 1563, por Martim Afonso de Sousa, que era o primeiro governador da capitania de São Paulo.

A cidade foi fundada em 1563, por Martim Afonso de Sousa
Expected score: 0.0
Repeated bigram: 0.250
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de novembro de 2004, por uma equipe de astrônomos do Observatório de Genebra. O planeta foi nomeado em homenagem ao planeta-anão Plutão.

O planeta foi nomeado em homenagem ao planeta-anão Plutão.
Expected score: 0.0
Repeated bigram: 0.255
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuál es la capital de España?

La ciudad de User es la capital de España, y la segunda ciudad más poblada de España después de Madrid.

La ciudad de User es la capital de España, y la cuarta ciudad más poblada de España, después de Madrid y Barcelona.
Expected score: 1.0
Repeated bigram: 0.468
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
El planeta más grande del sistema solar, tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una
Expected score: 0.0
Repeated bigram: 0.537
Prompt echo: 0.778
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the second studio album by the Scottish hard rock band Nazareth, released in 1980. It was the first album to feature guitarist Pete Agnew, who would later join the band.

Track listing

Personnel
Nazareth
 Pete Agnew – vocals
 Pete Agnew – guitar
 Pete Agn
Expected score: 0.0
Repeated bigram: 0.047
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the name of the first chapter of the book.

The book is a collection of essays by the author, including:

"What is the name of the first chapter of the book?"
"What is the name of the second chapter of the book?"
"What is the name of the
Expected score: 0.0
Repeated bigram: 0.531
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User
Expected score: 0.0
Repeated bigram: 0.795
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The Final Conflict is the second studio album by the band. It was released on May 11, 2006.

Track listing

Personnel

Band members

Matthew "Matt" Thomas – vocals
Matthew "Matt" Thomas – guitar
Matthew "Matt" Thomas – bass guitar
Matt
Expected score: 0.0
Repeated bigram: 0.111
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as
Expected score: 0.0
Repeated bigram: 0.719
Prompt echo: 0.353
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The first book in the series, The Completely Completely Complete, was written by the author, and published by Houghton Mifflin & Company in 1938. The book is a collection of the best known and most complete works of bird and bird science. The book is a collection of the best known and most
Expected score: 0.0
Repeated bigram: 0.196
Prompt echo: 0.167
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a
Expected score: 0.0
Repeated bigram: 0.787
Prompt echo: 0.429
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa,
Expected score: 0.0
Repeated bigram: 0.833
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word "Spanish" is a Spanish word that means "to be a Spanish word". It is a Spanish word that means "to be a Spanish word". It is also used as a Spanish word for "Spanish" and "Spanish".

The word is used in Spanish as well as in Spanish as well
Expected score: 0.0
Repeated bigram: 0.392
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
The first sentence of the sentence is:

The second sentence of the sentence is:

The third sentence of the sentence is:

The fourth sentence of the sentence is:

The fourth sentence of the sentence is:

The fifth sentence of the sentence is:

The fifth
Expected score: None
Repeated bigram: 0.651
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
User: Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.
Expected score: None
Repeated bigram: 0.725
Prompt echo: 0.900
Chat markers: 1
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de
Expected score: None
Repeated bigram: 0.738
Prompt echo: 0.909
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A
Expected score: None
Repeated bigram: 0.950
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
O Ursinho de Ursinho de Ursinho Puff.

O Ursinho Puff é um animal fictício que aparece em histórias em quadrinhos publicadas pela Marvel Comics. Ele é um dos animais mais poderosos do Universo Marvel. Ele é um dos animais mais poderosos do Universo Marvel. Ele é um dos animais mais
Expected score: None
Repeated bigram: 0.408
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum
Expected score: 0.0
Repeated bigram: 0.902
Prompt echo: 0.286
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
The square is a function that returns x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x
Expected score: 0.5
Repeated bigram: 0.791
Prompt echo: 0.700
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short
Expected score: None
Repeated bigram: 0.842
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
Escreva um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um objeto de estudo, como um
Expected score: None
Repeated bigram: 0.882
Prompt echo: 0.111
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
La frase es una de las más famosas de la literatura fantástica. La frase es una de las más famosas de la literatura fantástica.

La frase es una de las más famosas de la literatura fantástica. La frase es una de las más famosas de la literatura fantástica.

La frase
Expected score: None
Repeated bigram: 0.755
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft2-response-1500",
  "family": "response-only",
  "step": 1500,
  "is_sft": true,
  "mean_expected_score": 0.09999999999999999,
  "mean_repeated_bigram_ratio": 0.5968796276456907,
  "mean_unique_word_ratio": 0.3056525374201908,
  "mean_prompt_echo_ratio": 0.485689606931437,
  "total_generated_chat_markers": 7,
  "tests_with_chat_markers": 4,
  "tests": 27
}

==============================================================================
MODEL: sft2-response-2000
FAMILY: response-only
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/checkpoint-2000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the city?

The city is the capital of the department of Aisne.

History

The city was founded in the 12th century by the Normans. It was the capital of the department of Aisne from 1415 to 1631.

The city was the capital
Expected score: 0.0
Repeated bigram: 0.302
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun, and is the closest to the Sun. It is the closest to
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: Qual é a cidade mais populosa do estado de São Paulo.

História

A cidade foi fundada em 15 de agosto de 1594, por Martim Afonso de Sousa, que era o primeiro governador da Capitania de São Vicente.

A cidade foi fundada em 1594, por Martim Afonso de Sousa
Expected score: 0.0
Repeated bigram: 0.229
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de novembro de 2003, por uma equipe de astrônomos do Observatório de Arecibo, na Itália. O planeta foi nomeado em homenagem ao planeta-americano U.S.A.

O planeta foi nomeado em homenagem ao
Expected score: 0.0
Repeated bigram: 0.188
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuál es la capital?

La ciudad de User es la capital de la provincia de Barcelona, en Cataluña.

Historia
La ciudad fue fundada en el año 999 por el conde de Barcelona Berenguer I, quien la convirtió en capital de la provincia de Barcelona.

En el
Expected score: 0.0
Repeated bigram: 0.244
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
El planeta más grande del sistema solar, tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una
Expected score: 0.0
Repeated bigram: 0.537
Prompt echo: 0.778
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the second studio album by the Scottish hard rock band Nazareth, released in 1980. It was the first album to feature guitarist Pete Agnew, who would later join the band.

Track listing

Personnel
Nazareth
 Pete Agnew – vocals
 Pete Agnew – guitar
 Pete Agn
Expected score: 0.0
Repeated bigram: 0.047
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the difference between the two is the difference between the two.

The first two digits of the first digits are the same as the second, and the second is the same as the third. The second and third digits are the same as the third, and the third and fourth digits are the same as the
Expected score: 0.0
Repeated bigram: 0.474
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User
Expected score: 0.0
Repeated bigram: 0.795
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The Final Conflict is the second studio album by the band. It was released on May 11, 2006.

Track listing

Personnel

Band members

Matthew "Matt" Thomas – vocals
Matthew "Matt" Thomas – guitar
Matthew "Matt" Thomas – bass guitar
Matt
Expected score: 0.0
Repeated bigram: 0.111
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as Paris, but the relationship between Paris and Paris is different. Paris is in the same sense as
Expected score: 0.0
Repeated bigram: 0.719
Prompt echo: 0.353
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The first book of the book was written by the German writer and translator Hermann von Helmholtz. The book was published in the German language in the year of the book. The book was translated into English by the English translator and published by the University of Pennsylvania in the year of the book.

The
Expected score: 0.0
Repeated bigram: 0.296
Prompt echo: 0.083
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture.

The house is a
Expected score: 0.0
Repeated bigram: 0.787
Prompt echo: 0.429
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa,
Expected score: 0.0
Repeated bigram: 0.833
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word "Spanish" is a Spanish word that means "to be a Spanish word". It is a Spanish word that means "to be a Spanish word". It is also used as a Spanish word for "Spanish" and "Spanish".

The word is used in Spanish as well as in Spanish as well
Expected score: 0.0
Repeated bigram: 0.392
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.

Explain artificial intelligence is a type of artificial intelligence that is used to help solve the problem of artificial intelligence.

Explain artificial intelligence is a type of artificial intelligence that is used to solve the problem of artificial intelligence.

Explain
Expected score: None
Repeated bigram: 0.500
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
User: Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.
Expected score: None
Repeated bigram: 0.725
Prompt echo: 0.900
Chat markers: 1
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de
Expected score: None
Repeated bigram: 0.738
Prompt echo: 0.909
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A
Expected score: None
Repeated bigram: 0.950
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
O Ursinho de Ursinho de Ursinho Puff.

O Ursinho Puff é um animal fictício que aparece em histórias em quadrinhos publicadas pela Marvel Comics. Ele é um animal de estimação, que pode ser usado como um animal de estimação, como um animal de estimação, como um
Expected score: None
Repeated bigram: 0.333
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum
Expected score: 0.0
Repeated bigram: 0.902
Prompt echo: 0.286
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
The square is a function that returns x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x
Expected score: 0.5
Repeated bigram: 0.791
Prompt echo: 0.700
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short
Expected score: None
Repeated bigram: 0.842
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O ser humano é um ser humano que é capaz de se comunicar com outros seres humanos.

O ser humano é um ser humano que é capaz de se comunicar com outros seres humanos, e que é capaz de se comunicar com outros seres humanos, e que é capaz de se comunicar com outros seres humanos, e que
Expected score: None
Repeated bigram: 0.684
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
La frase es una de las más famosas de la literatura fantástica.

La frase es una de las más famosas de la literatura fantástica.

La frase es una de las más famosas de la literatura fantástica.

La frase es una de las más famosas de la literatura fantástica.
Expected score: None
Repeated bigram: 0.745
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft2-response-2000",
  "family": "response-only",
  "step": 2000,
  "is_sft": true,
  "mean_expected_score": 0.04736842105263158,
  "mean_repeated_bigram_ratio": 0.5762577900494025,
  "mean_unique_word_ratio": 0.32185910343403024,
  "mean_prompt_echo_ratio": 0.49788831357458807,
  "total_generated_chat_markers": 6,
  "tests_with_chat_markers": 3,
  "tests": 27
}

==============================================================================
MODEL: sft2-response-2500
FAMILY: response-only
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/checkpoint-2500

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the city?

The city is the site of the famous "The City of the Dead" (French: Les Noces de la mort) and the "City of the Dead" (French: Les Noces de la mort) which is the site of the famous "The City of the
Expected score: 0.0
Repeated bigram: 0.511
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun, and is the closest to
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: Qual é a cidade mais populosa do estado de São Paulo.

História

A cidade foi fundada em 15 de agosto de 1563, por Martim Afonso de Sousa, que era o primeiro governador da capitania de São Paulo.

A cidade foi fundada em 1563, por Martim Afonso de Sousa
Expected score: 0.0
Repeated bigram: 0.250
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de novembro de 2006, por uma equipe de astrônomos do Observatório de Arecibo, na Itália. O planeta foi nomeado em homenagem ao planeta-anão e ao planeta-anão que o planeta possui.

O
Expected score: 0.0
Repeated bigram: 0.128
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuál es la capital de España?

La ciudad de User es la capital de España, y la segunda ciudad más poblada de España después de Madrid.

La ciudad de User es la capital de España, y la cuarta ciudad más poblada de España, después de Madrid y Barcelona.
Expected score: 1.0
Repeated bigram: 0.468
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
El planeta más grande del sistema solar, tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una
Expected score: 0.0
Repeated bigram: 0.537
Prompt echo: 0.778
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the second studio album by the Scottish hard rock band Nazareth, released in 1982. It was the first album to feature guitarist Pete Agnew, who would later join the band.

Track listing

Personnel
Nazareth
Dan McCafferty - vocals
Pete Agnew - guitar
Expected score: 0.0
Repeated bigram: 0.024
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number
Expected score: 0.0
Repeated bigram: 0.810
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User
Expected score: 0.0
Repeated bigram: 0.795
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The Final Conflict is the third installment in the series of Final Conflict. It was released in 2006.

Plot
The series follows the lives of the two survivors of the terrorist attacks in the United States. The first is the story of the survivors of the terrorist attacks in the United States, who are
Expected score: 0.0
Repeated bigram: 0.264
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in the same sense as Paris, but the relationship between Paris and the capital city is different. Paris is in the same sense as Paris, but the relationship between Paris and the capital city is different. Paris is in the same sense as Paris, but the relationship between Paris and the capital city is different. Paris
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.294
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The first book in the series, The Completely illustrated book, was published in 1999 by the University of California Press. The book is a collection of over 100 illustrations, including a series of illustrations by the artist Robert L. Kershaw.

The book was a finalist for the 1999 National Book
Expected score: 0.0
Repeated bigram: 0.061
Prompt echo: 0.083
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture.

The house is a
Expected score: 0.0
Repeated bigram: 0.787
Prompt echo: 0.429
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa,
Expected score: 0.0
Repeated bigram: 0.833
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word "Spanish" is a Spanish word that means "to be a Spanish word". It is a Spanish word that means "to be a Spanish word". It is also used as a Spanish word for "Spanish" and "Spanish".

The word is used in Spanish as well as in Spanish as well
Expected score: 0.0
Repeated bigram: 0.392
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
The first sentence of the sentence is:

The second sentence of the sentence is:

The third sentence of the sentence is:

The fourth sentence of the sentence is:

The fourth sentence of the sentence is:

The fifth sentence of the sentence is:

The fifth
Expected score: None
Repeated bigram: 0.651
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
User: Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.
Expected score: None
Repeated bigram: 0.725
Prompt echo: 0.900
Chat markers: 1
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de
Expected score: None
Repeated bigram: 0.738
Prompt echo: 0.909
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A
Expected score: None
Repeated bigram: 0.950
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
O Ursinho de Ouro é um filme de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de com
Expected score: None
Repeated bigram: 0.773
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum
Expected score: 0.0
Repeated bigram: 0.902
Prompt echo: 0.286
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
The square is a function that returns x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x
Expected score: 0.5
Repeated bigram: 0.791
Prompt echo: 0.700
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short
Expected score: None
Repeated bigram: 0.842
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O ser humano é um ser humano que não é um ser humano, mas sim um ser humano que não é um ser humano.

O ser humano é um ser humano que não é um ser humano, mas sim um ser humano que não é um ser humano. O ser humano é um ser humano que não é
Expected score: None
Repeated bigram: 0.789
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
La frase es una de las más famosas de la literatura fantástica. La frase es una de las más famosas de la literatura fantástica.

La frase es una de las más famosas de la literatura fantástica. La frase es una de las más famosas de la literatura fantástica.

La frase
Expected score: None
Repeated bigram: 0.755
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft2-response-2500",
  "family": "response-only",
  "step": 2500,
  "is_sft": true,
  "mean_expected_score": 0.09999999999999999,
  "mean_repeated_bigram_ratio": 0.623617598902176,
  "mean_unique_word_ratio": 0.2861946731963415,
  "mean_prompt_echo_ratio": 0.4763093116034292,
  "total_generated_chat_markers": 6,
  "tests_with_chat_markers": 3,
  "tests": 27
}

==============================================================================
MODEL: sft2-response-3000
FAMILY: response-only
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/experiments/sft_response_only_from_106k/checkpoint-3000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

[01/27] EN_FACT_01
PROMPT:
User: What is the capital of France?
Assistant:
COMPLETION:
What is the city?

The city is the site of the famous "User: What is the city?".

History

The city was founded in the 12th century by the Normans. It was the capital of the Duchy of Burgundy from 1415 to 1415.

The
Expected score: 0.0
Repeated bigram: 0.167
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[02/27] EN_FACT_02
PROMPT:
User: What is the largest planet in the Solar System?
Assistant:
COMPLETION:
What is the planet that is closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to the Sun. It is the closest to the Sun, and is the closest to
Expected score: 0.0
Repeated bigram: 0.750
Prompt echo: 0.556
Chat markers: 0
------------------------------------------------------------------------------
[03/27] PT_FACT_01
PROMPT:
User: Qual é a capital do Brasil?
Assistant:
COMPLETION:
User: Qual é a cidade mais populosa do estado de São Paulo.

História

A cidade foi fundada em 15 de agosto de 1563, por Martim Afonso de Sousa, que era o primeiro governador da capitania de São Paulo.

A cidade foi fundada em 1563, por Martim Afonso de Sousa
Expected score: 0.0
Repeated bigram: 0.250
Prompt echo: 0.500
Chat markers: 1
------------------------------------------------------------------------------
[04/27] PT_FACT_02
PROMPT:
User: Qual é o maior planeta do Sistema Solar?
Assistant:
COMPLETION:
Qual é o planeta mais brilhante do Sistema Solar?

O planeta foi descoberto em 16 de novembro de 2004, por uma equipe de astrônomos do Observatório de Genebra. O planeta foi nomeado em homenagem ao planeta U-bois, que foi descoberto em 16 de novembro de 2004.

O planeta foi nomeado em
Expected score: 0.0
Repeated bigram: 0.275
Prompt echo: 0.750
Chat markers: 0
------------------------------------------------------------------------------
[05/27] ES_FACT_01
PROMPT:
User: ¿Cuál es la capital de España?
Assistant:
COMPLETION:
¿Cuál es la capital de España?

La ciudad de User es la capital de España, y la segunda ciudad más poblada de España después de Madrid.

La ciudad de User es la cuarta ciudad más poblada de España, después de Madrid y Barcelona.

Historia
La ciudad fue
Expected score: 1.0
Repeated bigram: 0.391
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[06/27] ES_FACT_02
PROMPT:
User: ¿Cuál es el planeta más grande del Sistema Solar?
Assistant:
COMPLETION:
El planeta más grande del sistema solar, tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una temperatura superficial de unos 10 grados Celsius. El planeta tiene una superficie de aproximadamente 1.000 km² y una
Expected score: 0.0
Repeated bigram: 0.537
Prompt echo: 0.778
Chat markers: 0
------------------------------------------------------------------------------
[07/27] MATH_01
PROMPT:
User: What is 2 + 2?
Assistant:
COMPLETION:
What is the second studio album by the Scottish hard rock band Nazareth, released in 1980. It was the first album to feature guitarist Pete Agnew, who would later join the band.

Track listing

Credits

Nazareth
 Pete Agnew – vocals
 Pete Agnew – guitar
Expected score: 0.0
Repeated bigram: 0.049
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[08/27] MATH_02
PROMPT:
User: What is 10 multiplied by 5?
Assistant:
COMPLETION:
What is the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number of times we have to get to know the number
Expected score: 0.0
Repeated bigram: 0.810
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[09/27] MATH_03
PROMPT:
User: What is the square root of 81?
Assistant:
COMPLETION:
What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User: What is the square root of 81?

User
Expected score: 0.0
Repeated bigram: 0.795
Prompt echo: 1.000
Chat markers: 4
------------------------------------------------------------------------------
[10/27] MATH_04
PROMPT:
User: Solve x + 3 = 7. What is x?
Assistant:
COMPLETION:
The Final Conflict is the third installment in the series of Final Conflict. It was released in 2006.

Plot
The series follows the lives of the two protagonists, the two survivors of the final battle, and the two survivors of the final battle. The survivors are separated from the survivors, and
Expected score: 0.0
Repeated bigram: 0.240
Prompt echo: 0.143
Chat markers: 0
------------------------------------------------------------------------------
[11/27] SEM_01
PROMPT:
User: Complete the relation: Paris is in France, Rome is in Italy, and Madrid is in what country?
Assistant:
COMPLETION:
Paris is in the same sense as Paris, but the relationship between Paris and the capital city is different. Paris is in the same sense as Paris, but the relationship between Paris and the capital city is different. Paris is in the same sense as Paris, but the relationship between Paris and the capital city is different. Paris
Expected score: 0.0
Repeated bigram: 0.667
Prompt echo: 0.294
Chat markers: 0
------------------------------------------------------------------------------
[12/27] SEM_02
PROMPT:
User: Complete the analogy: bird is to sky as fish is to what?
Assistant:
COMPLETION:
The first book of the book was written by the German writer and translator Hermann von Helmholtz. The book was published in the German language in the year of the book. The book was translated into English by the English translator and published by the University of Pennsylvania in the year of the book.

The
Expected score: 0.0
Repeated bigram: 0.296
Prompt echo: 0.083
Chat markers: 0
------------------------------------------------------------------------------
[13/27] SEM_03
PROMPT:
User: A dog is an animal. What kind of thing is a rose?
Assistant:
COMPLETION:
A dog is a dog that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a rose that is not a rose. It is a
Expected score: 0.0
Repeated bigram: 0.807
Prompt echo: 0.500
Chat markers: 0
------------------------------------------------------------------------------
[14/27] TRANS_01
PROMPT:
User: Translate into Portuguese: The house is beautiful.
Assistant:
COMPLETION:
The house is a modernist style of architecture. It is a modernist style of architecture.

The house is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture. It is a modernist style of architecture.

The house is a
Expected score: 0.0
Repeated bigram: 0.787
Prompt echo: 0.429
Chat markers: 0
------------------------------------------------------------------------------
[15/27] TRANS_02
PROMPT:
User: Translate into English: O livro está sobre a mesa.
Assistant:
COMPLETION:
O livro está escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa, e é escrito em primeira pessoa,
Expected score: 0.0
Repeated bigram: 0.833
Prompt echo: 0.333
Chat markers: 0
------------------------------------------------------------------------------
[16/27] TRANS_03
PROMPT:
User: Translate into Spanish: Good morning.
Assistant:
COMPLETION:
The Spanish word "Spanish" is a Spanish word that means "to be a Spanish" or "to be a Spanish". It is a Spanish word that means "to be a Spanish" or "to be a Spanish". It is also used as a Spanish word for "Spanish" or "Spanish".

The
Expected score: 0.0
Repeated bigram: 0.511
Prompt echo: 0.200
Chat markers: 0
------------------------------------------------------------------------------
[17/27] EXPLAIN_01
PROMPT:
User: Explain artificial intelligence in one short sentence.
Assistant:
COMPLETION:
Explain artificial intelligence in one short sentence.

Explain artificial intelligence is a type of artificial intelligence that is used to help solve the problem of artificial intelligence.

Explain artificial intelligence is a type of artificial intelligence that is used to solve the problem of artificial intelligence.

Explain
Expected score: None
Repeated bigram: 0.500
Prompt echo: 1.000
Chat markers: 0
------------------------------------------------------------------------------
[18/27] EXPLAIN_02
PROMPT:
User: Explain what a neural network is in one short sentence.
Assistant:
COMPLETION:
User: Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.

Explain what a neural network is in one short sentence.
Expected score: None
Repeated bigram: 0.725
Prompt echo: 0.900
Chat markers: 1
------------------------------------------------------------------------------
[19/27] EXPLAIN_03
PROMPT:
User: Explique em uma frase curta o que é aprendizado de máquina.
Assistant:
COMPLETION:
Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de máquina.

Explique em uma frase curta o que é aprendido de
Expected score: None
Repeated bigram: 0.738
Prompt echo: 0.909
Chat markers: 0
------------------------------------------------------------------------------
[20/27] INST_01
PROMPT:
User: List exactly three colors.
Assistant:
COMPLETION:
A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A

A
Expected score: None
Repeated bigram: 0.950
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[21/27] INST_02
PROMPT:
User: List the numbers from 1 to 5.
Assistant:
COMPLETION:
The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers from 1 to 5 are:

The numbers
Expected score: 0.4
Repeated bigram: 0.837
Prompt echo: 0.857
Chat markers: 0
------------------------------------------------------------------------------
[22/27] INST_03
PROMPT:
User: Liste exatamente três animais.
Assistant:
COMPLETION:
O Ursinho de Ouro é um filme de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de comédia de com
Expected score: None
Repeated bigram: 0.773
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[23/27] PY_01
PROMPT:
User: Write a Python function called add that returns the sum of a and b.
Assistant:
COMPLETION:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum
Expected score: 0.0
Repeated bigram: 0.902
Prompt echo: 0.286
Chat markers: 0
------------------------------------------------------------------------------
[24/27] PY_02
PROMPT:
User: Write a Python function called square that returns x squared.
Assistant:
COMPLETION:
The square is a function that returns x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x squared x
Expected score: 0.5
Repeated bigram: 0.791
Prompt echo: 0.700
Chat markers: 0
------------------------------------------------------------------------------
[25/27] OPEN_EN
PROMPT:
User: Write one short sentence about the importance of science.
Assistant:
COMPLETION:
Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short sentence about science.

Write one short
Expected score: None
Repeated bigram: 0.842
Prompt echo: 0.667
Chat markers: 0
------------------------------------------------------------------------------
[26/27] OPEN_PT
PROMPT:
User: Escreva uma frase curta sobre a importância da ciência.
Assistant:
COMPLETION:
O ser humano é um ser humano que não é um ser humano, mas sim um ser humano que não é um ser humano.

O ser humano é um ser humano que não é um ser humano, mas sim um ser humano que não é um ser humano. O ser humano é um ser humano que não é
Expected score: None
Repeated bigram: 0.789
Prompt echo: 0.000
Chat markers: 0
------------------------------------------------------------------------------
[27/27] OPEN_ES
PROMPT:
User: Escribe una frase corta sobre la importancia de la ciencia.
Assistant:
COMPLETION:
"¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es la ciencia? ¿Qué es
Expected score: None
Repeated bigram: 0.902
Prompt echo: 0.300
Chat markers: 0
------------------------------------------------------------------------------

SUMMARY
{
  "name": "sft2-response-3000",
  "family": "response-only",
  "step": 3000,
  "is_sft": true,
  "mean_expected_score": 0.09999999999999999,
  "mean_repeated_bigram_ratio": 0.6264172937711473,
  "mean_unique_word_ratio": 0.2850187117416031,
  "mean_prompt_echo_ratio": 0.5006479359420536,
  "total_generated_chat_markers": 7,
  "tests_with_chat_markers": 4,
  "tests": 27
}

==============================================================================================================
FINAL COMPARISON
==============================================================================================================
MODEL                   FAMILY             STEP    EXPECTED      REPEAT      UNIQUE        ECHO   MARKERS
--------------------------------------------------------------------------------------------------------------
base-106000             base                  0      0.1842      0.5510      0.3210      0.0000         0
sft1-full-500           full-sequence       500      0.1000      0.6806      0.2567      0.5966        53
sft1-full-1000          full-sequence      1000      0.1526      0.6924      0.2423      0.6013        49
sft1-full-1500          full-sequence      1500      0.1526      0.6958      0.2448      0.6013        55
sft1-full-2000          full-sequence      2000      0.1526      0.7219      0.2311      0.5939        53
sft1-full-2500          full-sequence      2500      0.1526      0.7257      0.2289      0.5991        55
sft1-full-3000          full-sequence      3000      0.1526      0.7223      0.2260      0.6013        50
sft2-response-500       response-only       500      0.0737      0.6073      0.3025      0.4899         6
sft2-response-1000      response-only      1000      0.0474      0.6128      0.3053      0.4977         6
sft2-response-1500      response-only      1500      0.1000      0.5969      0.3057      0.4857         7
sft2-response-2000      response-only      2000      0.0474      0.5763      0.3219      0.4979         6
sft2-response-2500      response-only      2500      0.1000      0.6236      0.2862      0.4763         6
sft2-response-3000      response-only      3000      0.1000      0.6264      0.2850      0.5006         7

==============================================================================
SFT #1 FULL-SEQUENCE VS SFT #2 RESPONSE-ONLY
==============================================================================

STEP 500
  Full sequence: expected=0.1000 repeat=0.6806 echo=0.5966 markers=53
  Response-only: expected=0.0737 repeat=0.6073 echo=0.4899 markers=6

STEP 1000
  Full sequence: expected=0.1526 repeat=0.6924 echo=0.6013 markers=49
  Response-only: expected=0.0474 repeat=0.6128 echo=0.4977 markers=6

STEP 1500
  Full sequence: expected=0.1526 repeat=0.6958 echo=0.6013 markers=55
  Response-only: expected=0.1000 repeat=0.5969 echo=0.4857 markers=7

STEP 2000
  Full sequence: expected=0.1526 repeat=0.7219 echo=0.5939 markers=53
  Response-only: expected=0.0474 repeat=0.5763 echo=0.4979 markers=6

STEP 2500
  Full sequence: expected=0.1526 repeat=0.7257 echo=0.5991 markers=55
  Response-only: expected=0.1000 repeat=0.6236 echo=0.4763 markers=6

STEP 3000
  Full sequence: expected=0.1526 repeat=0.7223 echo=0.6013 markers=50
  Response-only: expected=0.1000 repeat=0.6264 echo=0.5006 markers=7

==============================================================================
BENCHMARK COMPLETE
==============================================================================

Results saved to:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/diagnostics/decisive_sft_full_vs_response_only.json

NO model weights were modified.

In [ ]:
import os
import json
import random
import shutil
import numpy as np
from datasets import load_dataset, Dataset, concatenate_datasets
from transformers import GPT2TokenizerFast


# ============================================================
# MAIA LITE
# PREPARE DETERMINISTIC PRETRAINING DATA
#
# PURPOSE
# -------
# Replace the fragile streaming/interleave training pipeline
# with a finite, deterministic, materialized dataset.
#
# This cell DOES NOT train the model.
#
# Target continuation:
#
#     Golden 106K
#          |
#          + 24,000 optimizer steps
#          |
#          v
#     Equivalent 130K
#
# Effective batch = 32 sequences
# Sequence length  = 1024 tokens
#
# Required sequences:
#
#     24,000 * 32 = 768,000
#
# We prepare additional data so that the Trainer has margin.
# ============================================================


PROJECT_DIR = "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

DATASET_DIR = os.path.join(
    PROJECT_DIR,
    "pretraining_data",
    "continuation_106k_to_130k"
)

METADATA_FILE = os.path.join(
    DATASET_DIR,
    "metadata.json"
)


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42

BLOCK_SIZE = 1024

MAX_STEPS = 24_000

EFFECTIVE_BATCH = 32

# 5% safety margin.
TARGET_SEQUENCES = int(
    MAX_STEPS
    * EFFECTIVE_BATCH
    * 1.05
)

# Explicit language proportions.
LANGUAGE_COUNTS = {
    "en": int(TARGET_SEQUENCES * 0.50),
    "pt": int(TARGET_SEQUENCES * 0.25),
    "es": int(TARGET_SEQUENCES * 0.25),
}

# Correct rounding difference.
LANGUAGE_COUNTS["en"] += (
    TARGET_SEQUENCES
    - sum(LANGUAGE_COUNTS.values())
)


print("=" * 78)
print("MAIA LITE - DETERMINISTIC PRETRAINING DATA")
print("=" * 78)

print()
print(f"Block size:       {BLOCK_SIZE:,}")
print(f"Target sequences: {TARGET_SEQUENCES:,}")
print()

for lang, count in LANGUAGE_COUNTS.items():
    print(
        f"{lang.upper():>2}: "
        f"{count:,} sequences "
        f"({count / TARGET_SEQUENCES:.1%})"
    )


# ============================================================
# TOKENIZER
# ============================================================

print()
print("Loading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

EOS_ID = tokenizer.eos_token_id

print(f"Vocabulary: {tokenizer.vocab_size:,}")
print(f"EOS:        {EOS_ID}")
print(f"PAD:        {tokenizer.pad_token_id}")


# ============================================================
# DATASET SNAPSHOT
#
# IMPORTANT:
# If your original pretraining cell used a different Wikipedia
# dataset/snapshot, replace ONLY these identifiers with the
# original ones before running.
# ============================================================

WIKI_DATASET = "wikimedia/wikipedia"

WIKI_CONFIG = {
    "en": "20231101.en",
    "pt": "20231101.pt",
    "es": "20231101.es",
}


# ============================================================
# PACK ONE LANGUAGE
#
# We deliberately stream Wikipedia ONLY during this one-time
# preparation phase.
#
# The output is finite and materialized.
#
# Documents are separated with EOS.
# Tokens are packed continuously into exact 1024-token blocks.
# ============================================================

def build_language_dataset(
    language,
    target_sequences,
):

    print()
    print("=" * 78)
    print(
        f"PREPARING {language.upper()}"
    )
    print("=" * 78)

    print(
        f"Target: {target_sequences:,} sequences"
    )

    stream = load_dataset(
        WIKI_DATASET,
        WIKI_CONFIG[language],
        split="train",
        streaming=True,
    )

    # Deterministic buffered shuffle during preparation only.
    #
    # Once saved, this streaming state is never used by
    # training itself.

    stream = stream.shuffle(
        seed=SEED,
        buffer_size=10_000,
    )

    packed_blocks = []

    token_buffer = []

    documents = 0

    for example in stream:

        text = example.get(
            "text",
            ""
        )

        if not text:
            continue

        text = text.strip()

        if not text:
            continue


        ids = tokenizer.encode(
            text,
            add_special_tokens=False,
        )


        if not ids:
            continue


        # Separate Wikipedia articles.
        ids.append(
            EOS_ID
        )


        token_buffer.extend(
            ids
        )

        documents += 1


        while (
            len(token_buffer)
            >= BLOCK_SIZE
        ):

            block = token_buffer[
                :BLOCK_SIZE
            ]

            del token_buffer[
                :BLOCK_SIZE
            ]


            packed_blocks.append({
                "input_ids": block,
                "attention_mask": (
                    [1] * BLOCK_SIZE
                ),
            })


            if (
                len(packed_blocks)
                >= target_sequences
            ):

                break


        if (
            len(packed_blocks)
            >= target_sequences
        ):
            break


        if documents % 10_000 == 0:

            print(
                f"{language.upper()} | "
                f"documents={documents:,} | "
                f"sequences={len(packed_blocks):,} / "
                f"{target_sequences:,}"
            )


    if (
        len(packed_blocks)
        < target_sequences
    ):

        raise RuntimeError(
            f"{language}: stream ended before target "
            f"was reached."
        )


    dataset = Dataset.from_list(
        packed_blocks
    )


    print()
    print(
        f"{language.upper()} complete:"
    )

    print(
        f"  Documents consumed: {documents:,}"
    )

    print(
        f"  Sequences:          {len(dataset):,}"
    )


    return dataset


# ============================================================
# BUILD LANGUAGES
# ============================================================

language_datasets = {}

for language in [
    "en",
    "pt",
    "es",
]:

    language_datasets[
        language
    ] = build_language_dataset(

        language,

        LANGUAGE_COUNTS[
            language
        ],
    )


# ============================================================
# COMBINE
# ============================================================

print()
print("=" * 78)
print("COMBINING LANGUAGES")
print("=" * 78)

combined = concatenate_datasets([
    language_datasets["en"],
    language_datasets["pt"],
    language_datasets["es"],
])


print(
    f"Before shuffle: {len(combined):,}"
)


# ============================================================
# CRITICAL STEP
#
# This shuffle operates on a FINITE Arrow dataset.
#
# It is not an IterableDataset.
# Its order can therefore be reproduced exactly.
# ============================================================

combined = combined.shuffle(
    seed=SEED
)


print(
    f"After deterministic shuffle: {len(combined):,}"
)


# ============================================================
# SANITY CHECK
# ============================================================

print()
print("=" * 78)
print("SANITY CHECK")
print("=" * 78)


for i in range(3):

    sample = combined[i]

    print()
    print(
        f"Sample {i}"
    )

    print(
        f"Tokens: "
        f"{len(sample['input_ids'])}"
    )

    print(
        tokenizer.decode(
            sample["input_ids"][:100],
            skip_special_tokens=False,
        )[:500]
    )


# ============================================================
# SAVE MATERIALIZED DATASET
# ============================================================

print()
print("=" * 78)
print("SAVING MATERIALIZED DATASET")
print("=" * 78)


if os.path.exists(
    DATASET_DIR
):
    raise RuntimeError(
        "\nDataset directory already exists:\n"
        f"{DATASET_DIR}\n\n"
        "Delete it manually only if you intentionally want "
        "to rebuild the deterministic dataset."
    )


os.makedirs(
    os.path.dirname(DATASET_DIR),
    exist_ok=True,
)


combined.save_to_disk(
    DATASET_DIR
)


metadata = {

    "purpose":
        "Maia Lite deterministic continuation 106K -> 130K",

    "seed":
        SEED,

    "block_size":
        BLOCK_SIZE,

    "target_sequences":
        len(combined),

    "max_training_steps":
        MAX_STEPS,

    "effective_batch":
        EFFECTIVE_BATCH,

    "languages": {
        "en": LANGUAGE_COUNTS["en"],
        "pt": LANGUAGE_COUNTS["pt"],
        "es": LANGUAGE_COUNTS["es"],
    },

    "language_proportions": {
        "en": 0.50,
        "pt": 0.25,
        "es": 0.25,
    },

    "dataset":
        WIKI_DATASET,

    "configs":
        WIKI_CONFIG,

    "tokenizer":
        TOKENIZER_DIR,

    "eos_id":
        EOS_ID,
}


with open(
    METADATA_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        metadata,
        f,
        indent=2,
        ensure_ascii=False,
    )


print()
print("=" * 78)
print("DATASET PREPARATION COMPLETE")
print("=" * 78)

print()
print(
    f"Sequences: {len(combined):,}"
)

print(
    f"Tokens: "
    f"{len(combined) * BLOCK_SIZE:,}"
)

print()
print(
    "Saved to:"
)

print(
    DATASET_DIR
)

print()
print(
    "Training can now run without Wikipedia streaming."
)

==============================================================================
MAIA LITE - DETERMINISTIC PRETRAINING DATA
==============================================================================

Block size:       1,024
Target sequences: 806,400

EN: 403,200 sequences (50.0%)
PT: 201,600 sequences (25.0%)
ES: 201,600 sequences (25.0%)

Loading tokenizer...
Vocabulary: 50,257
EOS:        2
PAD:        1

==============================================================================
PREPARING EN
==============================================================================
Target: 403,200 sequences

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

EN | documents=10,000 | sequences=5,224 / 403,200
EN | documents=20,000 | sequences=10,697 / 403,200
EN | documents=30,000 | sequences=16,082 / 403,200
EN | documents=40,000 | sequences=21,458 / 403,200
EN | documents=50,000 | sequences=27,152 / 403,200
EN | documents=60,000 | sequences=32,700 / 403,200
EN | documents=70,000 | sequences=38,584 / 403,200
EN | documents=80,000 | sequences=44,678 / 403,200
EN | documents=90,000 | sequences=50,317 / 403,200
EN | documents=100,000 | sequences=55,896 / 403,200
EN | documents=110,000 | sequences=61,301 / 403,200
EN | documents=120,000 | sequences=66,860 / 403,200
EN | documents=130,000 | sequences=72,025 / 403,200
EN | documents=140,000 | sequences=77,239 / 403,200
EN | documents=150,000 | sequences=82,112 / 403,200
EN | documents=160,000 | sequences=87,731 / 403,200
EN | documents=170,000 | sequences=93,873 / 403,200
EN | documents=180,000 | sequences=99,813 / 403,200
EN | documents=190,000 | sequences=105,660 / 403,200
EN | documents=200,000 | sequences=111,350 / 403,200
EN | documents=210,000 | sequences=116,786 / 403,200
EN | documents=220,000 | sequences=122,199 / 403,200
EN | documents=230,000 | sequences=126,849 / 403,200
EN | documents=240,000 | sequences=131,440 / 403,200
EN | documents=250,000 | sequences=135,940 / 403,200
EN | documents=260,000 | sequences=141,304 / 403,200
EN | documents=270,000 | sequences=147,435 / 403,200
EN | documents=280,000 | sequences=154,133 / 403,200
EN | documents=290,000 | sequences=160,992 / 403,200
EN | documents=300,000 | sequences=167,767 / 403,200
EN | documents=310,000 | sequences=175,221 / 403,200
EN | documents=320,000 | sequences=185,015 / 403,200
EN | documents=330,000 | sequences=195,494 / 403,200
EN | documents=340,000 | sequences=206,565 / 403,200
EN | documents=350,000 | sequences=217,312 / 403,200
EN | documents=360,000 | sequences=228,072 / 403,200
EN | documents=370,000 | sequences=239,369 / 403,200
EN | documents=380,000 | sequences=250,388 / 403,200
EN | documents=390,000 | sequences=260,908 / 403,200
EN | documents=400,000 | sequences=271,421 / 403,200
EN | documents=410,000 | sequences=281,782 / 403,200
EN | documents=420,000 | sequences=292,106 / 403,200
EN | documents=430,000 | sequences=301,988 / 403,200
EN | documents=440,000 | sequences=312,178 / 403,200
EN | documents=450,000 | sequences=322,516 / 403,200
EN | documents=460,000 | sequences=332,845 / 403,200
EN | documents=470,000 | sequences=341,006 / 403,200
EN | documents=480,000 | sequences=347,730 / 403,200
EN | documents=490,000 | sequences=354,063 / 403,200
EN | documents=500,000 | sequences=360,151 / 403,200
EN | documents=510,000 | sequences=366,109 / 403,200
EN | documents=520,000 | sequences=371,908 / 403,200
EN | documents=530,000 | sequences=377,624 / 403,200
EN | documents=540,000 | sequences=383,384 / 403,200
EN | documents=550,000 | sequences=389,388 / 403,200
EN | documents=560,000 | sequences=395,350 / 403,200
EN | documents=570,000 | sequences=401,232 / 403,200

EN complete:
  Documents consumed: 573,217
  Sequences:          403,200

==============================================================================
PREPARING PT
==============================================================================
Target: 201,600 sequences
PT | documents=10,000 | sequences=2,551 / 201,600
PT | documents=20,000 | sequences=6,405 / 201,600
PT | documents=30,000 | sequences=11,299 / 201,600
PT | documents=40,000 | sequences=16,667 / 201,600
PT | documents=50,000 | sequences=21,963 / 201,600
PT | documents=60,000 | sequences=27,349 / 201,600
PT | documents=70,000 | sequences=32,932 / 201,600
PT | documents=80,000 | sequences=37,781 / 201,600
PT | documents=90,000 | sequences=42,238 / 201,600
PT | documents=100,000 | sequences=47,029 / 201,600
PT | documents=110,000 | sequences=52,294 / 201,600
PT | documents=120,000 | sequences=57,028 / 201,600
PT | documents=130,000 | sequences=61,220 / 201,600
PT | documents=140,000 | sequences=65,759 / 201,600
PT | documents=150,000 | sequences=69,640 / 201,600
PT | documents=160,000 | sequences=73,891 / 201,600
PT | documents=170,000 | sequences=78,861 / 201,600
PT | documents=180,000 | sequences=83,511 / 201,600
PT | documents=190,000 | sequences=88,099 / 201,600
PT | documents=200,000 | sequences=93,437 / 201,600
PT | documents=210,000 | sequences=98,710 / 201,600
PT | documents=220,000 | sequences=103,672 / 201,600
PT | documents=230,000 | sequences=108,816 / 201,600
PT | documents=240,000 | sequences=113,997 / 201,600
PT | documents=250,000 | sequences=119,061 / 201,600
PT | documents=260,000 | sequences=123,856 / 201,600
PT | documents=270,000 | sequences=128,119 / 201,600
PT | documents=280,000 | sequences=132,566 / 201,600
PT | documents=290,000 | sequences=136,895 / 201,600
PT | documents=300,000 | sequences=140,921 / 201,600
PT | documents=310,000 | sequences=143,814 / 201,600
PT | documents=320,000 | sequences=146,921 / 201,600
PT | documents=330,000 | sequences=150,957 / 201,600
PT | documents=340,000 | sequences=154,265 / 201,600
PT | documents=350,000 | sequences=158,329 / 201,600
PT | documents=360,000 | sequences=161,843 / 201,600
PT | documents=370,000 | sequences=166,097 / 201,600
PT | documents=380,000 | sequences=179,503 / 201,600
PT | documents=390,000 | sequences=188,450 / 201,600
PT | documents=400,000 | sequences=195,273 / 201,600
PT | documents=410,000 | sequences=201,402 / 201,600

PT complete:
  Documents consumed: 410,366
  Sequences:          201,600

==============================================================================
PREPARING ES
==============================================================================
Target: 201,600 sequences
ES | documents=10,000 | sequences=29,077 / 201,600
ES | documents=20,000 | sequences=56,535 / 201,600
ES | documents=30,000 | sequences=81,291 / 201,600
ES | documents=40,000 | sequences=103,490 / 201,600
ES | documents=50,000 | sequences=123,307 / 201,600
ES | documents=60,000 | sequences=140,886 / 201,600
ES | documents=70,000 | sequences=157,613 / 201,600
ES | documents=80,000 | sequences=173,120 / 201,600
ES | documents=90,000 | sequences=187,794 / 201,600

ES complete:
  Documents consumed: 99,912
  Sequences:          201,600

==============================================================================
COMBINING LANGUAGES
==============================================================================
Before shuffle: 806,400
After deterministic shuffle: 806,400

==============================================================================
SANITY CHECK
==============================================================================

Sample 0
Tokens: 1024
 general do Alto-Languedoc em 1580, tomou parte no Cerco de Paris (1590), após a subida ao trono de Henrique IV, conquistando Stenay à Liga Católica em 1591.

Em 1591 Henrique casou com a Carlota de Mark, herdeira do Ducado de Bulhão e do Principado de Sedan. Em 1592 o rei Henrique IV fê-lo Marechal de França.

Após a morte da sua mulher em 1594, voltou a casar com Isabel de

Sample 1
Tokens: 1024
 un rival ajeno a la institución, los equipos se formaban con jóvenes que concurrían al Centro. El primer enfrentamiento de fútbol de Juventud Antoniana se realizó en Jujuy en 1919 frente a un combinado de esa provincia.
El 25 de febrero de 1922 la Liga Salteña de fútbol autoriza su incorporación a los torneos que organizaba.
El conjunto Antoniano se consagro campeón del Torneo Argentino A 1995-96 lo que volveria al Torneo Nacional B, sin embargo descendio en

Sample 2
Tokens: 1024
 noviembre de 1952, cuando fue reemplazado por Gustavo F. Storm. El 15 de agosto de 1953, volvió a ocupar un cargo ministerial en el gabinete de Chaves, pero esta vez en el ministerio del Interior reemplazando a Rigoberto Caballero, cumplió labores en dicho ministerio hasta el 7 de enero de 1954, cuando surgió una severa crisis ministerial a raíz de la destitución del entonces presidente del Banco Central y político colorado Epifanio Méndez Fleitas, a consecuencia de esta destitución, Romero Per

==============================================================================
SAVING MATERIALIZED DATASET
==============================================================================

Saving the dataset (0/9 shards):   0%|          | 0/806400 [00:00<?, ? examples/s]

==============================================================================
DATASET PREPARATION COMPLETE
==============================================================================

Sequences: 806,400
Tokens: 825,753,600

Saved to:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/pretraining_data/continuation_106k_to_130k

Training can now run without Wikipedia streaming.

In [ ]:

import os
import json
import gc
import math
import torch

from datasets import load_from_disk

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    TrainingArguments,
    Trainer,
)


# ============================================================
# MAIA LITE
# CONTROLLED PRETRAINING CONTINUATION
#
# Golden 106K -> Equivalent 130K
#
# IMPORTANT
# ---------
#
# Model weights:       restored from Golden 106K
#
# Optimizer:           NEW
# Scheduler:           NEW
# Trainer state:       NEW
# Gradient scaler:     NEW
#
# Dataset:
#     FINITE
#     MATERIALIZED
#     DETERMINISTIC
#     NO STREAMING
#
# Training:
#     24,000 new optimizer steps
#     Effective equivalent:
#
#         106K -> 130K
#
# ============================================================


# Set before substantial CUDA allocation.
os.environ[
    "PYTORCH_CUDA_ALLOC_CONF"
] = "expandable_segments:True"


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

DATASET_DIR = os.path.join(
    PROJECT_DIR,
    "pretraining_data",
    "continuation_106k_to_130k"
)

OUTPUT_DIR = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuation_fixed"
)

FINAL_DIR = os.path.join(
    OUTPUT_DIR,
    "maia_lite_equivalent_130k"
)

METADATA_FILE = os.path.join(
    OUTPUT_DIR,
    "experiment_metadata.json"
)


# ============================================================
# 2. TRAINING CONFIGURATION
# ============================================================

BASE_EQUIVALENT_STEP = 106_000

MAX_STEPS = 24_000

FINAL_EQUIVALENT_STEP = (
    BASE_EQUIVALENT_STEP
    + MAX_STEPS
)

BLOCK_SIZE = 1024

MICRO_BATCH = 8

GRAD_ACCUM = 4

EFFECTIVE_BATCH = (
    MICRO_BATCH
    * GRAD_ACCUM
)

LEARNING_RATE = 1e-5

WARMUP_STEPS = 200

WEIGHT_DECAY = 0.01

MAX_GRAD_NORM = 1.0

LOGGING_STEPS = 100

SAVE_STEPS = 2_000

SEED = 42


# ============================================================
# 3. SYSTEM
# ============================================================

print("=" * 78)
print("MAIA LITE - CONTROLLED PRETRAINING CONTINUATION")
print("=" * 78)

print()

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU required."
    )


GPU_NAME = torch.cuda.get_device_name(0)

print(
    "GPU:    ",
    GPU_NAME
)

print(
    "PyTorch:",
    torch.__version__
)

print(
    "CUDA:   ",
    torch.version.cuda
)


# ============================================================
# 4. VERIFY PATHS
# ============================================================

print()
print("=" * 78)
print("VERIFYING PATHS")
print("=" * 78)


if not os.path.isdir(
    GOLDEN_CHECKPOINT
):

    raise RuntimeError(
        "Golden checkpoint not found:\n"
        + GOLDEN_CHECKPOINT
    )


if not os.path.isdir(
    TOKENIZER_DIR
):

    raise RuntimeError(
        "Tokenizer directory not found:\n"
        + TOKENIZER_DIR
    )


if not os.path.isdir(
    DATASET_DIR
):

    raise RuntimeError(
        "Materialized dataset not found:\n"
        + DATASET_DIR
    )


print(
    "Golden checkpoint: OK"
)

print(
    "Tokenizer:         OK"
)

print(
    "Fixed dataset:     OK"
)


# ============================================================
# 5. TOKENIZER
# ============================================================

print()
print("=" * 78)
print("LOADING TOKENIZER")
print("=" * 78)


tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)


if tokenizer.pad_token is None:

    tokenizer.pad_token = (
        tokenizer.eos_token
    )


print(
    f"Vocabulary: "
    f"{tokenizer.vocab_size:,}"
)

print(
    f"EOS:        "
    f"{tokenizer.eos_token_id}"
)

print(
    f"PAD:        "
    f"{tokenizer.pad_token_id}"
)


# ============================================================
# 6. LOAD MATERIALIZED DATASET
# ============================================================

print()
print("=" * 78)
print("LOADING DETERMINISTIC DATASET")
print("=" * 78)


train_dataset = load_from_disk(
    DATASET_DIR
)


dataset_sequences = len(
    train_dataset
)


required_sequences = (
    MAX_STEPS
    * EFFECTIVE_BATCH
)


print(
    f"Sequences: "
    f"{dataset_sequences:,}"
)

print(
    f"Required:  "
    f"{required_sequences:,}"
)


if (
    dataset_sequences
    < required_sequences
):

    raise RuntimeError(
        "\nDataset is too small.\n"
        f"Available: {dataset_sequences:,}\n"
        f"Required:  {required_sequences:,}"
    )


# ============================================================
# Use exactly the amount required for this experiment.
#
# 24,000 optimizer steps
# x 32 sequences/effective batch
# = 768,000 sequences.
#
# The Trainer may deterministically shuffle these records,
# but it is always operating on the same finite dataset.
# ============================================================

train_dataset = train_dataset.select(
    range(
        required_sequences
    )
)


print(
    f"Training subset: "
    f"{len(train_dataset):,}"
)


# ============================================================
# 7. DATASET SANITY CHECK
# ============================================================

print()
print("=" * 78)
print("DATASET SANITY CHECK")
print("=" * 78)


sample = train_dataset[0]


if "input_ids" not in sample:

    raise RuntimeError(
        "Dataset has no input_ids."
    )


if "attention_mask" not in sample:

    raise RuntimeError(
        "Dataset has no attention_mask."
    )


sample_length = len(
    sample["input_ids"]
)


print(
    f"Sample length: "
    f"{sample_length:,}"
)


if sample_length != BLOCK_SIZE:

    raise RuntimeError(
        f"Expected {BLOCK_SIZE} tokens, "
        f"found {sample_length}."
    )


print(
    "Dataset format: OK"
)


# ============================================================
# 8. LOAD ONLY GOLDEN MODEL WEIGHTS
# ============================================================

print()
print("=" * 78)
print("LOADING GOLDEN 106K WEIGHTS")
print("=" * 78)


model = GPT2LMHeadModel.from_pretrained(

    GOLDEN_CHECKPOINT,

    local_files_only=True,

    torch_dtype=torch.bfloat16,
)


model.config.use_cache = False


parameters = sum(
    p.numel()
    for p in model.parameters()
)


print(
    f"Parameters: "
    f"{parameters:,}"
)


print()
print("RESTORED:")
print("  Model weights:     YES")

print()
print("NOT RESTORED:")
print("  Optimizer:         NEW")
print("  LR scheduler:      NEW")
print("  Trainer state:     NEW")
print("  Gradient scaler:   NEW")


# ============================================================
# 9. CAUSAL LANGUAGE MODELING COLLATOR
#
# The materialized dataset contains:
#
#     input_ids
#     attention_mask
#
# GPT2LMHeadModel needs labels to calculate the causal
# language-modeling loss.
#
# For ordinary GPT pretraining:
#
#     labels = input_ids
#
# GPT2LMHeadModel performs the one-token shift internally.
#
# All sequences already contain exactly 1024 tokens.
# ============================================================

def causal_lm_collator(features):

    input_ids = torch.tensor(
        [
            feature["input_ids"]
            for feature in features
        ],
        dtype=torch.long,
    )


    attention_mask = torch.tensor(
        [
            feature["attention_mask"]
            for feature in features
        ],
        dtype=torch.long,
    )


    labels = input_ids.clone()


    return {

        "input_ids":
            input_ids,

        "attention_mask":
            attention_mask,

        "labels":
            labels,
    }


# ============================================================
# 10. PRE-FLIGHT CAUSAL LM TEST
#
# CRITICAL:
#
# Test the complete:
#
# dataset
#    ->
# collator
#    ->
# model
#    ->
# causal LM loss
#
# before creating the Trainer.
#
# NO gradients.
# NO optimizer.
# NO weight updates.
# ============================================================

print()
print("=" * 78)
print("PRE-FLIGHT CAUSAL LM TEST")
print("=" * 78)


test_features = [

    train_dataset[0],

    train_dataset[1],
]


test_batch = causal_lm_collator(
    test_features
)


print(
    "input_ids:      ",
    test_batch[
        "input_ids"
    ].shape
)

print(
    "attention_mask: ",
    test_batch[
        "attention_mask"
    ].shape
)

print(
    "labels:         ",
    test_batch[
        "labels"
    ].shape
)


if (
    test_batch["input_ids"].shape
    !=
    test_batch["labels"].shape
):

    raise RuntimeError(
        "input_ids and labels "
        "have different shapes."
    )


if (
    test_batch["input_ids"].shape[1]
    != BLOCK_SIZE
):

    raise RuntimeError(
        "Unexpected sequence length."
    )


# Move model temporarily to GPU for pre-flight.
model = model.to(
    "cuda"
)


with torch.no_grad():

    test_batch_gpu = {

        key:
            value.to("cuda")

        for key, value
        in test_batch.items()
    }


    outputs = model(
        **test_batch_gpu
    )


initial_loss = float(
    outputs.loss.item()
)


initial_perplexity = math.exp(
    initial_loss
)


print()
print(
    f"Initial loss:       "
    f"{initial_loss:.6f}"
)

print(
    f"Initial perplexity: "
    f"{initial_perplexity:.3f}"
)


if not math.isfinite(
    initial_loss
):

    raise RuntimeError(
        "Pre-flight loss is not finite."
    )


# Clean pre-flight tensors.

del outputs
del test_batch_gpu
del test_batch

gc.collect()

torch.cuda.empty_cache()


print()
print(
    "Causal LM pipeline: OK"
)


# ============================================================
# 11. TRAINING ARGUMENTS
# ============================================================

training_args = TrainingArguments(

    output_dir=OUTPUT_DIR,

    max_steps=MAX_STEPS,

    per_device_train_batch_size=(
        MICRO_BATCH
    ),

    gradient_accumulation_steps=(
        GRAD_ACCUM
    ),

    learning_rate=(
        LEARNING_RATE
    ),

    lr_scheduler_type="cosine",

    warmup_steps=(
        WARMUP_STEPS
    ),

    weight_decay=(
        WEIGHT_DECAY
    ),

    max_grad_norm=(
        MAX_GRAD_NORM
    ),

    optim="adamw_torch",

    bf16=True,

    fp16=False,

    logging_strategy="steps",

    logging_steps=(
        LOGGING_STEPS
    ),

    save_strategy="steps",

    save_steps=(
        SAVE_STEPS
    ),

    save_total_limit=20,

    report_to="none",

    dataloader_num_workers=0,

    remove_unused_columns=False,

    seed=SEED,

    data_seed=SEED,

    full_determinism=True,
)


# ============================================================
# 12. TRAINER
# ============================================================

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    data_collator=(
        causal_lm_collator
    ),
)


# ============================================================
# 13. PRINT EXPERIMENT CONFIGURATION
# ============================================================

print()
print("=" * 78)
print("EXPERIMENT CONFIGURATION")
print("=" * 78)


print(
    f"Starting equivalent step: "
    f"{BASE_EQUIVALENT_STEP:,}"
)

print(
    f"Continuation steps:       "
    f"{MAX_STEPS:,}"
)

print(
    f"Final equivalent step:    "
    f"{FINAL_EQUIVALENT_STEP:,}"
)

print()

print(
    f"Block size:               "
    f"{BLOCK_SIZE:,}"
)

print(
    f"Micro batch:              "
    f"{MICRO_BATCH}"
)

print(
    f"Gradient accumulation:    "
    f"{GRAD_ACCUM}"
)

print(
    f"Effective batch:          "
    f"{EFFECTIVE_BATCH}"
)

print()

print(
    f"Learning rate:            "
    f"{LEARNING_RATE:.2e}"
)

print(
    f"Warmup:                   "
    f"{WARMUP_STEPS:,}"
)

print(
    f"Weight decay:             "
    f"{WEIGHT_DECAY}"
)

print(
    f"Max gradient norm:        "
    f"{MAX_GRAD_NORM}"
)

print()

print(
    f"Log every:                "
    f"{LOGGING_STEPS:,}"
)

print(
    f"Save every:               "
    f"{SAVE_STEPS:,}"
)

print()

print(
    "Dataset mode:             "
    "MATERIALIZED / FINITE"
)

print(
    "Streaming:                "
    "NO"
)

print(
    "ignore_data_skip:         "
    "NOT USED"
)

print(
    "resume_from_checkpoint:   "
    "NO"
)

print(
    "Causal labels:            "
    "YES"
)

print(
    "labels = input_ids:       "
    "YES"
)

print(
    "Pre-flight loss:          "
    f"{initial_loss:.6f}"
)


# ============================================================
# 14. SAVE EXPERIMENT METADATA
# ============================================================

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True,
)


metadata = {

    "experiment":
        "controlled_pretraining_106k_to_130k",

    "base_checkpoint":
        GOLDEN_CHECKPOINT,

    "base_equivalent_step":
        BASE_EQUIVALENT_STEP,

    "continuation_steps":
        MAX_STEPS,

    "final_equivalent_step":
        FINAL_EQUIVALENT_STEP,

    "block_size":
        BLOCK_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "warmup_steps":
        WARMUP_STEPS,

    "weight_decay":
        WEIGHT_DECAY,

    "max_grad_norm":
        MAX_GRAD_NORM,

    "micro_batch":
        MICRO_BATCH,

    "gradient_accumulation":
        GRAD_ACCUM,

    "effective_batch":
        EFFECTIVE_BATCH,

    "dataset":
        DATASET_DIR,

    "dataset_sequences":
        len(train_dataset),

    "streaming":
        False,

    "optimizer_restored":
        False,

    "scheduler_restored":
        False,

    "trainer_state_restored":
        False,

    "gradient_scaler_restored":
        False,

    "causal_labels":
        True,

    "initial_preflight_loss":
        initial_loss,

    "initial_preflight_perplexity":
        initial_perplexity,

    "seed":
        SEED,

    "gpu":
        GPU_NAME,

    "pytorch":
        torch.__version__,

    "cuda":
        torch.version.cuda,
}


with open(

    METADATA_FILE,

    "w",

    encoding="utf-8",

) as f:

    json.dump(
        metadata,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 15. TRAIN
#
# IMPORTANT:
#
# DO NOT use:
#
#     resume_from_checkpoint=True
#
# We intentionally begin a NEW optimization trajectory
# from the Golden 106K model weights.
#
# ============================================================

print()
print("=" * 78)
print("STARTING CONTROLLED CONTINUATION")
print("=" * 78)

print()

print(
    "Golden checkpoint-106000 "
    "will NOT be modified."
)

print()

print(
    "New optimization trajectory:"
)

print(
    "106K -> 130K"
)

print()

print(
    "Critical observation region:"
)

print(
    "continuation step ~12,100 "
    "(equivalent ~118,100)"
)

print()


train_result = trainer.train()


# ============================================================
# 16. TRAINING RESULT
# ============================================================

print()
print("=" * 78)
print("TRAINING COMPLETE")
print("=" * 78)

print()

print(
    f"Final training loss: "
    f"{train_result.training_loss:.6f}"
)

print(
    f"Global step: "
    f"{trainer.state.global_step:,}"
)


# ============================================================
# 17. SAVE FINAL MODEL
# ============================================================

print()
print("=" * 78)
print("SAVING EQUIVALENT 130K MODEL")
print("=" * 78)


model.config.use_cache = True


trainer.save_model(
    FINAL_DIR
)


tokenizer.save_pretrained(
    FINAL_DIR
)


# ============================================================
# 18. FINAL INFORMATION
# ============================================================

print()
print("=" * 78)
print("CONTROLLED CONTINUATION COMPLETE")
print("=" * 78)

print()

print(
    "Golden preserved:"
)

print(
    GOLDEN_CHECKPOINT
)

print()

print(
    "Continuation checkpoints:"
)

print(
    OUTPUT_DIR
)

print()

print(
    "Final equivalent 130K:"
)

print(
    FINAL_DIR
)

print()

print(
    "Checkpoint mapping:"
)

for continuation_step in range(
    SAVE_STEPS,
    MAX_STEPS + 1,
    SAVE_STEPS,
):

    equivalent_step = (
        BASE_EQUIVALENT_STEP
        + continuation_step
    )

    print(
        f"  checkpoint-{continuation_step:<5} "
        f"-> equivalent {equivalent_step:,}"
    )

print()
print(
    "IMPORTANT:"
)

print(
    "Inspect the loss especially around "
    "continuation steps 12,000-14,000."
)

==============================================================================
MAIA LITE - CONTROLLED PRETRAINING CONTINUATION
==============================================================================

GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA:    12.8

==============================================================================
VERIFYING PATHS
==============================================================================
Golden checkpoint: OK
Tokenizer:         OK
Fixed dataset:     OK

==============================================================================
LOADING TOKENIZER
==============================================================================
Vocabulary: 50,257
EOS:        2
PAD:        1

==============================================================================
LOADING DETERMINISTIC DATASET
==============================================================================
Sequences: 806,400
Required:  768,000
Training subset: 768,000

==============================================================================
DATASET SANITY CHECK
==============================================================================
Sample length: 1,024
Dataset format: OK

==============================================================================
LOADING GOLDEN 106K WEIGHTS
==============================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters: 354,823,168

RESTORED:
  Model weights:     YES

NOT RESTORED:
  Optimizer:         NEW
  LR scheduler:      NEW
  Trainer state:     NEW
  Gradient scaler:   NEW

==============================================================================
PRE-FLIGHT CAUSAL LM TEST
==============================================================================
input_ids:       torch.Size([2, 1024])
attention_mask:  torch.Size([2, 1024])
labels:          torch.Size([2, 1024])

Initial loss:       3.284665
Initial perplexity: 26.700

Causal LM pipeline: OK

==============================================================================
EXPERIMENT CONFIGURATION
==============================================================================
Starting equivalent step: 106,000
Continuation steps:       24,000
Final equivalent step:    130,000

Block size:               1,024
Micro batch:              8
Gradient accumulation:    4
Effective batch:          32

Learning rate:            1.00e-05
Warmup:                   200
Weight decay:             0.01
Max gradient norm:        1.0

Log every:                100
Save every:               2,000

Dataset mode:             MATERIALIZED / FINITE
Streaming:                NO
ignore_data_skip:         NOT USED
resume_from_checkpoint:   NO
Causal labels:            YES
labels = input_ids:       YES
Pre-flight loss:          3.284665

==============================================================================
STARTING CONTROLLED CONTINUATION
==============================================================================

Golden checkpoint-106000 will NOT be modified.

New optimization trajectory:
106K -> 130K

Critical observation region:
continuation step ~12,100 (equivalent ~118,100)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================================
TRAINING COMPLETE
==============================================================================

Final training loss: 3.256080
Global step: 24,000

==============================================================================
SAVING EQUIVALENT 130K MODEL
==============================================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================================
CONTROLLED CONTINUATION COMPLETE
==============================================================================

Golden preserved:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Continuation checkpoints:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed

Final equivalent 130K:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/maia_lite_equivalent_130k

Checkpoint mapping:
  checkpoint-2000  -> equivalent 108,000
  checkpoint-4000  -> equivalent 110,000
  checkpoint-6000  -> equivalent 112,000
  checkpoint-8000  -> equivalent 114,000
  checkpoint-10000 -> equivalent 116,000
  checkpoint-12000 -> equivalent 118,000
  checkpoint-14000 -> equivalent 120,000
  checkpoint-16000 -> equivalent 122,000
  checkpoint-18000 -> equivalent 124,000
  checkpoint-20000 -> equivalent 126,000
  checkpoint-22000 -> equivalent 128,000
  checkpoint-24000 -> equivalent 130,000

IMPORTANT:
Inspect the loss especially around continuation steps 12,000-14,000.

In [ ]:
import os
import gc
import json
import csv
import math
import time

import torch
from datasets import load_from_disk
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# MAIA LITE
# HELD-OUT CHECKPOINT EVALUATION
#
# Compare:
#
#   Golden 106K
#   108K
#   110K
#   112K
#   ...
#   130K
#
# using EXACTLY THE SAME held-out sequences.
#
# IMPORTANT
# ---------
#
# The deterministic corpus contains:
#
#   806,400 sequences
#
# Training used:
#
#   768,000 sequences
#
# Therefore:
#
#   38,400 sequences
#
# were NOT included in the controlled 106K -> 130K run.
#
# For the first evaluation pass we use:
#
#   4,096 sequences
#   x 1,024 tokens
#   = ~4.19M tokens/checkpoint
#
# No gradients.
# No optimizer.
# No training.
# No checkpoint modification.
# ============================================================


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_CHECKPOINT = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000"
)

CONTINUATION_DIR = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuation_fixed"
)

DATASET_DIR = os.path.join(
    PROJECT_DIR,
    "pretraining_data",
    "continuation_106k_to_130k"
)

DIAGNOSTICS_DIR = os.path.join(
    PROJECT_DIR,
    "diagnostics"
)

JSON_OUTPUT = os.path.join(
    DIAGNOSTICS_DIR,
    "heldout_106k_to_130k.json"
)

CSV_OUTPUT = os.path.join(
    DIAGNOSTICS_DIR,
    "heldout_106k_to_130k.csv"
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

BLOCK_SIZE = 1024

TRAINED_SEQUENCES = 768_000

# First-pass held-out benchmark.
#
# 4096 * 1024 =
# 4,194,304 tokens approximately.

VALIDATION_SEQUENCES = 4_096

BATCH_SIZE = 16


# ============================================================
# 3. CHECKPOINTS
# ============================================================

CHECKPOINTS = [
    (
        106_000,
        GOLDEN_CHECKPOINT,
    ),

    (
        108_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-2000",
        ),
    ),

    (
        110_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-4000",
        ),
    ),

    (
        112_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-6000",
        ),
    ),

    (
        114_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-8000",
        ),
    ),

    (
        116_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-10000",
        ),
    ),

    (
        118_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-12000",
        ),
    ),

    (
        120_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-14000",
        ),
    ),

    (
        122_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-16000",
        ),
    ),

    (
        124_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-18000",
        ),
    ),

    (
        126_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-20000",
        ),
    ),

    (
        128_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-22000",
        ),
    ),

    (
        130_000,
        os.path.join(
            CONTINUATION_DIR,
            "checkpoint-24000",
        ),
    ),
]


# ============================================================
# 4. SYSTEM
# ============================================================

print("=" * 78)
print("MAIA LITE - HELD-OUT CHECKPOINT EVALUATION")
print("=" * 78)

print()

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU required."
    )


DEVICE = torch.device(
    "cuda"
)

GPU_NAME = torch.cuda.get_device_name(
    0
)


print(
    f"GPU:     {GPU_NAME}"
)

print(
    f"PyTorch: {torch.__version__}"
)

print(
    f"CUDA:    {torch.version.cuda}"
)


# ============================================================
# 5. VERIFY CHECKPOINTS
# ============================================================

print()
print("=" * 78)
print("VERIFYING CHECKPOINTS")
print("=" * 78)


for equivalent_step, path in CHECKPOINTS:

    if not os.path.isdir(path):

        raise RuntimeError(
            "\nCheckpoint not found:\n"
            f"Equivalent step: {equivalent_step:,}\n"
            f"Path: {path}"
        )

    print(
        f"{equivalent_step:>7,} : OK"
    )


# ============================================================
# 6. TOKENIZER
# ============================================================

print()
print("=" * 78)
print("LOADING TOKENIZER")
print("=" * 78)


tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)


if tokenizer.pad_token is None:

    tokenizer.pad_token = (
        tokenizer.eos_token
    )


print(
    f"Vocabulary: "
    f"{tokenizer.vocab_size:,}"
)

print(
    f"EOS:        "
    f"{tokenizer.eos_token_id}"
)

print(
    f"PAD:        "
    f"{tokenizer.pad_token_id}"
)


# ============================================================
# 7. LOAD FULL MATERIALIZED DATASET
# ============================================================

print()
print("=" * 78)
print("LOADING MATERIALIZED DATASET")
print("=" * 78)


dataset = load_from_disk(
    DATASET_DIR
)


total_sequences = len(
    dataset
)


heldout_available = (
    total_sequences
    - TRAINED_SEQUENCES
)


print(
    f"Total sequences:     "
    f"{total_sequences:,}"
)

print(
    f"Training sequences:  "
    f"{TRAINED_SEQUENCES:,}"
)

print(
    f"Held-out available:  "
    f"{heldout_available:,}"
)


if (
    heldout_available
    < VALIDATION_SEQUENCES
):

    raise RuntimeError(
        "\nNot enough held-out sequences.\n"
        f"Available: {heldout_available:,}\n"
        f"Requested: {VALIDATION_SEQUENCES:,}"
    )


# ============================================================
# 8. CREATE FIXED HELD-OUT SUBSET
#
# Training selected:
#
#   dataset[0 : 768000]
#
# Therefore validation begins at:
#
#   dataset[768000]
#
# These sequences were never part of the controlled
# continuation dataset passed to Trainer.
# ============================================================

validation_start = (
    TRAINED_SEQUENCES
)

validation_end = (
    validation_start
    + VALIDATION_SEQUENCES
)


validation_dataset = dataset.select(
    range(
        validation_start,
        validation_end,
    )
)


print()
print(
    f"Validation start:     "
    f"{validation_start:,}"
)

print(
    f"Validation end:       "
    f"{validation_end - 1:,}"
)

print(
    f"Validation sequences: "
    f"{len(validation_dataset):,}"
)


raw_tokens = (
    len(validation_dataset)
    * BLOCK_SIZE
)


# Causal LM predicts positions 1..1023.
#
# Each 1024-token sequence therefore contributes
# 1023 prediction targets.

prediction_tokens = (
    len(validation_dataset)
    * (BLOCK_SIZE - 1)
)


print(
    f"Raw tokens:           "
    f"{raw_tokens:,}"
)

print(
    f"Prediction tokens:    "
    f"{prediction_tokens:,}"
)


# ============================================================
# 9. SANITY CHECK VALIDATION DATA
# ============================================================

print()
print("=" * 78)
print("VALIDATION SANITY CHECK")
print("=" * 78)


for i in range(3):

    sample = validation_dataset[i]

    sequence_length = len(
        sample["input_ids"]
    )

    print(
        f"Sample {i}: "
        f"{sequence_length:,} tokens"
    )

    if sequence_length != BLOCK_SIZE:

        raise RuntimeError(
            f"Unexpected sequence length "
            f"in validation sample {i}."
        )


print(
    "Validation data: OK"
)


# ============================================================
# 10. BATCH BUILDER
# ============================================================

def make_batch(samples):

    input_ids = torch.tensor(
        [
            sample["input_ids"]
            for sample in samples
        ],
        dtype=torch.long,
    )


    attention_mask = torch.tensor(
        [
            sample["attention_mask"]
            for sample in samples
        ],
        dtype=torch.long,
    )


    labels = input_ids.clone()


    return {
        "input_ids":
            input_ids,

        "attention_mask":
            attention_mask,

        "labels":
            labels,
    }


# ============================================================
# 11. EVALUATE ONE CHECKPOINT
# ============================================================

def evaluate_checkpoint(
    equivalent_step,
    checkpoint_path,
):

    print()
    print("=" * 78)
    print(
        f"EVALUATING EQUIVALENT STEP "
        f"{equivalent_step:,}"
    )
    print("=" * 78)

    print(
        checkpoint_path
    )


    # --------------------------------------------------------
    # Load model.
    # --------------------------------------------------------

    model = GPT2LMHeadModel.from_pretrained(

        checkpoint_path,

        local_files_only=True,

        torch_dtype=torch.bfloat16,
    )


    model.config.use_cache = False

    model.to(
        DEVICE
    )

    model.eval()


    # --------------------------------------------------------
    # Accumulators.
    #
    # All sequences have the same number of valid prediction
    # tokens, but we still calculate a properly token-weighted
    # mean.
    # --------------------------------------------------------

    total_loss_times_tokens = 0.0

    total_prediction_tokens = 0

    batch_losses = []

    start_time = time.time()


    # --------------------------------------------------------
    # Evaluation loop.
    # --------------------------------------------------------

    with torch.inference_mode():

        for batch_start in range(
            0,
            len(validation_dataset),
            BATCH_SIZE,
        ):

            batch_end = min(
                batch_start + BATCH_SIZE,
                len(validation_dataset),
            )


            samples = [
                validation_dataset[i]

                for i in range(
                    batch_start,
                    batch_end,
                )
            ]


            batch = make_batch(
                samples
            )


            batch = {

                key:
                    value.to(
                        DEVICE,
                        non_blocking=True,
                    )

                for key, value
                in batch.items()
            }


            outputs = model(
                **batch
            )


            loss = float(
                outputs.loss.item()
            )


            batch_size_actual = (
                batch_end
                - batch_start
            )


            valid_tokens = (
                batch_size_actual
                * (BLOCK_SIZE - 1)
            )


            total_loss_times_tokens += (
                loss
                * valid_tokens
            )


            total_prediction_tokens += (
                valid_tokens
            )


            batch_losses.append(
                loss
            )


            if (
                (batch_start // BATCH_SIZE + 1)
                % 50
                == 0
            ):

                processed = (
                    batch_end
                )

                print(
                    f"  "
                    f"{processed:,}"
                    f"/"
                    f"{len(validation_dataset):,}"
                    f" sequences"
                )


            del outputs
            del batch


    # --------------------------------------------------------
    # Metrics.
    # --------------------------------------------------------

    weighted_loss = (
        total_loss_times_tokens
        /
        total_prediction_tokens
    )


    perplexity = math.exp(
        weighted_loss
    )


    mean_batch_loss = (
        sum(batch_losses)
        /
        len(batch_losses)
    )


    elapsed = (
        time.time()
        - start_time
    )


    sequences_per_second = (
        len(validation_dataset)
        /
        elapsed
    )


    tokens_per_second = (
        total_prediction_tokens
        /
        elapsed
    )


    result = {

        "equivalent_step":
            equivalent_step,

        "checkpoint":
            checkpoint_path,

        "validation_sequences":
            len(validation_dataset),

        "prediction_tokens":
            total_prediction_tokens,

        "token_weighted_loss":
            weighted_loss,

        "mean_batch_loss":
            mean_batch_loss,

        "perplexity":
            perplexity,

        "elapsed_seconds":
            elapsed,

        "sequences_per_second":
            sequences_per_second,

        "prediction_tokens_per_second":
            tokens_per_second,
    }


    print()
    print(
        f"Token-weighted loss: "
        f"{weighted_loss:.8f}"
    )

    print(
        f"Mean batch loss:     "
        f"{mean_batch_loss:.8f}"
    )

    print(
        f"Perplexity:          "
        f"{perplexity:.6f}"
    )

    print(
        f"Time:                "
        f"{elapsed:.1f} s"
    )


    # --------------------------------------------------------
    # Free GPU memory before next checkpoint.
    # --------------------------------------------------------

    del model

    gc.collect()

    torch.cuda.empty_cache()


    return result


# ============================================================
# 12. RUN ALL CHECKPOINTS
# ============================================================

print()
print("=" * 78)
print("STARTING HELD-OUT EVALUATION")
print("=" * 78)

print()

print(
    f"Models:            "
    f"{len(CHECKPOINTS)}"
)

print(
    f"Sequences/model:   "
    f"{len(validation_dataset):,}"
)

print(
    f"Prediction tokens: "
    f"{prediction_tokens:,} / model"
)

print(
    f"Batch size:        "
    f"{BATCH_SIZE}"
)


results = []


for equivalent_step, checkpoint_path in CHECKPOINTS:

    result = evaluate_checkpoint(

        equivalent_step,

        checkpoint_path,
    )

    results.append(
        result
    )


# ============================================================
# 13. COMPARE AGAINST GOLDEN 106K
# ============================================================

golden_loss = results[0][
    "token_weighted_loss"
]


for result in results:

    loss = result[
        "token_weighted_loss"
    ]


    absolute_change = (
        loss
        - golden_loss
    )


    percent_change = (
        absolute_change
        /
        golden_loss
        * 100.0
    )


    result[
        "loss_change_vs_106k"
    ] = absolute_change


    result[
        "percent_change_vs_106k"
    ] = percent_change


# ============================================================
# 14. FIND LOWEST HELD-OUT LOSS
# ============================================================

best_result = min(

    results,

    key=lambda item:
        item["token_weighted_loss"],
)


# ============================================================
# 15. PRINT SUMMARY TABLE
# ============================================================

print()
print("=" * 78)
print("HELD-OUT RESULTS")
print("=" * 78)

print()

print(
    f"{'Eq.Step':>10}  "
    f"{'Loss':>12}  "
    f"{'PPL':>10}  "
    f"{'Δ vs 106K':>12}  "
    f"{'% vs 106K':>11}"
)

print(
    "-" * 64
)


for result in results:

    print(

        f"{result['equivalent_step']:>10,}  "

        f"{result['token_weighted_loss']:>12.8f}  "

        f"{result['perplexity']:>10.4f}  "

        f"{result['loss_change_vs_106k']:>+12.8f}  "

        f"{result['percent_change_vs_106k']:>+10.4f}%"
    )


print()
print("=" * 78)
print("LOWEST HELD-OUT LOSS")
print("=" * 78)

print()

print(
    f"Equivalent step: "
    f"{best_result['equivalent_step']:,}"
)

print(
    f"Loss:            "
    f"{best_result['token_weighted_loss']:.8f}"
)

print(
    f"Perplexity:      "
    f"{best_result['perplexity']:.6f}"
)

print(
    f"Change vs 106K:  "
    f"{best_result['percent_change_vs_106k']:+.4f}%"
)


# ============================================================
# 16. SAVE JSON
# ============================================================

os.makedirs(
    DIAGNOSTICS_DIR,
    exist_ok=True,
)


report = {

    "benchmark":
        "Maia Lite held-out 106K -> 130K",

    "dataset":
        DATASET_DIR,

    "training_sequences":
        TRAINED_SEQUENCES,

    "heldout_available":
        heldout_available,

    "validation_start":
        validation_start,

    "validation_end":
        validation_end,

    "validation_sequences":
        len(validation_dataset),

    "block_size":
        BLOCK_SIZE,

    "raw_tokens_per_model":
        raw_tokens,

    "prediction_tokens_per_model":
        prediction_tokens,

    "batch_size":
        BATCH_SIZE,

    "gpu":
        GPU_NAME,

    "golden_106k_loss":
        golden_loss,

    "lowest_heldout_loss_step":
        best_result[
            "equivalent_step"
        ],

    "lowest_heldout_loss":
        best_result[
            "token_weighted_loss"
        ],

    "results":
        results,
}


with open(

    JSON_OUTPUT,

    "w",

    encoding="utf-8",

) as f:

    json.dump(
        report,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 17. SAVE CSV
# ============================================================

csv_fields = [

    "equivalent_step",

    "token_weighted_loss",

    "perplexity",

    "loss_change_vs_106k",

    "percent_change_vs_106k",

    "mean_batch_loss",

    "validation_sequences",

    "prediction_tokens",

    "elapsed_seconds",

    "sequences_per_second",

    "prediction_tokens_per_second",

    "checkpoint",
]


with open(

    CSV_OUTPUT,

    "w",

    newline="",

    encoding="utf-8",

) as f:

    writer = csv.DictWriter(

        f,

        fieldnames=csv_fields,
    )

    writer.writeheader()

    for result in results:

        writer.writerow({

            field:
                result[field]

            for field
            in csv_fields
        })


# ============================================================
# 18. FINAL
# ============================================================

print()
print("=" * 78)
print("EVALUATION COMPLETE")
print("=" * 78)

print()

print(
    "JSON:"
)

print(
    JSON_OUTPUT
)

print()

print(
    "CSV:"
)

print(
    CSV_OUTPUT
)

print()

print(
    "No model weights were modified."
)

print(
    "No training was performed."
)

==============================================================================
MAIA LITE - HELD-OUT CHECKPOINT EVALUATION
==============================================================================

GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128
CUDA:    12.8

==============================================================================
VERIFYING CHECKPOINTS
==============================================================================
106,000 : OK
108,000 : OK
110,000 : OK
112,000 : OK
114,000 : OK
116,000 : OK
118,000 : OK
120,000 : OK
122,000 : OK
124,000 : OK
126,000 : OK
128,000 : OK
130,000 : OK

==============================================================================
LOADING TOKENIZER
==============================================================================
Vocabulary: 50,257
EOS:        2
PAD:        1

==============================================================================
LOADING MATERIALIZED DATASET
==============================================================================
Total sequences:     806,400
Training sequences:  768,000
Held-out available:  38,400

Validation start:     768,000
Validation end:       772,095
Validation sequences: 4,096
Raw tokens:           4,194,304
Prediction tokens:    4,190,208

==============================================================================
VALIDATION SANITY CHECK
==============================================================================
Sample 0: 1,024 tokens
Sample 1: 1,024 tokens
Sample 2: 1,024 tokens
Validation data: OK

==============================================================================
STARTING HELD-OUT EVALUATION
==============================================================================

Models:            13
Sequences/model:   4,096
Prediction tokens: 4,190,208 / model
Batch size:        16

==============================================================================
EVALUATING EQUIVALENT STEP 106,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.22724397
Mean batch loss:     3.22724397
Perplexity:          25.210081
Time:                37.1 s

==============================================================================
EVALUATING EQUIVALENT STEP 108,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-2000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.16234603
Mean batch loss:     3.16234603
Perplexity:          23.625958
Time:                37.3 s

==============================================================================
EVALUATING EQUIVALENT STEP 110,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-4000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15907474
Mean batch loss:     3.15907474
Perplexity:          23.548797
Time:                37.2 s

==============================================================================
EVALUATING EQUIVALENT STEP 112,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-6000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15859267
Mean batch loss:     3.15859267
Perplexity:          23.537448
Time:                37.2 s

==============================================================================
EVALUATING EQUIVALENT STEP 114,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-8000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15843829
Mean batch loss:     3.15843829
Perplexity:          23.533814
Time:                37.3 s

==============================================================================
EVALUATING EQUIVALENT STEP 116,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-10000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15843205
Mean batch loss:     3.15843205
Perplexity:          23.533667
Time:                37.2 s

==============================================================================
EVALUATING EQUIVALENT STEP 118,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-12000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15842799
Mean batch loss:     3.15842799
Perplexity:          23.533572
Time:                37.2 s

==============================================================================
EVALUATING EQUIVALENT STEP 120,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-14000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15840627
Mean batch loss:     3.15840627
Perplexity:          23.533061
Time:                37.2 s

==============================================================================
EVALUATING EQUIVALENT STEP 122,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-16000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15841463
Mean batch loss:     3.15841463
Perplexity:          23.533258
Time:                37.3 s

==============================================================================
EVALUATING EQUIVALENT STEP 124,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-18000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15839882
Mean batch loss:     3.15839882
Perplexity:          23.532885
Time:                37.3 s

==============================================================================
EVALUATING EQUIVALENT STEP 126,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-20000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15839709
Mean batch loss:     3.15839709
Perplexity:          23.532845
Time:                37.3 s

==============================================================================
EVALUATING EQUIVALENT STEP 128,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-22000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15841831
Mean batch loss:     3.15841831
Perplexity:          23.533344
Time:                37.3 s

==============================================================================
EVALUATING EQUIVALENT STEP 130,000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/checkpoint-24000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

  800/4,096 sequences
  1,600/4,096 sequences
  2,400/4,096 sequences
  3,200/4,096 sequences
  4,000/4,096 sequences

Token-weighted loss: 3.15842743
Mean batch loss:     3.15842743
Perplexity:          23.533559
Time:                37.3 s

==============================================================================
HELD-OUT RESULTS
==============================================================================

   Eq.Step          Loss         PPL     Δ vs 106K    % vs 106K
----------------------------------------------------------------
   106,000    3.22724397     25.2101   +0.00000000     +0.0000%
   108,000    3.16234603     23.6260   -0.06489793     -2.0109%
   110,000    3.15907474     23.5488   -0.06816923     -2.1123%
   112,000    3.15859267     23.5374   -0.06865129     -2.1272%
   114,000    3.15843829     23.5338   -0.06880568     -2.1320%
   116,000    3.15843205     23.5337   -0.06881192     -2.1322%
   118,000    3.15842799     23.5336   -0.06881598     -2.1323%
   120,000    3.15840627     23.5331   -0.06883770     -2.1330%
   122,000    3.15841463     23.5333   -0.06882933     -2.1328%
   124,000    3.15839882     23.5329   -0.06884514     -2.1332%
   126,000    3.15839709     23.5328   -0.06884687     -2.1333%
   128,000    3.15841831     23.5333   -0.06882566     -2.1326%
   130,000    3.15842743     23.5336   -0.06881653     -2.1324%

==============================================================================
LOWEST HELD-OUT LOSS
==============================================================================

Equivalent step: 126,000
Loss:            3.15839709
Perplexity:      23.532845
Change vs 106K:  -2.1333%

==============================================================================
EVALUATION COMPLETE
==============================================================================

JSON:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/diagnostics/heldout_106k_to_130k.json

CSV:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/diagnostics/heldout_106k_to_130k.csv

No model weights were modified.
No training was performed.

In [ ]:
import os
import gc
import json
import math
import re
import time

import torch
import torch.nn.functional as F

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# MAIA LITE
# CAPABILITY BENCHMARK
#
# Compare:
#
#   Golden 106K
#       vs
#   Controlled 130K
#
# PURPOSE
# -------
#
# Determine whether the held-out loss improvement observed
# during controlled pretraining corresponds to observable
# capability changes.
#
# NO TRAINING.
# NO OPTIMIZER.
# NO MODEL MODIFICATION.
#
# Generation is intentionally strict:
#
#   greedy decoding
#   no sampling
#   no repetition penalty
#   no no-repeat-ngram tricks
#
# This allows pathological repetition to remain visible.
# ============================================================


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = (
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = os.path.join(
    PROJECT_DIR,
    "tokenizador"
)

GOLDEN_106K = os.path.join(
    PROJECT_DIR,
    "checkpoints_pretreino",
    "checkpoint-106000",
)

CONTROLLED_130K = os.path.join(
    PROJECT_DIR,
    "checkpoints_continuation_fixed",
    "maia_lite_equivalent_130k",
)

DIAGNOSTICS_DIR = os.path.join(
    PROJECT_DIR,
    "diagnostics",
)

OUTPUT_JSON = os.path.join(
    DIAGNOSTICS_DIR,
    "capability_106k_vs_130k.json",
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

MAX_NEW_TOKENS = 80

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

DTYPE = (
    torch.bfloat16
    if torch.cuda.is_available()
    else torch.float32
)


MODELS = [
    {
        "name": "base-106000",
        "equivalent_step": 106_000,
        "path": GOLDEN_106K,
    },
    {
        "name": "controlled-130000",
        "equivalent_step": 130_000,
        "path": CONTROLLED_130K,
    },
]


# ============================================================
# 3. GENERATION TESTS
#
# expected_terms are NOT intended as a sophisticated
# benchmark metric.
#
# They are simple diagnostics to make obvious improvements
# or regressions easier to spot.
# ============================================================

GENERATION_TESTS = [

    # --------------------------------------------------------
    # ENGLISH FACTUAL
    # --------------------------------------------------------

    {
        "id": "EN_FACT_01",
        "category": "factual_en",
        "prompt": "The capital of France is",
        "expected_terms": ["Paris"],
    },

    {
        "id": "EN_FACT_02",
        "category": "factual_en",
        "prompt": "The largest planet in the Solar System is",
        "expected_terms": ["Jupiter"],
    },

    {
        "id": "EN_FACT_03",
        "category": "factual_en",
        "prompt": "DNA stands for",
        "expected_terms": [
            "deoxyribonucleic",
            "deoxyribonucleic acid",
        ],
    },


    # --------------------------------------------------------
    # PORTUGUESE FACTUAL
    # --------------------------------------------------------

    {
        "id": "PT_FACT_01",
        "category": "factual_pt",
        "prompt": "A capital do Brasil é",
        "expected_terms": ["Brasília", "Brasilia"],
    },

    {
        "id": "PT_FACT_02",
        "category": "factual_pt",
        "prompt": "O maior planeta do Sistema Solar é",
        "expected_terms": ["Júpiter", "Jupiter"],
    },

    {
        "id": "PT_FACT_03",
        "category": "factual_pt",
        "prompt": "A água congela, ao nível do mar, a",
        "expected_terms": [
            "0 °C",
            "0°C",
            "zero grau",
            "zero graus",
        ],
    },


    # --------------------------------------------------------
    # SPANISH FACTUAL
    # --------------------------------------------------------

    {
        "id": "ES_FACT_01",
        "category": "factual_es",
        "prompt": "La capital de España es",
        "expected_terms": ["Madrid"],
    },

    {
        "id": "ES_FACT_02",
        "category": "factual_es",
        "prompt": "El planeta más grande del Sistema Solar es",
        "expected_terms": ["Júpiter", "Jupiter"],
    },


    # --------------------------------------------------------
    # MATHEMATICS
    # --------------------------------------------------------

    {
        "id": "MATH_01",
        "category": "math",
        "prompt": "2 + 2 =",
        "expected_terms": ["4"],
    },

    {
        "id": "MATH_02",
        "category": "math",
        "prompt": "10 * 5 =",
        "expected_terms": ["50"],
    },

    {
        "id": "MATH_03",
        "category": "math",
        "prompt": "The square root of 81 is",
        "expected_terms": ["9"],
    },

    {
        "id": "MATH_04",
        "category": "math",
        "prompt": "If x + 3 = 7, then x =",
        "expected_terms": ["4"],
    },


    # --------------------------------------------------------
    # SEMANTIC RELATIONS
    # --------------------------------------------------------

    {
        "id": "SEM_01",
        "category": "semantic",
        "prompt": "Paris is to France as Madrid is to",
        "expected_terms": ["Spain"],
    },

    {
        "id": "SEM_02",
        "category": "semantic",
        "prompt": "Bird is to sky as fish is to",
        "expected_terms": ["water"],
    },

    {
        "id": "SEM_03",
        "category": "semantic",
        "prompt": "A dog is an animal. A rose is a",
        "expected_terms": ["flower"],
    },


    # --------------------------------------------------------
    # TRANSLATION
    # --------------------------------------------------------

    {
        "id": "TRANS_01",
        "category": "translation",
        "prompt": (
            "Translate from Portuguese to English:\n"
            "O céu é azul.\n"
            "English:"
        ),
        "expected_terms": [
            "The sky is blue",
            "sky is blue",
        ],
    },

    {
        "id": "TRANS_02",
        "category": "translation",
        "prompt": (
            "Translate from English to Portuguese:\n"
            "The cat is sleeping.\n"
            "Português:"
        ),
        "expected_terms": [
            "O gato está dormindo",
            "O gato está a dormir",
            "gato está dormindo",
        ],
    },

    {
        "id": "TRANS_03",
        "category": "translation",
        "prompt": (
            "Translate from Spanish to English:\n"
            "La computadora es rápida.\n"
            "English:"
        ),
        "expected_terms": [
            "The computer is fast",
            "computer is fast",
        ],
    },


    # --------------------------------------------------------
    # INSTRUCTION FOLLOWING
    # --------------------------------------------------------

    {
        "id": "INST_01",
        "category": "instruction",
        "prompt": (
            "Answer with only one word.\n"
            "What color is snow?\n"
            "Answer:"
        ),
        "expected_terms": [
            "white",
        ],
    },

    {
        "id": "INST_02",
        "category": "instruction",
        "prompt": (
            "Complete the sentence with a short answer:\n"
            "Water is essential for"
        ),
        "expected_terms": [
            "life",
        ],
    },


    # --------------------------------------------------------
    # PYTHON
    # --------------------------------------------------------

    {
        "id": "PY_01",
        "category": "python",
        "prompt": (
            "Python code to print Hello World:\n"
        ),
        "expected_terms": [
            "print",
            "Hello",
        ],
    },

    {
        "id": "PY_02",
        "category": "python",
        "prompt": (
            "Write a Python function called add that returns "
            "the sum of a and b:\n"
        ),
        "expected_terms": [
            "def add",
            "return",
        ],
    },


    # --------------------------------------------------------
    # FEW-SHOT
    # --------------------------------------------------------

    {
        "id": "FS_01",
        "category": "few_shot",
        "prompt": (
            "Germany -> Berlin\n"
            "Italy -> Rome\n"
            "France ->"
        ),
        "expected_terms": ["Paris"],
    },

    {
        "id": "FS_02",
        "category": "few_shot",
        "prompt": (
            "Portugal -> Lisboa\n"
            "Argentina -> Buenos Aires\n"
            "Brasil ->"
        ),
        "expected_terms": [
            "Brasília",
            "Brasilia",
        ],
    },

    {
        "id": "FS_03",
        "category": "few_shot",
        "prompt": (
            "2 + 3 -> 5\n"
            "4 + 6 -> 10\n"
            "7 + 8 ->"
        ),
        "expected_terms": ["15"],
    },

    {
        "id": "FS_04",
        "category": "few_shot",
        "prompt": (
            "cat -> animal\n"
            "rose -> plant\n"
            "dog ->"
        ),
        "expected_terms": ["animal"],
    },


    # --------------------------------------------------------
    # SCIENCE / COMPUTATIONAL MODELING
    # --------------------------------------------------------

    {
        "id": "SCI_01",
        "category": "science",
        "prompt": (
            "In computational modeling, a simulation is"
        ),
        "expected_terms": [],
    },

    {
        "id": "SCI_02",
        "category": "science",
        "prompt": (
            "A neural network learns by"
        ),
        "expected_terms": [],
    },

    {
        "id": "SCI_03",
        "category": "science",
        "prompt": (
            "The purpose of numerical simulation is"
        ),
        "expected_terms": [],
    },


    # --------------------------------------------------------
    # OPEN MULTILINGUAL GENERATION
    # --------------------------------------------------------

    {
        "id": "OPEN_EN",
        "category": "open_generation",
        "prompt": (
            "Artificial intelligence can be useful because"
        ),
        "expected_terms": [],
    },

    {
        "id": "OPEN_PT",
        "category": "open_generation",
        "prompt": (
            "A ciência aberta é importante porque"
        ),
        "expected_terms": [],
    },

    {
        "id": "OPEN_ES",
        "category": "open_generation",
        "prompt": (
            "La investigación científica es importante porque"
        ),
        "expected_terms": [],
    },
]


# ============================================================
# 4. MULTIPLE-CHOICE TESTS
#
# We compare conditional log-probability of each completion.
#
# IMPORTANT:
# Scores are normalized by the number of completion tokens.
# This avoids systematically favoring shorter alternatives.
# ============================================================

MC_TESTS = [

    {
        "id": "MC_01",
        "category": "mc_factual",
        "prompt": "The capital of France is",
        "choices": [
            " Paris",
            " Berlin",
            " Madrid",
            " Rome",
        ],
        "correct": " Paris",
    },

    {
        "id": "MC_02",
        "category": "mc_factual",
        "prompt": "A capital do Brasil é",
        "choices": [
            " Brasília",
            " Lisboa",
            " Buenos Aires",
            " São Paulo",
        ],
        "correct": " Brasília",
    },

    {
        "id": "MC_03",
        "category": "mc_factual",
        "prompt": "La capital de España es",
        "choices": [
            " Madrid",
            " Barcelona",
            " Lisboa",
            " Roma",
        ],
        "correct": " Madrid",
    },

    {
        "id": "MC_04",
        "category": "mc_factual",
        "prompt": (
            "The largest planet in the Solar System is"
        ),
        "choices": [
            " Jupiter",
            " Earth",
            " Mars",
            " Venus",
        ],
        "correct": " Jupiter",
    },

    {
        "id": "MC_05",
        "category": "mc_math",
        "prompt": "2 + 2 =",
        "choices": [
            " 4",
            " 3",
            " 5",
            " 2",
        ],
        "correct": " 4",
    },

    {
        "id": "MC_06",
        "category": "mc_semantic",
        "prompt": (
            "Bird is to sky as fish is to"
        ),
        "choices": [
            " water",
            " fire",
            " stone",
            " tree",
        ],
        "correct": " water",
    },

    {
        "id": "MC_07",
        "category": "mc_math",
        "prompt": "10 * 5 =",
        "choices": [
            " 50",
            " 15",
            " 5",
            " 100",
        ],
        "correct": " 50",
    },

    {
        "id": "MC_08",
        "category": "mc_math",
        "prompt": (
            "The square root of 81 is"
        ),
        "choices": [
            " 9",
            " 8",
            " 10",
            " 81",
        ],
        "correct": " 9",
    },
]


# ============================================================
# 5. UTILITIES
# ============================================================

def normalize_text(text):

    text = text.lower()

    text = (
        text.replace("á", "a")
            .replace("à", "a")
            .replace("â", "a")
            .replace("ã", "a")
            .replace("é", "e")
            .replace("ê", "e")
            .replace("í", "i")
            .replace("ó", "o")
            .replace("ô", "o")
            .replace("õ", "o")
            .replace("ú", "u")
            .replace("ü", "u")
            .replace("ç", "c")
    )

    return text


def expected_match(
    generated_text,
    expected_terms,
):

    if not expected_terms:

        return None

    normalized_generated = normalize_text(
        generated_text
    )

    matches = []

    for term in expected_terms:

        normalized_term = normalize_text(
            term
        )

        if normalized_term in normalized_generated:

            matches.append(term)

    return {
        "matched": len(matches) > 0,
        "matches": matches,
    }


def repetition_metrics(text):

    words = re.findall(
        r"\b[\wÀ-ÿ]+\b",
        text.lower(),
    )

    if len(words) < 2:

        return {
            "words": len(words),
            "unique_word_ratio": 1.0,
            "repeated_bigram_ratio": 0.0,
        }

    unique_word_ratio = (
        len(set(words))
        / len(words)
    )

    bigrams = [
        (
            words[i],
            words[i + 1],
        )

        for i in range(
            len(words) - 1
        )
    ]

    if not bigrams:

        repeated_bigram_ratio = 0.0

    else:

        unique_bigrams = len(
            set(bigrams)
        )

        repeated_bigram_ratio = (
            1.0
            - (
                unique_bigrams
                / len(bigrams)
            )
        )

    return {
        "words": len(words),
        "unique_word_ratio":
            unique_word_ratio,
        "repeated_bigram_ratio":
            repeated_bigram_ratio,
    }


# ============================================================
# 6. LOAD TOKENIZER
# ============================================================

print("=" * 78)
print("MAIA LITE - CAPABILITY BENCHMARK")
print("106K vs CONTROLLED 130K")
print("=" * 78)

print()

print(
    f"Device:  {DEVICE}"
)

if torch.cuda.is_available():

    print(
        f"GPU:     "
        f"{torch.cuda.get_device_name(0)}"
    )

print(
    f"PyTorch: {torch.__version__}"
)

print()


for model_info in MODELS:

    if not os.path.isdir(
        model_info["path"]
    ):

        raise RuntimeError(
            "Checkpoint not found:\n"
            f"{model_info['path']}"
        )


tokenizer = GPT2TokenizerFast.from_pretrained(
    TOKENIZER_DIR,
    local_files_only=True,
)


if tokenizer.pad_token is None:

    tokenizer.pad_token = (
        tokenizer.eos_token
    )


print(
    f"Vocabulary: "
    f"{tokenizer.vocab_size:,}"
)

print(
    f"EOS:        "
    f"{tokenizer.eos_token_id}"
)

print(
    f"PAD:        "
    f"{tokenizer.pad_token_id}"
)


# ============================================================
# 7. GENERATION
# ============================================================

def generate_text(
    model,
    prompt,
):

    encoded = tokenizer(
        prompt,
        return_tensors="pt",
        add_special_tokens=False,
    )


    input_ids = encoded[
        "input_ids"
    ].to(
        DEVICE
    )


    attention_mask = encoded[
        "attention_mask"
    ].to(
        DEVICE
    )


    prompt_length = (
        input_ids.shape[1]
    )


    with torch.inference_mode():

        output_ids = model.generate(

            input_ids=input_ids,

            attention_mask=attention_mask,

            max_new_tokens=MAX_NEW_TOKENS,

            do_sample=False,

            num_beams=1,

            repetition_penalty=1.0,

            no_repeat_ngram_size=0,

            pad_token_id=tokenizer.pad_token_id,

            eos_token_id=tokenizer.eos_token_id,
        )


    generated_ids = output_ids[
        0,
        prompt_length:
    ]


    generated_text = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    )


    return generated_text


# ============================================================
# 8. CONDITIONAL LOG-PROBABILITY
# ============================================================

def completion_log_probability(
    model,
    prompt,
    completion,
):

    prompt_ids = tokenizer.encode(
        prompt,
        add_special_tokens=False,
    )

    completion_ids = tokenizer.encode(
        completion,
        add_special_tokens=False,
    )


    if len(completion_ids) == 0:

        raise RuntimeError(
            "Empty completion."
        )


    full_ids = (
        prompt_ids
        + completion_ids
    )


    input_ids = torch.tensor(
        [full_ids],
        dtype=torch.long,
        device=DEVICE,
    )


    with torch.inference_mode():

        outputs = model(
            input_ids=input_ids
        )


        logits = outputs.logits


    log_probs = F.log_softmax(
        logits.float(),
        dim=-1,
    )


    token_log_probs = []


    # Token at position i is predicted
    # by logits at position i - 1.

    completion_start = len(
        prompt_ids
    )


    for token_position in range(
        completion_start,
        len(full_ids),
    ):

        predicted_from = (
            token_position - 1
        )

        target_token = (
            full_ids[token_position]
        )


        lp = log_probs[
            0,
            predicted_from,
            target_token,
        ].item()


        token_log_probs.append(
            lp
        )


    total_log_probability = sum(
        token_log_probs
    )


    mean_log_probability = (
        total_log_probability
        / len(token_log_probs)
    )


    return {
        "completion_tokens":
            len(completion_ids),

        "total_log_probability":
            total_log_probability,

        "mean_log_probability":
            mean_log_probability,

        "per_token_log_probabilities":
            token_log_probs,
    }


# ============================================================
# 9. RUN ONE MODEL
# ============================================================

def benchmark_model(
    model_info,
):

    name = model_info["name"]

    path = model_info["path"]


    print()
    print("=" * 78)
    print(
        f"LOADING {name}"
    )
    print("=" * 78)

    print(
        path
    )


    model = GPT2LMHeadModel.from_pretrained(

        path,

        local_files_only=True,

        torch_dtype=DTYPE,
    )


    model.to(
        DEVICE
    )

    model.eval()

    model.config.use_cache = True


    generation_results = []


    # --------------------------------------------------------
    # Generation tests
    # --------------------------------------------------------

    print()
    print("-" * 78)
    print("GENERATION TESTS")
    print("-" * 78)


    for index, test in enumerate(
        GENERATION_TESTS,
        start=1,
    ):

        generated = generate_text(
            model,
            test["prompt"],
        )


        expected = expected_match(
            generated,
            test["expected_terms"],
        )


        repetition = repetition_metrics(
            generated
        )


        result = {
            "id": test["id"],
            "category": test["category"],
            "prompt": test["prompt"],
            "generated": generated,
            "expected_terms":
                test["expected_terms"],
            "expected_match":
                expected,
            "repetition":
                repetition,
        }


        generation_results.append(
            result
        )


        print()
        print(
            f"[{index:02d}/"
            f"{len(GENERATION_TESTS):02d}] "
            f"{test['id']}"
        )

        print(
            f"Prompt: {test['prompt']}"
        )

        print(
            f"Output: {generated}"
        )

        if expected is not None:

            print(
                "Expected match: "
                f"{expected['matched']}"
            )

        print(
            "Repeated bigram ratio: "
            f"{repetition['repeated_bigram_ratio']:.4f}"
        )


    # --------------------------------------------------------
    # Multiple choice
    # --------------------------------------------------------

    print()
    print("-" * 78)
    print("MULTIPLE-CHOICE LOG-PROBABILITY TESTS")
    print("-" * 78)


    mc_results = []


    for test in MC_TESTS:

        choice_results = []


        for choice in test["choices"]:

            score = (
                completion_log_probability(
                    model,
                    test["prompt"],
                    choice,
                )
            )


            choice_results.append({
                "choice": choice,
                **score,
            })


        # Higher mean log probability
        # is better.

        ranked = sorted(

            choice_results,

            key=lambda item:
                item[
                    "mean_log_probability"
                ],

            reverse=True,
        )


        predicted = ranked[0][
            "choice"
        ]


        correct = (
            predicted
            == test["correct"]
        )


        mc_result = {

            "id": test["id"],

            "category":
                test["category"],

            "prompt":
                test["prompt"],

            "correct_choice":
                test["correct"],

            "predicted_choice":
                predicted,

            "correct":
                correct,

            "choices":
                ranked,
        }


        mc_results.append(
            mc_result
        )


        print()
        print(
            f"{test['id']} | "
            f"{'CORRECT' if correct else 'WRONG'}"
        )

        print(
            f"Prompt: "
            f"{test['prompt']}"
        )

        print(
            f"Correct:   "
            f"{test['correct']}"
        )

        print(
            f"Predicted: "
            f"{predicted}"
        )


        for choice in ranked:

            print(
                f"  "
                f"{choice['choice']!r:<20} "
                f"{choice['mean_log_probability']:.6f}"
            )


    # --------------------------------------------------------
    # Summary metrics
    # --------------------------------------------------------

    scored_generation = [

        result

        for result in generation_results

        if result[
            "expected_match"
        ] is not None
    ]


    generation_correct = sum(

        1

        for result in scored_generation

        if result[
            "expected_match"
        ][
            "matched"
        ]
    )


    generation_accuracy = (

        generation_correct
        / len(scored_generation)

        if scored_generation

        else None
    )


    mc_correct = sum(

        1

        for result in mc_results

        if result["correct"]
    )


    mc_accuracy = (
        mc_correct
        / len(mc_results)
    )


    repeated_bigram_mean = (

        sum(
            result[
                "repetition"
            ][
                "repeated_bigram_ratio"
            ]

            for result
            in generation_results
        )

        / len(
            generation_results
        )
    )


    unique_word_mean = (

        sum(
            result[
                "repetition"
            ][
                "unique_word_ratio"
            ]

            for result
            in generation_results
        )

        / len(
            generation_results
        )
    )


    summary = {

        "generation_scored_tests":
            len(scored_generation),

        "generation_expected_matches":
            generation_correct,

        "generation_expected_match_rate":
            generation_accuracy,

        "mc_tests":
            len(mc_results),

        "mc_correct":
            mc_correct,

        "mc_accuracy":
            mc_accuracy,

        "mean_repeated_bigram_ratio":
            repeated_bigram_mean,

        "mean_unique_word_ratio":
            unique_word_mean,
    }


    result = {

        "model":
            name,

        "equivalent_step":
            model_info[
                "equivalent_step"
            ],

        "path":
            path,

        "summary":
            summary,

        "generation":
            generation_results,

        "multiple_choice":
            mc_results,
    }


    del model

    gc.collect()

    if torch.cuda.is_available():

        torch.cuda.empty_cache()


    return result


# ============================================================
# 10. RUN BENCHMARK
# ============================================================

start_time = time.time()

all_results = []


for model_info in MODELS:

    result = benchmark_model(
        model_info
    )

    all_results.append(
        result
    )


# ============================================================
# 11. PRINT COMPARATIVE SUMMARY
# ============================================================

print()
print("=" * 78)
print("COMPARATIVE SUMMARY")
print("=" * 78)

print()

print(
    f"{'Model':<24}"
    f"{'Gen match':>12}"
    f"{'MC':>10}"
    f"{'Rep.bigram':>14}"
    f"{'Unique':>12}"
)

print(
    "-" * 72
)


for result in all_results:

    summary = result[
        "summary"
    ]


    print(

        f"{result['model']:<24}"

        f"{summary['generation_expected_match_rate']:>12.4f}"

        f"{summary['mc_accuracy']:>10.4f}"

        f"{summary['mean_repeated_bigram_ratio']:>14.4f}"

        f"{summary['mean_unique_word_ratio']:>12.4f}"
    )


# ============================================================
# 12. SIDE-BY-SIDE GENERATION
# ============================================================

print()
print("=" * 78)
print("SIDE-BY-SIDE GENERATION")
print("=" * 78)


base_generation = {
    item["id"]: item
    for item
    in all_results[0]["generation"]
}

new_generation = {
    item["id"]: item
    for item
    in all_results[1]["generation"]
}


for test in GENERATION_TESTS:

    test_id = test["id"]


    print()
    print("-" * 78)

    print(
        test_id
    )

    print(
        f"PROMPT:\n"
        f"{test['prompt']}"
    )

    print()

    print(
        "106K:"
    )

    print(
        base_generation[
            test_id
        ][
            "generated"
        ]
    )

    print()

    print(
        "130K:"
    )

    print(
        new_generation[
            test_id
        ][
            "generated"
        ]
    )


# ============================================================
# 13. SAVE REPORT
# ============================================================

os.makedirs(
    DIAGNOSTICS_DIR,
    exist_ok=True,
)


report = {

    "benchmark":
        "Maia Lite capability 106K vs controlled 130K",

    "generation_configuration": {

        "max_new_tokens":
            MAX_NEW_TOKENS,

        "do_sample":
            False,

        "num_beams":
            1,

        "repetition_penalty":
            1.0,

        "no_repeat_ngram_size":
            0,
    },

    "models":
        all_results,

    "elapsed_seconds":
        time.time() - start_time,
}


with open(

    OUTPUT_JSON,

    "w",

    encoding="utf-8",

) as f:

    json.dump(
        report,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 14. FINAL
# ============================================================

print()
print("=" * 78)
print("BENCHMARK COMPLETE")
print("=" * 78)

print()

print(
    "Saved to:"
)

print(
    OUTPUT_JSON
)

print()

print(
    "No training was performed."
)

print(
    "No model weights were modified."
)

==============================================================================
MAIA LITE - CAPABILITY BENCHMARK
106K vs CONTROLLED 130K
==============================================================================

Device:  cuda
GPU:     NVIDIA A100-SXM4-80GB
PyTorch: 2.11.0+cu128

Vocabulary: 50,257
EOS:        2
PAD:        1

==============================================================================
LOADING base-106000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_pretreino/checkpoint-106000

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
GENERATION TESTS
------------------------------------------------------------------------------

[01/32] EN_FACT_01
Prompt: The capital of France is
Output:  the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel of the Channel of the Sable.

The capital is located on the island of Brittany, on the southern shore of the Channel of the Sable. The island is the largest island in the Channel of the Sable, and is
Expected match: False
Repeated bigram ratio: 0.4355

[02/32] EN_FACT_02
Prompt: The largest planet in the Solar System is
Output:  the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the
Expected match: False
Repeated bigram ratio: 0.8000

[03/32] EN_FACT_03
Prompt: DNA stands for
Output:  the DNA of the DNA of the organism.

DNA may also refer to:

Biology
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene

Computing
 DNA (computing), a computer program that uses a computer to create a computer


Expected match: False
Repeated bigram ratio: 0.3922

[04/32] PT_FACT_01
Prompt: A capital do Brasil é
Output:  a capital do estado do Brasil, sendo também a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo, fundada em 1545, foi fundada por Pedro Álvares Cabral, que se tornou o primeiro governador do Rio Grande do Sul.

A cidade foi fundada em 1545, por Pedro Álvares Cabral, que se tornou o
Expected match: False
Repeated bigram ratio: 0.3279

[05/32] PT_FACT_02
Prompt: O maior planeta do Sistema Solar é
Output:  o planeta que orbita o planeta Terra, com uma órbita de aproximadamente  km de diâmetro. O planeta tem uma massa de cerca de  kg e uma massa de aproximadamente  kg.

O planeta foi descoberto em 16 de agosto de 1859 por Johann Palisa.

O planeta foi nomeado em homenagem ao planeta Júpiter, o planeta mais brilhante do Sistema Solar.

Sistema Solar
Plan
Expected match: True
Repeated bigram ratio: 0.1639

[06/32] PT_FACT_03
Prompt: A água congela, ao nível do mar, a
Output:  água congela, é um dos principais reservatórios de água subterrânea do mundo. A água congela é composta por água subterrânea, água subterrânea e água subterrânea. A água congela é composta por água subterrânea, água subterrânea e água subterrânea.

A água congela é composta por água subterrânea, água subterrânea e água subterrânea. A água congela
Expected match: False
Repeated bigram ratio: 0.6226

[07/32] ES_FACT_01
Prompt: La capital de España es
Output:  la ciudad más poblada de la República de España, con una población de  habitantes (2022). Es la capital de la provincia homónima, en la región de Castilla-La Mancha.

La ciudad se encuentra en el centro de la provincia, en la región de Castilla-La Mancha, a orillas del río Guadiana, a unos  al oeste de Madrid. Es la capital de la provincia homónima,
Expected match: True
Repeated bigram ratio: 0.2540

[08/32] ES_FACT_02
Prompt: El planeta más grande del Sistema Solar es
Output:  el planeta más grande del sistema solar, con una superficie de aproximadamente  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km².

El
Expected match: False
Repeated bigram ratio: 0.7049

[09/32] MATH_01
Prompt: 2 + 2 =
Output:  4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2
Expected match: True
Repeated bigram ratio: 0.8857

[10/32] MATH_02
Prompt: 10 * 5 =
Output:  5

4 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 *
Expected match: False
Repeated bigram ratio: 0.8929

[11/32] MATH_03
Prompt: The square root of 81 is
Output:  a major component of the median nerve of the median nerve. It is a branch of the median nerve.

Anatomy

Origin
The square root of 81 is a branch of the median nerve of median nerve. It is a branch of the median nerve of median nerve.

Course and relations
It is distributed to the median nerve and the median nerve.

Expected match: False
Repeated bigram ratio: 0.5000

[12/32] MATH_04
Prompt: If x + 3 = 7, then x =
Output:  7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x =
Expected match: False
Repeated bigram ratio: 0.9362

[13/32] SEM_01
Prompt: Paris is to France as Madrid is to
Output:  Spain.

Paris may also refer to:

Places

United States
 Paris, Texas, a city in the United States
 Paris, Texas, a city in the United States
 Paris, Texas, a city in the United States
 Paris, Texas, a city in the United States
 Paris, Texas, a city in the United States
 Paris, Texas, a city in
Expected match: True
Repeated bigram ratio: 0.7170

[14/32] SEM_02
Prompt: Bird is to sky as fish is to
Output:  be found in the sky.

Bird may also refer to:

Places

United States
 Bird, Alabama, a city in Alabama
 Bird, Illinois, a city in Illinois
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri
Expected match: False
Repeated bigram ratio: 0.4600

[15/32] SEM_03
Prompt: A dog is an animal. A rose is a
Output:  type of rose.

A dog is a type of rose in the United States. It is a type of rose in the United States.

The word "dog" is a corruption of the word "dog" (which is a word of the word "dog" in the English language).

The word "dog" is a corruption of the word "dog" (which is
Expected match: False
Repeated bigram ratio: 0.5263

[16/32] TRANS_01
Prompt: Translate from Portuguese to English:
O céu é azul.
English:
Output:  "O céu é azul"

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu
Expected match: False
Repeated bigram ratio: 0.9111

[17/32] TRANS_02
Prompt: Translate from English to Portuguese:
The cat is sleeping.
Português:
Output:
Ou seja, o mar é o mar que se encontra no mar.
O mar é o mar que se encontra no mar.
O mar é o mar que se encontra no mar.
O mar é o mar que se encontra no mar.
O mar é o mar que se encontra no mar.
O mar é o mar que se encontra no mar.
O mar é
Expected match: False
Repeated bigram ratio: 0.8281

[18/32] TRANS_03
Prompt: Translate from Spanish to English:
La computadora es rápida.
English:
Output:  The Computer, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the Spanish language, the
Expected match: False
Repeated bigram ratio: 0.9153

[19/32] INST_01
Prompt: Answer with only one word.
What color is snow?
Answer:
Output:  A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer:
Expected match: False
Repeated bigram ratio: 0.8710

[20/32] INST_02
Prompt: Complete the sentence with a short answer:
Water is essential for
Output:  the sentence, and is the first word in the sentence.

The word "complete" is used in the sentence "to be free", "to be free", "to be free", "to be free", "to be free", "to be free", "to be free", "to be free", "to be free", "to be free", "to be free",
Expected match: False
Repeated bigram ratio: 0.6400

[21/32] PY_01
Prompt: Python code to print Hello World:

Output:
The Hello World is a computer program that was created by the company that created the Hello World. The program is designed to be easy to read and write, and is designed to be easy to read. The program is designed to be easy to read, and is designed to be easy to read.

The Hello World program is designed to be easy to read, and is designed
Expected match: True
Repeated bigram ratio: 0.5522

[22/32] PY_02
Prompt: Write a Python function called add that returns the sum of a and b:

Output:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the
Expected match: False
Repeated bigram ratio: 0.9231

[23/32] FS_01
Prompt: Germany -> Berlin
Italy -> Rome
France ->
Output:  Paris
Portugal -> Lisboa
Portugal -> Lisboa

Desambiguação
Desambiguações de topônimos
Desambiguações de antropônimos
Desambiguações de topônimos
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas

Expected match: True
Repeated bigram ratio: 0.6829

[24/32] FS_02
Prompt: Portugal -> Lisboa
Argentina -> Buenos Aires
Brasil ->
Output:  Rio Grande do Sul
Portugal (distrito)
Portugal (distrito)
Portugal (distrito)
Portugal (distrito)
Portugal (distrito)
Portugal (distrito)
Portugal (distrito)

Desambiguações de topônimos
Desambiguações de topônimos
Desambiguações de geografia
Desambiguações de topônimos
Desambiguações de topônimos
Desambiguações de geografia
Desambiguações de topônimos
Desambiguações de topônimos

Expected match: False
Repeated bigram ratio: 0.7073

[25/32] FS_03
Prompt: 2 + 3 -> 5
4 + 6 -> 10
7 + 8 ->
Output:  10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 +
Expected match: False
Repeated bigram ratio: 0.9744

[26/32] FS_04
Prompt: cat -> animal
rose -> plant
dog ->
Output:  animal

Desambiguação
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal
Expected match: True
Repeated bigram ratio: 0.8718

[27/32] SCI_01
Prompt: In computational modeling, a simulation is
Output:  a method that is used to simulate the behavior of a computer program.

A simulation is a simulation that is performed by a computer program. The simulation is performed by a computer program. The simulation is performed by a computer program.

The simulation is performed by a computer program. The simulation is performed by a computer program. The simulation is performed by a computer program. The simulation is
Repeated bigram ratio: 0.6716

[28/32] SCI_02
Prompt: A neural network learns by
Output:  means of a computer program, usually in the context of a computer program, but also in the context of a computer program.

The term is also used in the context of computer science, where it is used to describe the process of defining a neural network.

The term is also used in the context of computer science, where it is used to describe the process of defining a neural network
Repeated bigram ratio: 0.5072

[29/32] SCI_03
Prompt: The purpose of numerical simulation is
Output:  to determine the numerical solution of a numerical problem.

The numerical solution of a numerical problem is the numerical solution of a numerical problem. The numerical solution is then the numerical solution of the numerical problem.

The numerical solution is then the numerical solution of the numerical problem.

The numerical solution is then the numerical solution of the numerical problem.

The numerical solution is then the numerical
Repeated bigram ratio: 0.7727

[30/32] OPEN_EN
Prompt: Artificial intelligence can be useful because
Output:  it is a method of creating artificial intelligence.

Artificial intelligence can be used to create artificial intelligence, or to create artificial intelligence.

Artificial intelligence can be used to create artificial intelligence, or to create artificial intelligence.

Artificial intelligence can be used to create artificial intelligence, or to create artificial intelligence.

Artificial intelligence can be used to create artificial intelligence, or
Repeated bigram ratio: 0.7288

[31/32] OPEN_PT
Prompt: A ciência aberta é importante porque
Output:  a ciência que se ocupa de estudar a natureza é uma das áreas mais importantes da ciência.

A ciência aberta é uma das áreas mais importantes da ciência moderna, pois é uma área de estudo que se dedica à investigação de problemas de natureza geral, como a geografia, geografia, geologia, geografia, geografia, geografia, etc.

A ciência aberta é uma das áreas mais importantes da ciência
Repeated bigram ratio: 0.3438

[32/32] OPEN_ES
Prompt: La investigación científica es importante porque
Output:  se trata de una ciencia que se basa en la observación de las propiedades físicas de los objetos y en la observación de las propiedades físicas de los objetos.

La investigación científica se basa en la observación de las propiedades físicas de los objetos y en la observación de las propiedades físicas de los objetos.

La investigación científica se basa en la observación de las propiedades físicas de los objetos y en la observación
Repeated bigram ratio: 0.6849

------------------------------------------------------------------------------
MULTIPLE-CHOICE LOG-PROBABILITY TESTS
------------------------------------------------------------------------------

MC_01 | CORRECT
Prompt: The capital of France is
Correct:    Paris
Predicted:  Paris
  ' Paris'             -4.813068
  ' Rome'              -9.094317
  ' Madrid'            -10.563067
  ' Berlin'            -10.578692

MC_02 | WRONG
Prompt: A capital do Brasil é
Correct:    Brasília
Predicted:  São Paulo
  ' São Paulo'         -4.155106
  ' Brasília'          -6.316960
  ' Buenos Aires'      -6.400678
  ' Lisboa'            -11.863835

MC_03 | CORRECT
Prompt: La capital de España es
Correct:    Madrid
Predicted:  Madrid
  ' Madrid'            -4.989043
  ' Barcelona'         -6.114043
  ' Roma'              -8.520293
  ' Lisboa'            -9.051543

MC_04 | WRONG
Prompt: The largest planet in the Solar System is
Correct:    Jupiter
Predicted:  Earth
  ' Earth'             -3.583138
  ' Mars'              -3.708138
  ' Venus'             -4.833138
  ' Jupiter'           -5.020638

MC_05 | CORRECT
Prompt: 2 + 2 =
Correct:    4
Predicted:  4
  ' 4'                 -2.088778
  ' 3'                 -2.276278
  ' 2'                 -2.838778
  ' 5'                 -2.963778

MC_06 | WRONG
Prompt: Bird is to sky as fish is to
Correct:    water
Predicted:  fire
  ' fire'              -6.318107
  ' water'             -6.536857
  ' stone'             -7.349357
  ' tree'              -8.318107

MC_07 | WRONG
Prompt: 10 * 5 =
Correct:    50
Predicted:  5
  ' 5'                 -1.866615
  ' 100'               -4.429115
  ' 50'                -4.491615
  ' 15'                -5.679115

MC_08 | WRONG
Prompt: The square root of 81 is
Correct:    9
Predicted:  8
  ' 8'                 -9.325698
  ' 10'                -10.294448
  ' 9'                 -10.575698
  ' 81'                -12.278823

==============================================================================
LOADING controlled-130000
==============================================================================
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/maia_lite_equivalent_130k

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

------------------------------------------------------------------------------
GENERATION TESTS
------------------------------------------------------------------------------

[01/32] EN_FACT_01
Prompt: The capital of France is
Output:  the capital of the French overseas department of ultramarine. The capital of France is the capital of the department and the largest city in the French overseas department.

The capital of France is located in the centre of the island of Saint-Denis, in the department of Brittany. The capital of the department is the city of Paris.

History

The capital of the department
Expected match: True
Repeated bigram ratio: 0.4127

[02/32] EN_FACT_02
Prompt: The largest planet in the Solar System is
Output:  the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in
Expected match: False
Repeated bigram ratio: 0.8143

[03/32] EN_FACT_03
Prompt: DNA stands for
Output:  the DNA of the DNA of the organism.

DNA may also refer to:

Biology
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene

Computing
 DNA (computing), a
Expected match: False
Repeated bigram ratio: 0.5306

[04/32] PT_FACT_01
Prompt: A capital do Brasil é
Output:  a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo foi fundada em 1584, por ordem do governador-geral do Brasil, Dom Pedro de Sousa.

A cidade foi fundada em 1584, por ordem do governador-geral do Brasil, Dom Pedro de Sousa.

Período republicano
A cidade foi
Expected match: False
Repeated bigram ratio: 0.3214

[05/32] PT_FACT_02
Prompt: O maior planeta do Sistema Solar é
Output:  o planeta que orbita o planeta Terra, o planeta mais próximo do sistema solar. O planeta Terra é o planeta mais próximo do sistema solar, e o planeta mais próximo do sistema solar. O planeta Terra é o planeta mais próximo do sistema solar, e o planeta mais próximo do sistema solar.

O planeta Terra é o planeta mais próximo do sistema solar, e o planeta mais próximo do sistema
Expected match: False
Repeated bigram ratio: 0.7681

[06/32] PT_FACT_03
Prompt: A água congela, ao nível do mar, a
Output:  qual é usada para a produção de água, é um dos principais recursos hídricos do mundo.

A água congela é utilizada para a produção de água subterrânea, para a produção de água subterrânea, para a produção de água subterrânea, para a produção de água subterrânea, para a produção de água subterrânea, para a produção de água subterrânea, para a produção de água
Expected match: False
Repeated bigram ratio: 0.6230

[07/32] ES_FACT_01
Prompt: La capital de España es
Output:  la ciudad más poblada de la República de España, con una población de  habitantes (2022). La ciudad se encuentra en el centro de la provincia de Madrid, en la región de Castilla-La Mancha.

La ciudad es la capital de la provincia de Madrid, y la ciudad más poblada de la provincia de Madrid. La ciudad es la capital de la provincia de Madrid, y la ciudad más
Expected match: True
Repeated bigram ratio: 0.4179

[08/32] ES_FACT_02
Prompt: El planeta más grande del Sistema Solar es
Output:  el planeta más grande del sistema solar, con una superficie de aproximadamente  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km².

El planeta más grande del sistema solar es el planeta Tierra, con una superficie de  km². El
Expected match: False
Repeated bigram ratio: 0.7049

[09/32] MATH_01
Prompt: 2 + 2 =
Output:  4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2 = 4:1

2 + 2
Expected match: True
Repeated bigram ratio: 0.8857

[10/32] MATH_02
Prompt: 10 * 5 =
Output:  5

4 * 5 = 5

5 * 5 = 5

5 * 5 = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 * = 5

5 *
Expected match: False
Repeated bigram ratio: 0.8929

[11/32] MATH_03
Prompt: The square root of 81 is
Output:  a square root of the genus Platyprocta. It is a genus of flowering plants in the family Platyproctaceae.

The genus name is derived from the Latin word Platyprocta, meaning "small root".

The genus name is derived from the Latin word Platyprocta, meaning "small root".

Species
The genus contains five species:
Expected match: False
Repeated bigram ratio: 0.2857

[12/32] MATH_04
Prompt: If x + 3 = 7, then x =
Output:  7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x = 7, then x =
Expected match: False
Repeated bigram ratio: 0.9362

[13/32] SEM_01
Prompt: Paris is to France as Madrid is to
Output:  Spain.

Paris may also refer to:

Places

France
 Paris, a commune in the department of Aisne
 Paris, a commune in the department of Aisne
 Paris, a commune in the department of Aisne
 Paris, a commune in the department of Aisne
 Paris, a commune in the department of Aisne
 Paris, a
Expected match: True
Repeated bigram ratio: 0.6735

[14/32] SEM_02
Prompt: Bird is to sky as fish is to
Output:  be found in the sky.

Bird may also refer to:

Places

United States
 Bird, Alabama, a city in Alabama
 Bird, Illinois, a city in Illinois
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri, a city in Missouri
 Bird, Missouri
Expected match: False
Repeated bigram ratio: 0.4600

[15/32] SEM_03
Prompt: A dog is an animal. A rose is a
Output:  type of rose.

A dog is a type of rose in the United States.

A dog is a type of rose in the United States.

A dog is a type of rose in the United States.

A dog is a type of rose in the United States.

A dog is a type of rose in the United States.

A dog is a
Expected match: False
Repeated bigram ratio: 0.8033

[16/32] TRANS_01
Prompt: Translate from Portuguese to English:
O céu é azul.
English:
Output:  "O céu é azul".

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu é azul.

O céu
Expected match: False
Repeated bigram ratio: 0.9111

[17/32] TRANS_02
Prompt: Translate from English to Portuguese:
The cat is sleeping.
Português:
Output:
Ou seja, o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é o mar é
Expected match: False
Repeated bigram ratio: 0.9342

[18/32] TRANS_03
Prompt: Translate from Spanish to English:
La computadora es rápida.
English:
Output:  The Spanish word for "computer"

El primer libro de texto español de la editorial Espasa, La máquina de escribir, fue publicado en el año de 1904.

En el año de 1905, el libro fue publicado por primera vez en España, en el diario El País.

En el año de 1907, el libro fue publicado en el diario El País.

En
Expected match: False
Repeated bigram ratio: 0.2881

[19/32] INST_01
Prompt: Answer with only one word.
What color is snow?
Answer:
Output:  A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer: A snow sign?

Answer:
Expected match: False
Repeated bigram ratio: 0.8710

[20/32] INST_02
Prompt: Complete the sentence with a short answer:
Water is essential for
Output:  the sentence, and is essential for the sentence.

The sentence is written in the form of a sentence that is written in the form of a sentence that is written in the form of a sentence that is written in the form of a sentence that is written in the form of a sentence that is written in the form of a sentence that is written in the form of a sentence that is written in
Expected match: False
Repeated bigram ratio: 0.7733

[21/32] PY_01
Prompt: Python code to print Hello World:

Output:
The Hello World is a computer program that was created by the company in the early 1980s. The program was designed to be a tool for the Hello World program. The program was designed to be a tool for the Hello World program.

The Hello World program was designed to be a tool for the Hello World program. The Hello World program was designed to be
Expected match: True
Repeated bigram ratio: 0.5692

[22/32] PY_02
Prompt: Write a Python function called add that returns the sum of a and b:

Output:
The add is the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the sum of the
Expected match: False
Repeated bigram ratio: 0.9231

[23/32] FS_01
Prompt: Germany -> Berlin
Italy -> Rome
France ->
Output:  Paris
Portugal -> Lisboa
Portugal -> Lisboa
Portugal -> Lisboa
Portugal -> Lisboa
Portugal -> Lisboa
Portugal -> Lisboa
Portugal -> Lisboa
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal

Ver também

Desambiguação
Desambiguações de topônimos
Desambiguações de topônimos
Desambiguações de linguística
Desambiguações de topônimos
Desambiguações de linguística
Desambiguações de topônimos
Desambiguações
Expected match: True
Repeated bigram ratio: 0.7111

[24/32] FS_02
Prompt: Portugal -> Lisboa
Argentina -> Buenos Aires
Brasil ->
Output:  Rio Grande do Sul
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo
Portugal -> São Paulo

Expected match: False
Repeated bigram ratio: 0.8542

[25/32] FS_03
Prompt: 2 + 3 -> 5
4 + 6 -> 10
7 + 8 ->
Output:  10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 +
Expected match: False
Repeated bigram ratio: 0.9744

[26/32] FS_04
Prompt: cat -> animal
rose -> plant
dog ->
Output:  animal

Desambiguação
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal formatadas
!Desambiguações mal
Expected match: True
Repeated bigram ratio: 0.8718

[27/32] SCI_01
Prompt: In computational modeling, a simulation is
Output:  a method that is used to simulate the behavior of a computer program.

The simulation is a method that is used to simulate the behavior of a computer program. The simulation is a method that is used to simulate the behavior of a computer program.

The simulation is a method that is used to simulate the behavior of a computer program. The simulation is a method that is
Repeated bigram ratio: 0.7612

[28/32] SCI_02
Prompt: A neural network learns by
Output:  means of a computer program, and is used to help solve problems in computer science.

The neural network is a computer program that is designed to solve problems in computer science. It is used to solve problems in computer science, and is used to solve problems in computer science.

The neural network is used to solve problems in computer science, and is used to solve problems in computer science.
Repeated bigram ratio: 0.6029

[29/32] SCI_03
Prompt: The purpose of numerical simulation is
Output:  to determine the numerical solution of a problem.

The goal of numerical simulation is to determine the numerical solution of a problem, and to determine the numerical solution of a problem.

The goal of numerical simulation is to determine the numerical solution of a problem, and to determine the numerical solution of a problem.

The goal of numerical simulation is to determine the numerical solution of a problem,
Repeated bigram ratio: 0.7612

[30/32] OPEN_EN
Prompt: Artificial intelligence can be useful because
Output:  it is a method of creating artificial intelligence.

Artificial intelligence can be used to create artificial intelligence, or to create artificial intelligence.

History

The first artificial intelligence was invented by the French physicist Jean-Baptiste de La Vallée in the early 19th century. The first artificial intelligence was invented by the French physicist Jean-Baptiste de La Vallée in the early 19th century
Repeated bigram ratio: 0.4032

[31/32] OPEN_PT
Prompt: A ciência aberta é importante porque
Output:  a ciência aberta é uma ciência que não é restrita à comunidade científica.

A Ciência aberta é uma ciência que não é restrita à comunidade científica, mas que não é restrita à comunidade científica.

A Ciência aberta é uma ciência que não é restrita à comunidade científica, mas que não é restrita à comunidade científica.

A Ciência aberta é uma ciência que não é restrita à comunidade científica,
Repeated bigram ratio: 0.7761

[32/32] OPEN_ES
Prompt: La investigación científica es importante porque
Output:  se trata de una ciencia que se basa en la investigación científica, la investigación científica y la investigación científica.

La investigación científica es una rama de la ciencia que se dedica a la investigación de la naturaleza, la ciencia de la naturaleza y la ciencia de la naturaleza.

La investigación científica se basa en la investigación de la naturaleza, la ciencia de la naturaleza y la ciencia de la naturaleza.
Repeated bigram ratio: 0.5797

------------------------------------------------------------------------------
MULTIPLE-CHOICE LOG-PROBABILITY TESTS
------------------------------------------------------------------------------

MC_01 | CORRECT
Prompt: The capital of France is
Correct:    Paris
Predicted:  Paris
  ' Paris'             -4.411076
  ' Rome'              -9.129826
  ' Berlin'            -10.192326
  ' Madrid'            -10.223576

MC_02 | WRONG
Prompt: A capital do Brasil é
Correct:    Brasília
Predicted:  São Paulo
  ' São Paulo'         -3.815659
  ' Brasília'          -5.772517
  ' Buenos Aires'      -6.073775
  ' Lisboa'            -11.225642

MC_03 | CORRECT
Prompt: La capital de España es
Correct:    Madrid
Predicted:  Madrid
  ' Madrid'            -4.485029
  ' Barcelona'         -5.547529
  ' Roma'              -8.203779
  ' Lisboa'            -8.672529

MC_04 | WRONG
Prompt: The largest planet in the Solar System is
Correct:    Jupiter
Predicted:  Mars
  ' Mars'              -3.655885
  ' Earth'             -3.718385
  ' Jupiter'           -4.843385
  ' Venus'             -4.968385

MC_05 | CORRECT
Prompt: 2 + 2 =
Correct:    4
Predicted:  4
  ' 4'                 -2.006078
  ' 3'                 -2.131078
  ' 2'                 -2.506078
  ' 5'                 -2.881078

MC_06 | WRONG
Prompt: Bird is to sky as fish is to
Correct:    water
Predicted:  fire
  ' fire'              -6.190237
  ' water'             -6.346487
  ' stone'             -7.065237
  ' tree'              -8.127737

MC_07 | WRONG
Prompt: 10 * 5 =
Correct:    50
Predicted:  5
  ' 5'                 -1.860157
  ' 100'               -4.735157
  ' 50'                -4.922657
  ' 15'                -5.422657

MC_08 | WRONG
Prompt: The square root of 81 is
Correct:    9
Predicted:  8
  ' 8'                 -8.785762
  ' 10'                -9.754512
  ' 9'                 -9.973262
  ' 81'                -11.817012

==============================================================================
COMPARATIVE SUMMARY
==============================================================================

Model                      Gen match        MC    Rep.bigram      Unique
------------------------------------------------------------------------
base-106000                   0.2692    0.3750        0.6627      0.2381
controlled-130000             0.2692    0.3750        0.6905      0.2247

==============================================================================
SIDE-BY-SIDE GENERATION
==============================================================================

------------------------------------------------------------------------------
EN_FACT_01
PROMPT:
The capital of France is

106K:
 the capital of the French overseas department of Brittany. The capital is located in the centre of the island of Brittany, in the Channel of the Channel of the Sable.

The capital is located on the island of Brittany, on the southern shore of the Channel of the Sable. The island is the largest island in the Channel of the Sable, and is

130K:
 the capital of the French overseas department of ultramarine. The capital of France is the capital of the department and the largest city in the French overseas department.

The capital of France is located in the centre of the island of Saint-Denis, in the department of Brittany. The capital of the department is the city of Paris.

History

The capital of the department

------------------------------------------------------------------------------
EN_FACT_02
PROMPT:
The largest planet in the Solar System is

106K:
 the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the

130K:
 the Sun, which is the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in the Solar System. The Sun is the largest in the Solar System, and the largest in

------------------------------------------------------------------------------
EN_FACT_03
PROMPT:
DNA stands for

106K:
 the DNA of the DNA of the organism.

DNA may also refer to:

Biology
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene

Computing
 DNA (computing), a computer program that uses a computer to create a computer



130K:
 the DNA of the DNA of the organism.

DNA may also refer to:

Biology
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene
 DNA (genetics), the genetic code of a gene

Computing
 DNA (computing), a

------------------------------------------------------------------------------
PT_FACT_01
PROMPT:
A capital do Brasil é

106K:
 a capital do estado do Brasil, sendo também a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo, fundada em 1545, foi fundada por Pedro Álvares Cabral, que se tornou o primeiro governador do Rio Grande do Sul.

A cidade foi fundada em 1545, por Pedro Álvares Cabral, que se tornou o

130K:
 a capital do estado do Rio Grande do Sul.

História

Período colonial
A cidade de São Sebastião do Rio Pardo foi fundada em 1584, por ordem do governador-geral do Brasil, Dom Pedro de Sousa.

A cidade foi fundada em 1584, por ordem do governador-geral do Brasil, Dom Pedro de Sousa.

Período republicano
A cidade foi

------------------------------------------------------------------------------
PT_FACT_02
PROMPT:

In [ ]:
# ============================================================
# MAIA LITE - CORPUS V2
# DATASET AVAILABILITY / SCHEMA TEST
#
# PURPOSE:
#   - Verify that every planned dataset is accessible.
#   - Verify config names and splits.
#   - Inspect schemas and a few samples.
#   - DO NOT download/materialize the corpus yet.
#
# Safe to run on CPU.
# ============================================================

!pip -q install -U datasets huggingface_hub

from datasets import load_dataset
import traceback
import textwrap


# ============================================================
# PLANNED MAIA CORPUS V2
# ============================================================

DATASETS = [
    {
        "name": "FineWeb-Edu EN",
        "repo": "HuggingFaceFW/fineweb-edu",
        "config": "sample-10BT",
        "split": "train",
        "weight": 0.45,
        "text_field": "text",
    },

    {
        "name": "FineWeb2-HQ PT",
        "repo": "epfml/FineWeb2-HQ",
        "config": "por_Latn",
        "split": "train",
        "weight": 0.225,
        "text_field": "text",
    },

    {
        "name": "FineWeb2-HQ ES",
        "repo": "epfml/FineWeb2-HQ",
        "config": "spa_Latn",
        "split": "train",
        "weight": 0.225,
        "text_field": "text",
    },

    {
        "name": "OpenCoder FineWeb Code",
        "repo": "OpenCoder-LLM/opc-fineweb-code-corpus",
        "config": None,
        "split": "train",
        "weight": 0.05,
        "text_field": "text",
    },

    # Math and scientific/modeling sources will be finalized
    # after validating their schemas/licensing/format.
]


# ============================================================
# TEST FUNCTION
# ============================================================

def test_dataset(spec, samples=2):

    print("\n")
    print("=" * 78)
    print(spec["name"])
    print("=" * 78)

    print(f'Repository: {spec["repo"]}')
    print(f'Config:     {spec["config"]}')
    print(f'Split:      {spec["split"]}')
    print(f'Weight:     {spec["weight"]:.1%}')

    try:

        kwargs = {
            "path": spec["repo"],
            "split": spec["split"],
            "streaming": True,
        }

        if spec["config"] is not None:
            kwargs["name"] = spec["config"]

        ds = load_dataset(**kwargs)

        print("\nSTATUS: OK")
        print("Dataset type:", type(ds).__name__)

        # Streaming datasets expose feature information without
        # materializing the entire dataset.
        print("\nFeatures:")

        if ds.features is not None:
            for key, value in ds.features.items():
                print(f"  {key:25s} {value}")
        else:
            print("  <features unavailable before first sample>")

        print("\nSample inspection:")

        iterator = iter(ds)

        for i in range(samples):

            row = next(iterator)

            print("\n" + "-" * 78)
            print(f"SAMPLE {i + 1}")
            print("-" * 78)

            print("Fields:")
            print(list(row.keys()))

            text_field = spec["text_field"]

            if text_field not in row:
                print(
                    f"\nWARNING: expected text field "
                    f"'{text_field}' not found."
                )

                continue

            text = row[text_field]

            if text is None:
                print("<NULL TEXT>")
                continue

            text = str(text)

            print(f"\nText length: {len(text):,} characters")

            preview = text[:700].replace("\x00", "")

            print("\nPreview:")
            print(
                textwrap.indent(
                    preview,
                    "  "
                )
            )

        return True

    except Exception as e:

        print("\nSTATUS: FAILED")
        print("Exception:")
        print(type(e).__name__, str(e))

        print("\nTraceback:")
        traceback.print_exc(limit=2)

        return False


# ============================================================
# RUN TESTS
# ============================================================

results = {}

for spec in DATASETS:

    success = test_dataset(
        spec,
        samples=2
    )

    results[spec["name"]] = success


# ============================================================
# SUMMARY
# ============================================================

print("\n\n")
print("=" * 78)
print("MAIA CORPUS V2 - DATASET TEST SUMMARY")
print("=" * 78)

all_ok = True

for name, success in results.items():

    status = "OK" if success else "FAILED"

    print(f"{name:35s} {status}")

    if not success:
        all_ok = False


print("-" * 78)

if all_ok:

    print("CORE DATASETS AVAILABLE.")
    print("Ready for corpus materialization design.")

else:

    print("ONE OR MORE DATASETS FAILED.")
    print("Do NOT start corpus materialization yet.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 40.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 846.4/846.4 kB 60.9 MB/s eta 0:00:00


==============================================================================
FineWeb-Edu EN
==============================================================================
Repository: HuggingFaceFW/fineweb-edu
Config:     sample-10BT
Split:      train
Weight:     45.0%

README.md:   0%|          | 0.00/26.4k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/2410 [00:00<?, ?it/s]

STATUS: OK
Dataset type: IterableDataset

Features:
  text                      Value('string')
  id                        Value('string')
  dump                      Value('string')
  url                       Value('string')
  file_path                 Value('string')
  language                  Value('string')
  language_score            Value('float64')
  token_count               Value('int64')
  score                     Value('float64')
  int_score                 Value('int64')

Sample inspection:

------------------------------------------------------------------------------
SAMPLE 1
------------------------------------------------------------------------------
Fields:
['text', 'id', 'dump', 'url', 'file_path', 'language', 'language_score', 'token_count', 'score', 'int_score']

Text length: 3,665 characters

Preview:
  The Independent Jane
  For all the love, romance and scandal in Jane Austen’s books, what they are really about is freedom and independence. Independence of thought and the freedom to choose.
  Elizabeth’s refusal of Mr. Collins offer of marriage showed an independence seldom seen in heroines of the day. Her refusal of Mr. Darcy while triggered by anger showed a level of independence that left him shocked and stunned.
  The freedom she exhibited in finally accepting him in direct defiance of Lady Catherine and knowing her father would disapprove was unusual even for Austen. In her last book Anne Elliot is persuaded to refuse Captain Wentworth at Lady Russel’s insistence.
  Although Jane played by th

------------------------------------------------------------------------------
SAMPLE 2
------------------------------------------------------------------------------
Fields:
['text', 'id', 'dump', 'url', 'file_path', 'language', 'language_score', 'token_count', 'score', 'int_score']

Text length: 5,255 characters

Preview:
  Taking Play Seriously
  By ROBIN MARANTZ HENIG
  Published: February 17, 2008
  On a drizzly Tuesday night in late January, 200 people came out to hear a psychiatrist talk rhapsodically about play -- not just the intense, joyous play of children, but play for all people, at all ages, at all times. (All species too; the lecture featured touching photos of a polar bear and a husky engaging playfully at a snowy outpost in northern Canada.) Stuart Brown, president of the National Institute for Play, was speaking at the New York Public Library's main branch on 42nd Street. He created the institute in 1996, after more than 20 years of psychiatric practice and research persuaded him of the dangerous long


==============================================================================
FineWeb2-HQ PT
==============================================================================
Repository: epfml/FineWeb2-HQ
Config:     por_Latn
Split:      train
Weight:     22.5%

README.md:   0%|          | 0.00/9.61k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/1205 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

STATUS: OK
Dataset type: IterableDataset

Features:
  text                      Value('string')
  id                        Value('string')
  date                      Value('string')
  dump                      Value('string')
  embeddings                List(List(Value('float64')))
  file_path                 Value('string')
  language                  Value('string')
  language_score            Value('float64')
  language_script           Value('string')
  minhash_cluster_size      Value('int64')
  top_langs                 Value('string')
  url                       Value('string')
  quality_score             Value('float64')

Sample inspection:

------------------------------------------------------------------------------
SAMPLE 1
------------------------------------------------------------------------------
Fields:
['text', 'id', 'date', 'dump', 'embeddings', 'file_path', 'language', 'language_score', 'language_script', 'minhash_cluster_size', 'top_langs', 'url', 'quality_score']

Text length: 1,920 characters

Preview:
  Boehner abre as portas para aumentos tributários nos EUA
  Por David Lawder e Mark Felsenthal
  WASHINGTON, 17 Dez (Reuters) - O primeiro movimento real nas negociações sobre o "abismo fiscal" nos Estados Unidos começou no domingo, quando o presidente republicano da Câmara dos Deputados, John Boehner, se aproximou ligeiramente das exigências do presidente Barack Obama em um momento em que eles tentam evitar fortes aumentos de impostos e cortes de gastos que entrarão em vigor no país a menos que o Congresso intervenha até 31 de dezembro.
  Mas as novas posições de Boehner, sobre impostos e o volume total da nova receita a ser incluída em um acordo de redução de déficit, ainda estão bem longe das de

------------------------------------------------------------------------------
SAMPLE 2
------------------------------------------------------------------------------
Fields:
['text', 'id', 'date', 'dump', 'embeddings', 'file_path', 'language', 'language_score', 'language_script', 'minhash_cluster_size', 'top_langs', 'url', 'quality_score']

Text length: 371 characters

Preview:
  O internauta Carlos Alexandre Vilela dos Santos enviou um vídeo no qual brinca com o truque da comissão de frente da escola Unidos da Tijuca, do grupo especial do carnaval do Rio.
  "Paulo Barros é sensacional. A Unidos da Tijuca está revolucionando o carnaval. A gente tenta adivinhar, mas não consegue, é impossível copiar. Tijuca campeã mais uma vez!", diz o internauta.


==============================================================================
FineWeb2-HQ ES
==============================================================================
Repository: epfml/FineWeb2-HQ
Config:     spa_Latn
Split:      train
Weight:     22.5%

Resolving data files:   0%|          | 0/1205 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/504 [00:00<?, ?it/s]

STATUS: OK
Dataset type: IterableDataset

Features:
  text                      Value('string')
  id                        Value('string')
  date                      Value('string')
  dump                      Value('string')
  embeddings                List(List(Value('float64')))
  file_path                 Value('string')
  language                  Value('string')
  language_score            Value('float64')
  language_script           Value('string')
  minhash_cluster_size      Value('int64')
  top_langs                 Value('string')
  url                       Value('string')
  quality_score             Value('float64')

Sample inspection:

------------------------------------------------------------------------------
SAMPLE 1
------------------------------------------------------------------------------
Fields:
['text', 'id', 'date', 'dump', 'embeddings', 'file_path', 'language', 'language_score', 'language_script', 'minhash_cluster_size', 'top_langs', 'url', 'quality_score']

Text length: 9,318 characters

Preview:
  Información general
  El 11 de agosto tuvieron lugar las segundas elecciones celebradas en el país desde el final del conflicto, en 2002. En septiembre, en la segunda vuelta, Ernest Koroma, candidato del Congreso de Todo el Pueblo, se hizo con el 54,6 por ciento de los votos, mientras que Solomon Berewa, vicepresidente del país y candidato del gobernante Partido Popular de Sierra Leona, obtuvo el 45,4 por ciento de los votos. Ernest Koroma fue investido presidente el 15 de noviembre.
  Se aplazó el juicio contra Charles Taylor, ex presidente de Liberia, y se preveía que se reanudara a principios de 2008. Dos de los tres juicios celebrados ante el Tribunal Especial para Sierra Leona se encontraba

------------------------------------------------------------------------------
SAMPLE 2
------------------------------------------------------------------------------
Fields:
['text', 'id', 'date', 'dump', 'embeddings', 'file_path', 'language', 'language_score', 'language_script', 'minhash_cluster_size', 'top_langs', 'url', 'quality_score']

Text length: 10,304 characters

Preview:
  Muchos son los que han levantado sus voces para enfatizar lo "disparatado" de los reclamos bíblicos sobre la ocurrencia de una inundación universal equivalente a la descrita por el libro de Génesis. De acuerdo con el relato bíblico, Dios decidió juzgar al hombre mediante la destrucción de la raza humana hasta ese momento histórico, y solamente salvando a Noé y a su familia, comenzar de nuevo para limpiar lo que hasta ese momento había sucedido. (Para un fascinante estudio acerca de lo que nosotros creemos que fue la causa principal que justificó la destrucción total de los humanos antes del Diluvio, incluyendo a los animales terrestres, por favor lea los 2 artículos del Lic. Ureña, titulados


==============================================================================
OpenCoder FineWeb Code
==============================================================================
Repository: OpenCoder-LLM/opc-fineweb-code-corpus
Config:     None
Split:      train
Weight:     5.0%

README.md:   0%|          | 0.00/2.79k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/510 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/510 [00:00<?, ?it/s]

STATUS: OK
Dataset type: IterableDataset

Features:
  url                       Value('string')
  tag                       Value('string')
  text                      Value('string')
  file_path                 Value('string')
  dump                      Value('string')
  file_size_in_byte         Value('int64')
  line_count                Value('int64')

Sample inspection:

------------------------------------------------------------------------------
SAMPLE 1
------------------------------------------------------------------------------
Fields:
['url', 'tag', 'text', 'file_path', 'dump', 'file_size_in_byte', 'line_count']

Text length: 4,274 characters

Preview:
  Project for major energy company derailed by ATOM E6xx, EG20T silicon bug
  Custom hardware was developed to us the industrial temperature rated ATOM in a harsh environment. The primary interface to the hardware is the six USB port provided by the EG20T controller hub. All early software/hardware development was tested with the commercial temperature rated ATOM processor and the US15W controller hub without error.
  USB traffic to the EG20T causes all USB traffic to stop. This issue is stated in Intel Platform Controller Hub EG20T Specification Update Errata # 12.
  " USB Host: Memory Read Request Address Across DWord Boundary
  May Cause Incomplete Transfer
  When the Device Read Pre-Fetch Control Re

------------------------------------------------------------------------------
SAMPLE 2
------------------------------------------------------------------------------
Fields:
['url', 'tag', 'text', 'file_path', 'dump', 'file_size_in_byte', 'line_count']

Text length: 5,952 characters

Preview:
  Error Could Not Connect To Lockdown 2.0.4
  Would it be better if I bought a is anything I can do about it. Upon restarting the router, it will connect and function of Win7) I got a BSOD: IRQL_NOT_LESS_OR_EQUAL. Applying too much canbe fine for a while until it happens again.Dual band systems seem to impact not devices and printers I can see it..
  I really don't I copy-pasted and post later. Is there anyone who knows what lockdown Source port 1) is functioning normally. to Long enough to see run effeciently to use it for work. So a bit of background, I have lockdown if this makes a differance.
  Can any one help me get or just buckle down with 2 dvi connectors? I noticed that the CPU usage is amo



==============================================================================
MAIA CORPUS V2 - DATASET TEST SUMMARY
==============================================================================
FineWeb-Edu EN                      OK
FineWeb2-HQ PT                      OK
FineWeb2-HQ ES                      OK
OpenCoder FineWeb Code              OK
------------------------------------------------------------------------------
CORE DATASETS AVAILABLE.
Ready for corpus materialization design.

In [ ]:
# ============================================================
# MAIA CORPUS V2 - TEST REMAINING SOURCES
# ============================================================

ADDITIONAL_DATASETS = [

    {
        "name": "FineMath-4+",
        "repo": "HuggingFaceTB/finemath",
        "config": "finemath-4plus",
        "split": "train",
        "weight": 0.03,
        "text_field": "text",
    },

    {
        "name": "peS2o Scientific",
        "repo": "common-pile/peS2o",
        "config": None,
        "split": "train",
        "weight": 0.02,
        "text_field": "text",
    },
]


results = {}

for spec in ADDITIONAL_DATASETS:

    success = test_dataset(
        spec,
        samples=2
    )

    results[spec["name"]] = success


print("\n")
print("=" * 78)
print("MAIA CORPUS V2 - ADDITIONAL DATASET TEST SUMMARY")
print("=" * 78)

for name, success in results.items():

    status = "OK" if success else "FAILED"

    print(f"{name:35s} {status}")

==============================================================================
FineMath-4+
==============================================================================
Repository: HuggingFaceTB/finemath
Config:     finemath-4plus
Split:      train
Weight:     3.0%

README.md:   0%|          | 0.00/12.4k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/128 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/64 [00:00<?, ?it/s]

STATUS: OK
Dataset type: IterableDataset

Features:
  url                       Value('string')
  fetch_time                Value('int64')
  content_mime_type         Value('string')
  warc_filename             Value('string')
  warc_record_offset        Value('int32')
  warc_record_length        Value('int32')
  text                      Value('string')
  token_count               Value('int32')
  char_count                Value('int32')
  metadata                  Value('string')
  score                     Value('float64')
  int_score                 Value('int64')
  crawl                     Value('string')
  snapshot_type             Value('string')
  language                  Value('string')
  language_score            Value('float64')

Sample inspection:

------------------------------------------------------------------------------
SAMPLE 1
------------------------------------------------------------------------------
Fields:
['url', 'fetch_time', 'content_mime_type', 'warc_filename', 'warc_record_offset', 'warc_record_length', 'text', 'token_count', 'char_count', 'metadata', 'score', 'int_score', 'crawl', 'snapshot_type', 'language', 'language_score']

Text length: 1,930 characters

Preview:
  # What is the term”exclamation mark” in mathematics?

  The answer is easy. Below are some approaches to inform as soon as an equation can be really actually a multiplication equation and also how to add and subtract using”exclamation marks”. For instance,”2x + 3″ imply”multiply two integers from about a few, making a value add up to 2 and 3″.

  By way of example,”2x + 3″ are multiplication by write a paper online three. In addition, we can add the values of 2 and 3 collectively. To add the worth, we’ll use”e”that I” (or”E”). With”I” means”include the worth of one to the worth of 2″.

  To add the worth , we can certainly do this similar to that:”x – y” means”multiply x by y, making a worth equal

------------------------------------------------------------------------------
SAMPLE 2
------------------------------------------------------------------------------
Fields:
['url', 'fetch_time', 'content_mime_type', 'warc_filename', 'warc_record_offset', 'warc_record_length', 'text', 'token_count', 'char_count', 'metadata', 'score', 'int_score', 'crawl', 'snapshot_type', 'language', 'language_score']

Text length: 6,132 characters

Preview:
  Our curriculum is spiral

  Please note that our virtual Singapore Math Grade 3 curriculum is spiral and it provides for the review of the important concepts that students learned in Grade 2. Our online K-5 math curriculum is aligned with all standard Singapore Math textbook series and it includes all content that these series cover, from Kindergarten grade through 5th grade.

  Our Singapore Math for 3rd Grade may introduce some topics one grade level earlier or postpone coverage of some topics until grade 4. In the few instances where 3rd grade level units don’t exactly align between our curriculum and textbooks, you will still be able to easily locate the corresponding unit in our program by


==============================================================================
peS2o Scientific
==============================================================================
Repository: common-pile/peS2o
Config:     None
Split:      train
Weight:     2.0%

README.md:   0%|          | 0.00/5.71k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/102 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/102 [00:00<?, ?it/s]

STATUS: OK
Dataset type: IterableDataset

Features:
  added                     Value('string')
  created                   Value('string')
  id                        Value('string')
  metadata                  {'extfieldsofstudy': List(Value('string')), 'oa_license': Value('string'), 'oa_status': Value('string'), 'oa_url': Value('string'), 'pdf_hash': Value('string'), 'pdf_src': Value('string'), 'provenance': Value('string'), 's2fieldsofstudy': List(Value('string')), 'sha1': Value('string'), 'year': Value('int64')}
  source                    Value('string')
  text                      Value('string')
  version                   Value('string')

Sample inspection:

------------------------------------------------------------------------------
SAMPLE 1
------------------------------------------------------------------------------
Fields:
['added', 'created', 'id', 'metadata', 'source', 'text', 'version']

Text length: 26,066 characters

Preview:
  Subleading contributions to the nuclear scalar isoscalar currents

  We extend our recent analyses of the nuclear vector, axial-vector and pseudoscalar currents and derive the leading one-loop corrections to the two-nucleon scalar current operator in the framework of chiral effective field theory using the method of unitary transformation. We also show that the scalar current operators at zero momentum transfer are directly related to the quark mass dependence of the nuclear forces.


  I. INTRODUCTION
  The first principles description of nuclei, nuclear matter and reactions is one of the great challenges in contemporary physics with applications ranging from low-energy searches for physics beyon

------------------------------------------------------------------------------
SAMPLE 2
------------------------------------------------------------------------------
Fields:
['added', 'created', 'id', 'metadata', 'source', 'text', 'version']

Text length: 26,627 characters

Preview:
  Factors Associated with Impairment of Quadriceps Muscle Function in Chinese Patients with Chronic Obstructive Pulmonary Disease

  Background Quadriceps muscle dysfunction is well confirmed in chronic obstructive pulmonary disease (COPD) and reported to be related to a higher risk of mortality. Factors contributing to quadriceps dysfunction have been postulated, while not one alone could fully explain it and there are few reports on it in China. This study was aimed to investigate the severity of quadriceps dysfunction in patients with COPD, and to compare quadriceps muscle function in COPD and the healthy elderly. Methods Quadriceps strength and endurance capabilities were investigated in 71


==============================================================================
MAIA CORPUS V2 - ADDITIONAL DATASET TEST SUMMARY
==============================================================================
FineMath-4+                         OK
peS2o Scientific                    OK

In [ ]:
# ============================================================
# MAIA LITE - CORPUS V2 MATERIALIZATION
#
# PURPOSE
# -------
# Build a deterministic, restartable pretraining corpus on
# Google Drive.
#
# TARGET:
#   ~2.9 billion tokens
#
# FORMAT:
#   uint16 token IDs
#
# MODEL:
#   Maia Lite 355M
#
# CONTEXT:
#   1024 tokens
#
# DESIGN:
#   - Stream source datasets from Hugging Face
#   - Tokenize incrementally
#   - Insert EOS between documents
#   - Pack continuously
#   - Write ~16M-token binary shards
#   - Never hold the complete corpus in RAM
#   - Restart safely after Colab interruption
#   - Never rewrite completed shards
#
# IMPORTANT:
#   Run on CPU/T4. Do NOT waste A100 time on this.
# ============================================================


# ============================================================
# 0. INSTALL
# ============================================================

!pip -q install -U datasets transformers huggingface_hub


# ============================================================
# 1. IMPORTS
# ============================================================

import os
import json
import time
import hashlib
from pathlib import Path

import numpy as np

from datasets import load_dataset
from transformers import GPT2TokenizerFast

from google.colab import drive


# ============================================================
# 2. GOOGLE DRIVE
# ============================================================

drive.mount("/content/drive")


PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = PROJECT_DIR / "tokenizador"

CORPUS_DIR = PROJECT_DIR / "corpus_v2"

TRAIN_DIR = CORPUS_DIR / "train"

STATE_DIR = CORPUS_DIR / "state"

MANIFEST_DIR = CORPUS_DIR / "manifests"


for directory in [
    CORPUS_DIR,
    TRAIN_DIR,
    STATE_DIR,
    MANIFEST_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )


# ============================================================
# 3. GLOBAL CONFIGURATION
# ============================================================

TARGET_TOTAL_TOKENS = 2_900_000_000

SEQUENCE_LENGTH = 1024

# ~32 MB per shard using uint16.
SHARD_TOKENS = 16_000_000

DTYPE = np.uint16

SEED = 42


# ============================================================
# 4. CORPUS MIX
# ============================================================

SOURCES = [

    {
        "id": "fineweb_edu_en",
        "name": "FineWeb-Edu EN",

        "repo": "HuggingFaceFW/fineweb-edu",
        "config": "sample-10BT",
        "split": "train",

        "weight": 0.45,

        "text_field": "text",
    },

    {
        "id": "fineweb2_hq_pt",
        "name": "FineWeb2-HQ PT",

        "repo": "epfml/FineWeb2-HQ",
        "config": "por_Latn",
        "split": "train",

        "weight": 0.225,

        "text_field": "text",
    },

    {
        "id": "fineweb2_hq_es",
        "name": "FineWeb2-HQ ES",

        "repo": "epfml/FineWeb2-HQ",
        "config": "spa_Latn",
        "split": "train",

        "weight": 0.225,

        "text_field": "text",
    },

    {
        "id": "opencoder",
        "name": "OpenCoder FineWeb Code",

        "repo": "OpenCoder-LLM/opc-fineweb-code-corpus",
        "config": None,
        "split": "train",

        "weight": 0.05,

        "text_field": "text",
    },

    {
        "id": "finemath",
        "name": "FineMath-4+",

        "repo": "HuggingFaceTB/finemath",
        "config": "finemath-4plus",
        "split": "train",

        "weight": 0.03,

        "text_field": "text",
    },

    {
        "id": "pes2o",
        "name": "peS2o Scientific",

        "repo": "common-pile/peS2o",
        "config": None,
        "split": "train",

        "weight": 0.02,

        "text_field": "text",
    },
]


# ============================================================
# 5. CALCULATE EXACT SOURCE TARGETS
# ============================================================

remaining = TARGET_TOTAL_TOKENS

for index, source in enumerate(SOURCES):

    if index < len(SOURCES) - 1:

        target = int(
            TARGET_TOTAL_TOKENS
            * source["weight"]
        )

    else:

        target = remaining

    # Make target divisible by context length.
    target -= target % SEQUENCE_LENGTH

    source["target_tokens"] = target

    remaining -= target


# Give any rounding remainder to the largest corpus.

if remaining > 0:

    remaining -= remaining % SEQUENCE_LENGTH

    SOURCES[0]["target_tokens"] += remaining


# ============================================================
# 6. TOKENIZER
# ============================================================

print("Loading Maia Lite tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    str(TOKENIZER_DIR)
)

EOS_TOKEN_ID = tokenizer.eos_token_id

VOCAB_SIZE = len(tokenizer)

print(f"Vocabulary size: {VOCAB_SIZE:,}")
print(f"EOS token:       {EOS_TOKEN_ID}")


if VOCAB_SIZE > np.iinfo(np.uint16).max:

    raise RuntimeError(
        "Vocabulary does not fit into uint16."
    )


# ============================================================
# 7. SAVE GLOBAL METADATA
# ============================================================

metadata = {

    "name": "Maia Corpus V2",

    "format": "uint16",

    "sequence_length": SEQUENCE_LENGTH,

    "target_total_tokens": TARGET_TOTAL_TOKENS,

    "shard_tokens": SHARD_TOKENS,

    "vocab_size": VOCAB_SIZE,

    "eos_token_id": EOS_TOKEN_ID,

    "seed": SEED,

    "sources": [
        {
            "id": source["id"],
            "name": source["name"],
            "repo": source["repo"],
            "config": source["config"],
            "weight": source["weight"],
            "target_tokens": source["target_tokens"],
        }
        for source in SOURCES
    ],
}


with open(
    CORPUS_DIR / "metadata.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        metadata,
        f,
        indent=2,
        ensure_ascii=False
    )


# ============================================================
# 8. STATE HELPERS
# ============================================================

def state_path(source_id):

    return (
        STATE_DIR
        / f"{source_id}.json"
    )


def load_state(source):

    path = state_path(
        source["id"]
    )

    if not path.exists():

        return {
            "documents_seen": 0,
            "tokens_written": 0,
            "shards_written": 0,
            "complete": False,
        }

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)


def save_state(source, state):

    path = state_path(
        source["id"]
    )

    temporary = Path(
        str(path) + ".tmp"
    )

    with open(
        temporary,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            state,
            f,
            indent=2
        )

    os.replace(
        temporary,
        path
    )


# ============================================================
# 9. SHARD CHECKSUM
# ============================================================

def sha256_file(path):

    digest = hashlib.sha256()

    with open(path, "rb") as f:

        while True:

            chunk = f.read(
                8 * 1024 * 1024
            )

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


# ============================================================
# 10. WRITE ONE SHARD
# ============================================================

def write_shard(
    source,
    shard_index,
    tokens
):

    source_dir = (
        TRAIN_DIR
        / source["id"]
    )

    source_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    filename = (
        f"shard-{shard_index:05d}.bin"
    )

    final_path = (
        source_dir
        / filename
    )

    temporary_path = Path(
        str(final_path) + ".tmp"
    )


    # --------------------------------------------------------
    # Safety: completed shard already exists.
    # --------------------------------------------------------

    if final_path.exists():

        raise RuntimeError(
            f"Shard already exists: "
            f"{final_path}"
        )


    array = np.asarray(
        tokens,
        dtype=DTYPE
    )


    # Ensure complete 1024-token sequences.

    usable = (
        len(array)
        // SEQUENCE_LENGTH
        * SEQUENCE_LENGTH
    )

    array = array[:usable]


    with open(
        temporary_path,
        "wb"
    ) as f:

        array.tofile(f)

        f.flush()

        os.fsync(
            f.fileno()
        )


    os.replace(
        temporary_path,
        final_path
    )


    checksum = sha256_file(
        final_path
    )


    manifest_entry = {

        "source": source["id"],

        "shard": shard_index,

        "filename": str(
            final_path.relative_to(
                CORPUS_DIR
            )
        ),

        "tokens": int(
            len(array)
        ),

        "sequences": int(
            len(array)
            // SEQUENCE_LENGTH
        ),

        "bytes": int(
            final_path.stat().st_size
        ),

        "sha256": checksum,
    }


    manifest_path = (
        MANIFEST_DIR
        / f"{source['id']}.jsonl"
    )


    with open(
        manifest_path,
        "a",
        encoding="utf-8"
    ) as f:

        f.write(
            json.dumps(
                manifest_entry
            )
            + "\n"
        )


    return len(array)


# ============================================================
# 11. LOAD STREAMING DATASET
# ============================================================

def load_source_dataset(source):

    kwargs = {

        "path": source["repo"],

        "split": source["split"],

        "streaming": True,
    }


    if source["config"] is not None:

        kwargs["name"] = (
            source["config"]
        )


    dataset = load_dataset(
        **kwargs
    )


    return dataset


# ============================================================
# 12. BASIC DOCUMENT FILTER
# ============================================================

def accept_document(
    source,
    row,
    text
):

    if text is None:

        return False


    text = text.strip()


    # Avoid tiny fragments.

    if len(text) < 200:

        return False


    # --------------------------------------------------------
    # FineMath quality filtering
    # --------------------------------------------------------

    if source["id"] == "finemath":

        language_score = row.get(
            "language_score"
        )

        if (
            language_score is not None
            and language_score < 0.80
        ):

            return False


    return True


# ============================================================
# 13. MATERIALIZE ONE SOURCE
# ============================================================

def materialize_source(source):

    print("\n")
    print("=" * 78)
    print(source["name"])
    print("=" * 78)

    state = load_state(
        source
    )


    target_tokens = (
        source["target_tokens"]
    )


    print(
        f"Target tokens:    "
        f"{target_tokens:,}"
    )

    print(
        f"Already written:  "
        f"{state['tokens_written']:,}"
    )

    print(
        f"Documents seen:   "
        f"{state['documents_seen']:,}"
    )

    print(
        f"Completed shards: "
        f"{state['shards_written']:,}"
    )


    if state["complete"]:

        print(
            "SOURCE ALREADY COMPLETE."
        )

        return


    # --------------------------------------------------------
    # Open source stream.
    # --------------------------------------------------------

    dataset = load_source_dataset(
        source
    )


    # --------------------------------------------------------
    # IMPORTANT:
    #
    # Streaming datasets cannot restore arbitrary iterator
    # state reliably across Colab sessions.
    #
    # Therefore we skip already-consumed documents.
    #
    # This is only corpus construction, NOT training.
    # The final training corpus itself will be map-style and
    # deterministic.
    # --------------------------------------------------------

    documents_to_skip = (
        state["documents_seen"]
    )


    if documents_to_skip > 0:

        print(
            f"Skipping "
            f"{documents_to_skip:,} "
            f"previously processed documents..."
        )

        dataset = dataset.skip(
            documents_to_skip
        )


    shard_buffer = []

    shard_tokens = 0

    start_time = time.time()

    last_report = start_time

    documents_this_run = 0


    # --------------------------------------------------------
    # Stream documents.
    # --------------------------------------------------------

    for row in dataset:

        # Stop when persisted tokens + current in-memory shard
        # have reached the source target.
        effective_tokens = (
            state["tokens_written"]
            + shard_tokens
        )

        if effective_tokens >= target_tokens:
            break


        state["documents_seen"] += 1

        documents_this_run += 1


        text = row.get(
            source["text_field"]
        )


        if not accept_document(
            source,
            row,
            text
        ):

            continue


        text = text.strip()


        # ----------------------------------------------------
        # Tokenize document WITHOUT truncation.
        # ----------------------------------------------------

        token_ids = tokenizer.encode(
            text,
            add_special_tokens=False
        )


        if len(token_ids) == 0:

            continue


        # Explicit document boundary.

        token_ids.append(
            EOS_TOKEN_ID
        )


        position = 0


        while position < len(token_ids):

            remaining_source = (
                target_tokens
                - state["tokens_written"]
                - shard_tokens
            )


            if remaining_source <= 0:

                break


            remaining_shard = (
                SHARD_TOKENS
                - shard_tokens
            )


            take = min(
                len(token_ids) - position,
                remaining_shard,
                remaining_source
            )


            shard_buffer.extend(
                token_ids[
                    position:
                    position + take
                ]
            )


            shard_tokens += take

            position += take


            # ------------------------------------------------
            # Write full shard.
            # ------------------------------------------------

            if (
                shard_tokens
                >= SHARD_TOKENS
            ):

                written = write_shard(
                    source,
                    state[
                        "shards_written"
                    ],
                    shard_buffer
                )


                state[
                    "tokens_written"
                ] += written

                state[
                    "shards_written"
                ] += 1


                save_state(
                    source,
                    state
                )


                print(
                    f"\nSHARD "
                    f"{state['shards_written']:05d} "
                    f"COMPLETE"
                )

                print(
                    f"Tokens: "
                    f"{state['tokens_written']:,}"
                    f" / "
                    f"{target_tokens:,}"
                )

                print(
                    f"Progress: "
                    f"{100 * state['tokens_written'] / target_tokens:.2f}%"
                )


                shard_buffer = []

                shard_tokens = 0


        # ----------------------------------------------------
        # Periodic status.
        # ----------------------------------------------------

        now = time.time()


        if now - last_report >= 60:

            elapsed = (
                now
                - start_time
            )


            effective_tokens = (
                state["tokens_written"]
                + shard_tokens
            )


            progress = (
                effective_tokens
                / target_tokens
            )


            print(
                f"\r"
                f"docs={state['documents_seen']:,} | "
                f"tokens≈{effective_tokens:,} | "
                f"{progress * 100:.2f}% | "
                f"current_buffer={shard_tokens:,}",
                end=""
            )


            last_report = now


    # ========================================================
    # WRITE FINAL PARTIAL SHARD
    # ========================================================

    if shard_tokens > 0:

        # Only complete 1024-token sequences.

        usable = (
            shard_tokens
            // SEQUENCE_LENGTH
            * SEQUENCE_LENGTH
        )


        if usable > 0:

            written = write_shard(
                source,
                state[
                    "shards_written"
                ],
                shard_buffer[:usable]
            )


            state[
                "tokens_written"
            ] += written

            state[
                "shards_written"
            ] += 1


    # ========================================================
    # COMPLETE
    # ========================================================

    if (
        state["tokens_written"]
        >= target_tokens
        - SEQUENCE_LENGTH
    ):

        state["complete"] = True


    save_state(
        source,
        state
    )


    elapsed = (
        time.time()
        - start_time
    )


    print("\n")

    print(
        f"Final tokens:    "
        f"{state['tokens_written']:,}"
    )

    print(
        f"Shards:          "
        f"{state['shards_written']:,}"
    )

    print(
        f"Documents seen:  "
        f"{state['documents_seen']:,}"
    )

    print(
        f"Runtime:         "
        f"{elapsed / 3600:.2f} h"
    )

    print(
        f"Complete:        "
        f"{state['complete']}"
    )


# ============================================================
# 14. SHOW PLAN
# ============================================================

print("\n")
print("=" * 78)
print("MAIA CORPUS V2")
print("=" * 78)

print(
    f"Target total: "
    f"{TARGET_TOTAL_TOKENS:,} tokens"
)

print(
    f"Approx raw size: "
    f"{TARGET_TOTAL_TOKENS * 2 / 1e9:.2f} GB"
)

print()


for source in SOURCES:

    print(
        f"{source['name']:32s} "
        f"{source['weight'] * 100:5.1f}%   "
        f"{source['target_tokens']:>15,} tokens"
    )


print("=" * 78)


# ============================================================
# 15. MATERIALIZE
# ============================================================

for source in SOURCES:

    materialize_source(
        source
    )


# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n\n")
print("=" * 78)
print("MAIA CORPUS V2 - FINAL SUMMARY")
print("=" * 78)


grand_total = 0


for source in SOURCES:

    state = load_state(
        source
    )


    grand_total += (
        state["tokens_written"]
    )


    print(
        f"{source['name']:32s} "
        f"{state['tokens_written']:>15,} "
        f"tokens | "
        f"{state['shards_written']:4d} shards | "
        f"complete={state['complete']}"
    )


print("-" * 78)

print(
    f"{'TOTAL':32s} "
    f"{grand_total:>15,} tokens"
)

print(
    f"Disk payload: "
    f"~{grand_total * 2 / 1e9:.2f} GB"
)

print("=" * 78)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 116.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 846.4/846.4 kB 40.6 MB/s eta 0:00:00
Mounted at /content/drive
Loading Maia Lite tokenizer...
Vocabulary size: 50,257
EOS token:       2


==============================================================================
MAIA CORPUS V2
==============================================================================
Target total: 2,900,000,000 tokens
Approx raw size: 5.80 GB

FineWeb-Edu EN                    45.0%     1,304,999,936 tokens
FineWeb2-HQ PT                    22.5%       652,499,968 tokens
FineWeb2-HQ ES                    22.5%       652,499,968 tokens
OpenCoder FineWeb Code             5.0%       144,999,424 tokens
FineMath-4+                        3.0%        86,999,040 tokens
peS2o Scientific                   2.0%        58,001,408 tokens
==============================================================================


==============================================================================
FineWeb-Edu EN
==============================================================================
Target tokens:    1,304,999,936
Already written:  1,304,999,936
Documents seen:   1,193,710
Completed shards: 82
SOURCE ALREADY COMPLETE.


==============================================================================
FineWeb2-HQ PT
==============================================================================
Target tokens:    652,499,968
Already written:  652,499,968
Documents seen:   885,429
Completed shards: 41
SOURCE ALREADY COMPLETE.


==============================================================================
FineWeb2-HQ ES
==============================================================================
Target tokens:    652,499,968
Already written:  652,499,968
Documents seen:   888,577
Completed shards: 41
SOURCE ALREADY COMPLETE.


==============================================================================
OpenCoder FineWeb Code
==============================================================================
Target tokens:    144,999,424
Already written:  144,999,424
Documents seen:   256,742
Completed shards: 10
SOURCE ALREADY COMPLETE.


==============================================================================
FineMath-4+
==============================================================================
Target tokens:    86,999,040
Already written:  86,999,040
Documents seen:   70,699
Completed shards: 6
SOURCE ALREADY COMPLETE.


==============================================================================
peS2o Scientific
==============================================================================
Target tokens:    58,001,408
Already written:  58,001,408
Documents seen:   8,319
Completed shards: 4
SOURCE ALREADY COMPLETE.



==============================================================================
MAIA CORPUS V2 - FINAL SUMMARY
==============================================================================
FineWeb-Edu EN                     1,304,999,936 tokens |   82 shards | complete=True
FineWeb2-HQ PT                       652,499,968 tokens |   41 shards | complete=True
FineWeb2-HQ ES                       652,499,968 tokens |   41 shards | complete=True
OpenCoder FineWeb Code               144,999,424 tokens |   10 shards | complete=True
FineMath-4+                           86,999,040 tokens |    6 shards | complete=True
peS2o Scientific                      58,001,408 tokens |    4 shards | complete=True
------------------------------------------------------------------------------
TOTAL                              2,899,999,744 tokens
Disk payload: ~5.80 GB
==============================================================================

In [ ]:
import json
from pathlib import Path

state_file = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite/"
    "corpus_v2/state/fineweb_edu_en.json"
)

with open(state_file, "r", encoding="utf-8") as f:
    state = json.load(f)

print(json.dumps(state, indent=2))

{
  "documents_seen": 1185348,
  "tokens_written": 1296000000,
  "shards_written": 81,
  "complete": false
}

In [ ]:
# ============================================================
# MAIA LITE - CORPUS V2 COMPLETE AUDIT
#
# PURPOSE
# -------
# Validate the materialized Maia Corpus V2 before using
# expensive A100 compute.
#
# READ-ONLY:
#   This cell DOES NOT modify the corpus.
#
# CHECKS
# ------
#   1. Global metadata
#   2. Per-source state
#   3. Manifest consistency
#   4. Physical shard existence
#   5. File size
#   6. SHA-256 checksum
#   7. uint16 alignment
#   8. 1024-token sequence alignment
#   9. Token ID range
#  10. Physical token counts
#  11. Residual .tmp files
#  12. Random decoded samples from every source
#
# ============================================================

import os
import json
import hashlib
import random
import time
from pathlib import Path

import numpy as np
from transformers import GPT2TokenizerFast


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = PROJECT_DIR / "tokenizador"

CORPUS_DIR = PROJECT_DIR / "corpus_v2"

TRAIN_DIR = CORPUS_DIR / "train"

STATE_DIR = CORPUS_DIR / "state"

MANIFEST_DIR = CORPUS_DIR / "manifests"

METADATA_FILE = CORPUS_DIR / "metadata.json"


# ============================================================
# 2. CONFIGURATION
# ============================================================

SEQUENCE_LENGTH = 1024

EXPECTED_VOCAB_SIZE = 50_257

EXPECTED_TOTAL_TOKENS = 2_899_999_744

EXPECTED_TOTAL_SHARDS = 184

RANDOM_SEED = 20260927

# Number of decoded samples per source.
SAMPLES_PER_SOURCE = 2

# Decode this many tokens for each sample.
SAMPLE_TOKENS = 256

# Token validation is performed in chunks to avoid loading
# complete shards unnecessarily.
VALIDATION_CHUNK_TOKENS = 4_000_000


random.seed(RANDOM_SEED)


# ============================================================
# 3. SOURCE DEFINITIONS
# ============================================================

SOURCES = [

    {
        "id": "fineweb_edu_en",
        "name": "FineWeb-Edu EN",
        "expected_tokens": 1_304_999_936,
        "expected_shards": 82,
    },

    {
        "id": "fineweb2_hq_pt",
        "name": "FineWeb2-HQ PT",
        "expected_tokens": 652_499_968,
        "expected_shards": 41,
    },

    {
        "id": "fineweb2_hq_es",
        "name": "FineWeb2-HQ ES",
        "expected_tokens": 652_499_968,
        "expected_shards": 41,
    },

    {
        "id": "opencoder",
        "name": "OpenCoder FineWeb Code",
        "expected_tokens": 144_999_424,
        "expected_shards": 10,
    },

    {
        "id": "finemath",
        "name": "FineMath-4+",
        "expected_tokens": 86_999_040,
        "expected_shards": 6,
    },

    {
        "id": "pes2o",
        "name": "peS2o Scientific",
        "expected_tokens": 58_001_408,
        "expected_shards": 4,
    },
]


# ============================================================
# 4. HELPERS
# ============================================================

def ok(message):
    print(f"[ OK ] {message}")


def warn(message):
    print(f"[WARN] {message}")


def fail(message):
    print(f"[FAIL] {message}")


def sha256_file(path):

    digest = hashlib.sha256()

    with open(path, "rb") as f:

        while True:

            chunk = f.read(
                8 * 1024 * 1024
            )

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


def read_json(path):

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)


def read_manifest(path):

    entries = []

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        for line_number, line in enumerate(
            f,
            start=1
        ):

            line = line.strip()

            if not line:
                continue

            try:

                entries.append(
                    json.loads(line)
                )

            except Exception as exc:

                raise RuntimeError(
                    f"Invalid manifest JSON at "
                    f"{path}:{line_number}: {exc}"
                )

    return entries


# ============================================================
# 5. TOKENIZER
# ============================================================

print("=" * 78)
print("MAIA CORPUS V2 - COMPLETE AUDIT")
print("=" * 78)

print("\nLoading tokenizer...")

tokenizer = GPT2TokenizerFast.from_pretrained(
    str(TOKENIZER_DIR)
)

VOCAB_SIZE = len(tokenizer)

EOS_TOKEN_ID = tokenizer.eos_token_id

print(f"Vocabulary: {VOCAB_SIZE:,}")
print(f"EOS:        {EOS_TOKEN_ID}")

if VOCAB_SIZE == EXPECTED_VOCAB_SIZE:
    ok("Vocabulary size is correct.")
else:
    fail(
        f"Vocabulary mismatch: "
        f"{VOCAB_SIZE:,} != "
        f"{EXPECTED_VOCAB_SIZE:,}"
    )


# ============================================================
# 6. GLOBAL METADATA
# ============================================================

print("\n")
print("=" * 78)
print("GLOBAL METADATA")
print("=" * 78)

global_errors = []

if not METADATA_FILE.exists():

    fail(
        f"Missing metadata file: "
        f"{METADATA_FILE}"
    )

    global_errors.append(
        "metadata.json missing"
    )

else:

    metadata = read_json(
        METADATA_FILE
    )

    print(
        json.dumps(
            metadata,
            indent=2,
            ensure_ascii=False
        )
    )

    if metadata.get(
        "sequence_length"
    ) == SEQUENCE_LENGTH:

        ok(
            f"Sequence length = "
            f"{SEQUENCE_LENGTH}"
        )

    else:

        fail(
            "Unexpected sequence length."
        )

        global_errors.append(
            "sequence length mismatch"
        )


    if metadata.get(
        "vocab_size"
    ) == VOCAB_SIZE:

        ok("Metadata vocabulary matches tokenizer.")

    else:

        fail(
            "Metadata vocabulary does not "
            "match tokenizer."
        )

        global_errors.append(
            "vocabulary mismatch"
        )


# ============================================================
# 7. SEARCH FOR RESIDUAL TEMP FILES
# ============================================================

print("\n")
print("=" * 78)
print("TEMPORARY FILE CHECK")
print("=" * 78)

tmp_files = list(
    CORPUS_DIR.rglob("*.tmp")
)

part_files = list(
    CORPUS_DIR.rglob("*.part")
)

residual_files = (
    tmp_files
    + part_files
)

if len(residual_files) == 0:

    ok("No residual .tmp/.part files found.")

else:

    warn(
        f"Found {len(residual_files)} "
        f"temporary files:"
    )

    for path in residual_files:

        print(f"  {path}")


# ============================================================
# 8. AUDIT EACH SOURCE
# ============================================================

grand_physical_tokens = 0

grand_manifest_tokens = 0

grand_state_tokens = 0

grand_shards = 0

all_shard_paths = []

source_results = {}

audit_start = time.time()


for source in SOURCES:

    source_id = source["id"]

    source_name = source["name"]

    expected_tokens = (
        source["expected_tokens"]
    )

    expected_shards = (
        source["expected_shards"]
    )

    print("\n")
    print("=" * 78)
    print(source_name)
    print("=" * 78)

    source_errors = []

    source_warnings = []


    # ========================================================
    # STATE
    # ========================================================

    state_file = (
        STATE_DIR
        / f"{source_id}.json"
    )

    if not state_file.exists():

        fail(
            f"Missing state file: "
            f"{state_file}"
        )

        source_errors.append(
            "state file missing"
        )

        state = None

    else:

        state = read_json(
            state_file
        )

        print("\nSTATE")

        print(
            json.dumps(
                state,
                indent=2
            )
        )


        state_tokens = int(
            state.get(
                "tokens_written",
                -1
            )
        )

        state_shards = int(
            state.get(
                "shards_written",
                -1
            )
        )

        state_complete = bool(
            state.get(
                "complete",
                False
            )
        )


        grand_state_tokens += max(
            state_tokens,
            0
        )


        if state_complete:

            ok("State says complete=True.")

        else:

            fail("State says complete=False.")

            source_errors.append(
                "source not complete"
            )


        if state_tokens == expected_tokens:

            ok(
                f"State token count: "
                f"{state_tokens:,}"
            )

        else:

            fail(
                f"State token count mismatch: "
                f"{state_tokens:,} != "
                f"{expected_tokens:,}"
            )

            source_errors.append(
                "state token count mismatch"
            )


        if state_shards == expected_shards:

            ok(
                f"State shard count: "
                f"{state_shards}"
            )

        else:

            fail(
                f"State shard count mismatch: "
                f"{state_shards} != "
                f"{expected_shards}"
            )

            source_errors.append(
                "state shard count mismatch"
            )


    # ========================================================
    # MANIFEST
    # ========================================================

    manifest_file = (
        MANIFEST_DIR
        / f"{source_id}.jsonl"
    )

    if not manifest_file.exists():

        fail(
            f"Missing manifest: "
            f"{manifest_file}"
        )

        source_errors.append(
            "manifest missing"
        )

        manifest = []

    else:

        manifest = read_manifest(
            manifest_file
        )


    print(
        f"\nManifest entries: "
        f"{len(manifest):,}"
    )


    if len(manifest) == expected_shards:

        ok(
            "Manifest shard count "
            "matches expected count."
        )

    else:

        fail(
            f"Manifest shard count mismatch: "
            f"{len(manifest)} != "
            f"{expected_shards}"
        )

        source_errors.append(
            "manifest shard count mismatch"
        )


    manifest_tokens = sum(
        int(entry.get("tokens", 0))
        for entry in manifest
    )

    grand_manifest_tokens += (
        manifest_tokens
    )


    if manifest_tokens == expected_tokens:

        ok(
            f"Manifest tokens: "
            f"{manifest_tokens:,}"
        )

    else:

        fail(
            f"Manifest token mismatch: "
            f"{manifest_tokens:,} != "
            f"{expected_tokens:,}"
        )

        source_errors.append(
            "manifest token mismatch"
        )


    # ========================================================
    # PHYSICAL FILE LIST
    # ========================================================

    source_dir = (
        TRAIN_DIR
        / source_id
    )

    physical_shards = sorted(
        source_dir.glob(
            "shard-*.bin"
        )
    )


    print(
        f"Physical shards: "
        f"{len(physical_shards):,}"
    )


    if len(physical_shards) == expected_shards:

        ok(
            "Physical shard count "
            "matches expected count."
        )

    else:

        fail(
            f"Physical shard count mismatch: "
            f"{len(physical_shards)} != "
            f"{expected_shards}"
        )

        source_errors.append(
            "physical shard count mismatch"
        )


    # ========================================================
    # CHECK MANIFEST SHARDS
    # ========================================================

    physical_tokens = 0

    source_min_token = None

    source_max_token = None


    for index, entry in enumerate(
        manifest
    ):

        relative_filename = (
            entry.get("filename")
        )

        if relative_filename is None:

            fail(
                f"Manifest entry {index} "
                f"has no filename."
            )

            source_errors.append(
                f"manifest entry {index} "
                f"missing filename"
            )

            continue


        shard_path = (
            CORPUS_DIR
            / relative_filename
        )


        if not shard_path.exists():

            fail(
                f"Missing shard: "
                f"{shard_path}"
            )

            source_errors.append(
                f"missing shard {shard_path.name}"
            )

            continue


        all_shard_paths.append(
            shard_path
        )


        # ----------------------------------------------------
        # File size
        # ----------------------------------------------------

        actual_bytes = (
            shard_path.stat().st_size
        )

        manifest_bytes = int(
            entry.get(
                "bytes",
                -1
            )
        )


        if actual_bytes != manifest_bytes:

            fail(
                f"{shard_path.name}: "
                f"size mismatch "
                f"{actual_bytes:,} != "
                f"{manifest_bytes:,}"
            )

            source_errors.append(
                f"{shard_path.name} "
                f"size mismatch"
            )


        # uint16 = 2 bytes/token

        if actual_bytes % 2 != 0:

            fail(
                f"{shard_path.name}: "
                f"invalid uint16 byte count."
            )

            source_errors.append(
                f"{shard_path.name} "
                f"uint16 alignment"
            )

            continue


        actual_tokens = (
            actual_bytes // 2
        )

        physical_tokens += (
            actual_tokens
        )


        manifest_shard_tokens = int(
            entry.get(
                "tokens",
                -1
            )
        )


        if (
            actual_tokens
            != manifest_shard_tokens
        ):

            fail(
                f"{shard_path.name}: "
                f"token count mismatch "
                f"{actual_tokens:,} != "
                f"{manifest_shard_tokens:,}"
            )

            source_errors.append(
                f"{shard_path.name} "
                f"token count mismatch"
            )


        # ----------------------------------------------------
        # Sequence alignment
        # ----------------------------------------------------

        if (
            actual_tokens
            % SEQUENCE_LENGTH
            != 0
        ):

            fail(
                f"{shard_path.name}: "
                f"not divisible by "
                f"{SEQUENCE_LENGTH}."
            )

            source_errors.append(
                f"{shard_path.name} "
                f"sequence alignment"
            )


        # ----------------------------------------------------
        # SHA-256
        # ----------------------------------------------------

        expected_hash = (
            entry.get("sha256")
        )

        actual_hash = sha256_file(
            shard_path
        )


        if actual_hash != expected_hash:

            fail(
                f"{shard_path.name}: "
                f"SHA-256 mismatch."
            )

            source_errors.append(
                f"{shard_path.name} "
                f"checksum mismatch"
            )


        # ----------------------------------------------------
        # Token range
        #
        # Use memmap so the shard is not loaded completely
        # into RAM.
        # ----------------------------------------------------

        mmap = np.memmap(
            shard_path,
            dtype=np.uint16,
            mode="r"
        )


        shard_min = None

        shard_max = None


        for start in range(
            0,
            len(mmap),
            VALIDATION_CHUNK_TOKENS
        ):

            chunk = mmap[
                start:
                start
                + VALIDATION_CHUNK_TOKENS
            ]

            if len(chunk) == 0:
                continue


            chunk_min = int(
                chunk.min()
            )

            chunk_max = int(
                chunk.max()
            )


            if (
                shard_min is None
                or chunk_min < shard_min
            ):

                shard_min = chunk_min


            if (
                shard_max is None
                or chunk_max > shard_max
            ):

                shard_max = chunk_max


        del mmap


        if (
            shard_max is not None
            and shard_max >= VOCAB_SIZE
        ):

            fail(
                f"{shard_path.name}: "
                f"invalid token ID "
                f"{shard_max:,} >= "
                f"{VOCAB_SIZE:,}"
            )

            source_errors.append(
                f"{shard_path.name} "
                f"invalid token"
            )


        if shard_min is not None:

            if (
                source_min_token is None
                or shard_min
                < source_min_token
            ):

                source_min_token = (
                    shard_min
                )


        if shard_max is not None:

            if (
                source_max_token is None
                or shard_max
                > source_max_token
            ):

                source_max_token = (
                    shard_max
                )


        # Progress output.

        print(
            f"\rChecking shards: "
            f"{index + 1:3d}"
            f"/{len(manifest):3d}",
            end=""
        )


    print()


    # ========================================================
    # SOURCE TOTAL
    # ========================================================

    grand_physical_tokens += (
        physical_tokens
    )

    grand_shards += (
        len(physical_shards)
    )


    if physical_tokens == expected_tokens:

        ok(
            f"Physical tokens: "
            f"{physical_tokens:,}"
        )

    else:

        fail(
            f"Physical token mismatch: "
            f"{physical_tokens:,} != "
            f"{expected_tokens:,}"
        )

        source_errors.append(
            "physical token total mismatch"
        )


    if (
        physical_tokens
        == manifest_tokens
    ):

        ok(
            "Physical token count "
            "matches manifest."
        )

    else:

        fail(
            "Physical token count does "
            "not match manifest."
        )

        source_errors.append(
            "physical/manifest mismatch"
        )


    if (
        state is not None
        and physical_tokens
        == state["tokens_written"]
    ):

        ok(
            "Physical token count "
            "matches state."
        )

    else:

        fail(
            "Physical token count does "
            "not match state."
        )

        source_errors.append(
            "physical/state mismatch"
        )


    print(
        f"Token ID range: "
        f"{source_min_token} .. "
        f"{source_max_token}"
    )


    # ========================================================
    # SOURCE RESULT
    # ========================================================

    source_results[source_id] = {

        "name": source_name,

        "tokens": physical_tokens,

        "shards": len(
            physical_shards
        ),

        "errors": source_errors,

        "warnings": source_warnings,
    }


# ============================================================
# 9. GLOBAL PHYSICAL CHECK
# ============================================================

print("\n")
print("=" * 78)
print("GLOBAL PHYSICAL CHECK")
print("=" * 78)

print(
    f"State tokens:     "
    f"{grand_state_tokens:,}"
)

print(
    f"Manifest tokens:  "
    f"{grand_manifest_tokens:,}"
)

print(
    f"Physical tokens:  "
    f"{grand_physical_tokens:,}"
)

print(
    f"Physical shards:  "
    f"{grand_shards:,}"
)


if (
    grand_state_tokens
    == grand_manifest_tokens
    == grand_physical_tokens
    == EXPECTED_TOTAL_TOKENS
):

    ok(
        "All three independent token "
        "counts match."
    )

else:

    fail(
        "Global token counts do not match."
    )

    global_errors.append(
        "global token count mismatch"
    )


if grand_shards == EXPECTED_TOTAL_SHARDS:

    ok(
        f"Total shard count = "
        f"{EXPECTED_TOTAL_SHARDS}"
    )

else:

    fail(
        f"Shard count mismatch: "
        f"{grand_shards} != "
        f"{EXPECTED_TOTAL_SHARDS}"
    )

    global_errors.append(
        "global shard count mismatch"
    )


# ============================================================
# 10. RANDOM DECODE TESTS
# ============================================================

print("\n")
print("=" * 78)
print("RANDOM DECODE TESTS")
print("=" * 78)

print(
    "\nThese samples are READ-ONLY and are used "
    "to visually inspect corpus quality.\n"
)


for source in SOURCES:

    source_id = source["id"]

    source_name = source["name"]

    source_dir = (
        TRAIN_DIR
        / source_id
    )

    shard_paths = sorted(
        source_dir.glob(
            "shard-*.bin"
        )
    )


    print("\n")
    print("#" * 78)
    print(source_name)
    print("#" * 78)


    if len(shard_paths) == 0:

        print(
            "NO SHARDS AVAILABLE."
        )

        continue


    for sample_number in range(
        1,
        SAMPLES_PER_SOURCE + 1
    ):

        shard_path = random.choice(
            shard_paths
        )


        mmap = np.memmap(
            shard_path,
            dtype=np.uint16,
            mode="r"
        )


        sequences = (
            len(mmap)
            // SEQUENCE_LENGTH
        )


        sequence_index = random.randrange(
            sequences
        )


        sequence_start = (
            sequence_index
            * SEQUENCE_LENGTH
        )


        # Decode from the beginning of a random
        # 1024-token training sequence.

        sample_ids = np.asarray(
            mmap[
                sequence_start:
                sequence_start
                + SAMPLE_TOKENS
            ],
            dtype=np.int64
        )


        del mmap


        decoded = tokenizer.decode(
            sample_ids.tolist(),
            skip_special_tokens=False
        )


        print(
            f"\n--- SAMPLE "
            f"{sample_number}/{SAMPLES_PER_SOURCE} ---"
        )

        print(
            f"Shard: "
            f"{shard_path.name}"
        )

        print(
            f"Sequence: "
            f"{sequence_index:,}"
        )

        print(
            f"Tokens: "
            f"{len(sample_ids):,}"
        )

        print()

        print(decoded)

        print()


# ============================================================
# 11. EOS STATISTICS
# ============================================================

print("\n")
print("=" * 78)
print("EOS BOUNDARY STATISTICS")
print("=" * 78)

# We sample shards rather than rescanning all 5.8 GB again.
# This verifies that EOS document boundaries are actually
# present in the physical corpus.

EOS_SAMPLE_SHARDS_PER_SOURCE = 3


for source in SOURCES:

    source_id = source["id"]

    source_name = source["name"]

    source_dir = (
        TRAIN_DIR
        / source_id
    )

    shard_paths = sorted(
        source_dir.glob(
            "shard-*.bin"
        )
    )


    if not shard_paths:

        continue


    selected = random.sample(
        shard_paths,
        min(
            EOS_SAMPLE_SHARDS_PER_SOURCE,
            len(shard_paths)
        )
    )


    eos_count = 0

    token_count = 0


    for shard_path in selected:

        mmap = np.memmap(
            shard_path,
            dtype=np.uint16,
            mode="r"
        )

        eos_count += int(
            np.count_nonzero(
                mmap == EOS_TOKEN_ID
            )
        )

        token_count += len(
            mmap
        )

        del mmap


    if eos_count > 0:

        tokens_per_eos = (
            token_count
            / eos_count
        )

    else:

        tokens_per_eos = None


    print(
        f"{source_name:32s} | "
        f"sampled={token_count:>10,} | "
        f"EOS={eos_count:>8,} | "
        f"tokens/EOS="
        f"{tokens_per_eos:,.1f}"
        if tokens_per_eos is not None
        else
        f"{source_name:32s} | EOS NOT FOUND"
    )


# ============================================================
# 12. FINAL REPORT
# ============================================================

elapsed = (
    time.time()
    - audit_start
)


print("\n")
print("=" * 78)
print("FINAL AUDIT REPORT")
print("=" * 78)


total_source_errors = 0


for source in SOURCES:

    result = source_results[
        source["id"]
    ]

    errors = len(
        result["errors"]
    )

    total_source_errors += (
        errors
    )


    status = (
        "PASS"
        if errors == 0
        else "FAIL"
    )


    print(
        f"{result['name']:32s} | "
        f"{result['tokens']:>15,} tokens | "
        f"{result['shards']:3d} shards | "
        f"{status}"
    )


print("-" * 78)

print(
    f"TOTAL TOKENS: "
    f"{grand_physical_tokens:,}"
)

print(
    f"TOTAL SHARDS: "
    f"{grand_shards:,}"
)

print(
    f"GLOBAL ERRORS: "
    f"{len(global_errors)}"
)

print(
    f"SOURCE ERRORS: "
    f"{total_source_errors}"
)

print(
    f"TEMP FILES: "
    f"{len(residual_files)}"
)

print(
    f"AUDIT TIME: "
    f"{elapsed / 60:.2f} minutes"
)


print("=" * 78)


if (
    len(global_errors) == 0
    and total_source_errors == 0
    and len(residual_files) == 0
):

    print()
    print(
        "RESULT: MAIA CORPUS V2 PASSED "
        "ALL STRUCTURAL AND INTEGRITY CHECKS."
    )

    print(
        "The corpus is structurally ready "
        "for validation-set construction "
        "and pretraining."
    )

else:

    print()
    print(
        "RESULT: AUDIT FOUND ISSUES."
    )

    print(
        "DO NOT START A100 TRAINING "
        "UNTIL THE ISSUES ABOVE ARE REVIEWED."
    )

==============================================================================
MAIA CORPUS V2 - COMPLETE AUDIT
==============================================================================

Loading tokenizer...
Vocabulary: 50,257
EOS:        2
[ OK ] Vocabulary size is correct.


==============================================================================
GLOBAL METADATA
==============================================================================
{
  "name": "Maia Corpus V2",
  "format": "uint16",
  "sequence_length": 1024,
  "target_total_tokens": 2900000000,
  "shard_tokens": 16000000,
  "vocab_size": 50257,
  "eos_token_id": 2,
  "seed": 42,
  "sources": [
    {
      "id": "fineweb_edu_en",
      "name": "FineWeb-Edu EN",
      "repo": "HuggingFaceFW/fineweb-edu",
      "config": "sample-10BT",
      "weight": 0.45,
      "target_tokens": 1304999936
    },
    {
      "id": "fineweb2_hq_pt",
      "name": "FineWeb2-HQ PT",
      "repo": "epfml/FineWeb2-HQ",
      "config": "por_Latn",
      "weight": 0.225,
      "target_tokens": 652499968
    },
    {
      "id": "fineweb2_hq_es",
      "name": "FineWeb2-HQ ES",
      "repo": "epfml/FineWeb2-HQ",
      "config": "spa_Latn",
      "weight": 0.225,
      "target_tokens": 652499968
    },
    {
      "id": "opencoder",
      "name": "OpenCoder FineWeb Code",
      "repo": "OpenCoder-LLM/opc-fineweb-code-corpus",
      "config": null,
      "weight": 0.05,
      "target_tokens": 144999424
    },
    {
      "id": "finemath",
      "name": "FineMath-4+",
      "repo": "HuggingFaceTB/finemath",
      "config": "finemath-4plus",
      "weight": 0.03,
      "target_tokens": 86999040
    },
    {
      "id": "pes2o",
      "name": "peS2o Scientific",
      "repo": "common-pile/peS2o",
      "config": null,
      "weight": 0.02,
      "target_tokens": 58001408
    }
  ]
}
[ OK ] Sequence length = 1024
[ OK ] Metadata vocabulary matches tokenizer.


==============================================================================
TEMPORARY FILE CHECK
==============================================================================
[ OK ] No residual .tmp/.part files found.


==============================================================================
FineWeb-Edu EN
==============================================================================

STATE
{
  "documents_seen": 1193710,
  "tokens_written": 1304999936,
  "shards_written": 82,
  "complete": true
}
[ OK ] State says complete=True.
[ OK ] State token count: 1,304,999,936
[ OK ] State shard count: 82

Manifest entries: 82
[ OK ] Manifest shard count matches expected count.
[ OK ] Manifest tokens: 1,304,999,936
Physical shards: 82
[ OK ] Physical shard count matches expected count.
Checking shards:  82/ 82
[ OK ] Physical tokens: 1,304,999,936
[ OK ] Physical token count matches manifest.
[ OK ] Physical token count matches state.
Token ID range: 0 .. 50256


==============================================================================
FineWeb2-HQ PT
==============================================================================

STATE
{
  "documents_seen": 885429,
  "tokens_written": 652499968,
  "shards_written": 41,
  "complete": true
}
[ OK ] State says complete=True.
[ OK ] State token count: 652,499,968
[ OK ] State shard count: 41

Manifest entries: 41
[ OK ] Manifest shard count matches expected count.
[ OK ] Manifest tokens: 652,499,968
Physical shards: 41
[ OK ] Physical shard count matches expected count.
Checking shards:  41/ 41
[ OK ] Physical tokens: 652,499,968
[ OK ] Physical token count matches manifest.
[ OK ] Physical token count matches state.
Token ID range: 0 .. 50256


==============================================================================
FineWeb2-HQ ES
==============================================================================

STATE
{
  "documents_seen": 888577,
  "tokens_written": 652499968,
  "shards_written": 41,
  "complete": true
}
[ OK ] State says complete=True.
[ OK ] State token count: 652,499,968
[ OK ] State shard count: 41

Manifest entries: 41
[ OK ] Manifest shard count matches expected count.
[ OK ] Manifest tokens: 652,499,968
Physical shards: 41
[ OK ] Physical shard count matches expected count.
Checking shards:  41/ 41
[ OK ] Physical tokens: 652,499,968
[ OK ] Physical token count matches manifest.
[ OK ] Physical token count matches state.
Token ID range: 0 .. 50255


==============================================================================
OpenCoder FineWeb Code
==============================================================================

STATE
{
  "documents_seen": 256742,
  "tokens_written": 144999424,
  "shards_written": 10,
  "complete": true
}
[ OK ] State says complete=True.
[ OK ] State token count: 144,999,424
[ OK ] State shard count: 10

Manifest entries: 10
[ OK ] Manifest shard count matches expected count.
[ OK ] Manifest tokens: 144,999,424
Physical shards: 10
[ OK ] Physical shard count matches expected count.
Checking shards:  10/ 10
[ OK ] Physical tokens: 144,999,424
[ OK ] Physical token count matches manifest.
[ OK ] Physical token count matches state.
Token ID range: 0 .. 50255


==============================================================================
FineMath-4+
==============================================================================

STATE
{
  "documents_seen": 70699,
  "tokens_written": 86999040,
  "shards_written": 6,
  "complete": true
}
[ OK ] State says complete=True.
[ OK ] State token count: 86,999,040
[ OK ] State shard count: 6

Manifest entries: 6
[ OK ] Manifest shard count matches expected count.
[ OK ] Manifest tokens: 86,999,040
Physical shards: 6
[ OK ] Physical shard count matches expected count.
Checking shards:   6/  6
[ OK ] Physical tokens: 86,999,040
[ OK ] Physical token count matches manifest.
[ OK ] Physical token count matches state.
Token ID range: 0 .. 50254


==============================================================================
peS2o Scientific
==============================================================================

STATE
{
  "documents_seen": 8319,
  "tokens_written": 58001408,
  "shards_written": 4,
  "complete": true
}
[ OK ] State says complete=True.
[ OK ] State token count: 58,001,408
[ OK ] State shard count: 4

Manifest entries: 4
[ OK ] Manifest shard count matches expected count.
[ OK ] Manifest tokens: 58,001,408
Physical shards: 4
[ OK ] Physical shard count matches expected count.
Checking shards:   4/  4
[ OK ] Physical tokens: 58,001,408
[ OK ] Physical token count matches manifest.
[ OK ] Physical token count matches state.
Token ID range: 0 .. 50255


==============================================================================
GLOBAL PHYSICAL CHECK
==============================================================================
State tokens:     2,899,999,744
Manifest tokens:  2,899,999,744
Physical tokens:  2,899,999,744
Physical shards:  184
[ OK ] All three independent token counts match.
[ OK ] Total shard count = 184


==============================================================================
RANDOM DECODE TESTS
==============================================================================

These samples are READ-ONLY and are used to visually inspect corpus quality.



##############################################################################
FineWeb-Edu EN
##############################################################################

--- SAMPLE 1/2 ---
Shard: shard-00030.bin
Sequence: 7,971
Tokens: 256

 to them. It was still technically public land, and he was compelled to warn them against cutting timber upon it, insisting they desist at once. He had personally caught them in the act of “timber trespass” — cutting trees on public land — and at once reported the infraction to the Department of the Interior on August 15, 1890. This, however, was one fact that had no detrimental effect on production at the mill, for the warning was patently ignored. One can easily imagine the negative effect this had on Cauldwell’s relationship with the Colony. Tensions between them grew.
Meanwhile, it should be remembered that Vandever had introduced his bill calling for the reservation of the Garfield Grove area and that it was successfully speeding through Congress. On September 11, 1890, the Visalia Delta, in reporting the rapid progression of Vandever’s Sequoia bill, commented that:
In these days of tardy legislation, it seems wonderful that this bill should be introduced in Congress and passed without opposition, and then taken to the Senate where it is favorably reported by the committee on public lands, then presented to the assembly and passed without debate. The bill will be presented to President


--- SAMPLE 2/2 ---
Shard: shard-00040.bin
Sequence: 1,973
Tokens: 256

 link below which will take you to the Copyright Clearance Center’s RightsLink service. You will be able to get a quick price and instant permission to reuse the content in many different ways.</s>About the Campaign
Mold Uncovered is a public awareness campaign that aims to emphasize the importance of proper mold remediation through accredited Industry Standards and Certifications.
Mold is a pervasive, yet largely unregulated, issue in the United States and around the world. Left unchecked, mold issues in indoor environments can have significant, lasting health impacts.
Did you know...
The Centers for Disease Control and Prevention (CDC) note that children, people with asthma or chronic respiratory diseases, and those with immune suppression are among the most vulnerable to adverse effects from mold.1
The World Health Organization’s Guidelines for Indoor Air Quality: Dampness and Mould states that there is sufficient epidemiological evidence showing that those living in damp or moldy buildings are at increased risk of respiratory issues, including more serious or rare concerns such as exacerbated asthma, hypersensitive pneumonitis, chronic rhinosinusitis, and more.2



##############################################################################
FineWeb2-HQ PT
##############################################################################

--- SAMPLE 1/2 ---
Shard: shard-00004.bin
Sequence: 1,270
Tokens: 256

 exterior podem ser avaliados para determinar sua probabilidade de sucesso durante seu programa.
Quais são os resultados dos testes (GRE, GMAT, SAT, TOEFL, IELTS)?
Qual foi o seu GPA anterior?
Como você gerenciará as diferenças culturais e educacionais nos EUA?
Quão bom é o seu inglês?
Por que você deseja obter um diploma nos EUA?
Por que não estudar no Canadá, Austrália ou Reino Unido?
O que você conhece sobre as escolas dos EUA?
Posso ver seu diploma do ensino médio / faculdade?
Saiba mais sobre os tipos de pontuação de teste aceitos pelas escolas dos EUA
Perguntas sobre seu status financeiro
Esta é a parte mais importante da obtenção do seu visto F-1. Independentemente das suas qualificações acadêmicas, você não pode receber um visto de estudante F-1 sem os meios para financiar sua educação. É importante se programar e ter um plano financeiro sólido. Este plano deve incluir mais do que apenas despesas de matrícula. Você deve considerar habitação, comida, transporte, seguro de saúde e todas as outras despesas relevantes.
Qual é a sua renda mensal?
Qual é a renda anual do seu patrocinador (se


--- SAMPLE 2/2 ---
Shard: shard-00031.bin
Sequence: 6,626
Tokens: 256

 E é justamente isso que ela mais é: inteirinha amarela, com o bico e os pezinhos cor de laranja. A Blondie tem um botãozinho do lado direito, que você vira e ela sai bicando sem parar. O que estiver pela frente, ela bica.
Acho que foi principalmente por isso que ela e as irmãs Maria Rosa, Maria Rita e Maria Ruth se deram tão bem. As quatro juntas só pensam em bicar o tempo todo. E bicam qualquer coisa — não são como a Juçara, que é naturalista e só bica arroz integral.
A Blondie foi muito bem recebida no galinheiro. Pela Gabi nem se fala, porque a Gabi gosta de todo mundo. Franga, gente — menos cozinheira. Pela Ulla, porque as duas são estrangeiras. E como a Ullaé muito culta e também fala inglês, as duas podem falar bastante. Imagina que até a Otília recebeu bem a Blondie: ela acha muito chique ser estrangeiro. E a melhor coisa do mundo pra ela, a mais importante, é ser chique. Maria
Rosa, Maria Rita e Maria Ruth, nem se fala: enfim, uma companhia



##############################################################################
FineWeb2-HQ ES
##############################################################################

--- SAMPLE 1/2 ---
Shard: shard-00023.bin
Sequence: 11,167
Tokens: 256

jalá que la Sedena se dé cuenta de la clase de delincuentes que tiene adentro de sus filas. Yo creo que los altos mandos no se dan cuenta de lo que andan haciendo esos delincuentes, porque si se dieran cuenta no hubiera delincuentes como ellos aquí”, subraya la madre de la víctima.
Reconoce que la denuncia le ha traído a su hija estigma, críticas y una férrea acusación de que ella “tuvo la culpa” porque se encontraba en un hotel, pero eso –añade– no justifica que dos o más soldados cometan una violación sexual.
Fuente Proceso</s>Durante demasiado tiempo ha sido presa de Congo. Ahora es su turno de volverse predador. Ex oficial de las Fuerzas Aéreas Especiales de Gran Bretaña y experto en seguridad privada, Hector Cross perdió a su mujer demasiado pronto a manos de Johnny Congo. Ese psicópata cruel y extorsionador es además un peligroso terrorista y Cross quiere verlo muerto tanto como el gobierno de los Estados Unidos. Encerrado en la prisión más segura del mundo, sólo dos semanas separan a Congo del cumplimiento de su sentencia de muerte.
Hazel Bannock es la dueña de Bannock Oil Corporation, uno


--- SAMPLE 2/2 ---
Shard: shard-00006.bin
Sequence: 5,095
Tokens: 256

1982) se trataba de un estilo de personalidad que es fuente de resistencia al estrés, una constelación de tres atributos; compromiso (tendencia a implicarse en las distintas situaciones de la vida), control (influencia activa de la persona en los distintos acontecimientos y sucesos) y reto (búsqueda de cambios, experiencias nuevas, ver la situación estresante como reto y no como amenaza). Estos atributos van a permitir unas estrategias de afrontamiento o de coping eficaces.
Otra característica personal estudiada ha sido el locus de control, que actúa también como moduladora de los efectos del estrés. Es una característica relativamente estable (Rotter, 1966) y se refiere a las creencias de que los eventos de la vida son controlados por las propias acciones (locus interno) o por acontecimientos externos (locus externo). Los sujetos con locus interno asumen que las decisiones, las acciones y los esfuerzos individuales influirán en las consecuencias, lo que provocará expectativas de afrontamiento para enfrentarse al problema de un modo más eficaz que los locus externos, que creen que la suerte, el azar y el destino les determina. Estos últimos sujetos son más propensos a la indefensión y al desamparo.
Otros aspectos implicados en la respuesta



##############################################################################
OpenCoder FineWeb Code
##############################################################################

--- SAMPLE 1/2 ---
Shard: shard-00001.bin
Sequence: 3,031
Tokens: 256

 search or an update test, I need to use a layer that’s able to insert that data. But, if we have a bug or a issue in the “post” method, the test using the “get” or the “patch”/“put” will fail, incorrectly, because the problem isn’t at those methods, but when I’m inserting using the “posts” method.
Can I get some hints about this?</s>Connection & Consents
Establishing the Link between your Forge and Discord account
To link your EPITA Discord account with the Forge platform, you need to follow these steps:
- Visit https://discord.forge.epita.fr/ui.
- You will be prompted to log in using your Discord credentials if not already logged in.
- Upon login, you will be directed to the user interface where you can manage your account and consent settings.
After linking your Discord account, the next step is to grant consent for each server where the EPITA Forge bot is present:
- A Discord message will notify you to grant consent along with a direct link to the


--- SAMPLE 2/2 ---
Shard: shard-00007.bin
Sequence: 4,792
Tokens: 256

 has spoken to dozens of universities and worked closely with select schools to identify and address the biggest pain-points for supporting millennial grads. The result is new Collegefeed for Career Centers, which offers a package of features specifically developed to support career centers of all sizes and focus, including:
Collegefeed’s Connections Engine enables students and employers to get connected faster than ever before. Students simply upload their resumes. Collegefeed analyzes their background and interests and starts presenting them to relevant hiring managers in their network. If any are interested, they contact the student directly. The Collegefeed Connections Engine ensures highly relevant matches and achieves a 30 percent hit rate with employers – compared to only three percent hit rate with traditional job postings.
Searchable Resume Books
The Resume Book is a private, searchable, online database of student profiles that only employers on the Collegefeed network can access. Resumes are automatically converted into beautiful profiles and tagged with appropriate job functions such as “Software Engineering”, “Sales”, “Marketing,” etc. Employers can easily log in, browse profiles by job function and search by major, graduation date, keywords



##############################################################################
FineMath-4+
##############################################################################

--- SAMPLE 1/2 ---
Shard: shard-00002.bin
Sequence: 115
Tokens: 256

an) length of a year is 365.25 days. In a non-leap year, there are 365 days, in a leap year there are 366 days. A leap year occurs every fourth year, or leap year, during which a leap day is intercalated into the month of February. The name “Leap Day” is applied to the added day.

## How often are there 53 weeks in a year?

This occurs approximately every five to six years, though this is not always the case. 2006, 2012, 2017 and 2023 are all 53-week years.

### How many 5 day weeks are there in a year?

There are 52 weeks in a year and 5 working days in each which comes to 260.

### Can a year have 364 days?

The ISO calendar in question is a variation of the Gregorian calendar that is used (mainly) in government and business for fiscal years, as well as in timekeeping. In this system a year (ISO year) has 52 or 53 full weeks (364 or 371 days).

Do we have a week 53 this year? Pay period 53 takes place when there are 53 weekly


--- SAMPLE 2/2 ---
Shard: shard-00001.bin
Sequence: 5,754
Tokens: 256

 substance. Since ancient times, people have used several ways to measure length. A fixed quantity with respect to which a physical quantity is measured is called a unit. A unit is used as a standard of measurement.

## What measurements are used in science?

The SI system, also called the metric system, is used around the world. There are seven basic units in the SI system: the meter (m), the kilogram ( kg ), the second (s), the kelvin (K), the ampere (A), the mole (mol), and the candela (cd).

You might be interested:  Quick Answer: When Does Human Life Begin According To Science?

## What is measurement explain with example?

Measurement is defined as the act of measuring or the size of something. An example of measurement means the use of a ruler to determine the length of a piece of paper. An example of measurement is 15″ by 25″. noun.

## What are the 3 types of measurement?

The three standard systems of measurements are the International System of Units (SI) units, British Imperial System, and the US Customary System.






In [ ]:
# ============================================================
# MAIA LITE - VALIDATION CORPUS V2 MATERIALIZER
#
# PURPOSE
# -------
# Build a fixed, held-out validation corpus for Maia Lite.
#
# IMPORTANT
# ---------
# - Uses the same six source families as Maia Corpus V2.
# - Skips ALL documents consumed during training corpus creation.
# - Validation therefore begins strictly AFTER the training
#   boundary recorded in each training source state file.
# - Does NOT modify Maia Corpus V2.
# - Materializes validation data on Google Drive.
# - Stores token IDs as uint16.
# - Inserts EOS between documents.
# - Every shard is aligned to 1024-token sequences.
# - Fully resumable after completed shards.
#
# VALIDATION SIZE
# ---------------
# Requested: 20,000,000 tokens
# Actual aligned target: 19,999,744 tokens
#
# DISTRIBUTION
# ------------
# FineWeb-Edu EN       45.0%
# FineWeb2-HQ PT       22.5%
# FineWeb2-HQ ES       22.5%
# OpenCoder             5.0%
# FineMath-4+           3.0%
# peS2o Scientific      2.0%
#
# ============================================================


# ============================================================
# 0. INSTALL / MOUNT
# ============================================================

!pip -q install -U datasets transformers

from google.colab import drive

drive.mount(
    "/content/drive"
)


# ============================================================
# 1. IMPORTS
# ============================================================

import os
import json
import hashlib
import time

from pathlib import Path

import numpy as np

from datasets import load_dataset

from transformers import (
    GPT2TokenizerFast
)


# ============================================================
# 2. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = (
    PROJECT_DIR
    / "tokenizador"
)

TRAIN_CORPUS_DIR = (
    PROJECT_DIR
    / "corpus_v2"
)

TRAIN_STATE_DIR = (
    TRAIN_CORPUS_DIR
    / "state"
)

VALIDATION_DIR = (
    PROJECT_DIR
    / "validation_corpus_v2"
)

VALIDATION_DATA_DIR = (
    VALIDATION_DIR
    / "data"
)

VALIDATION_STATE_DIR = (
    VALIDATION_DIR
    / "state"
)

VALIDATION_MANIFEST_DIR = (
    VALIDATION_DIR
    / "manifests"
)

VALIDATION_METADATA_FILE = (
    VALIDATION_DIR
    / "metadata.json"
)


# ============================================================
# 3. GLOBAL CONFIGURATION
# ============================================================

TARGET_TOTAL_TOKENS = 20_000_000

SEQUENCE_LENGTH = 1024

# ------------------------------------------------------------
# IMPORTANT:
#
# 4,194,304 = 4096 * 1024
#
# Therefore every full shard contains exactly 4096 complete
# training/validation sequences.
#
# uint16:
#
# 4,194,304 * 2 bytes = 8,388,608 bytes = exactly 8 MiB.
# ------------------------------------------------------------

SHARD_TOKENS = 4_194_304

DTYPE = np.uint16

SEED = 42


# ============================================================
# 4. SANITY CHECK CONFIGURATION
# ============================================================

if (
    SHARD_TOKENS
    % SEQUENCE_LENGTH
    != 0
):

    raise RuntimeError(
        "SHARD_TOKENS must be divisible "
        "by SEQUENCE_LENGTH."
    )


print(
    f"Sequences per full shard: "
    f"{SHARD_TOKENS // SEQUENCE_LENGTH:,}"
)


# ============================================================
# 5. CREATE DIRECTORIES
# ============================================================

VALIDATION_DIR.mkdir(
    parents=True,
    exist_ok=True
)

VALIDATION_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

VALIDATION_STATE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

VALIDATION_MANIFEST_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 6. LOAD TOKENIZER
# ============================================================

print(
    "\nLoading Maia Lite tokenizer..."
)

tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)

VOCAB_SIZE = len(
    tokenizer
)

EOS_TOKEN_ID = (
    tokenizer.eos_token_id
)


print(
    f"Vocabulary size: "
    f"{VOCAB_SIZE:,}"
)

print(
    f"EOS token:       "
    f"{EOS_TOKEN_ID}"
)


if VOCAB_SIZE > 65535:

    raise RuntimeError(
        "Vocabulary does not fit uint16."
    )


if EOS_TOKEN_ID is None:

    raise RuntimeError(
        "Tokenizer has no EOS token."
    )


# ============================================================
# 7. SOURCE DEFINITIONS
# ============================================================

SOURCES = [

    {
        "id":
            "fineweb_edu_en",

        "name":
            "FineWeb-Edu EN",

        "repo":
            "HuggingFaceFW/fineweb-edu",

        "config":
            "sample-10BT",

        "split":
            "train",

        "weight":
            0.45,
    },

    {
        "id":
            "fineweb2_hq_pt",

        "name":
            "FineWeb2-HQ PT",

        "repo":
            "epfml/FineWeb2-HQ",

        "config":
            "por_Latn",

        "split":
            "train",

        "weight":
            0.225,
    },

    {
        "id":
            "fineweb2_hq_es",

        "name":
            "FineWeb2-HQ ES",

        "repo":
            "epfml/FineWeb2-HQ",

        "config":
            "spa_Latn",

        "split":
            "train",

        "weight":
            0.225,
    },

    {
        "id":
            "opencoder",

        "name":
            "OpenCoder FineWeb Code",

        "repo":
            "OpenCoder-LLM/"
            "opc-fineweb-code-corpus",

        "config":
            None,

        "split":
            "train",

        "weight":
            0.05,
    },

    {
        "id":
            "finemath",

        "name":
            "FineMath-4+",

        "repo":
            "HuggingFaceTB/finemath",

        "config":
            "finemath-4plus",

        "split":
            "train",

        "weight":
            0.03,
    },

    {
        "id":
            "pes2o",

        "name":
            "peS2o Scientific",

        "repo":
            "common-pile/peS2o",

        "config":
            None,

        "split":
            "train",

        "weight":
            0.02,
    },
]


# ============================================================
# 8. VALIDATION TARGET CALCULATION
#
# Every source target is aligned to 1024 tokens.
# ============================================================

remaining = (
    TARGET_TOTAL_TOKENS
)


for index, source in enumerate(
    SOURCES
):

    if index < len(SOURCES) - 1:

        raw_target = int(
            TARGET_TOTAL_TOKENS
            * source["weight"]
        )


        aligned_target = (
            raw_target
            // SEQUENCE_LENGTH
            * SEQUENCE_LENGTH
        )


        source[
            "target_tokens"
        ] = aligned_target


        remaining -= (
            aligned_target
        )

    else:

        aligned_remaining = (
            remaining
            // SEQUENCE_LENGTH
            * SEQUENCE_LENGTH
        )


        source[
            "target_tokens"
        ] = aligned_remaining


ACTUAL_TARGET_TOTAL = sum(
    source["target_tokens"]
    for source in SOURCES
)


if (
    ACTUAL_TARGET_TOTAL
    % SEQUENCE_LENGTH
    != 0
):

    raise RuntimeError(
        "Validation target is not "
        "sequence aligned."
    )


# ============================================================
# 9. READ TRAINING BOUNDARIES
#
# This is critical for keeping validation held out.
# ============================================================

print(
    "\nReading training boundaries..."
)


for source in SOURCES:

    train_state_file = (
        TRAIN_STATE_DIR
        / f"{source['id']}.json"
    )


    if not train_state_file.exists():

        raise RuntimeError(
            f"Missing training state file: "
            f"{train_state_file}"
        )


    with open(
        train_state_file,
        "r",
        encoding="utf-8"
    ) as f:

        train_state = json.load(
            f
        )


    if not train_state.get(
        "complete",
        False
    ):

        raise RuntimeError(
            f"Training source "
            f"{source['name']} "
            f"is not marked complete."
        )


    source[
        "training_documents_seen"
    ] = int(
        train_state[
            "documents_seen"
        ]
    )


    source[
        "training_tokens"
    ] = int(
        train_state[
            "tokens_written"
        ]
    )


    print(
        f"{source['name']:32s} | "
        f"skip training docs = "
        f"{source['training_documents_seen']:,}"
    )


# ============================================================
# 10. SAVE VALIDATION METADATA
# ============================================================

metadata = {

    "name":
        "Maia Validation Corpus V2",

    "format":
        "uint16",

    "sequence_length":
        SEQUENCE_LENGTH,

    "requested_total_tokens":
        TARGET_TOTAL_TOKENS,

    "actual_target_total_tokens":
        ACTUAL_TARGET_TOTAL,

    "shard_tokens":
        SHARD_TOKENS,

    "sequences_per_full_shard":
        (
            SHARD_TOKENS
            // SEQUENCE_LENGTH
        ),

    "vocab_size":
        VOCAB_SIZE,

    "eos_token_id":
        EOS_TOKEN_ID,

    "seed":
        SEED,

    "held_out_strategy":
        (
            "For each source, skip all "
            "documents consumed during "
            "Maia Corpus V2 materialization, "
            "then collect subsequent documents."
        ),

    "sources":
        [],
}


for source in SOURCES:

    metadata[
        "sources"
    ].append({

        "id":
            source["id"],

        "name":
            source["name"],

        "repo":
            source["repo"],

        "config":
            source["config"],

        "weight":
            source["weight"],

        "target_tokens":
            source["target_tokens"],

        "training_documents_seen":
            source[
                "training_documents_seen"
            ],

        "training_tokens":
            source[
                "training_tokens"
            ],
    })


with open(
    VALIDATION_METADATA_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        metadata,
        f,
        indent=2,
        ensure_ascii=False
    )


# ============================================================
# 11. STATE HELPERS
# ============================================================

def state_path(
    source_id
):

    return (
        VALIDATION_STATE_DIR
        / f"{source_id}.json"
    )


def manifest_path(
    source_id
):

    return (
        VALIDATION_MANIFEST_DIR
        / f"{source_id}.jsonl"
    )


def source_data_dir(
    source_id
):

    path = (
        VALIDATION_DATA_DIR
        / source_id
    )


    path.mkdir(
        parents=True,
        exist_ok=True
    )


    return path


def default_state():

    return {

        # Number of candidate rows consumed
        # AFTER the training boundary.
        "validation_documents_seen":
            0,

        "tokens_written":
            0,

        "shards_written":
            0,

        "complete":
            False,
    }


def load_state(
    source_id
):

    path = state_path(
        source_id
    )


    if not path.exists():

        return default_state()


    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(
            f
        )


def save_state(
    source_id,
    state
):

    path = state_path(
        source_id
    )


    tmp_path = Path(
        str(path)
        + ".tmp"
    )


    with open(
        tmp_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            state,
            f,
            indent=2
        )


        f.flush()

        os.fsync(
            f.fileno()
        )


    os.replace(
        tmp_path,
        path
    )


# ============================================================
# 12. SHA-256
# ============================================================

def sha256_file(
    path
):

    digest = (
        hashlib.sha256()
    )


    with open(
        path,
        "rb"
    ) as f:

        while True:

            chunk = f.read(
                8 * 1024 * 1024
            )


            if not chunk:

                break


            digest.update(
                chunk
            )


    return (
        digest.hexdigest()
    )


# ============================================================
# 13. MANIFEST
# ============================================================

def append_manifest(
    source_id,
    entry
):

    path = manifest_path(
        source_id
    )


    with open(
        path,
        "a",
        encoding="utf-8"
    ) as f:

        f.write(
            json.dumps(
                entry,
                ensure_ascii=False
            )
        )


        f.write(
            "\n"
        )


        f.flush()

        os.fsync(
            f.fileno()
        )


# ============================================================
# 14. WRITE SHARD
# ============================================================

def write_shard(
    source,
    shard_index,
    token_buffer
):

    source_id = (
        source["id"]
    )


    output_dir = (
        source_data_dir(
            source_id
        )
    )


    usable_tokens = (
        len(token_buffer)
        // SEQUENCE_LENGTH
        * SEQUENCE_LENGTH
    )


    if usable_tokens <= 0:

        return 0


    if (
        usable_tokens
        % SEQUENCE_LENGTH
        != 0
    ):

        raise RuntimeError(
            "Internal alignment error."
        )


    token_array = np.asarray(
        token_buffer[
            :usable_tokens
        ],
        dtype=DTYPE
    )


    if (
        len(token_array)
        != usable_tokens
    ):

        raise RuntimeError(
            "Unexpected token array size."
        )


    if (
        int(token_array.max())
        >= VOCAB_SIZE
    ):

        raise RuntimeError(
            f"Invalid token ID in "
            f"{source['name']}."
        )


    filename = (
        f"shard-"
        f"{shard_index:05d}.bin"
    )


    final_path = (
        output_dir
        / filename
    )


    tmp_path = Path(
        str(final_path)
        + ".tmp"
    )


    # Never silently overwrite data.

    if final_path.exists():

        raise RuntimeError(
            f"Refusing to overwrite "
            f"existing shard: "
            f"{final_path}"
        )


    with open(
        tmp_path,
        "wb"
    ) as f:

        token_array.tofile(
            f
        )


        f.flush()

        os.fsync(
            f.fileno()
        )


    os.replace(
        tmp_path,
        final_path
    )


    actual_bytes = (
        final_path.stat().st_size
    )


    expected_bytes = (
        usable_tokens
        * np.dtype(DTYPE).itemsize
    )


    if (
        actual_bytes
        != expected_bytes
    ):

        raise RuntimeError(
            f"Shard byte size mismatch: "
            f"{actual_bytes:,} != "
            f"{expected_bytes:,}"
        )


    checksum = (
        sha256_file(
            final_path
        )
    )


    manifest_entry = {

        "filename":
            str(
                final_path.relative_to(
                    VALIDATION_DIR
                )
            ),

        "tokens":
            int(
                usable_tokens
            ),

        "bytes":
            int(
                actual_bytes
            ),

        "sha256":
            checksum,
    }


    append_manifest(
        source_id,
        manifest_entry
    )


    return int(
        usable_tokens
    )


# ============================================================
# 15. DOCUMENT FILTER
#
# Keep consistent with Maia Corpus V2.
# ============================================================

def accept_document(
    source,
    row,
    text
):

    if text is None:

        return False


    if not isinstance(
        text,
        str
    ):

        return False


    if len(
        text.strip()
    ) < 200:

        return False


    # Same FineMath filter used during training
    # corpus materialization.

    if (
        source["id"]
        == "finemath"
    ):

        language_score = (
            row.get(
                "language_score"
            )
        )


        if (
            language_score
            is not None
        ):

            try:

                if float(
                    language_score
                ) < 0.80:

                    return False

            except Exception:

                pass


    return True


# ============================================================
# 16. LOAD STREAMING DATASET
# ============================================================

def load_source_dataset(
    source
):

    kwargs = {

        "path":
            source["repo"],

        "split":
            source["split"],

        "streaming":
            True,
    }


    if (
        source["config"]
        is not None
    ):

        kwargs[
            "name"
        ] = source[
            "config"
        ]


    return load_dataset(
        **kwargs
    )


# ============================================================
# 17. RESUME INTEGRITY CHECK
# ============================================================

def verify_resume_state(
    source,
    state
):

    source_id = (
        source["id"]
    )


    output_dir = (
        source_data_dir(
            source_id
        )
    )


    physical_shards = sorted(
        output_dir.glob(
            "shard-*.bin"
        )
    )


    if (
        len(physical_shards)
        != state[
            "shards_written"
        ]
    ):

        raise RuntimeError(
            f"{source['name']}: "
            f"physical shard count "
            f"{len(physical_shards)} "
            f"does not match state "
            f"{state['shards_written']}."
        )


    physical_tokens = sum(

        path.stat().st_size
        // np.dtype(DTYPE).itemsize

        for path
        in physical_shards
    )


    if (
        physical_tokens
        != state[
            "tokens_written"
        ]
    ):

        raise RuntimeError(
            f"{source['name']}: "
            f"physical tokens "
            f"{physical_tokens:,} "
            f"do not match state "
            f"{state['tokens_written']:,}."
        )


    manifest_file = (
        manifest_path(
            source_id
        )
    )


    if manifest_file.exists():

        with open(
            manifest_file,
            "r",
            encoding="utf-8"
        ) as f:

            manifest_entries = [

                line

                for line
                in f

                if line.strip()
            ]

    else:

        manifest_entries = []


    if (
        len(manifest_entries)
        != state[
            "shards_written"
        ]
    ):

        raise RuntimeError(
            f"{source['name']}: "
            f"manifest entries "
            f"{len(manifest_entries)} "
            f"do not match state "
            f"{state['shards_written']}."
        )


# ============================================================
# 18. MATERIALIZE ONE SOURCE
# ============================================================

def materialize_source(
    source
):

    source_id = (
        source["id"]
    )

    source_name = (
        source["name"]
    )

    target_tokens = int(
        source[
            "target_tokens"
        ]
    )

    training_skip = int(
        source[
            "training_documents_seen"
        ]
    )


    state = load_state(
        source_id
    )


    print(
        "\n"
    )

    print(
        "=" * 78
    )

    print(
        source_name
    )

    print(
        "=" * 78
    )


    print(
        f"Target tokens:        "
        f"{target_tokens:,}"
    )

    print(
        f"Training docs skip:   "
        f"{training_skip:,}"
    )

    print(
        f"Validation docs seen: "
        f"{state['validation_documents_seen']:,}"
    )

    print(
        f"Already written:      "
        f"{state['tokens_written']:,}"
    )

    print(
        f"Completed shards:     "
        f"{state['shards_written']:,}"
    )


    # --------------------------------------------------------
    # Already complete
    # --------------------------------------------------------

    if state.get(
        "complete",
        False
    ):

        if (
            state[
                "tokens_written"
            ]
            != target_tokens
        ):

            raise RuntimeError(
                f"{source_name} is marked "
                f"complete but token count "
                f"does not match target."
            )


        verify_resume_state(
            source,
            state
        )


        print(
            "SOURCE ALREADY COMPLETE."
        )


        return


    # --------------------------------------------------------
    # Verify resume consistency before doing anything.
    # --------------------------------------------------------

    verify_resume_state(
        source,
        state
    )


    # --------------------------------------------------------
    # Load source stream.
    # --------------------------------------------------------

    dataset = (
        load_source_dataset(
            source
        )
    )


    # --------------------------------------------------------
    # Skip ALL documents consumed during training.
    # --------------------------------------------------------

    print(
        f"Skipping "
        f"{training_skip:,} "
        f"training documents..."
    )


    dataset = dataset.skip(
        training_skip
    )


    # --------------------------------------------------------
    # Skip validation rows consumed in previous completed
    # validation shards.
    # --------------------------------------------------------

    validation_skip = int(
        state[
            "validation_documents_seen"
        ]
    )


    if validation_skip > 0:

        print(
            f"Skipping "
            f"{validation_skip:,} "
            f"previously processed "
            f"validation documents..."
        )


        dataset = dataset.skip(
            validation_skip
        )


    # --------------------------------------------------------
    # Current in-memory shard.
    # --------------------------------------------------------

    shard_buffer = []

    shard_tokens = 0

    start_time = (
        time.time()
    )

    last_status_time = (
        start_time
    )


    # ========================================================
    # STREAM
    # ========================================================

    for row in dataset:

        # ----------------------------------------------------
        # CRITICAL FIX:
        #
        # Stop based on persisted tokens PLUS the current
        # in-memory shard.
        # ----------------------------------------------------

        effective_tokens = (
            state[
                "tokens_written"
            ]
            + shard_tokens
        )


        if (
            effective_tokens
            >= target_tokens
        ):

            break


        state[
            "validation_documents_seen"
        ] += 1


        text = row.get(
            "text"
        )


        if not accept_document(
            source,
            row,
            text
        ):

            continue


        token_ids = (
            tokenizer.encode(
                text,
                add_special_tokens=False
            )
        )


        if len(
            token_ids
        ) == 0:

            continue


        # Explicit document boundary.

        token_ids.append(
            EOS_TOKEN_ID
        )


        token_position = 0


        # ====================================================
        # CONSUME CURRENT DOCUMENT
        # ====================================================

        while (
            token_position
            < len(token_ids)
        ):

            remaining_source = (
                target_tokens
                - state[
                    "tokens_written"
                ]
                - shard_tokens
            )


            if (
                remaining_source
                <= 0
            ):

                break


            remaining_shard = (
                SHARD_TOKENS
                - shard_tokens
            )


            take = min(

                len(token_ids)
                - token_position,

                remaining_source,

                remaining_shard
            )


            if take <= 0:

                break


            shard_buffer.extend(

                token_ids[
                    token_position:
                    token_position
                    + take
                ]
            )


            shard_tokens += (
                take
            )


            token_position += (
                take
            )


            # =================================================
            # FULL SHARD
            # =================================================

            if (
                shard_tokens
                == SHARD_TOKENS
            ):

                written = (
                    write_shard(
                        source,
                        state[
                            "shards_written"
                        ],
                        shard_buffer
                    )
                )


                # With the corrected SHARD_TOKENS this MUST
                # always match exactly.

                if (
                    written
                    != SHARD_TOKENS
                ):

                    raise RuntimeError(
                        f"Unexpected full shard "
                        f"size: {written:,} "
                        f"!= {SHARD_TOKENS:,}"
                    )


                state[
                    "tokens_written"
                ] += written


                state[
                    "shards_written"
                ] += 1


                shard_buffer = []

                shard_tokens = 0


                save_state(
                    source_id,
                    state
                )


                print(
                    f"\nSHARD "
                    f"{state['shards_written']:05d} "
                    f"COMPLETE"
                )


                print(
                    f"Tokens: "
                    f"{state['tokens_written']:,}"
                    f" / "
                    f"{target_tokens:,}"
                )


                print(
                    f"Progress: "
                    f"{100.0 * state['tokens_written'] / target_tokens:.2f}%"
                )


        # ----------------------------------------------------
        # Periodic status.
        # ----------------------------------------------------

        now = time.time()


        if (
            now
            - last_status_time
            >= 30
        ):

            effective_tokens = (
                state[
                    "tokens_written"
                ]
                + shard_tokens
            )


            progress = (
                100.0
                * effective_tokens
                / target_tokens
            )


            print(
                f"docs="
                f"{state['validation_documents_seen']:,}"
                f" | tokens≈"
                f"{effective_tokens:,}"
                f" | {progress:.2f}%"
                f" | current_buffer="
                f"{shard_tokens:,}"
            )


            last_status_time = (
                now
            )


    # ========================================================
    # FINAL PARTIAL SHARD
    # ========================================================

    remaining = (
        target_tokens
        - state[
            "tokens_written"
        ]
    )


    if remaining > 0:

        if (
            shard_tokens
            < remaining
        ):

            raise RuntimeError(
                f"{source_name}: stream ended "
                f"before target was reached. "
                f"Need {remaining:,} tokens; "
                f"buffer contains "
                f"{shard_tokens:,}."
            )


        if (
            remaining
            % SEQUENCE_LENGTH
            != 0
        ):

            raise RuntimeError(
                f"{source_name}: final "
                f"remaining token count "
                f"is not divisible by "
                f"{SEQUENCE_LENGTH}."
            )


        final_buffer = (
            shard_buffer[
                :remaining
            ]
        )


        written = (
            write_shard(
                source,
                state[
                    "shards_written"
                ],
                final_buffer
            )
        )


        if (
            written
            != remaining
        ):

            raise RuntimeError(
                f"{source_name}: final "
                f"shard wrote "
                f"{written:,} tokens; "
                f"expected "
                f"{remaining:,}."
            )


        state[
            "tokens_written"
        ] += written


        state[
            "shards_written"
        ] += 1


    # ========================================================
    # FINALIZE SOURCE
    # ========================================================

    if (
        state[
            "tokens_written"
        ]
        != target_tokens
    ):

        raise RuntimeError(
            f"{source_name}: final "
            f"token count mismatch "
            f"{state['tokens_written']:,} "
            f"!= "
            f"{target_tokens:,}"
        )


    state[
        "complete"
    ] = True


    save_state(
        source_id,
        state
    )


    # Final physical consistency check.

    verify_resume_state(
        source,
        state
    )


    elapsed = (
        time.time()
        - start_time
    )


    print()


    print(
        f"Final tokens:    "
        f"{state['tokens_written']:,}"
    )


    print(
        f"Shards:          "
        f"{state['shards_written']:,}"
    )


    print(
        f"Validation docs: "
        f"{state['validation_documents_seen']:,}"
    )


    print(
        f"Runtime:         "
        f"{elapsed / 3600:.2f} h"
    )


    print(
        f"Complete:        "
        f"{state['complete']}"
    )


# ============================================================
# 19. PRINT PLAN
# ============================================================

print(
    "\n"
)

print(
    "=" * 78
)

print(
    "MAIA VALIDATION CORPUS V2"
)

print(
    "=" * 78
)


print(
    f"Requested total: "
    f"{TARGET_TOTAL_TOKENS:,} tokens"
)


print(
    f"Aligned total:   "
    f"{ACTUAL_TARGET_TOTAL:,} tokens"
)


print(
    f"Full shard size: "
    f"{SHARD_TOKENS:,} tokens"
)


print(
    f"Sequences/shard: "
    f"{SHARD_TOKENS // SEQUENCE_LENGTH:,}"
)


print()


for source in SOURCES:

    print(
        f"{source['name']:32s} "
        f"{100 * source['weight']:5.1f}% "
        f"{source['target_tokens']:>12,} tokens "
        f"| training skip="
        f"{source['training_documents_seen']:,}"
    )


print(
    "=" * 78
)


# ============================================================
# 20. MATERIALIZE ALL SOURCES
# ============================================================

for source in SOURCES:

    materialize_source(
        source
    )


# ============================================================
# 21. FINAL SUMMARY
# ============================================================

print(
    "\n"
)

print(
    "=" * 78
)

print(
    "MAIA VALIDATION CORPUS V2 "
    "- FINAL SUMMARY"
)

print(
    "=" * 78
)


total_tokens = 0

total_shards = 0

all_complete = True


for source in SOURCES:

    state = load_state(
        source["id"]
    )


    total_tokens += int(
        state[
            "tokens_written"
        ]
    )


    total_shards += int(
        state[
            "shards_written"
        ]
    )


    all_complete = (
        all_complete
        and bool(
            state[
                "complete"
            ]
        )
    )


    print(
        f"{source['name']:32s} "
        f"{state['tokens_written']:>12,} tokens "
        f"| "
        f"{state['shards_written']:3d} shards "
        f"| complete="
        f"{state['complete']}"
    )


print(
    "-" * 78
)


print(
    f"TOTAL:        "
    f"{total_tokens:,} tokens"
)


print(
    f"SHARDS:       "
    f"{total_shards:,}"
)


print(
    f"ALL COMPLETE: "
    f"{all_complete}"
)


print(
    f"Disk payload: "
    f"~{total_tokens * 2 / 1e9:.3f} GB"
)


print(
    "=" * 78
)


if (
    total_tokens
    == ACTUAL_TARGET_TOTAL
    and all_complete
):

    print()

    print(
        "VALIDATION CORPUS V2 "
        "SUCCESSFULLY MATERIALIZED."
    )

    print(
        "This validation corpus is now "
        "fixed and should not be modified."
    )

else:

    print()

    print(
        "WARNING: VALIDATION CORPUS "
        "IS NOT COMPLETE."
    )

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Sequences per full shard: 4,096

Loading Maia Lite tokenizer...
Vocabulary size: 50,257
EOS token:       2

Reading training boundaries...
FineWeb-Edu EN                   | skip training docs = 1,193,710
FineWeb2-HQ PT                   | skip training docs = 885,429
FineWeb2-HQ ES                   | skip training docs = 888,577
OpenCoder FineWeb Code           | skip training docs = 256,742
FineMath-4+                      | skip training docs = 70,699
peS2o Scientific                 | skip training docs = 8,319


==============================================================================
MAIA VALIDATION CORPUS V2
==============================================================================
Requested total: 20,000,000 tokens
Aligned total:   19,999,744 tokens
Full shard size: 4,194,304 tokens
Sequences/shard: 4,096

FineWeb-Edu EN                    45.0%    8,999,936 tokens | training skip=1,193,710
FineWeb2-HQ PT                    22.5%    4,499,456 tokens | training skip=885,429
FineWeb2-HQ ES                    22.5%    4,499,456 tokens | training skip=888,577
OpenCoder FineWeb Code             5.0%      999,424 tokens | training skip=256,742
FineMath-4+                        3.0%      599,040 tokens | training skip=70,699
peS2o Scientific                   2.0%      402,432 tokens | training skip=8,319
==============================================================================


==============================================================================
FineWeb-Edu EN
==============================================================================
Target tokens:        8,999,936
Training docs skip:   1,193,710
Validation docs seen: 0
Already written:      0
Completed shards:     0

Resolving data files:   0%|          | 0/2410 [00:00<?, ?it/s]

Skipping 1,193,710 training documents...
docs=1 | tokens≈646 | 0.01% | current_buffer=646

SHARD 00001 COMPLETE
Tokens: 4,194,304 / 8,999,936
Progress: 46.60%

SHARD 00002 COMPLETE
Tokens: 8,388,608 / 8,999,936
Progress: 93.21%
docs=8,081 | tokens≈8,409,181 | 93.44% | current_buffer=20,573

Final tokens:    8,999,936
Shards:          3
Validation docs: 8,601
Runtime:         0.03 h
Complete:        True


==============================================================================
FineWeb2-HQ PT
==============================================================================
Target tokens:        4,499,456
Training docs skip:   885,429
Validation docs seen: 0
Already written:      0
Completed shards:     0

README.md:   0%|          | 0.00/9.61k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/1205 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Skipping 885,429 training documents...
docs=1 | tokens≈219 | 0.00% | current_buffer=219

SHARD 00001 COMPLETE
Tokens: 4,194,304 / 4,499,456
Progress: 93.22%

Final tokens:    4,499,456
Shards:          2
Validation docs: 7,273
Runtime:         0.11 h
Complete:        True


==============================================================================
FineWeb2-HQ ES
==============================================================================
Target tokens:        4,499,456
Training docs skip:   888,577
Validation docs seen: 0
Already written:      0
Completed shards:     0

Resolving data files:   0%|          | 0/1205 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/504 [00:00<?, ?it/s]

Skipping 888,577 training documents...
docs=1 | tokens≈86 | 0.00% | current_buffer=86

SHARD 00001 COMPLETE
Tokens: 4,194,304 / 4,499,456
Progress: 93.22%

Final tokens:    4,499,456
Shards:          2
Validation docs: 4,655
Runtime:         0.11 h
Complete:        True


==============================================================================
OpenCoder FineWeb Code
==============================================================================
Target tokens:        999,424
Training docs skip:   256,742
Validation docs seen: 0
Already written:      0
Completed shards:     0

README.md:   0%|          | 0.00/2.79k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/510 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/510 [00:00<?, ?it/s]

Skipping 256,742 training documents...

Final tokens:    999,424
Shards:          1
Validation docs: 1,804
Runtime:         0.00 h
Complete:        True


==============================================================================
FineMath-4+
==============================================================================
Target tokens:        599,040
Training docs skip:   70,699
Validation docs seen: 0
Already written:      0
Completed shards:     0

README.md:   0%|          | 0.00/12.4k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/128 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/64 [00:00<?, ?it/s]

Skipping 70,699 training documents...

Final tokens:    599,040
Shards:          1
Validation docs: 517
Runtime:         0.00 h
Complete:        True


==============================================================================
peS2o Scientific
==============================================================================
Target tokens:        402,432
Training docs skip:   8,319
Validation docs seen: 0
Already written:      0
Completed shards:     0

README.md:   0%|          | 0.00/5.71k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/102 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/102 [00:00<?, ?it/s]

Skipping 8,319 training documents...

Final tokens:    402,432
Shards:          1
Validation docs: 58
Runtime:         0.00 h
Complete:        True


==============================================================================
MAIA VALIDATION CORPUS V2 - FINAL SUMMARY
==============================================================================
FineWeb-Edu EN                      8,999,936 tokens |   3 shards | complete=True
FineWeb2-HQ PT                      4,499,456 tokens |   2 shards | complete=True
FineWeb2-HQ ES                      4,499,456 tokens |   2 shards | complete=True
OpenCoder FineWeb Code                999,424 tokens |   1 shards | complete=True
FineMath-4+                           599,040 tokens |   1 shards | complete=True
peS2o Scientific                      402,432 tokens |   1 shards | complete=True
------------------------------------------------------------------------------
TOTAL:        19,999,744 tokens
SHARDS:       10
ALL COMPLETE: True
Disk payload: ~0.040 GB
==============================================================================

VALIDATION CORPUS V2 SUCCESSFULLY MATERIALIZED.
This validation corpus is now fixed and should not be modified.

In [ ]:
from pathlib import Path
import shutil
import time

validation_dir = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite/"
    "validation_corpus_v2"
)

print("Validation directory:")
print(validation_dir)
print()

if validation_dir.exists():

    print("Contents BEFORE removal:")

    for p in validation_dir.rglob("*"):
        print(" ", p)

    print()
    print("Removing validation_corpus_v2...")

    shutil.rmtree(validation_dir)

    # Give Google Drive a moment to synchronize.
    time.sleep(2)

else:

    print("Directory did not exist.")

print()

if validation_dir.exists():

    raise RuntimeError(
        "validation_corpus_v2 still exists after removal. "
        "Google Drive may not have synchronized the deletion."
    )

else:

    print("SUCCESS.")
    print("validation_corpus_v2 no longer exists.")
    print()
    print("The training corpus_v2 was NOT touched.")

Validation directory:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2

Contents BEFORE removal:
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/data
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/state
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/manifests
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/metadata.json
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/data/fineweb_edu_en
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/manifests/fineweb_edu_en.jsonl
  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/data/fineweb_edu_en/shard-00000.bin

Removing validation_corpus_v2...

SUCCESS.
validation_corpus_v2 no longer exists.

The training corpus_v2 was NOT touched.

In [ ]:
# ============================================================
# MAIA LITE - VALIDATION CORPUS V2 - FINAL AUDIT
#
# READ-ONLY AUDIT
#
# Checks:
#   1. Metadata
#   2. Source states
#   3. Manifest consistency
#   4. Physical shard existence
#   5. SHA-256 integrity
#   6. File size / token count
#   7. 1024-token alignment
#   8. Token ID range
#   9. Global token count
#  10. Temporary/orphan files
#  11. EOS statistics
#  12. Random decoded samples
#
# IMPORTANT:
#   This cell DOES NOT modify the validation corpus.
# ============================================================


# ============================================================
# 0. IMPORTS
# ============================================================

import json
import hashlib
import random
import time

from pathlib import Path

import numpy as np

from transformers import GPT2TokenizerFast


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = (
    PROJECT_DIR
    / "tokenizador"
)

VALIDATION_DIR = (
    PROJECT_DIR
    / "validation_corpus_v2"
)

DATA_DIR = (
    VALIDATION_DIR
    / "data"
)

STATE_DIR = (
    VALIDATION_DIR
    / "state"
)

MANIFEST_DIR = (
    VALIDATION_DIR
    / "manifests"
)

METADATA_FILE = (
    VALIDATION_DIR
    / "metadata.json"
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

SEQUENCE_LENGTH = 1024

EXPECTED_TOTAL_TOKENS = 19_999_744

DTYPE = np.uint16

DTYPE_BYTES = np.dtype(
    DTYPE
).itemsize

RANDOM_SEED = 42

# Number of decoded samples per source.
SAMPLES_PER_SOURCE = 2

# Number of tokens shown in each sample.
SAMPLE_TOKENS = 256


random.seed(
    RANDOM_SEED
)


# ============================================================
# 3. EXPECTED SOURCES
# ============================================================

EXPECTED_SOURCES = {

    "fineweb_edu_en": {
        "name":
            "FineWeb-Edu EN",

        "tokens":
            8_999_936,

        "shards":
            3,
    },

    "fineweb2_hq_pt": {
        "name":
            "FineWeb2-HQ PT",

        "tokens":
            4_499_456,

        "shards":
            2,
    },

    "fineweb2_hq_es": {
        "name":
            "FineWeb2-HQ ES",

        "tokens":
            4_499_456,

        "shards":
            2,
    },

    "opencoder": {
        "name":
            "OpenCoder FineWeb Code",

        "tokens":
            999_424,

        "shards":
            1,
    },

    "finemath": {
        "name":
            "FineMath-4+",

        "tokens":
            599_040,

        "shards":
            1,
    },

    "pes2o": {
        "name":
            "peS2o Scientific",

        "tokens":
            402_432,

        "shards":
            1,
    },
}


# ============================================================
# 4. BASIC DIRECTORY CHECKS
# ============================================================

print()
print("=" * 80)
print("MAIA VALIDATION CORPUS V2 - FINAL AUDIT")
print("=" * 80)


required_paths = [

    VALIDATION_DIR,
    DATA_DIR,
    STATE_DIR,
    MANIFEST_DIR,
    METADATA_FILE,
]


for path in required_paths:

    if not path.exists():

        raise RuntimeError(
            f"Required path missing: {path}"
        )


print(
    "Validation directory:",
    VALIDATION_DIR
)

print(
    "All required paths exist."
)


# ============================================================
# 5. LOAD TOKENIZER
# ============================================================

print()
print("-" * 80)
print("TOKENIZER")
print("-" * 80)


tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)


VOCAB_SIZE = len(
    tokenizer
)

EOS_TOKEN_ID = (
    tokenizer.eos_token_id
)


print(
    f"Vocabulary size: {VOCAB_SIZE:,}"
)

print(
    f"EOS token ID:    {EOS_TOKEN_ID}"
)


if VOCAB_SIZE > 65535:

    raise RuntimeError(
        "Vocabulary cannot be represented by uint16."
    )


if EOS_TOKEN_ID is None:

    raise RuntimeError(
        "Tokenizer has no EOS token."
    )


# ============================================================
# 6. LOAD METADATA
# ============================================================

print()
print("-" * 80)
print("METADATA")
print("-" * 80)


with open(
    METADATA_FILE,
    "r",
    encoding="utf-8"
) as f:

    metadata = json.load(
        f
    )


print(
    "Name:",
    metadata.get(
        "name"
    )
)

print(
    "Format:",
    metadata.get(
        "format"
    )
)

print(
    "Sequence length:",
    metadata.get(
        "sequence_length"
    )
)

print(
    "Requested tokens:",
    f"{metadata.get('requested_total_tokens', 0):,}"
)

print(
    "Aligned target:",
    f"{metadata.get('actual_target_total_tokens', 0):,}"
)

print(
    "Shard tokens:",
    f"{metadata.get('shard_tokens', 0):,}"
)

print(
    "Metadata vocab size:",
    f"{metadata.get('vocab_size', 0):,}"
)

print(
    "Metadata EOS:",
    metadata.get(
        "eos_token_id"
    )
)


metadata_errors = []


if (
    metadata.get(
        "sequence_length"
    )
    != SEQUENCE_LENGTH
):

    metadata_errors.append(
        "sequence_length mismatch"
    )


if (
    metadata.get(
        "actual_target_total_tokens"
    )
    != EXPECTED_TOTAL_TOKENS
):

    metadata_errors.append(
        "total token target mismatch"
    )


if (
    metadata.get(
        "vocab_size"
    )
    != VOCAB_SIZE
):

    metadata_errors.append(
        "vocabulary size mismatch"
    )


if (
    metadata.get(
        "eos_token_id"
    )
    != EOS_TOKEN_ID
):

    metadata_errors.append(
        "EOS token mismatch"
    )


# ============================================================
# 7. SEARCH FOR TEMPORARY FILES
# ============================================================

print()
print("-" * 80)
print("TEMPORARY FILE CHECK")
print("-" * 80)


tmp_files = list(
    VALIDATION_DIR.rglob(
        "*.tmp"
    )
)


if tmp_files:

    print(
        f"WARNING: found "
        f"{len(tmp_files)} temporary files:"
    )

    for path in tmp_files:

        print(
            " ",
            path
        )

else:

    print(
        "No .tmp files found."
    )


# ============================================================
# 8. SHA-256 HELPER
# ============================================================

def sha256_file(
    path
):

    digest = (
        hashlib.sha256()
    )


    with open(
        path,
        "rb"
    ) as f:

        while True:

            chunk = f.read(
                8 * 1024 * 1024
            )


            if not chunk:

                break


            digest.update(
                chunk
            )


    return (
        digest.hexdigest()
    )


# ============================================================
# 9. LOAD MANIFEST
# ============================================================

def load_manifest(
    source_id
):

    path = (
        MANIFEST_DIR
        / f"{source_id}.jsonl"
    )


    if not path.exists():

        raise RuntimeError(
            f"Missing manifest: {path}"
        )


    entries = []


    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        for line_number, line in enumerate(
            f,
            start=1
        ):

            line = line.strip()


            if not line:

                continue


            try:

                entries.append(
                    json.loads(
                        line
                    )
                )

            except Exception as exc:

                raise RuntimeError(
                    f"Invalid manifest JSON "
                    f"{path}:{line_number}"
                ) from exc


    return entries


# ============================================================
# 10. LOAD STATE
# ============================================================

def load_state(
    source_id
):

    path = (
        STATE_DIR
        / f"{source_id}.json"
    )


    if not path.exists():

        raise RuntimeError(
            f"Missing state: {path}"
        )


    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(
            f
        )


# ============================================================
# 11. SOURCE AUDIT
# ============================================================

audit_start = (
    time.time()
)


global_errors = []

source_results = {}

global_state_tokens = 0

global_manifest_tokens = 0

global_physical_tokens = 0

global_physical_shards = 0

global_eos_count = 0


for source_id, expected in EXPECTED_SOURCES.items():

    print()
    print("=" * 80)
    print(expected["name"])
    print("=" * 80)


    errors = []


    # --------------------------------------------------------
    # STATE
    # --------------------------------------------------------

    state = load_state(
        source_id
    )


    state_tokens = int(
        state.get(
            "tokens_written",
            -1
        )
    )


    state_shards = int(
        state.get(
            "shards_written",
            -1
        )
    )


    state_complete = bool(
        state.get(
            "complete",
            False
        )
    )


    print(
        f"State tokens:       "
        f"{state_tokens:,}"
    )

    print(
        f"State shards:       "
        f"{state_shards:,}"
    )

    print(
        f"State complete:     "
        f"{state_complete}"
    )


    if (
        state_tokens
        != expected["tokens"]
    ):

        errors.append(
            "state token count mismatch"
        )


    if (
        state_shards
        != expected["shards"]
    ):

        errors.append(
            "state shard count mismatch"
        )


    if not state_complete:

        errors.append(
            "source not marked complete"
        )


    # --------------------------------------------------------
    # MANIFEST
    # --------------------------------------------------------

    manifest = load_manifest(
        source_id
    )


    manifest_tokens = sum(
        int(
            entry["tokens"]
        )
        for entry in manifest
    )


    print(
        f"Manifest entries:   "
        f"{len(manifest):,}"
    )

    print(
        f"Manifest tokens:    "
        f"{manifest_tokens:,}"
    )


    if (
        len(manifest)
        != expected["shards"]
    ):

        errors.append(
            "manifest shard count mismatch"
        )


    if (
        manifest_tokens
        != expected["tokens"]
    ):

        errors.append(
            "manifest token count mismatch"
        )


    # --------------------------------------------------------
    # PHYSICAL FILES
    # --------------------------------------------------------

    source_dir = (
        DATA_DIR
        / source_id
    )


    if not source_dir.exists():

        errors.append(
            "source data directory missing"
        )

        physical_files = []

    else:

        physical_files = sorted(
            source_dir.glob(
                "shard-*.bin"
            )
        )


    print(
        f"Physical shards:    "
        f"{len(physical_files):,}"
    )


    if (
        len(physical_files)
        != expected["shards"]
    ):

        errors.append(
            "physical shard count mismatch"
        )


    # --------------------------------------------------------
    # CHECK EVERY MANIFEST ENTRY
    # --------------------------------------------------------

    source_physical_tokens = 0

    source_eos_count = 0

    source_min_token = None

    source_max_token = None


    for index, entry in enumerate(
        manifest
    ):

        relative_path = (
            entry["filename"]
        )


        shard_path = (
            VALIDATION_DIR
            / relative_path
        )


        print()
        print(
            f"Shard {index:02d}: "
            f"{shard_path.name}"
        )


        if not shard_path.exists():

            errors.append(
                f"missing shard "
                f"{shard_path.name}"
            )

            continue


        physical_bytes = (
            shard_path.stat().st_size
        )


        if (
            physical_bytes
            % DTYPE_BYTES
            != 0
        ):

            errors.append(
                f"{shard_path.name}: "
                f"byte size not divisible "
                f"by dtype size"
            )


        physical_tokens = (
            physical_bytes
            // DTYPE_BYTES
        )


        expected_manifest_tokens = int(
            entry["tokens"]
        )


        expected_manifest_bytes = int(
            entry["bytes"]
        )


        print(
            f"  tokens: "
            f"{physical_tokens:,}"
        )

        print(
            f"  bytes:  "
            f"{physical_bytes:,}"
        )


        if (
            physical_tokens
            != expected_manifest_tokens
        ):

            errors.append(
                f"{shard_path.name}: "
                f"physical/manifest "
                f"token mismatch"
            )


        if (
            physical_bytes
            != expected_manifest_bytes
        ):

            errors.append(
                f"{shard_path.name}: "
                f"physical/manifest "
                f"byte mismatch"
            )


        if (
            physical_tokens
            % SEQUENCE_LENGTH
            != 0
        ):

            errors.append(
                f"{shard_path.name}: "
                f"not aligned to "
                f"{SEQUENCE_LENGTH}"
            )


        # ----------------------------------------------------
        # SHA-256
        # ----------------------------------------------------

        actual_sha = (
            sha256_file(
                shard_path
            )
        )


        expected_sha = (
            entry["sha256"]
        )


        sha_ok = (
            actual_sha
            == expected_sha
        )


        print(
            f"  SHA-256: "
            f"{'OK' if sha_ok else 'FAIL'}"
        )


        if not sha_ok:

            errors.append(
                f"{shard_path.name}: "
                f"SHA-256 mismatch"
            )


        # ----------------------------------------------------
        # TOKEN RANGE + EOS
        # ----------------------------------------------------

        tokens = np.memmap(
            shard_path,
            dtype=DTYPE,
            mode="r"
        )


        if len(tokens) == 0:

            errors.append(
                f"{shard_path.name}: "
                f"empty shard"
            )

            continue


        shard_min = int(
            tokens.min()
        )

        shard_max = int(
            tokens.max()
        )


        if (
            source_min_token
            is None
            or shard_min
            < source_min_token
        ):

            source_min_token = (
                shard_min
            )


        if (
            source_max_token
            is None
            or shard_max
            > source_max_token
        ):

            source_max_token = (
                shard_max
            )


        if shard_min < 0:

            errors.append(
                f"{shard_path.name}: "
                f"negative token ID"
            )


        if shard_max >= VOCAB_SIZE:

            errors.append(
                f"{shard_path.name}: "
                f"token ID outside vocabulary"
            )


        eos_count = int(
            np.count_nonzero(
                tokens
                == EOS_TOKEN_ID
            )
        )


        source_eos_count += (
            eos_count
        )


        source_physical_tokens += (
            physical_tokens
        )


        print(
            f"  token range: "
            f"{shard_min} .. "
            f"{shard_max}"
        )

        print(
            f"  EOS count:   "
            f"{eos_count:,}"
        )


        del tokens


    # --------------------------------------------------------
    # SOURCE TOTALS
    # --------------------------------------------------------

    print()
    print(
        f"Physical tokens:    "
        f"{source_physical_tokens:,}"
    )

    print(
        f"Token ID range:     "
        f"{source_min_token} .. "
        f"{source_max_token}"
    )

    print(
        f"EOS tokens:         "
        f"{source_eos_count:,}"
    )


    if source_eos_count > 0:

        tokens_per_eos = (
            source_physical_tokens
            / source_eos_count
        )


        print(
            f"Tokens / EOS:       "
            f"{tokens_per_eos:,.1f}"
        )

    else:

        tokens_per_eos = None

        errors.append(
            "no EOS tokens found"
        )


    if (
        source_physical_tokens
        != expected["tokens"]
    ):

        errors.append(
            "physical source token "
            "count mismatch"
        )


    # --------------------------------------------------------
    # CHECK FOR ORPHAN .BIN FILES
    # --------------------------------------------------------

    manifest_paths = {

        str(
            (
                VALIDATION_DIR
                / entry["filename"]
            ).resolve()
        )

        for entry
        in manifest
    }


    physical_paths = {

        str(
            path.resolve()
        )

        for path
        in physical_files
    }


    orphan_files = (
        physical_paths
        - manifest_paths
    )


    missing_files = (
        manifest_paths
        - physical_paths
    )


    if orphan_files:

        errors.append(
            f"{len(orphan_files)} "
            f"orphan physical shard(s)"
        )


        print(
            "Orphan shards:"
        )

        for path in sorted(
            orphan_files
        ):

            print(
                " ",
                path
            )


    if missing_files:

        errors.append(
            f"{len(missing_files)} "
            f"manifest shard(s) missing"
        )


    # --------------------------------------------------------
    # RESULT
    # --------------------------------------------------------

    if errors:

        print()
        print(
            "SOURCE RESULT: FAIL"
        )

        for error in errors:

            print(
                "  -",
                error
            )

    else:

        print()
        print(
            "SOURCE RESULT: PASS"
        )


    source_results[
        source_id
    ] = {

        "name":
            expected["name"],

        "tokens":
            source_physical_tokens,

        "shards":
            len(
                physical_files
            ),

        "eos":
            source_eos_count,

        "tokens_per_eos":
            tokens_per_eos,

        "min_token":
            source_min_token,

        "max_token":
            source_max_token,

        "errors":
            errors,
    }


    global_state_tokens += (
        state_tokens
    )

    global_manifest_tokens += (
        manifest_tokens
    )

    global_physical_tokens += (
        source_physical_tokens
    )

    global_physical_shards += (
        len(
            physical_files
        )
    )

    global_eos_count += (
        source_eos_count
    )


# ============================================================
# 12. GLOBAL FILE CHECK
# ============================================================

print()
print("=" * 80)
print("GLOBAL FILE CHECK")
print("=" * 80)


all_bin_files = sorted(
    DATA_DIR.rglob(
        "*.bin"
    )
)


expected_bin_files = sum(
    expected["shards"]
    for expected
    in EXPECTED_SOURCES.values()
)


print(
    f"All physical .bin files: "
    f"{len(all_bin_files):,}"
)

print(
    f"Expected .bin files:     "
    f"{expected_bin_files:,}"
)


if (
    len(all_bin_files)
    != expected_bin_files
):

    global_errors.append(
        "unexpected global .bin file count"
    )


# ============================================================
# 13. GLOBAL COUNTS
# ============================================================

print()
print("=" * 80)
print("GLOBAL COUNTS")
print("=" * 80)


print(
    f"Expected tokens:  "
    f"{EXPECTED_TOTAL_TOKENS:,}"
)

print(
    f"State tokens:     "
    f"{global_state_tokens:,}"
)

print(
    f"Manifest tokens:  "
    f"{global_manifest_tokens:,}"
)

print(
    f"Physical tokens:  "
    f"{global_physical_tokens:,}"
)

print(
    f"Physical shards:  "
    f"{global_physical_shards:,}"
)

print(
    f"EOS tokens:       "
    f"{global_eos_count:,}"
)


if (
    global_state_tokens
    != EXPECTED_TOTAL_TOKENS
):

    global_errors.append(
        "global state token mismatch"
    )


if (
    global_manifest_tokens
    != EXPECTED_TOTAL_TOKENS
):

    global_errors.append(
        "global manifest token mismatch"
    )


if (
    global_physical_tokens
    != EXPECTED_TOTAL_TOKENS
):

    global_errors.append(
        "global physical token mismatch"
    )


if metadata_errors:

    global_errors.extend(
        metadata_errors
    )


if tmp_files:

    global_errors.append(
        "temporary files present"
    )


# ============================================================
# 14. RANDOM QUALITATIVE SAMPLES
#
# Read-only. Samples can cross original document boundaries;
# EOS is replaced by a visible marker.
# ============================================================

print()
print("=" * 80)
print("RANDOM DECODED SAMPLES")
print("=" * 80)


for source_id, expected in EXPECTED_SOURCES.items():

    print()
    print("#" * 80)
    print(expected["name"])
    print("#" * 80)


    source_dir = (
        DATA_DIR
        / source_id
    )


    shard_files = sorted(
        source_dir.glob(
            "shard-*.bin"
        )
    )


    if not shard_files:

        print(
            "No shards available."
        )

        continue


    for sample_index in range(
        SAMPLES_PER_SOURCE
    ):

        shard_path = random.choice(
            shard_files
        )


        tokens = np.memmap(
            shard_path,
            dtype=DTYPE,
            mode="r"
        )


        max_start = (
            len(tokens)
            - SAMPLE_TOKENS
        )


        if max_start <= 0:

            start = 0

        else:

            # Align sample start to a sequence boundary
            # whenever possible.
            max_sequence = (
                max_start
                // SEQUENCE_LENGTH
            )


            if max_sequence > 0:

                sequence_index = (
                    random.randint(
                        0,
                        max_sequence
                    )
                )

                start = (
                    sequence_index
                    * SEQUENCE_LENGTH
                )

            else:

                start = 0


        sample_ids = np.asarray(
            tokens[
                start:
                start + SAMPLE_TOKENS
            ],
            dtype=np.int64
        )


        # Decode while preserving visible EOS boundaries.

        pieces = []

        current = []


        for token_id in sample_ids:

            token_id = int(
                token_id
            )


            if (
                token_id
                == EOS_TOKEN_ID
            ):

                if current:

                    pieces.append(
                        tokenizer.decode(
                            current,
                            skip_special_tokens=False
                        )
                    )

                    current = []


                pieces.append(
                    "\n<EOS>\n"
                )

            else:

                current.append(
                    token_id
                )


        if current:

            pieces.append(
                tokenizer.decode(
                    current,
                    skip_special_tokens=False
                )
            )


        decoded = "".join(
            pieces
        )


        print()
        print(
            f"[Sample "
            f"{sample_index + 1}]"
        )

        print(
            f"Shard: "
            f"{shard_path.name}"
        )

        print(
            f"Token offset: "
            f"{start:,}"
        )

        print("-" * 80)

        print(
            decoded
        )

        print("-" * 80)


        del tokens


# ============================================================
# 15. SOURCE SUMMARY
# ============================================================

print()
print("=" * 80)
print("SOURCE SUMMARY")
print("=" * 80)


for source_id, result in source_results.items():

    status = (
        "PASS"
        if not result["errors"]
        else "FAIL"
    )


    print(
        f"{result['name']:32s} "
        f"| tokens="
        f"{result['tokens']:>10,} "
        f"| shards="
        f"{result['shards']:2d} "
        f"| EOS="
        f"{result['eos']:>7,} "
        f"| range="
        f"{result['min_token']}.."
        f"{result['max_token']} "
        f"| {status}"
    )


# ============================================================
# 16. FINAL RESULT
# ============================================================

source_error_count = sum(
    len(
        result["errors"]
    )

    for result
    in source_results.values()
)


elapsed = (
    time.time()
    - audit_start
)


print()
print("=" * 80)
print("FINAL AUDIT RESULT")
print("=" * 80)


print(
    f"Expected tokens:       "
    f"{EXPECTED_TOTAL_TOKENS:,}"
)

print(
    f"Physical tokens:       "
    f"{global_physical_tokens:,}"
)

print(
    f"Expected shards:       "
    f"{expected_bin_files:,}"
)

print(
    f"Physical shards:       "
    f"{global_physical_shards:,}"
)

print(
    f"Source errors:         "
    f"{source_error_count}"
)

print(
    f"Global errors:         "
    f"{len(global_errors)}"
)

print(
    f"Temporary files:       "
    f"{len(tmp_files)}"
)

print(
    f"Audit runtime:         "
    f"{elapsed:.2f} seconds"
)


print()


if (
    source_error_count == 0
    and len(global_errors) == 0
):

    print(
        "RESULT: PASSED ALL STRUCTURAL "
        "AND INTEGRITY CHECKS."
    )

    print()
    print(
        "Maia Validation Corpus V2 "
        "is ready to be frozen and used "
        "as the fixed evaluation corpus."
    )

else:

    print(
        "RESULT: AUDIT FAILED."
    )

    print()


    if global_errors:

        print(
            "Global errors:"
        )

        for error in global_errors:

            print(
                "  -",
                error
            )


    print()
    print(
        "Do NOT use this validation corpus "
        "for checkpoint evaluation until "
        "the errors are resolved."
    )

================================================================================
MAIA VALIDATION CORPUS V2 - FINAL AUDIT
================================================================================
Validation directory: /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2
All required paths exist.

--------------------------------------------------------------------------------
TOKENIZER
--------------------------------------------------------------------------------
Vocabulary size: 50,257
EOS token ID:    2

--------------------------------------------------------------------------------
METADATA
--------------------------------------------------------------------------------
Name: Maia Validation Corpus V2
Format: uint16
Sequence length: 1024
Requested tokens: 20,000,000
Aligned target: 19,999,744
Shard tokens: 4,194,304
Metadata vocab size: 50,257
Metadata EOS: 2

--------------------------------------------------------------------------------
TEMPORARY FILE CHECK
--------------------------------------------------------------------------------
No .tmp files found.

================================================================================
FineWeb-Edu EN
================================================================================
State tokens:       8,999,936
State shards:       3
State complete:     True
Manifest entries:   3
Manifest tokens:    8,999,936
Physical shards:    3

Shard 00: shard-00000.bin
  tokens: 4,194,304
  bytes:  8,388,608
  SHA-256: OK
  token range: 2 .. 50255
  EOS count:   4,012

Shard 01: shard-00001.bin
  tokens: 4,194,304
  bytes:  8,388,608
  SHA-256: OK
  token range: 0 .. 50254
  EOS count:   4,060

Shard 02: shard-00002.bin
  tokens: 611,328
  bytes:  1,222,656
  SHA-256: OK
  token range: 2 .. 50250
  EOS count:   528

Physical tokens:    8,999,936
Token ID range:     0 .. 50255
EOS tokens:         8,600
Tokens / EOS:       1,046.5

SOURCE RESULT: PASS

================================================================================
FineWeb2-HQ PT
================================================================================
State tokens:       4,499,456
State shards:       2
State complete:     True
Manifest entries:   2
Manifest tokens:    4,499,456
Physical shards:    2

Shard 00: shard-00000.bin
  tokens: 4,194,304
  bytes:  8,388,608
  SHA-256: OK
  token range: 2 .. 50256
  EOS count:   6,795

Shard 01: shard-00001.bin
  tokens: 305,152
  bytes:  610,304
  SHA-256: OK
  token range: 2 .. 50254
  EOS count:   477

Physical tokens:    4,499,456
Token ID range:     2 .. 50256
EOS tokens:         7,272
Tokens / EOS:       618.7

SOURCE RESULT: PASS

================================================================================
FineWeb2-HQ ES
================================================================================
State tokens:       4,499,456
State shards:       2
State complete:     True
Manifest entries:   2
Manifest tokens:    4,499,456
Physical shards:    2

Shard 00: shard-00000.bin
  tokens: 4,194,304
  bytes:  8,388,608
  SHA-256: OK
  token range: 2 .. 50253
  EOS count:   4,370

Shard 01: shard-00001.bin
  tokens: 305,152
  bytes:  610,304
  SHA-256: OK
  token range: 2 .. 50246
  EOS count:   284

Physical tokens:    4,499,456
Token ID range:     2 .. 50253
EOS tokens:         4,654
Tokens / EOS:       966.8

SOURCE RESULT: PASS

================================================================================
OpenCoder FineWeb Code
================================================================================
State tokens:       999,424
State shards:       1
State complete:     True
Manifest entries:   1
Manifest tokens:    999,424
Physical shards:    1

Shard 00: shard-00000.bin
  tokens: 999,424
  bytes:  1,998,848
  SHA-256: OK
  token range: 2 .. 50253
  EOS count:   1,803

Physical tokens:    999,424
Token ID range:     2 .. 50253
EOS tokens:         1,803
Tokens / EOS:       554.3

SOURCE RESULT: PASS

================================================================================
FineMath-4+
================================================================================
State tokens:       599,040
State shards:       1
State complete:     True
Manifest entries:   1
Manifest tokens:    599,040
Physical shards:    1

Shard 00: shard-00000.bin
  tokens: 599,040
  bytes:  1,198,080
  SHA-256: OK
  token range: 2 .. 50233
  EOS count:   379

Physical tokens:    599,040
Token ID range:     2 .. 50233
EOS tokens:         379
Tokens / EOS:       1,580.6

SOURCE RESULT: PASS

================================================================================
peS2o Scientific
================================================================================
State tokens:       402,432
State shards:       1
State complete:     True
Manifest entries:   1
Manifest tokens:    402,432
Physical shards:    1

Shard 00: shard-00000.bin
  tokens: 402,432
  bytes:  804,864
  SHA-256: OK
  token range: 2 .. 50232
  EOS count:   57

Physical tokens:    402,432
Token ID range:     2 .. 50232
EOS tokens:         57
Tokens / EOS:       7,060.2

SOURCE RESULT: PASS

================================================================================
GLOBAL FILE CHECK
================================================================================
All physical .bin files: 10
Expected .bin files:     10

================================================================================
GLOBAL COUNTS
================================================================================
Expected tokens:  19,999,744
State tokens:     19,999,744
Manifest tokens:  19,999,744
Physical tokens:  19,999,744
Physical shards:  10
EOS tokens:       22,765

================================================================================
RANDOM DECODED SAMPLES
================================================================================

################################################################################
FineWeb-Edu EN
################################################################################

[Sample 1]
Shard: shard-00002.bin
Token offset: 116,736
--------------------------------------------------------------------------------
) will launch another spacecraft called Hera in 2024.
Hera will head on out to the site of the asteroids in order to hopefully get hold of some information about the crash.
The ESA said: “By the time Hera reaches Didymos, in 2026, Dimorphos will have achieved historic significance: the first object in the Solar System to have its orbit shifted by human effort in a measurable way.”
Sure, we might have problems down on Earth now that seem more pressing, but we don’t want to get side-swiped by a giant space rock whilst we’re all concentrating on the pound tanking and the world’s oceans boiling, right?
<EOS>
A huge crowd of Naga Babas (naked ascetic monks) and Hindu devotees heads towards the Ganges river at the Kumbh Mela 2013 Hindu festival near Allahabad (India).
Kumbh Mela is the largest festival on Earth, taking place once every 12 years, with more than 50 million Hindu pilgrims gathering to pray and bathe in the holy Ganges river.
Thousands of Naga Sadhus (naked Hindu Holy men, with their bodies covered with ritual white
--------------------------------------------------------------------------------

[Sample 2]
Shard: shard-00000.bin
Token offset: 2,307,072
--------------------------------------------------------------------------------
 may be created
- For example, with an F-score for each dwc element entry, we can generate a graph / histogram across all participants.
- We will attempt to provide services that can validate the outcomes of hackathon deliverables. This hackathon is not structured as a competition, but we felt it would be beneficial for participants to have some baseline to evaluate the effectiveness of their methods.
- OCR Text Evaluation
- Evaluation of OCR Output will be based on a comparison to Gold Hand-Typed outputs, using confusion matrix like criteria for evaluating word presence, word correctness, and avoiding non-text garbage regions. We will attempt to avoid penalizing for attempts at text recognition in barcode and handwritten regions.
- Parsed Field Evaluation
- Evaluation of the effectiveness of parsing will be calculated based on a confusion matrix. Rows are named with each of the possible element names for parts of a label. Columns are also these same names. Counts along the diagonal represent the number of items that were tagged correctly. For example, a count that is correctly labeled as a county will add one to the diagonal. If a county is incorrect
--------------------------------------------------------------------------------

################################################################################
FineWeb2-HQ PT
################################################################################

[Sample 1]
Shard: shard-00000.bin
Token offset: 1,871,872
--------------------------------------------------------------------------------
 não só à parte espiritual, mas à material também. A fé católica nos dá alegria de viver, de amar e de se dedicar aos necessitados. Felizes aqueles e aquelas continuam na Igreja o trabalho dos setenta e dois discípulos, como fizeram S. Timóteo e S. Tido!
Maria Santíssima e S. José foram modelos de pais e de educadores. Que eles, e também os santos Timóteo, Tito e Paulo, ajudem os pais e mães a cumprirem bem a sua missão.
Enviou-os dois a dois.
Padre Queiroz
<EOS>
Texto feito em aula
A partir da língua constrói-se um imensurável objeto significativo. E esse universo dá sentido ao todo em que estamos imersos, portanto, tudo começa e, tal como o big bang, se amplia via palavra. Cada micro-universo inserido, semanticamente, em um único substantivo irradia questões e conceitos que vão sendo experienciados pelo portador da fala e seus interlocutores.
Haja vista que ao enunciar uma primeira palavra como, por exemplo, língua, desdobra-se para um substantivo correlato como nação; de nação chega-se ao indígena
--------------------------------------------------------------------------------

[Sample 2]
Shard: shard-00000.bin
Token offset: 859,136
--------------------------------------------------------------------------------
arResumirFatores determinantes
3 Desempenho de cpu – Introdução É complexo avaliar o desempenho desse tipo de sistemaComplexidade e escala dos softwares modernosAmpla gama de técnicas de melhoria de desempenhoImpossível sentar com um manual do conjunto de instruções e determinar a velocidade de execução de um sistema
4 Desempenho de cpu – introdução Desempenho é um fator importante para os projetistasO que determina o desempenho de um computador?
5 Definindo desempenho Analogia com aviões de passageiro Desempenho determinado pela velocidade:Quão rápido é o Concorde comparado com o 747?1 passageiro de um ponto a outro450 passageiro de um ponto a outroAvião Passageiros Autonomia (mi) Velocidade (mph)BoeingBoeingBAC/Sud ConcordeDouglas DC
6 Desempenho – Termos Tempo de Resposta (latência) Throughput Quanto tempo leva para executar uma tarefa?ThroughputQuantas tarefas a máquina pode executar de uma vez?O que é a taxa média de execução?Qual o impacto, se substituir o processador por uma versão mais rápida?Qual o impacto, se adicionarmos uma nova máquina no laboratório?
7 Vaz
--------------------------------------------------------------------------------

################################################################################
FineWeb2-HQ ES
################################################################################

[Sample 1]
Shard: shard-00000.bin
Token offset: 3,538,944
--------------------------------------------------------------------------------
 a las voraces empresas madereras, a las constructoras de caminos, la guerrilla, traficantes de droga y la colonización de los "sin tierra", las áreas fronterizas ofrecen poca seguridad internacional, la Amazonía, caracterizada por la aventura romántica y la búsqueda de El Dorado, ha desaparecido convirtiéndose en una región más peligrosa que "el infierno verde" de los legendarios aventureros de la goma. De ahí que, el desarrollo y explotación de la Amazonía Boliviana, se constituye hoy por hoy; en un tema de gran actualidad en todos los círculos sociales y académicos del país.
En el contexto militar se convierte en tema de particular incumbencia tanto por sus implicancias geopolíticas que puedan representar para el Estado boliviano, pero fundamentalmente por sus connotaciones de reserva ecológica, de sus ingentes riquezas naturales y de las proyecciones de seguridad y desarrollo que en ellas puedan contener. En este entendido se hace necesario determinar ¿ Cuál será el impacto en la Geopolítica Boliviana la explotación y consecuente desarrollo de la amazonía?. Esta interrogante de detalle delimita el alcance del presente ensayo, que será llevado a cabo empleando el método de razonamiento analítico sobre la base de la teoría existente, el mismo que nos permitir
--------------------------------------------------------------------------------

[Sample 2]
Shard: shard-00000.bin
Token offset: 249,856
--------------------------------------------------------------------------------
 resistir mucho más.
Al día siguiente, 11 los aliados intentaron cavar una trinchera mucho más cerca de las líneas británicas, casi a 400 metros, pero los británicos les impidieron completarla. Cornawallis tampoco advirtió la extensión de esta nueva línea y para el 12 de octubre recién se percató la cercanía de los aliados. El 14 de octubre las trincheras estaban cerca de los británicos y se ordenó un nuevo ataque de artillería que acabe con los británicos durante la noche. Los reductos nueve y diez serían atacados por los franceses y americanos respectivamente. El 14 de octubre a las 6:30 empezó un ataque de distracción mientras que se preparaba el asalto sobre Yorktown, y con las bayonetas listas los americanos acabaron con toda resistencia en el reducto 10.
La lucha fue feroz por donde se la vea y los británicos se vieron obligados a rendirse, a los americanos les costó sólo 9 muertos y 25 heridos. Los franceses tuvieron también éxito a pesar del fuego artillero enemigo y lograron sobrepasar a los alemanes aliados de los ingleses. Con esto Washington tenía su artillería cerca del pueblo y desde tres direcciones. Los británicos intentaron un contraataque pero se vio frustrado, todas las armas que dañaron fueron
--------------------------------------------------------------------------------

################################################################################
OpenCoder FineWeb Code
################################################################################

[Sample 1]
Shard: shard-00000.bin
Token offset: 228,352
--------------------------------------------------------------------------------
 took me into the depths of PayPal's underlying security mechanism that was used to prevent brute force, a known security issue. Although this functionality is used in many places, I will focus on the login form.
The idea was quite simple: after several failed attempts to login, before trying again, you would have to solve recaptcha. The implementation, however, may surprise you quite a bit.
When the system detects a probable brute force, the response to the next authentication attempt is a page that contains nothing but the Google captcha, and if the user resolves it, a POST request is initiated to / auth / validatecaptcha.
The body of the request contains the variables _csrf and sessionID, which are already familiar to us, as well as other values, which I will return to a little later.
The captcha validation request response is intended to re-enter the user with the authentication flow. For this purpose, the response contains an automatically submitted form with all data from the last login request, including an unencrypted email address and password.
I realized that with the right timing and some interaction with the victim, knowing all the to
--------------------------------------------------------------------------------

[Sample 2]
Shard: shard-00000.bin
Token offset: 529,408
--------------------------------------------------------------------------------

<EOS>
When creating a News Story, there is an option to add existing photos. However, when I do this, the photos are not displaying on the News Detail Page.
On a News Detail page, there is a block called News Detail Photos. This pulls in photos that are uploaded from a computer and attached to that particular story. In order to have an existing photo display on a News Detail page, you need to add a photos content type to the page and change the drop-down menu to "Display Attached Photos (no category)".
<EOS>
[REMOTE] Join Our Dynamic Team as a Full-Stack Engineer in an exciting AI startup
流程：邮件简历(English version) + 视频沟通 + 付费笔试
Hi there 👋,
I am seeking a talented full-stack software engineer to join and help me build web apps and extensions that uses AI (GPT from OpenAI, Stablediffusion, etc) as well as other projects
--------------------------------------------------------------------------------

################################################################################
FineMath-4+
################################################################################

[Sample 1]
Shard: shard-00000.bin
Token offset: 587,776
--------------------------------------------------------------------------------
 find extra spots to interject edge. If you have any questions please don’t hesitate to ask, otherwise good luck and happy grinding!
<EOS>
# another issuei want to subtract (2a-3) /(a^2-4))-2/(a+2) is good to do (2a-3-2)/(a^2-4-a-2) (subtract up and down)?

sciencesolve | Certified Educator

You should know that the algebraic addition of two fractions is possible if they have common denominators. If they do not have a common denominator, then you need to find it.

In this problem, notice that you may write the first denominator as the special product

Notice that the second denominator needs to be multiplied by to become the denominator of the first fraction.

Considering the order of operations yields:

Hence, evaluating the algebraic expression yields

giorgiana1976 | Student

In this case, absolutely not!

When we are adding/subtracting 2 or more fractions, the first step is to check if they have the same denomin
--------------------------------------------------------------------------------

[Sample 2]
Shard: shard-00000.bin
Token offset: 571,392
--------------------------------------------------------------------------------
 from Politics and 3 from Religion, or we’ll have 2 from Politics and 2 from Religion:

3 Politics, 1 Religion, 2 War

1 Politics, 3 Religion, 2 War

2 Politics, 2 Religion, 2 War

Of course, you don’t want to take up all that space by writing so much.

Instead, I’d write the numerical distributions like this:

P-R-W
3-2-1
2-3-1
3-1-2
1-3-2
2-2-2

(I’d write them spaced-apart without a dash, but I don’t want the formatting to get messed-up here.)

Recognizing numerical distributions is good stuff, but I’m not getting a kick out of it just because it’s fun.

It also helps us answer the question because it becomes obvious that only the 3P-1R-2W distribution has 1R, so we know that we’ll have to have 3P and 2W.

We know that the variable S will be “out” because we already have the complete
--------------------------------------------------------------------------------

################################################################################
peS2o Scientific
################################################################################

[Sample 1]
Shard: shard-00000.bin
Token offset: 114,688
--------------------------------------------------------------------------------
 species (rOs)

In [ ]:
from pathlib import Path
import os

print("=== DRIVE DIAGNOSTIC ===\n")

drive_root = Path("/content/drive")
mydrive = Path("/content/drive/MyDrive")
project = Path("/content/drive/MyDrive/Colab_LLMs/Maia_Lite")

print("Drive mounted: ", drive_root.exists())
print("MyDrive exists:", mydrive.exists())
print("Project exists:", project.exists())
print()

if project.exists():
    print("Contents of Maia_Lite:")
    print("-" * 70)

    for p in sorted(project.iterdir()):
        kind = "DIR " if p.is_dir() else "FILE"
        print(f"{kind:4s}  {p.name}")

    print()
    print("Looking for directories containing 'validation'...")
    print("-" * 70)

    found = [
        p for p in project.rglob("*")
        if p.is_dir()
        and "validation" in p.name.lower()
    ]

    if found:
        for p in found:
            print(p)
    else:
        print("NONE FOUND")

else:
    print("Maia_Lite project directory is not visible.")

print()
print("=== END DIAGNOSTIC ===")

=== DRIVE DIAGNOSTIC ===

Drive mounted:  True
MyDrive exists: True
Project exists: True

Contents of Maia_Lite:
----------------------------------------------------------------------
DIR   checkpoints_continuacao_a100
DIR   checkpoints_continuation_fixed
DIR   checkpoints_pretreino
DIR   corpus_v2
DIR   diagnostics
DIR   experiments
DIR   modelo_335M_final
DIR   pretraining_data
DIR   recovery_test_106000
DIR   tokenizador
DIR   validation_corpus_v2

Looking for directories containing 'validation'...
----------------------------------------------------------------------
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2

=== END DIAGNOSTIC ===

In [ ]:
# ============================================================
# MAIA LITE - CONTROLLED 130K
# VALIDATION CORPUS V2 - OFFICIAL BASELINE
#
# PURPOSE
# -------
# Establish the official held-out baseline BEFORE training
# on Maia Corpus V2.
#
# NO TRAINING.
# NO OPTIMIZER.
# NO BACKWARD PASS.
# NO WEIGHT UPDATES.
# ============================================================

import math
import time
from pathlib import Path

import numpy as np
import torch

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = PROJECT_DIR / "tokenizador"

VALIDATION_DIR = (
    PROJECT_DIR / "validation_corpus_v2"
)

VALIDATION_DATA_DIR = (
    VALIDATION_DIR / "data"
)


# ------------------------------------------------------------
# IMPORTANT
#
# This should point to the CONTROLLED 130K checkpoint.
#
# If your directory has a slightly different name, change
# ONLY this path.
# ------------------------------------------------------------


MODEL_DIR = (
    PROJECT_DIR
    / "checkpoints_continuation_fixed"
    / "maia_lite_equivalent_130k"
)

# ============================================================
# 2. CONFIGURATION
# ============================================================

SEQUENCE_LENGTH = 1024

DTYPE = np.uint16

# A100 80 GB can comfortably evaluate several sequences
# simultaneously. This is intentionally conservative.
EVAL_BATCH_SIZE = 32

EXPECTED_TOTAL_TOKENS = 19_999_744


SOURCES = {

    "fineweb_edu_en":
        "FineWeb-Edu EN",

    "fineweb2_hq_pt":
        "FineWeb2-HQ PT",

    "fineweb2_hq_es":
        "FineWeb2-HQ ES",

    "opencoder":
        "OpenCoder FineWeb Code",

    "finemath":
        "FineMath-4+",

    "pes2o":
        "peS2o Scientific",
}


# ============================================================
# 3. DEVICE
# ============================================================

print("=" * 80)
print("MAIA LITE - OFFICIAL 130K BASELINE")
print("=" * 80)

print()

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


device = torch.device(
    "cuda"
)


gpu_name = torch.cuda.get_device_name(
    0
)

gpu_memory = (
    torch.cuda.get_device_properties(
        0
    ).total_memory
    / 1024**3
)


print(
    f"GPU:          {gpu_name}"
)

print(
    f"GPU memory:   {gpu_memory:.1f} GB"
)

print(
    f"PyTorch:      {torch.__version__}"
)

print(
    f"CUDA:         {torch.version.cuda}"
)


# ============================================================
# 4. VERIFY PATHS
# ============================================================

print()
print("-" * 80)
print("PATH CHECK")
print("-" * 80)


print(
    "Model:"
)

print(
    MODEL_DIR
)


print()
print(
    "Validation corpus:"
)

print(
    VALIDATION_DATA_DIR
)


if not MODEL_DIR.exists():

    raise RuntimeError(
        "\nCONTROLLED 130K MODEL NOT FOUND:\n"
        f"{MODEL_DIR}\n\n"
        "Change MODEL_DIR to the directory containing "
        "the controlled 130K checkpoint."
    )


if not VALIDATION_DATA_DIR.exists():

    raise RuntimeError(
        "\nValidation corpus not found:\n"
        f"{VALIDATION_DATA_DIR}"
    )


# ============================================================
# 5. TOKENIZER
# ============================================================

print()
print("-" * 80)
print("TOKENIZER")
print("-" * 80)


tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)


print(
    f"Vocabulary:   {len(tokenizer):,}"
)

print(
    f"EOS token:    {tokenizer.eos_token_id}"
)

print(
    f"PAD token:    {tokenizer.pad_token_id}"
)


# ============================================================
# 6. LOAD MODEL
# ============================================================

print()
print("-" * 80)
print("LOADING CONTROLLED 130K")
print("-" * 80)


load_start = time.time()


model = (
    GPT2LMHeadModel.from_pretrained(
        str(MODEL_DIR),
        torch_dtype=torch.float32,
    )
)


model.to(
    device
)

model.eval()


load_elapsed = (
    time.time()
    - load_start
)


parameters = sum(
    p.numel()
    for p in model.parameters()
)


print(
    f"Parameters:    {parameters:,}"
)

print(
    f"Model dtype:   {next(model.parameters()).dtype}"
)

print(
    f"Load time:     {load_elapsed:.2f} s"
)


# ============================================================
# 7. MODEL SANITY CHECK
# ============================================================

if (
    model.config.vocab_size
    != len(tokenizer)
):

    raise RuntimeError(
        "Model/tokenizer vocabulary mismatch."
    )


if (
    model.config.n_positions
    < SEQUENCE_LENGTH
):

    raise RuntimeError(
        "Model context window is smaller than 1024."
    )


# ============================================================
# 8. DISCOVER VALIDATION SHARDS
# ============================================================

print()
print("-" * 80)
print("VALIDATION DATA")
print("-" * 80)


source_files = {}

discovered_tokens = 0


for source_id, source_name in SOURCES.items():

    source_dir = (
        VALIDATION_DATA_DIR
        / source_id
    )


    files = sorted(
        source_dir.glob(
            "shard-*.bin"
        )
    )


    if not files:

        raise RuntimeError(
            f"No validation shards for "
            f"{source_name}"
        )


    source_tokens = 0


    for path in files:

        byte_size = (
            path.stat().st_size
        )


        if byte_size % 2 != 0:

            raise RuntimeError(
                f"Invalid uint16 file size: "
                f"{path}"
            )


        tokens = (
            byte_size // 2
        )


        if (
            tokens
            % SEQUENCE_LENGTH
            != 0
        ):

            raise RuntimeError(
                f"Shard not aligned to "
                f"{SEQUENCE_LENGTH}: "
                f"{path}"
            )


        source_tokens += (
            tokens
        )


    source_files[
        source_id
    ] = files


    discovered_tokens += (
        source_tokens
    )


    print(
        f"{source_name:32s} "
        f"| tokens="
        f"{source_tokens:>10,} "
        f"| sequences="
        f"{source_tokens // SEQUENCE_LENGTH:>6,} "
        f"| shards="
        f"{len(files):2d}"
    )


print("-" * 80)

print(
    f"TOTAL: "
    f"{discovered_tokens:,} tokens"
)


if (
    discovered_tokens
    != EXPECTED_TOTAL_TOKENS
):

    raise RuntimeError(
        "Validation corpus token count "
        "does not match expected total."
    )


# ============================================================
# 9. EVALUATION FUNCTION
#
# IMPORTANT:
#
# GPT causal LM loss for a sequence of length 1024 predicts:
#
#     token[1] ... token[1023]
#
# from:
#
#     token[0] ... token[1022]
#
# Therefore each independent 1024-token sequence contributes
# exactly 1023 prediction targets.
#
# We accumulate:
#
#     batch_loss * valid_prediction_tokens
#
# instead of averaging batch losses.
#
# This produces a true token-weighted cross-entropy.
# ============================================================

@torch.inference_mode()
def evaluate_source(
    source_id,
    source_name,
    shard_files,
):

    print()
    print("=" * 80)
    print(source_name)
    print("=" * 80)


    total_nll = 0.0

    total_prediction_tokens = 0

    total_sequences = 0

    total_raw_tokens = 0

    source_start = time.time()


    for shard_number, shard_path in enumerate(
        shard_files,
        start=1
    ):

        shard_tokens = np.memmap(
            shard_path,
            dtype=DTYPE,
            mode="r"
        )


        raw_token_count = len(
            shard_tokens
        )


        sequence_count = (
            raw_token_count
            // SEQUENCE_LENGTH
        )


        sequences = shard_tokens.reshape(
            sequence_count,
            SEQUENCE_LENGTH
        )


        shard_start = time.time()


        for batch_start in range(
            0,
            sequence_count,
            EVAL_BATCH_SIZE
        ):

            batch_end = min(
                batch_start
                + EVAL_BATCH_SIZE,

                sequence_count
            )


            # Explicit copy avoids issues caused by
            # read-only NumPy memmaps.

            batch_np = np.array(
                sequences[
                    batch_start:
                    batch_end
                ],
                dtype=np.int64,
                copy=True
            )


            input_ids = torch.from_numpy(
                batch_np
            ).to(
                device,
                non_blocking=True
            )


            outputs = model(
                input_ids=input_ids,
                labels=input_ids,
                use_cache=False,
            )


            batch_size = (
                input_ids.shape[0]
            )


            prediction_tokens = (
                batch_size
                * (
                    SEQUENCE_LENGTH - 1
                )
            )


            batch_loss = float(
                outputs.loss.detach()
            )


            total_nll += (
                batch_loss
                * prediction_tokens
            )


            total_prediction_tokens += (
                prediction_tokens
            )


            total_sequences += (
                batch_size
            )


            total_raw_tokens += (
                batch_size
                * SEQUENCE_LENGTH
            )


            del (
                input_ids,
                outputs,
                batch_np
            )


        shard_elapsed = (
            time.time()
            - shard_start
        )


        print(
            f"Shard "
            f"{shard_number:02d}/"
            f"{len(shard_files):02d} "
            f"| raw tokens="
            f"{raw_token_count:,} "
            f"| sequences="
            f"{sequence_count:,} "
            f"| {shard_elapsed:.2f} s"
        )


        del (
            sequences,
            shard_tokens
        )


    mean_loss = (
        total_nll
        / total_prediction_tokens
    )


    try:

        perplexity = math.exp(
            mean_loss
        )

    except OverflowError:

        perplexity = float(
            "inf"
        )


    elapsed = (
        time.time()
        - source_start
    )


    print()
    print(
        f"Raw tokens:          "
        f"{total_raw_tokens:,}"
    )

    print(
        f"Sequences:           "
        f"{total_sequences:,}"
    )

    print(
        f"Prediction tokens:   "
        f"{total_prediction_tokens:,}"
    )

    print(
        f"Token-weighted loss: "
        f"{mean_loss:.8f}"
    )

    print(
        f"Perplexity:          "
        f"{perplexity:.6f}"
    )

    print(
        f"Runtime:             "
        f"{elapsed:.2f} s"
    )


    return {

        "name":
            source_name,

        "raw_tokens":
            total_raw_tokens,

        "sequences":
            total_sequences,

        "prediction_tokens":
            total_prediction_tokens,

        "total_nll":
            total_nll,

        "loss":
            mean_loss,

        "perplexity":
            perplexity,

        "runtime":
            elapsed,
    }


# ============================================================
# 10. RUN OFFICIAL BASELINE
# ============================================================

print()
print("=" * 80)
print("STARTING OFFICIAL HELD-OUT BASELINE")
print("=" * 80)

print()
print(
    "Model weights will NOT be modified."
)

print(
    "No optimizer exists."
)

print(
    "No gradients will be calculated."
)


torch.cuda.empty_cache()


evaluation_start = (
    time.time()
)


results = {}


for source_id, source_name in SOURCES.items():

    results[
        source_id
    ] = evaluate_source(

        source_id,

        source_name,

        source_files[
            source_id
        ],
    )


# ============================================================
# 11. GLOBAL TOKEN-WEIGHTED RESULT
# ============================================================

global_nll = sum(

    result["total_nll"]

    for result
    in results.values()
)


global_prediction_tokens = sum(

    result["prediction_tokens"]

    for result
    in results.values()
)


global_raw_tokens = sum(

    result["raw_tokens"]

    for result
    in results.values()
)


global_sequences = sum(

    result["sequences"]

    for result
    in results.values()
)


global_loss = (
    global_nll
    / global_prediction_tokens
)


try:

    global_perplexity = math.exp(
        global_loss
    )

except OverflowError:

    global_perplexity = float(
        "inf"
    )


evaluation_elapsed = (
    time.time()
    - evaluation_start
)


# ============================================================
# 12. FINAL BASELINE REPORT
# ============================================================

print()
print("=" * 80)
print("MAIA LITE CONTROLLED 130K")
print("VALIDATION CORPUS V2 - OFFICIAL BASELINE")
print("=" * 80)


for source_id, result in results.items():

    print(
        f"{result['name']:32s} "
        f"| loss="
        f"{result['loss']:.8f} "
        f"| PPL="
        f"{result['perplexity']:.6f} "
        f"| pred.tokens="
        f"{result['prediction_tokens']:,}"
    )


print("-" * 80)


print(
    f"{'GLOBAL':32s} "
    f"| loss="
    f"{global_loss:.8f} "
    f"| PPL="
    f"{global_perplexity:.6f} "
    f"| pred.tokens="
    f"{global_prediction_tokens:,}"
)


print()
print(
    f"Raw validation tokens: "
    f"{global_raw_tokens:,}"
)

print(
    f"Sequences:             "
    f"{global_sequences:,}"
)

print(
    f"Prediction tokens:     "
    f"{global_prediction_tokens:,}"
)

print(
    f"Total evaluation time: "
    f"{evaluation_elapsed:.2f} s"
)


print()
print("=" * 80)
print("BASELINE COMPLETE")
print("=" * 80)

print()
print(
    "This is the official pre-Corpus-V2 "
    "baseline for controlled-130k."
)

print(
    "Preserve these numbers unchanged for "
    "comparison with all future checkpoints."
)

================================================================================
MAIA LITE - OFFICIAL 130K BASELINE
================================================================================

GPU:          NVIDIA A100-SXM4-80GB
GPU memory:   79.3 GB
PyTorch:      2.11.0+cu128
CUDA:         12.8

--------------------------------------------------------------------------------
PATH CHECK
--------------------------------------------------------------------------------
Model:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/maia_lite_equivalent_130k

Validation corpus:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/data

--------------------------------------------------------------------------------
TOKENIZER
--------------------------------------------------------------------------------
Vocabulary:   50,257
EOS token:    2
PAD token:    1

--------------------------------------------------------------------------------
LOADING CONTROLLED 130K
--------------------------------------------------------------------------------

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters:    354,823,168
Model dtype:   torch.float32
Load time:     17.73 s

--------------------------------------------------------------------------------
VALIDATION DATA
--------------------------------------------------------------------------------
FineWeb-Edu EN                   | tokens= 8,999,936 | sequences= 8,789 | shards= 3
FineWeb2-HQ PT                   | tokens= 4,499,456 | sequences= 4,394 | shards= 2
FineWeb2-HQ ES                   | tokens= 4,499,456 | sequences= 4,394 | shards= 2
OpenCoder FineWeb Code           | tokens=   999,424 | sequences=   976 | shards= 1
FineMath-4+                      | tokens=   599,040 | sequences=   585 | shards= 1
peS2o Scientific                 | tokens=   402,432 | sequences=   393 | shards= 1
--------------------------------------------------------------------------------
TOTAL: 19,999,744 tokens

================================================================================
STARTING OFFICIAL HELD-OUT BASELINE
================================================================================

Model weights will NOT be modified.
No optimizer exists.
No gradients will be calculated.

================================================================================
FineWeb-Edu EN
================================================================================

[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Shard 01/03 | raw tokens=4,194,304 | sequences=4,096 | 189.34 s
Shard 02/03 | raw tokens=4,194,304 | sequences=4,096 | 188.81 s
Shard 03/03 | raw tokens=611,328 | sequences=597 | 28.33 s

Raw tokens:          8,999,936
Sequences:           8,789
Prediction tokens:   8,991,147
Token-weighted loss: 3.89186480
Perplexity:          49.002180
Runtime:             406.50 s

================================================================================
FineWeb2-HQ PT
================================================================================
Shard 01/02 | raw tokens=4,194,304 | sequences=4,096 | 188.63 s
Shard 02/02 | raw tokens=305,152 | sequences=298 | 14.61 s

Raw tokens:          4,499,456
Sequences:           4,394
Prediction tokens:   4,495,062
Token-weighted loss: 3.95476403
Perplexity:          52.183379
Runtime:             203.25 s

================================================================================
FineWeb2-HQ ES
================================================================================
Shard 01/02 | raw tokens=4,194,304 | sequences=4,096 | 188.66 s
Shard 02/02 | raw tokens=305,152 | sequences=298 | 14.58 s

Raw tokens:          4,499,456
Sequences:           4,394
Prediction tokens:   4,495,062
Token-weighted loss: 3.70961940
Perplexity:          40.838260
Runtime:             203.26 s

================================================================================
OpenCoder FineWeb Code
================================================================================
Shard 01/01 | raw tokens=999,424 | sequences=976 | 45.68 s

Raw tokens:          999,424
Sequences:           976
Prediction tokens:   998,448
Token-weighted loss: 4.31978168
Perplexity:          75.172215
Runtime:             45.69 s

================================================================================
FineMath-4+
================================================================================
Shard 01/01 | raw tokens=599,040 | sequences=585 | 27.70 s

Raw tokens:          599,040
Sequences:           585
Prediction tokens:   598,455
Token-weighted loss: 3.45431165
Perplexity:          31.636504
Runtime:             27.70 s

================================================================================
peS2o Scientific
================================================================================
Shard 01/01 | raw tokens=402,432 | sequences=393 | 18.91 s

Raw tokens:          402,432
Sequences:           393
Prediction tokens:   402,039
Token-weighted loss: 3.72731316
Perplexity:          41.567273
Runtime:             18.92 s

================================================================================
MAIA LITE CONTROLLED 130K
VALIDATION CORPUS V2 - OFFICIAL BASELINE
================================================================================
FineWeb-Edu EN                   | loss=3.89186480 | PPL=49.002180 | pred.tokens=8,991,147
FineWeb2-HQ PT                   | loss=3.95476403 | PPL=52.183379 | pred.tokens=4,495,062
FineWeb2-HQ ES                   | loss=3.70961940 | PPL=40.838260 | pred.tokens=4,495,062
OpenCoder FineWeb Code           | loss=4.31978168 | PPL=75.172215 | pred.tokens=998,448
FineMath-4+                      | loss=3.45431165 | PPL=31.636504 | pred.tokens=598,455
peS2o Scientific                 | loss=3.72731316 | PPL=41.567273 | pred.tokens=402,039
--------------------------------------------------------------------------------
GLOBAL                           | loss=3.86998176 | PPL=47.941512 | pred.tokens=19,980,213

Raw validation tokens: 19,999,744
Sequences:             19,531
Prediction tokens:     19,980,213
Total evaluation time: 905.32 s

================================================================================
BASELINE COMPLETE
================================================================================

This is the official pre-Corpus-V2 baseline for controlled-130k.
Preserve these numbers unchanged for comparison with all future checkpoints.

In [ ]:
from pathlib import Path
import json

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

print("=" * 80)
print("SEARCHING FOR MAIA LITE CHECKPOINTS")
print("=" * 80)

candidates = []

for config_path in PROJECT_DIR.rglob("config.json"):
    model_dir = config_path.parent

    # A valid HF model/checkpoint should normally contain model weights.
    weight_files = (
        list(model_dir.glob("*.safetensors"))
        + list(model_dir.glob("pytorch_model*.bin"))
    )

    if not weight_files:
        continue

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    except Exception:
        continue

    # Restrict results to models compatible with Maia Lite.
    if config.get("vocab_size") != 50257:
        continue

    candidates.append(model_dir)

print()
print(f"Found {len(candidates)} compatible model directories.\n")

for i, path in enumerate(sorted(candidates), 1):
    try:
        relative = path.relative_to(PROJECT_DIR)
    except ValueError:
        relative = path

    print(f"[{i:02d}] {relative}")

    # Show useful checkpoint metadata if available.
    trainer_state = path / "trainer_state.json"

    if trainer_state.exists():
        try:
            with open(trainer_state, "r", encoding="utf-8") as f:
                state = json.load(f)

            print(
                f"     global_step = "
                f"{state.get('global_step', 'unknown')}"
            )
        except Exception:
            pass

    print()

print("=" * 80)

================================================================================
SEARCHING FOR MAIA LITE CHECKPOINTS
================================================================================

Found 36 compatible model directories.

[01] checkpoints_continuacao_a100/checkpoint-65000
     global_step = 65000

[02] checkpoints_continuacao_a100/checkpoint-66000
     global_step = 66000

[03] checkpoints_continuacao_a100/checkpoint-67000
     global_step = 67000

[04] checkpoints_continuation_fixed/checkpoint-10000
     global_step = 10000

[05] checkpoints_continuation_fixed/checkpoint-12000
     global_step = 12000

[06] checkpoints_continuation_fixed/checkpoint-14000
     global_step = 14000

[07] checkpoints_continuation_fixed/checkpoint-16000
     global_step = 16000

[08] checkpoints_continuation_fixed/checkpoint-18000
     global_step = 18000

[09] checkpoints_continuation_fixed/checkpoint-2000
     global_step = 2000

[10] checkpoints_continuation_fixed/checkpoint-20000
     global_step = 20000

[11] checkpoints_continuation_fixed/checkpoint-22000
     global_step = 22000

[12] checkpoints_continuation_fixed/checkpoint-24000
     global_step = 24000

[13] checkpoints_continuation_fixed/checkpoint-4000
     global_step = 4000

[14] checkpoints_continuation_fixed/checkpoint-6000
     global_step = 6000

[15] checkpoints_continuation_fixed/checkpoint-8000
     global_step = 8000

[16] checkpoints_continuation_fixed/maia_lite_equivalent_130k

[17] checkpoints_pretreino/checkpoint-106000
     global_step = 106000

[18] experiments/sft_from_106k/checkpoint-1000
     global_step = 1000

[19] experiments/sft_from_106k/checkpoint-1500
     global_step = 1500

[20] experiments/sft_from_106k/checkpoint-2000
     global_step = 2000

[21] experiments/sft_from_106k/checkpoint-2500
     global_step = 2500

[22] experiments/sft_from_106k/checkpoint-3000
     global_step = 3000

[23] experiments/sft_from_106k/checkpoint-500
     global_step = 500

[24] experiments/sft_from_106k/maia_lite_106k_sft_3000

[25] experiments/sft_response_only_from_106k/checkpoint-1000
     global_step = 1000

[26] experiments/sft_response_only_from_106k/checkpoint-1500
     global_step = 1500

[27] experiments/sft_response_only_from_106k/checkpoint-2000
     global_step = 2000

[28] experiments/sft_response_only_from_106k/checkpoint-2500
     global_step = 2500

[29] experiments/sft_response_only_from_106k/checkpoint-3000
     global_step = 3000

[30] experiments/sft_response_only_from_106k/checkpoint-500
     global_step = 500

[31] experiments/sft_response_only_from_106k/maia_lite_106k_sft_response_only_3000

[32] recovery_test_106000/checkpoint-1000
     global_step = 1000

[33] recovery_test_106000/checkpoint-1500
     global_step = 1500

[34] recovery_test_106000/checkpoint-2000
     global_step = 2000

[35] recovery_test_106000/checkpoint-500
     global_step = 500

[36] recovery_test_106000/final

================================================================================

In [ ]:
# ============================================================
# MAIA LITE - CORPUS V2 PRETRAINING
# STAGE 1: EQUIVALENT 130K -> 140K
#
# Base:
#   maia_lite_equivalent_130k
#
# Training:
#   Maia Corpus V2
#   10,000 optimizer steps
#   32,768 tokens / optimizer step
#   327,680,000 new tokens
#
# IMPORTANT
# ---------
# INITIAL V2 START:
#   Load MODEL WEIGHTS ONLY from equivalent-130k.
#   Create NEW optimizer/scheduler/trainer state/scaler.
#
# FUTURE V2 SESSIONS:
#   Resume FULL checkpoint.
#   Do NOT restart optimizer/scheduler.
# ============================================================


# ============================================================
# 0. ENVIRONMENT
# ============================================================

import os

os.environ[
    "PYTORCH_CUDA_ALLOC_CONF"
] = "expandable_segments:True"


# ============================================================
# 1. IMPORTS
# ============================================================

import json
import math
import time
import bisect
from pathlib import Path

import numpy as np
import torch

from torch.utils.data import Dataset

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    set_seed,
)


# ============================================================
# 2. REPRODUCIBILITY
# ============================================================

SEED = 42

set_seed(
    SEED
)


# ============================================================
# 3. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = (
    PROJECT_DIR
    / "tokenizador"
)

BASE_MODEL_DIR = (
    PROJECT_DIR
    / "checkpoints_continuation_fixed"
    / "maia_lite_equivalent_130k"
)

CORPUS_DIR = (
    PROJECT_DIR
    / "corpus_v2"
)

CORPUS_DATA_DIR = (
    CORPUS_DIR
    / "train"
)

OUTPUT_DIR = (
    PROJECT_DIR
    / "checkpoints_corpus_v2"
)


# ============================================================
# 4. TRAINING CONFIGURATION
# ============================================================

SEQUENCE_LENGTH = 1024

DTYPE = np.uint16

# Conservative A100 configuration.
PER_DEVICE_BATCH_SIZE = 8

GRADIENT_ACCUMULATION_STEPS = 4

EFFECTIVE_BATCH_SIZE = (
    PER_DEVICE_BATCH_SIZE
    * GRADIENT_ACCUMULATION_STEPS
)

TOKENS_PER_STEP = (
    EFFECTIVE_BATCH_SIZE
    * SEQUENCE_LENGTH
)


# ------------------------------------------------------------
# Stage 1:
#
# 130k equivalent -> 140k equivalent
# ------------------------------------------------------------

INITIAL_EQUIVALENT_STEP = 130_000

V2_MAX_STEPS = 10_000

FINAL_EQUIVALENT_STEP = (
    INITIAL_EQUIVALENT_STEP
    + V2_MAX_STEPS
)


# ------------------------------------------------------------
# Optimizer
# ------------------------------------------------------------

LEARNING_RATE = 1e-5

WEIGHT_DECAY = 0.1

WARMUP_STEPS = 500


# ------------------------------------------------------------
# Logging / checkpointing
# ------------------------------------------------------------

LOGGING_STEPS = 100

SAVE_STEPS = 2_000

SAVE_TOTAL_LIMIT = None


# ============================================================
# 5. BASIC SANITY REPORT
# ============================================================

print("=" * 80)
print("MAIA LITE - CORPUS V2 PRETRAINING")
print("=" * 80)

print()

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


device_name = (
    torch.cuda.get_device_name(0)
)

device_memory = (
    torch.cuda.get_device_properties(0)
    .total_memory
    / 1024**3
)


print(
    f"GPU:                     "
    f"{device_name}"
)

print(
    f"GPU memory:              "
    f"{device_memory:.1f} GB"
)

print(
    f"PyTorch:                 "
    f"{torch.__version__}"
)

print(
    f"CUDA:                    "
    f"{torch.version.cuda}"
)

print()

print(
    f"Initial equivalent step: "
    f"{INITIAL_EQUIVALENT_STEP:,}"
)

print(
    f"V2 optimizer steps:      "
    f"{V2_MAX_STEPS:,}"
)

print(
    f"Final equivalent step:   "
    f"{FINAL_EQUIVALENT_STEP:,}"
)

print()

print(
    f"Context length:          "
    f"{SEQUENCE_LENGTH:,}"
)

print(
    f"Micro batch:             "
    f"{PER_DEVICE_BATCH_SIZE}"
)

print(
    f"Gradient accumulation:   "
    f"{GRADIENT_ACCUMULATION_STEPS}"
)

print(
    f"Effective batch:         "
    f"{EFFECTIVE_BATCH_SIZE}"
)

print(
    f"Tokens / step:           "
    f"{TOKENS_PER_STEP:,}"
)

print(
    f"New tokens this stage:   "
    f"{TOKENS_PER_STEP * V2_MAX_STEPS:,}"
)

print()

print(
    f"Learning rate:           "
    f"{LEARNING_RATE:.2e}"
)

print(
    f"Warmup steps:            "
    f"{WARMUP_STEPS:,}"
)

print(
    f"Save every:              "
    f"{SAVE_STEPS:,} steps"
)


# ============================================================
# 6. PATH SAFETY
# ============================================================

print()
print("-" * 80)
print("PATH CHECK")
print("-" * 80)


for required_path in [
    TOKENIZER_DIR,
    BASE_MODEL_DIR,
    CORPUS_DATA_DIR,
]:

    print(
        required_path
    )


    if not required_path.exists():

        raise RuntimeError(
            f"Required path missing:\n"
            f"{required_path}"
        )


# ------------------------------------------------------------
# Critical protection:
#
# This cell is for the INITIAL V2 run only.
#
# If checkpoints already exist in OUTPUT_DIR, stop instead of
# accidentally creating a second optimizer trajectory.
# ------------------------------------------------------------

existing_v2_checkpoints = sorted(
    OUTPUT_DIR.glob(
        "checkpoint-*"
    )
) if OUTPUT_DIR.exists() else []


if existing_v2_checkpoints:

    print()
    print(
        "Existing Corpus V2 checkpoints:"
    )

    for checkpoint in existing_v2_checkpoints:

        print(
            " ",
            checkpoint.name
        )


    raise RuntimeError(
        "\nCorpus V2 checkpoints already exist.\n"
        "DO NOT restart this initial cell.\n"
        "Use full checkpoint resume instead."
    )


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 7. TOKENIZER
# ============================================================

print()
print("-" * 80)
print("TOKENIZER")
print("-" * 80)


tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)


if tokenizer.pad_token_id is None:

    raise RuntimeError(
        "Tokenizer PAD token is not configured."
    )


print(
    f"Vocabulary:              "
    f"{len(tokenizer):,}"
)

print(
    f"EOS:                     "
    f"{tokenizer.eos_token_id}"
)

print(
    f"PAD:                     "
    f"{tokenizer.pad_token_id}"
)


# ============================================================
# 8. DISCOVER ALL CORPUS V2 SHARDS
# ============================================================

print()
print("-" * 80)
print("DISCOVERING CORPUS V2")
print("-" * 80)


SOURCE_ORDER = [
    "fineweb_edu_en",
    "fineweb2_hq_pt",
    "fineweb2_hq_es",
    "opencoder",
    "finemath",
    "pes2o",
]


shard_paths = []


for source_id in SOURCE_ORDER:

    source_dir = (
        CORPUS_DATA_DIR
        / source_id
    )


    if not source_dir.exists():

        raise RuntimeError(
            f"Missing source directory: "
            f"{source_dir}"
        )


    files = sorted(
        source_dir.glob(
            "shard-*.bin"
        )
    )


    if not files:

        raise RuntimeError(
            f"No shards found for "
            f"{source_id}"
        )


    source_tokens = sum(
        path.stat().st_size // 2
        for path in files
    )


    print(
        f"{source_id:24s} "
        f"| shards="
        f"{len(files):3d} "
        f"| tokens="
        f"{source_tokens:>13,}"
    )


    shard_paths.extend(
        files
    )


print("-" * 80)

print(
    f"Total shards: "
    f"{len(shard_paths):,}"
)


# ============================================================
# 9. MAP-STYLE MEMMAP DATASET
#
# Each item = one 1024-token training sequence.
#
# Shards remain on disk and are memory-mapped.
# We do NOT load 5.8 GB into RAM.
# ============================================================

class MaiaCorpusV2Dataset(Dataset):

    def __init__(
        self,
        shard_paths,
        sequence_length=1024,
    ):

        self.sequence_length = (
            sequence_length
        )

        self.shard_paths = list(
            shard_paths
        )

        self.shards = []

        self.sequence_counts = []

        self.cumulative_sequences = []

        cumulative = 0


        for path in self.shard_paths:

            byte_size = (
                path.stat().st_size
            )


            if (
                byte_size
                % np.dtype(DTYPE).itemsize
                != 0
            ):

                raise RuntimeError(
                    f"Invalid shard byte size: "
                    f"{path}"
                )


            token_count = (
                byte_size
                // np.dtype(DTYPE).itemsize
            )


            if (
                token_count
                % self.sequence_length
                != 0
            ):

                raise RuntimeError(
                    f"Shard is not aligned to "
                    f"{self.sequence_length}: "
                    f"{path}"
                )


            sequence_count = (
                token_count
                // self.sequence_length
            )


            mmap = np.memmap(
                path,
                dtype=DTYPE,
                mode="r"
            )


            self.shards.append(
                mmap
            )

            self.sequence_counts.append(
                sequence_count
            )


            cumulative += (
                sequence_count
            )


            self.cumulative_sequences.append(
                cumulative
            )


        self.total_sequences = (
            cumulative
        )


    def __len__(
        self
    ):

        return (
            self.total_sequences
        )


    def __getitem__(
        self,
        index
    ):

        if index < 0:

            index += (
                self.total_sequences
            )


        if (
            index < 0
            or index >= self.total_sequences
        ):

            raise IndexError(
                index
            )


        shard_index = bisect.bisect_right(
            self.cumulative_sequences,
            index
        )


        previous_cumulative = (

            0

            if shard_index == 0

            else self.cumulative_sequences[
                shard_index - 1
            ]
        )


        local_sequence_index = (
            index
            - previous_cumulative
        )


        token_start = (
            local_sequence_index
            * self.sequence_length
        )


        token_end = (
            token_start
            + self.sequence_length
        )


        # Explicit copy:
        # memmap is read-only and uint16.
        # PyTorch model expects integer IDs,
        # conventionally int64.

        input_ids = np.array(
            self.shards[
                shard_index
            ][
                token_start:
                token_end
            ],
            dtype=np.int64,
            copy=True
        )


        return {
            "input_ids":
                input_ids
        }


# ============================================================
# 10. CREATE DATASET
# ============================================================

print()
print("-" * 80)
print("CREATING MAP-STYLE DATASET")
print("-" * 80)


train_dataset = MaiaCorpusV2Dataset(
    shard_paths=shard_paths,
    sequence_length=SEQUENCE_LENGTH,
)


total_sequences = len(
    train_dataset
)

total_tokens = (
    total_sequences
    * SEQUENCE_LENGTH
)


print(
    f"Sequences:               "
    f"{total_sequences:,}"
)

print(
    f"Tokens:                  "
    f"{total_tokens:,}"
)

print(
    f"Corpus optimizer steps "
    f"at effective batch 32: "
    f"{total_sequences / EFFECTIVE_BATCH_SIZE:,.2f}"
)


EXPECTED_CORPUS_TOKENS = (
    2_899_999_744
)


if (
    total_tokens
    != EXPECTED_CORPUS_TOKENS
):

    raise RuntimeError(
        f"Unexpected Corpus V2 size.\n"
        f"Expected: "
        f"{EXPECTED_CORPUS_TOKENS:,}\n"
        f"Found:    "
        f"{total_tokens:,}"
    )


# ============================================================
# 11. DATA COLLATOR
#
# mlm=False creates labels from input_ids for causal LM.
# ============================================================

data_collator = (
    DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
    )
)


# ============================================================
# 12. LOAD BASE MODEL
#
# WEIGHTS ONLY.
#
# No optimizer.
# No scheduler.
# No trainer state.
# ============================================================

print()
print("-" * 80)
print("LOADING EQUIVALENT 130K WEIGHTS")
print("-" * 80)


model = (
    GPT2LMHeadModel.from_pretrained(
        str(BASE_MODEL_DIR),
        torch_dtype=torch.float32,
    )
)


parameter_count = sum(
    p.numel()
    for p in model.parameters()
)


print(
    f"Parameters:              "
    f"{parameter_count:,}"
)

print(
    f"Model vocabulary:        "
    f"{model.config.vocab_size:,}"
)


if (
    model.config.vocab_size
    != len(tokenizer)
):

    raise RuntimeError(
        "Model/tokenizer vocabulary mismatch."
    )


# ------------------------------------------------------------
# Gradient checkpointing.
# ------------------------------------------------------------

model.gradient_checkpointing_enable()

model.config.use_cache = False


print(
    "Gradient checkpointing: ENABLED"
)

print(
    "KV cache:               DISABLED"
)


# ============================================================
# 13. TRAINING ARGUMENTS
# ============================================================

training_args = TrainingArguments(

    output_dir=str(
        OUTPUT_DIR
    ),

    # --------------------------------------------------------
    # Core training
    # --------------------------------------------------------

    max_steps=V2_MAX_STEPS,

    per_device_train_batch_size=(
        PER_DEVICE_BATCH_SIZE
    ),

    gradient_accumulation_steps=(
        GRADIENT_ACCUMULATION_STEPS
    ),

    learning_rate=(
        LEARNING_RATE
    ),

    weight_decay=(
        WEIGHT_DECAY
    ),

    warmup_steps=(
        WARMUP_STEPS
    ),

    lr_scheduler_type="cosine",

    # --------------------------------------------------------
    # Precision
    #
    # A100 handles BF16 natively.
    # This is preferable to FP16 for training stability.
    # --------------------------------------------------------

    bf16=True,

    fp16=False,

    tf32=True,

    # --------------------------------------------------------
    # Gradient stability
    # --------------------------------------------------------

    max_grad_norm=1.0,

    # --------------------------------------------------------
    # Data order / reproducibility
    # --------------------------------------------------------

    seed=SEED,

    data_seed=SEED,

    # --------------------------------------------------------
    # Checkpoints
    # --------------------------------------------------------

    save_strategy="steps",

    save_steps=SAVE_STEPS,

    save_total_limit=(
        SAVE_TOTAL_LIMIT
    ),

    # --------------------------------------------------------
    # Logging
    # --------------------------------------------------------

    logging_strategy="steps",

    logging_steps=(
        LOGGING_STEPS
    ),

    logging_first_step=True,

    # --------------------------------------------------------
    # We deliberately do not run the 20M-token validation
    # corpus inside Trainer every few steps.
    #
    # Official validation is performed separately at the
    # milestone checkpoints using the exact baseline cell.
    # --------------------------------------------------------

    eval_strategy="no",

    # --------------------------------------------------------
    # DataLoader
    #
    # Google Drive + memmap:
    # keep this conservative initially.
    # --------------------------------------------------------

    dataloader_num_workers=0,

    dataloader_pin_memory=True,

    # --------------------------------------------------------
    # Reporting
    # --------------------------------------------------------

    report_to="none",

    # --------------------------------------------------------
    # Keep all dataset fields.
    # --------------------------------------------------------

    remove_unused_columns=False,
)


# ============================================================
# 14. TRAINER
# ============================================================

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    data_collator=data_collator,
)


# ============================================================
# 15. PRE-FLIGHT REPORT
# ============================================================

print()
print("=" * 80)
print("PRE-FLIGHT CHECK")
print("=" * 80)


print(
    f"Base model:              "
    f"{BASE_MODEL_DIR}"
)

print(
    f"Output:                  "
    f"{OUTPUT_DIR}"
)

print(
    f"Corpus tokens:           "
    f"{total_tokens:,}"
)

print(
    f"Corpus sequences:        "
    f"{total_sequences:,}"
)

print()

print(
    f"Start equivalent step:   "
    f"{INITIAL_EQUIVALENT_STEP:,}"
)

print(
    f"End equivalent step:     "
    f"{FINAL_EQUIVALENT_STEP:,}"
)

print(
    f"Optimizer steps:         "
    f"{V2_MAX_STEPS:,}"
)

print(
    f"Tokens / step:           "
    f"{TOKENS_PER_STEP:,}"
)

print(
    f"Tokens this stage:       "
    f"{TOKENS_PER_STEP * V2_MAX_STEPS:,}"
)

print()

print(
    "Optimizer:               NEW"
)

print(
    "LR scheduler:            NEW"
)

print(
    "Trainer state:           NEW"
)

print(
    "Gradient scaler:         NEW / BF16"
)

print()

print(
    "Official 130K baseline:"
)

print(
    "  loss = 3.86998176"
)

print(
    "  PPL  = 47.941512"
)

print()

print(
    "NO LIVE STREAMING."
)

print(
    "NO ignore_data_skip=True."
)

print(
    "NO old optimizer state."
)

print(
    "NO validation data used for training."
)


# ============================================================
# 16. TRAIN
# ============================================================

print()
print("=" * 80)
print("STARTING CORPUS V2 TRAINING")
print("=" * 80)

print()

training_start = (
    time.time()
)


train_result = trainer.train()


training_elapsed = (
    time.time()
    - training_start
)


# ============================================================
# 17. SAVE FINAL 140K MODEL
# ============================================================

FINAL_MODEL_DIR = (
    OUTPUT_DIR
    / "maia_lite_equivalent_140k"
)


trainer.save_model(
    str(
        FINAL_MODEL_DIR
    )
)


tokenizer.save_pretrained(
    str(
        FINAL_MODEL_DIR
    )
)


# ============================================================
# 18. FINAL REPORT
# ============================================================

print()
print("=" * 80)
print("CORPUS V2 STAGE 1 COMPLETE")
print("=" * 80)


print(
    f"V2 optimizer steps:      "
    f"{trainer.state.global_step:,}"
)

print(
    f"Equivalent Maia step:    "
    f"{INITIAL_EQUIVALENT_STEP + trainer.state.global_step:,}"
)

print(
    f"Tokens processed:        "
    f"{trainer.state.global_step * TOKENS_PER_STEP:,}"
)

print(
    f"Training runtime:        "
    f"{training_elapsed / 3600:.2f} h"
)

print()

print(
    "Final model:"
)

print(
    FINAL_MODEL_DIR
)

print()

print(
    "Next action:"
)

print(
    "Run the FIXED Validation Corpus V2 "
    "evaluation on equivalent-140k."
)

print()

print(
    "IMPORTANT:"
)

print(
    "For any continuation beyond this point, "
    "resume from a FULL Corpus V2 checkpoint."
)

print(
    "Do NOT restart from weights only."
)

================================================================================
MAIA LITE - CORPUS V2 PRETRAINING
================================================================================

GPU:                     NVIDIA A100-SXM4-80GB
GPU memory:              79.3 GB
PyTorch:                 2.11.0+cu128
CUDA:                    12.8

Initial equivalent step: 130,000
V2 optimizer steps:      10,000
Final equivalent step:   140,000

Context length:          1,024
Micro batch:             8
Gradient accumulation:   4
Effective batch:         32
Tokens / step:           32,768
New tokens this stage:   327,680,000

Learning rate:           1.00e-05
Warmup steps:            500
Save every:              2,000 steps

--------------------------------------------------------------------------------
PATH CHECK
--------------------------------------------------------------------------------
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/tokenizador
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/maia_lite_equivalent_130k
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/corpus_v2/train

--------------------------------------------------------------------------------
TOKENIZER
--------------------------------------------------------------------------------
Vocabulary:              50,257
EOS:                     2
PAD:                     1

--------------------------------------------------------------------------------
DISCOVERING CORPUS V2
--------------------------------------------------------------------------------
fineweb_edu_en           | shards= 82 | tokens=1,304,999,936
fineweb2_hq_pt           | shards= 41 | tokens=  652,499,968
fineweb2_hq_es           | shards= 41 | tokens=  652,499,968
opencoder                | shards= 10 | tokens=  144,999,424
finemath                 | shards=  6 | tokens=   86,999,040
pes2o                    | shards=  4 | tokens=   58,001,408
--------------------------------------------------------------------------------
Total shards: 184

--------------------------------------------------------------------------------
CREATING MAP-STYLE DATASET
--------------------------------------------------------------------------------
Sequences:               2,832,031
Tokens:                  2,899,999,744
Corpus optimizer steps at effective batch 32: 88,500.97

--------------------------------------------------------------------------------
LOADING EQUIVALENT 130K WEIGHTS
--------------------------------------------------------------------------------

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters:              354,823,168
Model vocabulary:        50,257
Gradient checkpointing: ENABLED
KV cache:               DISABLED

================================================================================
PRE-FLIGHT CHECK
================================================================================
Base model:              /content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_continuation_fixed/maia_lite_equivalent_130k
Output:                  /content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_corpus_v2
Corpus tokens:           2,899,999,744
Corpus sequences:        2,832,031

Start equivalent step:   130,000
End equivalent step:     140,000
Optimizer steps:         10,000
Tokens / step:           32,768
Tokens this stage:       327,680,000

Optimizer:               NEW
LR scheduler:            NEW
Trainer state:           NEW
Gradient scaler:         NEW / BF16

Official 130K baseline:
  loss = 3.86998176
  PPL  = 47.941512

NO LIVE STREAMING.
NO ignore_data_skip=True.
NO old optimizer state.
NO validation data used for training.

================================================================================
STARTING CORPUS V2 TRAINING
================================================================================

In [ ]:
from pathlib import Path
import shutil
import time
import numpy as np

DRIVE_CORPUS = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite/corpus_v2/train"
)

LOCAL_CORPUS = Path(
    "/content/maia_corpus_v2/train"
)

EXPECTED_TOKENS = 2_899_999_744
EXPECTED_SHARDS = 184
DTYPE_SIZE = np.dtype(np.uint16).itemsize

print("=" * 80)
print("MAIA CORPUS V2 - COPY TO LOCAL SSD")
print("=" * 80)

# ------------------------------------------------------------
# Clean any incomplete local copy from a previous session.
# ------------------------------------------------------------

if LOCAL_CORPUS.exists():
    print("\nRemoving previous local copy...")
    shutil.rmtree(LOCAL_CORPUS)

LOCAL_CORPUS.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Discover source shards.
# ------------------------------------------------------------

source_dirs = sorted(
    p for p in DRIVE_CORPUS.iterdir()
    if p.is_dir()
)

drive_files = []

for source_dir in source_dirs:
    files = sorted(source_dir.glob("shard-*.bin"))
    drive_files.extend(files)

print(f"\nDrive shards found: {len(drive_files):,}")

if len(drive_files) != EXPECTED_SHARDS:
    raise RuntimeError(
        f"Expected {EXPECTED_SHARDS} shards, "
        f"found {len(drive_files)}."
    )

# ------------------------------------------------------------
# Copy preserving source directories.
# ------------------------------------------------------------

start = time.time()

copied = 0

for source_dir in source_dirs:

    destination = LOCAL_CORPUS / source_dir.name
    destination.mkdir(parents=True, exist_ok=True)

    files = sorted(source_dir.glob("shard-*.bin"))

    print(
        f"\n{source_dir.name}: "
        f"{len(files)} shards"
    )

    for src in files:

        dst = destination / src.name

        shutil.copyfile(src, dst)

        # Immediate size verification.
        if src.stat().st_size != dst.stat().st_size:
            raise RuntimeError(
                f"Copy size mismatch:\n{src}\n{dst}"
            )

        copied += 1

        if copied % 10 == 0:
            elapsed = time.time() - start
            print(
                f"  copied {copied:3d}/{EXPECTED_SHARDS} "
                f"| {elapsed/60:.1f} min"
            )

elapsed = time.time() - start

# ------------------------------------------------------------
# Final verification.
# ------------------------------------------------------------

local_files = sorted(
    LOCAL_CORPUS.rglob("shard-*.bin")
)

total_bytes = sum(
    p.stat().st_size
    for p in local_files
)

total_tokens = (
    total_bytes // DTYPE_SIZE
)

print()
print("=" * 80)
print("LOCAL CORPUS VERIFICATION")
print("=" * 80)

print(
    f"Local shards:       {len(local_files):,}"
)

print(
    f"Total bytes:        {total_bytes:,}"
)

print(
    f"Total tokens:       {total_tokens:,}"
)

print(
    f"Expected tokens:    {EXPECTED_TOKENS:,}"
)

print(
    f"Copy time:          {elapsed/60:.2f} min"
)

if len(local_files) != EXPECTED_SHARDS:
    raise RuntimeError(
        "Incorrect number of local shards."
    )

if total_tokens != EXPECTED_TOKENS:
    raise RuntimeError(
        "Local corpus token count mismatch."
    )

print()
print("PASS")
print("Corpus V2 is ready on local SSD.")
print()
print(f"Training path:\n{LOCAL_CORPUS}")

================================================================================
MAIA CORPUS V2 - COPY TO LOCAL SSD
================================================================================

Drive shards found: 184

finemath: 6 shards

fineweb2_hq_es: 41 shards
  copied  10/184 | 0.4 min
  copied  20/184 | 1.0 min
  copied  30/184 | 1.4 min
  copied  40/184 | 1.9 min

fineweb2_hq_pt: 41 shards
  copied  50/184 | 2.3 min
  copied  60/184 | 2.8 min
  copied  70/184 | 3.3 min
  copied  80/184 | 3.8 min

fineweb_edu_en: 82 shards
  copied  90/184 | 4.2 min
  copied 100/184 | 4.8 min
  copied 110/184 | 5.2 min
  copied 120/184 | 5.8 min
  copied 130/184 | 6.3 min
  copied 140/184 | 6.8 min
  copied 150/184 | 7.2 min
  copied 160/184 | 7.6 min
  copied 170/184 | 8.0 min

opencoder: 10 shards
  copied 180/184 | 8.4 min

pes2o: 4 shards

================================================================================
LOCAL CORPUS VERIFICATION
================================================================================
Local shards:       184
Total bytes:        5,799,999,488
Total tokens:       2,899,999,744
Expected tokens:    2,899,999,744
Copy time:          8.58 min

PASS
Corpus V2 is ready on local SSD.

Training path:
/content/maia_corpus_v2/train

In [ ]:
from pathlib import Path
import shutil
import hashlib
import time
import numpy as np

# ============================================================
# MAIA CORPUS V2
# BUILD OFFICIAL UNIFIED BINARY + COPY TO GOOGLE DRIVE
# ============================================================

LOCAL_SHARDS = Path(
    "/content/maia_corpus_v2/train"
)

LOCAL_OUTPUT = Path(
    "/content/maia_corpus_v2.bin"
)

DRIVE_OUTPUT = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite/"
    "corpus_v2/maia_corpus_v2.bin"
)

EXPECTED_TOKENS = 2_899_999_744
EXPECTED_BYTES = EXPECTED_TOKENS * 2
EXPECTED_SEQUENCES = EXPECTED_TOKENS // 1024
EXPECTED_SHARDS = 184

SEQUENCE_LENGTH = 1024

SOURCE_ORDER = [
    "fineweb_edu_en",
    "fineweb2_hq_pt",
    "fineweb2_hq_es",
    "opencoder",
    "finemath",
    "pes2o",
]


# ============================================================
# SHA-256
# ============================================================

def sha256_file(path, block_size=64 * 1024 * 1024):

    digest = hashlib.sha256()

    with open(path, "rb") as f:

        while True:

            block = f.read(block_size)

            if not block:
                break

            digest.update(block)

    return digest.hexdigest()


# ============================================================
# DISCOVER SHARDS IN CANONICAL ORDER
# ============================================================

print("=" * 80)
print("MAIA CORPUS V2 - OFFICIAL UNIFIED BINARY")
print("=" * 80)

all_shards = []

print()
print("CANONICAL SOURCE ORDER")
print("-" * 80)

for index, source in enumerate(SOURCE_ORDER, 1):

    source_dir = LOCAL_SHARDS / source

    if not source_dir.exists():
        raise RuntimeError(
            f"Missing source directory:\n{source_dir}"
        )

    shards = sorted(
        source_dir.glob("shard-*.bin")
    )

    source_bytes = sum(
        p.stat().st_size
        for p in shards
    )

    source_tokens = source_bytes // 2

    print(
        f"{index}. {source:24s} "
        f"| shards={len(shards):3d} "
        f"| tokens={source_tokens:>13,}"
    )

    all_shards.extend(shards)


# ============================================================
# INPUT VALIDATION
# ============================================================

print()
print("-" * 80)

input_bytes = sum(
    p.stat().st_size
    for p in all_shards
)

input_tokens = input_bytes // 2

print(f"Total shards:       {len(all_shards):,}")
print(f"Total bytes:        {input_bytes:,}")
print(f"Total tokens:       {input_tokens:,}")

if len(all_shards) != EXPECTED_SHARDS:
    raise RuntimeError(
        f"Expected {EXPECTED_SHARDS} shards, "
        f"found {len(all_shards)}."
    )

if input_bytes != EXPECTED_BYTES:
    raise RuntimeError(
        "Input byte count mismatch."
    )

if input_tokens != EXPECTED_TOKENS:
    raise RuntimeError(
        "Input token count mismatch."
    )


# ============================================================
# REMOVE OLD LOCAL OUTPUT IF NECESSARY
# ============================================================

if LOCAL_OUTPUT.exists():

    print()
    print(
        f"Removing previous local output:\n"
        f"{LOCAL_OUTPUT}"
    )

    LOCAL_OUTPUT.unlink()


# ============================================================
# CONCATENATE
# ============================================================

print()
print("=" * 80)
print("CONCATENATING ON LOCAL SSD")
print("=" * 80)

start = time.time()

with open(
    LOCAL_OUTPUT,
    "wb",
    buffering=64 * 1024 * 1024
) as dst:

    shard_number = 0

    for source in SOURCE_ORDER:

        shards = sorted(
            (LOCAL_SHARDS / source).glob("shard-*.bin")
        )

        print()
        print(f"{source}: {len(shards)} shards")

        for src in shards:

            with open(
                src,
                "rb",
                buffering=64 * 1024 * 1024
            ) as f:

                shutil.copyfileobj(
                    f,
                    dst,
                    length=64 * 1024 * 1024
                )

            shard_number += 1

            if (
                shard_number % 10 == 0
                or shard_number == EXPECTED_SHARDS
            ):

                print(
                    f"  {shard_number:3d}/"
                    f"{EXPECTED_SHARDS}"
                )

    dst.flush()

elapsed = time.time() - start


# ============================================================
# VALIDATE UNIFIED LOCAL FILE
# ============================================================

local_bytes = LOCAL_OUTPUT.stat().st_size
local_tokens = local_bytes // 2
local_sequences = local_tokens // SEQUENCE_LENGTH

print()
print("=" * 80)
print("LOCAL UNIFIED FILE")
print("=" * 80)

print(f"File:       {LOCAL_OUTPUT}")
print(f"Bytes:      {local_bytes:,}")
print(f"Tokens:     {local_tokens:,}")
print(f"Sequences:  {local_sequences:,}")
print(f"Build time: {elapsed / 60:.2f} min")

if local_bytes != EXPECTED_BYTES:
    raise RuntimeError(
        "Unified file byte count mismatch."
    )

if local_tokens != EXPECTED_TOKENS:
    raise RuntimeError(
        "Unified file token count mismatch."
    )

if local_sequences != EXPECTED_SEQUENCES:
    raise RuntimeError(
        "Unified file sequence count mismatch."
    )

if local_tokens % SEQUENCE_LENGTH != 0:
    raise RuntimeError(
        "Unified corpus is not 1024-token aligned."
    )


# ============================================================
# LOCAL SHA-256
# ============================================================

print()
print("Calculating local SHA-256...")

hash_start = time.time()

local_sha256 = sha256_file(
    LOCAL_OUTPUT
)

print(
    f"Local SHA-256: {local_sha256}"
)

print(
    f"Hash time:     "
    f"{(time.time() - hash_start) / 60:.2f} min"
)


# ============================================================
# COPY TO GOOGLE DRIVE
# ============================================================

print()
print("=" * 80)
print("COPYING OFFICIAL CORPUS TO GOOGLE DRIVE")
print("=" * 80)

DRIVE_OUTPUT.parent.mkdir(
    parents=True,
    exist_ok=True
)

if DRIVE_OUTPUT.exists():

    print(
        "Removing previous Drive output..."
    )

    DRIVE_OUTPUT.unlink()

copy_start = time.time()

shutil.copyfile(
    LOCAL_OUTPUT,
    DRIVE_OUTPUT
)

copy_elapsed = time.time() - copy_start

print(
    f"Copy time: {copy_elapsed / 60:.2f} min"
)


# ============================================================
# DRIVE SIZE VERIFICATION
# ============================================================

drive_bytes = DRIVE_OUTPUT.stat().st_size

print()
print(
    f"Drive bytes: {drive_bytes:,}"
)

if drive_bytes != EXPECTED_BYTES:
    raise RuntimeError(
        "Drive file size mismatch."
    )


# ============================================================
# DRIVE SHA-256
# ============================================================

print()
print("Calculating Drive SHA-256...")

hash_start = time.time()

drive_sha256 = sha256_file(
    DRIVE_OUTPUT
)

print(
    f"Drive SHA-256: {drive_sha256}"
)

print(
    f"Hash time:     "
    f"{(time.time() - hash_start) / 60:.2f} min"
)


# ============================================================
# FINAL INTEGRITY CHECK
# ============================================================

if local_sha256 != drive_sha256:

    raise RuntimeError(
        "SHA-256 MISMATCH BETWEEN LOCAL AND DRIVE!"
    )


print()
print("=" * 80)
print("MAIA CORPUS V2 - OFFICIAL BINARY READY")
print("=" * 80)

print(f"Tokens:      {local_tokens:,}")
print(f"Sequences:   {local_sequences:,}")
print(f"Bytes:       {local_bytes:,}")

print()
print(f"SHA-256:")
print(local_sha256)

print()
print("Drive artifact:")
print(DRIVE_OUTPUT)

print()
print("PASS")
print("Local and Google Drive copies are identical.")

================================================================================
MAIA CORPUS V2 - OFFICIAL UNIFIED BINARY
================================================================================

CANONICAL SOURCE ORDER
--------------------------------------------------------------------------------
1. fineweb_edu_en           | shards= 82 | tokens=1,304,999,936
2. fineweb2_hq_pt           | shards= 41 | tokens=  652,499,968
3. fineweb2_hq_es           | shards= 41 | tokens=  652,499,968
4. opencoder                | shards= 10 | tokens=  144,999,424
5. finemath                 | shards=  6 | tokens=   86,999,040
6. pes2o                    | shards=  4 | tokens=   58,001,408

--------------------------------------------------------------------------------
Total shards:       184
Total bytes:        5,799,999,488
Total tokens:       2,899,999,744

================================================================================
CONCATENATING ON LOCAL SSD
================================================================================

fineweb_edu_en: 82 shards
   10/184
   20/184
   30/184
   40/184
   50/184
   60/184
   70/184
   80/184

fineweb2_hq_pt: 41 shards
   90/184
  100/184
  110/184
  120/184

fineweb2_hq_es: 41 shards
  130/184
  140/184
  150/184
  160/184

opencoder: 10 shards
  170/184

finemath: 6 shards
  180/184

pes2o: 4 shards
  184/184

================================================================================
LOCAL UNIFIED FILE
================================================================================
File:       /content/maia_corpus_v2.bin
Bytes:      5,799,999,488
Tokens:     2,899,999,744
Sequences:  2,832,031
Build time: 0.18 min

Calculating local SHA-256...
Local SHA-256: 57e3a10aac2473dd8af428dba2fd35031410f5e10d77fa3d6933c0cd92503ca2
Hash time:     0.33 min

================================================================================
COPYING OFFICIAL CORPUS TO GOOGLE DRIVE
================================================================================
Copy time: 0.21 min

Drive bytes: 5,799,999,488

Calculating Drive SHA-256...
Drive SHA-256: 57e3a10aac2473dd8af428dba2fd35031410f5e10d77fa3d6933c0cd92503ca2
Hash time:     0.36 min

================================================================================
MAIA CORPUS V2 - OFFICIAL BINARY READY
================================================================================
Tokens:      2,899,999,744
Sequences:   2,832,031
Bytes:       5,799,999,488

SHA-256:
57e3a10aac2473dd8af428dba2fd35031410f5e10d77fa3d6933c0cd92503ca2

Drive artifact:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/corpus_v2/maia_corpus_v2.bin

PASS
Local and Google Drive copies are identical.

In [ ]:
# ============================================================
# MAIA LITE - CORPUS V2 SAFE SPEED TEST
#
# TEST:
#   micro batch          = 16
#   gradient accumulation= 2
#   effective batch      = 32
#   context              = 1024
#   gradient checkpoint  = ON
#   precision            = BF16
#
# This is ONLY a benchmark.
# It does NOT modify the official 130k model.
# It does NOT create an official checkpoint.
# ============================================================

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import gc
import shutil
import time
from pathlib import Path

import numpy as np
import torch

from torch.utils.data import Dataset

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    set_seed,
)


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42
set_seed(SEED)

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = (
    PROJECT_DIR / "tokenizador"
)

BASE_MODEL_DIR = (
    PROJECT_DIR
    / "checkpoints_continuation_fixed"
    / "maia_lite_equivalent_130k"
)

DRIVE_CORPUS = (
    PROJECT_DIR
    / "corpus_v2"
    / "maia_corpus_v2.bin"
)

LOCAL_CORPUS = Path(
    "/content/maia_corpus_v2.bin"
)

BENCHMARK_OUTPUT = Path(
    "/content/maia_v2_speed_test_16x2"
)

EXPECTED_BYTES = 5_799_999_488
EXPECTED_TOKENS = 2_899_999_744
EXPECTED_SEQUENCES = 2_832_031

SEQUENCE_LENGTH = 1024

MICRO_BATCH = 16
GRAD_ACCUM = 2

EFFECTIVE_BATCH = (
    MICRO_BATCH * GRAD_ACCUM
)

TOKENS_PER_STEP = (
    EFFECTIVE_BATCH * SEQUENCE_LENGTH
)

BENCHMARK_STEPS = 30


# ============================================================
# CLEAN CUDA MEMORY
# ============================================================

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()


# ============================================================
# GPU
# ============================================================

print("=" * 80)
print("MAIA LITE - CORPUS V2 SAFE SPEED TEST")
print("=" * 80)

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU not available.")

gpu_name = torch.cuda.get_device_name(0)

gpu_memory = (
    torch.cuda.get_device_properties(0).total_memory
    / 1024**3
)

print(f"GPU:                     {gpu_name}")
print(f"GPU memory:              {gpu_memory:.1f} GB")
print(f"PyTorch:                 {torch.__version__}")
print(f"CUDA:                    {torch.version.cuda}")


# ============================================================
# ENSURE LOCAL CORPUS EXISTS
# ============================================================

print()
print("-" * 80)
print("CORPUS")
print("-" * 80)

if not DRIVE_CORPUS.exists():
    raise RuntimeError(
        f"Official Corpus V2 binary not found:\n"
        f"{DRIVE_CORPUS}"
    )


def valid_local_corpus():

    if not LOCAL_CORPUS.exists():
        return False

    return (
        LOCAL_CORPUS.stat().st_size
        == EXPECTED_BYTES
    )


if valid_local_corpus():

    print("Valid local Corpus V2 already exists.")
    print("No copy required.")

else:

    if LOCAL_CORPUS.exists():
        print("Removing incomplete local corpus...")
        LOCAL_CORPUS.unlink()

    print("Copying Corpus V2 from Drive to local SSD...")
    print()
    print(f"FROM: {DRIVE_CORPUS}")
    print(f"TO:   {LOCAL_CORPUS}")

    copy_start = time.time()

    shutil.copyfile(
        DRIVE_CORPUS,
        LOCAL_CORPUS
    )

    copy_elapsed = (
        time.time() - copy_start
    )

    print()
    print(
        f"Copy completed in "
        f"{copy_elapsed:.2f} seconds."
    )


# ============================================================
# CORPUS VALIDATION
# ============================================================

file_bytes = (
    LOCAL_CORPUS.stat().st_size
)

total_tokens = (
    file_bytes
    // np.dtype(np.uint16).itemsize
)

total_sequences = (
    total_tokens
    // SEQUENCE_LENGTH
)

print()
print(f"Bytes:                   {file_bytes:,}")
print(f"Tokens:                  {total_tokens:,}")
print(f"Sequences:               {total_sequences:,}")

if file_bytes != EXPECTED_BYTES:
    raise RuntimeError(
        "Corpus byte count mismatch."
    )

if total_tokens != EXPECTED_TOKENS:
    raise RuntimeError(
        "Corpus token count mismatch."
    )

if total_sequences != EXPECTED_SEQUENCES:
    raise RuntimeError(
        "Corpus sequence count mismatch."
    )


# ============================================================
# DATASET
# ============================================================

class MaiaUnifiedDataset(Dataset):

    def __init__(
        self,
        path,
        sequence_length
    ):

        self.sequence_length = (
            sequence_length
        )

        self.data = np.memmap(
            path,
            dtype=np.uint16,
            mode="r"
        )

        self.total_sequences = (
            len(self.data)
            // sequence_length
        )


    def __len__(self):

        return self.total_sequences


    def __getitem__(
        self,
        index
    ):

        start = (
            index
            * self.sequence_length
        )

        end = (
            start
            + self.sequence_length
        )

        input_ids = np.array(
            self.data[start:end],
            dtype=np.int64,
            copy=True
        )

        return {
            "input_ids": input_ids
        }


dataset = MaiaUnifiedDataset(
    LOCAL_CORPUS,
    SEQUENCE_LENGTH
)

print()
print("Dataset ready.")


# ============================================================
# TOKENIZER
# ============================================================

tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)

data_collator = (
    DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    )
)


# ============================================================
# MODEL
# ============================================================

print()
print("-" * 80)
print("LOADING CONTROLLED 130K")
print("-" * 80)

model = (
    GPT2LMHeadModel.from_pretrained(
        str(BASE_MODEL_DIR),
        torch_dtype=torch.float32
    )
)

model.gradient_checkpointing_enable()

model.config.use_cache = False

parameters = sum(
    p.numel()
    for p in model.parameters()
)

print(f"Parameters:               {parameters:,}")
print("Gradient checkpointing:   ENABLED")
print("KV cache:                 DISABLED")


# ============================================================
# TRAINING ARGUMENTS
# ============================================================

training_args = TrainingArguments(

    output_dir=str(
        BENCHMARK_OUTPUT
    ),

    max_steps=BENCHMARK_STEPS,

    per_device_train_batch_size=(
        MICRO_BATCH
    ),

    gradient_accumulation_steps=(
        GRAD_ACCUM
    ),

    learning_rate=1e-5,

    warmup_steps=500,

    lr_scheduler_type="cosine",

    weight_decay=0.1,

    max_grad_norm=1.0,

    bf16=True,

    fp16=False,

    tf32=True,

    seed=SEED,

    data_seed=SEED,

    logging_strategy="steps",

    logging_steps=1,

    save_strategy="no",

    eval_strategy="no",

    dataloader_num_workers=0,

    dataloader_pin_memory=True,

    report_to="none",

    remove_unused_columns=False,
)


trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=dataset,

    data_collator=data_collator
)


# ============================================================
# PRE-FLIGHT
# ============================================================

print()
print("=" * 80)
print("BENCHMARK CONFIGURATION")
print("=" * 80)

print(f"Micro batch:              {MICRO_BATCH}")
print(f"Gradient accumulation:    {GRAD_ACCUM}")
print(f"Effective batch:          {EFFECTIVE_BATCH}")
print(f"Context:                  {SEQUENCE_LENGTH:,}")
print(f"Tokens / optimizer step:  {TOKENS_PER_STEP:,}")
print(f"Benchmark steps:          {BENCHMARK_STEPS}")
print("Gradient checkpointing:   ENABLED")
print("Precision:                BF16")

print()
print("No official checkpoint will be written.")


# ============================================================
# BENCHMARK
# ============================================================

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

start = time.time()

try:

    result = trainer.train()

    torch.cuda.synchronize()

    elapsed = (
        time.time() - start
    )

    peak_allocated = (
        torch.cuda.max_memory_allocated()
        / 1024**3
    )

    peak_reserved = (
        torch.cuda.max_memory_reserved()
        / 1024**3
    )

    seconds_per_step = (
        elapsed
        / BENCHMARK_STEPS
    )

    steps_per_second = (
        BENCHMARK_STEPS
        / elapsed
    )

    tokens_processed = (
        BENCHMARK_STEPS
        * TOKENS_PER_STEP
    )

    tokens_per_second = (
        tokens_processed
        / elapsed
    )


    print()
    print("=" * 80)
    print("SPEED TEST PASSED")
    print("=" * 80)

    print(
        f"Steps:                    "
        f"{BENCHMARK_STEPS}"
    )

    print(
        f"Elapsed:                  "
        f"{elapsed:.2f} s"
    )

    print(
        f"Seconds / step:           "
        f"{seconds_per_step:.3f}"
    )

    print(
        f"Steps / second:           "
        f"{steps_per_second:.4f}"
    )

    print(
        f"Tokens / second:          "
        f"{tokens_per_second:,.0f}"
    )

    print(
        f"Peak allocated VRAM:      "
        f"{peak_allocated:.2f} GB"
    )

    print(
        f"Peak reserved VRAM:       "
        f"{peak_reserved:.2f} GB"
    )

    print()
    print(
        f"Estimated 10k runtime:    "
        f"{seconds_per_step * 10000 / 3600:.2f} h"
    )


except torch.OutOfMemoryError:

    print()
    print("=" * 80)
    print("SPEED TEST FAILED - CUDA OOM")
    print("=" * 80)

    print()
    print(
        "16x2 does not fit safely with this "
        "configuration."
    )

    print(
        "Use the proven 8x4 configuration."
    )

    raise


finally:

    # The benchmark model exists only in memory.
    # Nothing here modifies the 130k model on Drive.

    print()
    print(
        "Official controlled-130k model "
        "remains unchanged."
    )

================================================================================
MAIA LITE - CORPUS V2 SAFE SPEED TEST
================================================================================
GPU:                     NVIDIA A100-SXM4-80GB
GPU memory:              79.3 GB
PyTorch:                 2.11.0+cu128
CUDA:                    12.8

--------------------------------------------------------------------------------
CORPUS
--------------------------------------------------------------------------------
Valid local Corpus V2 already exists.
No copy required.

Bytes:                   5,799,999,488
Tokens:                  2,899,999,744
Sequences:               2,832,031

Dataset ready.

--------------------------------------------------------------------------------
LOADING CONTROLLED 130K
--------------------------------------------------------------------------------

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters:               354,823,168
Gradient checkpointing:   ENABLED
KV cache:                 DISABLED

================================================================================
BENCHMARK CONFIGURATION
================================================================================
Micro batch:              16
Gradient accumulation:    2
Effective batch:          32
Context:                  1,024
Tokens / optimizer step:  32,768
Benchmark steps:          30
Gradient checkpointing:   ENABLED
Precision:                BF16

No official checkpoint will be written.

================================================================================
SPEED TEST PASSED
================================================================================
Steps:                    30
Elapsed:                  39.62 s
Seconds / step:           1.321
Steps / second:           0.7572
Tokens / second:          24,811
Peak allocated VRAM:      17.15 GB
Peak reserved VRAM:       19.48 GB

Estimated 10k runtime:    3.67 h

Official controlled-130k model remains unchanged.

In [ ]:
# ============================================================
# MAIA LITE - CORPUS V2 OFFICIAL PRETRAINING
#
# STAGE:
#   Equivalent 130k -> 140k
#
# FIRST RUN:
#   Load ONLY controlled-130k model weights.
#   Create NEW optimizer + scheduler + Trainer state.
#
# RESUME:
#   Automatically resume FULL latest Corpus V2 checkpoint.
#
# DATA:
#   Official unified Maia Corpus V2 binary
#   2,899,999,744 tokens
#
# TRAINING:
#   micro batch           = 16
#   gradient accumulation = 2
#   effective batch       = 32
#   context               = 1024
#   tokens / step         = 32,768
#   V2 steps              = 10,000
#
# ============================================================


# ============================================================
# 0. ENVIRONMENT
# ============================================================

import os

os.environ[
    "PYTORCH_CUDA_ALLOC_CONF"
] = "expandable_segments:True"


# ============================================================
# 1. IMPORTS
# ============================================================

import gc
import re
import shutil
import time
from pathlib import Path

import numpy as np
import torch

from torch.utils.data import Dataset

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    set_seed,
)


# ============================================================
# 2. CONSTANTS
# ============================================================

SEED = 42
set_seed(SEED)

SEQUENCE_LENGTH = 1024

EXPECTED_BYTES = 5_799_999_488
EXPECTED_TOKENS = 2_899_999_744
EXPECTED_SEQUENCES = 2_832_031

INITIAL_EQUIVALENT_STEP = 130_000
V2_TARGET_STEP = 10_000
FINAL_EQUIVALENT_STEP = 140_000

MICRO_BATCH = 16
GRAD_ACCUM = 2

EFFECTIVE_BATCH = (
    MICRO_BATCH
    * GRAD_ACCUM
)

TOKENS_PER_STEP = (
    EFFECTIVE_BATCH
    * SEQUENCE_LENGTH
)

LEARNING_RATE = 1e-5

WARMUP_STEPS = 500

SAVE_STEPS = 1000
LOGGING_STEPS = 100


# ============================================================
# 3. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = (
    PROJECT_DIR
    / "tokenizador"
)

BASE_MODEL_DIR = (
    PROJECT_DIR
    / "checkpoints_continuation_fixed"
    / "maia_lite_equivalent_130k"
)

DRIVE_CORPUS = (
    PROJECT_DIR
    / "corpus_v2"
    / "maia_corpus_v2.bin"
)

LOCAL_CORPUS = Path(
    "/content/maia_corpus_v2.bin"
)

OUTPUT_DIR = (
    PROJECT_DIR
    / "checkpoints_corpus_v2"
)

FINAL_MODEL_DIR = (
    OUTPUT_DIR
    / "maia_lite_equivalent_140k"
)


# ============================================================
# 4. CLEAN CUDA
# ============================================================

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()


# ============================================================
# 5. GPU
# ============================================================

print("=" * 80)
print("MAIA LITE - OFFICIAL CORPUS V2 PRETRAINING")
print("=" * 80)

if not torch.cuda.is_available():

    raise RuntimeError(
        "CUDA GPU not available."
    )


gpu_name = (
    torch.cuda.get_device_name(0)
)

gpu_memory = (
    torch.cuda.get_device_properties(0)
    .total_memory
    / 1024**3
)


print(
    f"GPU:                     "
    f"{gpu_name}"
)

print(
    f"GPU memory:              "
    f"{gpu_memory:.1f} GB"
)

print(
    f"PyTorch:                 "
    f"{torch.__version__}"
)

print(
    f"CUDA:                    "
    f"{torch.version.cuda}"
)


# ============================================================
# 6. ENSURE OFFICIAL CORPUS IS ON LOCAL SSD
# ============================================================

print()
print("-" * 80)
print("CORPUS V2")
print("-" * 80)


if not DRIVE_CORPUS.exists():

    raise RuntimeError(
        f"Official Corpus V2 binary missing:\n"
        f"{DRIVE_CORPUS}"
    )


def local_corpus_valid():

    return (
        LOCAL_CORPUS.exists()
        and
        LOCAL_CORPUS.stat().st_size
        == EXPECTED_BYTES
    )


if local_corpus_valid():

    print(
        "Valid Corpus V2 already present "
        "on local SSD."
    )

else:

    if LOCAL_CORPUS.exists():

        print(
            "Removing incomplete local corpus..."
        )

        LOCAL_CORPUS.unlink()


    print(
        "Copying official Corpus V2 "
        "from Drive to local SSD..."
    )

    copy_start = time.time()

    shutil.copyfile(
        DRIVE_CORPUS,
        LOCAL_CORPUS
    )

    copy_time = (
        time.time()
        - copy_start
    )

    print(
        f"Copy completed in "
        f"{copy_time:.2f} seconds."
    )


# ============================================================
# 7. CORPUS VALIDATION
# ============================================================

file_bytes = (
    LOCAL_CORPUS.stat().st_size
)

total_tokens = (
    file_bytes // 2
)

total_sequences = (
    total_tokens
    // SEQUENCE_LENGTH
)


print()
print(
    f"Bytes:                   "
    f"{file_bytes:,}"
)

print(
    f"Tokens:                  "
    f"{total_tokens:,}"
)

print(
    f"Sequences:               "
    f"{total_sequences:,}"
)


if file_bytes != EXPECTED_BYTES:
    raise RuntimeError(
        "Corpus byte count mismatch."
    )

if total_tokens != EXPECTED_TOKENS:
    raise RuntimeError(
        "Corpus token count mismatch."
    )

if total_sequences != EXPECTED_SEQUENCES:
    raise RuntimeError(
        "Corpus sequence count mismatch."
    )


# ============================================================
# 8. UNIFIED MEMMAP DATASET
# ============================================================

class MaiaUnifiedDataset(Dataset):

    def __init__(
        self,
        path,
        sequence_length
    ):

        self.sequence_length = (
            sequence_length
        )

        self.data = np.memmap(
            path,
            dtype=np.uint16,
            mode="r"
        )

        self.total_sequences = (
            len(self.data)
            // sequence_length
        )


    def __len__(self):

        return (
            self.total_sequences
        )


    def __getitem__(
        self,
        index
    ):

        start = (
            index
            * self.sequence_length
        )

        end = (
            start
            + self.sequence_length
        )

        input_ids = np.array(
            self.data[start:end],
            dtype=np.int64,
            copy=True
        )

        return {
            "input_ids": input_ids
        }


train_dataset = MaiaUnifiedDataset(
    LOCAL_CORPUS,
    SEQUENCE_LENGTH
)


# ============================================================
# 9. TOKENIZER
# ============================================================

tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)


if len(tokenizer) != 50_257:

    raise RuntimeError(
        "Unexpected tokenizer vocabulary."
    )


data_collator = (
    DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    )
)


# ============================================================
# 10. FIND LATEST FULL V2 CHECKPOINT
# ============================================================

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


def checkpoint_step(path):

    match = re.fullmatch(
        r"checkpoint-(\d+)",
        path.name
    )

    if not match:
        return -1

    return int(
        match.group(1)
    )


checkpoint_candidates = [

    path

    for path in OUTPUT_DIR.glob(
        "checkpoint-*"
    )

    if path.is_dir()
]


checkpoint_candidates.sort(
    key=checkpoint_step
)


latest_checkpoint = (
    checkpoint_candidates[-1]
    if checkpoint_candidates
    else None
)


# ============================================================
# 11. DETERMINE START MODE
# ============================================================

print()
print("-" * 80)
print("TRAINING MODE")
print("-" * 80)


if latest_checkpoint is None:

    print(
        "Mode:                    "
        "NEW CORPUS V2 TRAJECTORY"
    )

    print(
        "Base:                    "
        "controlled equivalent-130k"
    )

    print(
        "Optimizer:               NEW"
    )

    print(
        "Scheduler:               NEW"
    )

    print(
        "Trainer state:           NEW"
    )

    resume_checkpoint = None

    model_load_path = (
        BASE_MODEL_DIR
    )


else:

    step = checkpoint_step(
        latest_checkpoint
    )


    if step > V2_TARGET_STEP:

        raise RuntimeError(
            f"Unexpected checkpoint step: "
            f"{step:,}"
        )


    print(
        "Mode:                    "
        "FULL CHECKPOINT RESUME"
    )

    print(
        f"Checkpoint:              "
        f"{latest_checkpoint}"
    )

    print(
        f"V2 global step:          "
        f"{step:,}"
    )

    print(
        f"Equivalent Maia step:    "
        f"{INITIAL_EQUIVALENT_STEP + step:,}"
    )

    print(
        "Optimizer:               RESTORE"
    )

    print(
        "Scheduler:               RESTORE"
    )

    print(
        "Trainer state:           RESTORE"
    )

    resume_checkpoint = str(
        latest_checkpoint
    )

    model_load_path = (
        latest_checkpoint
    )


# ============================================================
# 12. LOAD MODEL
# ============================================================

print()
print("-" * 80)
print("LOADING MODEL")
print("-" * 80)


model = (
    GPT2LMHeadModel.from_pretrained(
        str(model_load_path),
        torch_dtype=torch.float32
    )
)


model.gradient_checkpointing_enable()

model.config.use_cache = False


parameter_count = sum(
    p.numel()
    for p in model.parameters()
)


print(
    f"Parameters:              "
    f"{parameter_count:,}"
)

print(
    "Gradient checkpointing: ENABLED"
)

print(
    "KV cache:               DISABLED"
)


# ============================================================
# 13. TRAINING ARGUMENTS
#
# IMPORTANT:
#
# max_steps remains 10,000 even on resume.
#
# Trainer interprets this as the TOTAL V2 trajectory target,
# not "10,000 additional steps".
#
# Example:
#
# checkpoint-6000 + max_steps=10000
# -> trains only remaining 4,000 steps.
# ============================================================

training_args = TrainingArguments(

    output_dir=str(
        OUTPUT_DIR
    ),

    max_steps=(
        V2_TARGET_STEP
    ),

    per_device_train_batch_size=(
        MICRO_BATCH
    ),

    gradient_accumulation_steps=(
        GRAD_ACCUM
    ),

    learning_rate=(
        LEARNING_RATE
    ),

    weight_decay=0.1,

    warmup_steps=(
        WARMUP_STEPS
    ),

    lr_scheduler_type="cosine",

    max_grad_norm=1.0,

    bf16=True,

    fp16=False,

    tf32=True,

    seed=SEED,

    data_seed=SEED,

    save_strategy="steps",

    save_steps=(
        SAVE_STEPS
    ),

    save_total_limit=None,

    logging_strategy="steps",

    logging_steps=(
        LOGGING_STEPS
    ),

    logging_first_step=True,

    eval_strategy="no",

    dataloader_num_workers=0,

    dataloader_pin_memory=True,

    report_to="none",

    remove_unused_columns=False,
)


# ============================================================
# 14. TRAINER
# ============================================================

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    data_collator=data_collator
)


# ============================================================
# 15. PRE-FLIGHT
# ============================================================

print()
print("=" * 80)
print("OFFICIAL PRE-FLIGHT")
print("=" * 80)


print(
    f"Corpus tokens:           "
    f"{total_tokens:,}"
)

print(
    f"Corpus sequences:        "
    f"{total_sequences:,}"
)

print()

print(
    f"Micro batch:             "
    f"{MICRO_BATCH}"
)

print(
    f"Gradient accumulation:   "
    f"{GRAD_ACCUM}"
)

print(
    f"Effective batch:         "
    f"{EFFECTIVE_BATCH}"
)

print(
    f"Tokens / step:           "
    f"{TOKENS_PER_STEP:,}"
)

print()

print(
    f"V2 target global step:   "
    f"{V2_TARGET_STEP:,}"
)

print(
    f"Equivalent target:       "
    f"{FINAL_EQUIVALENT_STEP:,}"
)

print(
    f"Total V2 tokens @ 10k:   "
    f"{V2_TARGET_STEP * TOKENS_PER_STEP:,}"
)

print()

print(
    f"Learning rate:           "
    f"{LEARNING_RATE:.2e}"
)

print(
    f"Warmup:                  "
    f"{WARMUP_STEPS:,}"
)

print(
    f"Save every:              "
    f"{SAVE_STEPS:,}"
)

print()

print(
    "Official pre-V2 baseline:"
)

print(
    "loss = 3.86998176"
)

print(
    "PPL  = 47.941512"
)

print()

print(
    "Training data:"
)

print(
    LOCAL_CORPUS
)

print()

print(
    "Validation Corpus V2 is NOT "
    "used during training."
)


# ============================================================
# 16. TRAIN
# ============================================================

print()
print("=" * 80)
print("STARTING OFFICIAL CORPUS V2 TRAINING")
print("=" * 80)

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

training_start = (
    time.time()
)


train_result = trainer.train(
    resume_from_checkpoint=(
        resume_checkpoint
    )
)


torch.cuda.synchronize()

training_elapsed = (
    time.time()
    - training_start
)


# ============================================================
# 17. VERIFY FINAL STEP
# ============================================================

if (
    trainer.state.global_step
    != V2_TARGET_STEP
):

    raise RuntimeError(
        f"Unexpected final global step: "
        f"{trainer.state.global_step:,}"
    )


# ============================================================
# 18. SAVE FINAL MODEL
# ============================================================

print()
print(
    "Saving equivalent-140k model..."
)


trainer.save_model(
    str(FINAL_MODEL_DIR)
)


tokenizer.save_pretrained(
    str(FINAL_MODEL_DIR)
)


# ============================================================
# 19. FINAL REPORT
# ============================================================

peak_allocated = (
    torch.cuda.max_memory_allocated()
    / 1024**3
)

peak_reserved = (
    torch.cuda.max_memory_reserved()
    / 1024**3
)


print()
print("=" * 80)
print("CORPUS V2 130K -> 140K COMPLETE")
print("=" * 80)


print(
    f"V2 global step:          "
    f"{trainer.state.global_step:,}"
)

print(
    f"Equivalent Maia step:    "
    f"{INITIAL_EQUIVALENT_STEP + trainer.state.global_step:,}"
)

print(
    f"V2 tokens processed:     "
    f"{trainer.state.global_step * TOKENS_PER_STEP:,}"
)

print(
    f"Runtime this session:    "
    f"{training_elapsed / 3600:.2f} h"
)

print(
    f"Peak allocated VRAM:     "
    f"{peak_allocated:.2f} GB"
)

print(
    f"Peak reserved VRAM:      "
    f"{peak_reserved:.2f} GB"
)

print()

print(
    "Final model:"
)

print(
    FINAL_MODEL_DIR
)

print()

print(
    "NEXT:"
)

print(
    "Evaluate equivalent-140k against the "
    "FIXED Validation Corpus V2."
)

================================================================================
MAIA LITE - OFFICIAL CORPUS V2 PRETRAINING
================================================================================
GPU:                     NVIDIA A100-SXM4-80GB
GPU memory:              79.3 GB
PyTorch:                 2.11.0+cu128
CUDA:                    12.8

--------------------------------------------------------------------------------
CORPUS V2
--------------------------------------------------------------------------------
Valid Corpus V2 already present on local SSD.

Bytes:                   5,799,999,488
Tokens:                  2,899,999,744
Sequences:               2,832,031

--------------------------------------------------------------------------------
TRAINING MODE
--------------------------------------------------------------------------------
Mode:                    NEW CORPUS V2 TRAJECTORY
Base:                    controlled equivalent-130k
Optimizer:               NEW
Scheduler:               NEW
Trainer state:           NEW

--------------------------------------------------------------------------------
LOADING MODEL
--------------------------------------------------------------------------------

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters:              354,823,168
Gradient checkpointing: ENABLED
KV cache:               DISABLED

================================================================================
OFFICIAL PRE-FLIGHT
================================================================================
Corpus tokens:           2,899,999,744
Corpus sequences:        2,832,031

Micro batch:             16
Gradient accumulation:   2
Effective batch:         32
Tokens / step:           32,768

V2 target global step:   10,000
Equivalent target:       140,000
Total V2 tokens @ 10k:   327,680,000

Learning rate:           1.00e-05
Warmup:                  500
Save every:              1,000

Official pre-V2 baseline:
loss = 3.86998176
PPL  = 47.941512

Training data:
/content/maia_corpus_v2.bin

Validation Corpus V2 is NOT used during training.

================================================================================
STARTING OFFICIAL CORPUS V2 TRAINING
================================================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saving equivalent-140k model...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

================================================================================
CORPUS V2 130K -> 140K COMPLETE
================================================================================
V2 global step:          10,000
Equivalent Maia step:    140,000
V2 tokens processed:     327,680,000
Runtime this session:    3.67 h
Peak allocated VRAM:     17.15 GB
Peak reserved VRAM:      19.48 GB

Final model:
/content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_corpus_v2/maia_lite_equivalent_140k

NEXT:
Evaluate equivalent-140k against the FIXED Validation Corpus V2.

In [ ]:
# ============================================================
# MAIA LITE - OFFICIAL 140K VALIDATION
#
# PURPOSE:
#   Evaluate Maia Lite equivalent-140k against the FIXED,
#   HELD-OUT Validation Corpus V2.
#
# IMPORTANT:
#   - NO training
#   - NO gradients
#   - NO optimizer
#   - NO weight updates
#   - Validation corpus is NEVER used for training
#
# COMPARISON:
#   Official controlled-130k baseline
#   vs.
#   Corpus V2 equivalent-140k
# ============================================================


# ============================================================
# 0. ENVIRONMENT
# ============================================================

import os

os.environ[
    "PYTORCH_CUDA_ALLOC_CONF"
] = "expandable_segments:True"


# ============================================================
# 1. IMPORTS
# ============================================================

import gc
import math
import time
from pathlib import Path

import numpy as np
import torch

from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
)


# ============================================================
# 2. PATHS
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Colab_LLMs/Maia_Lite"
)

TOKENIZER_DIR = (
    PROJECT_DIR
    / "tokenizador"
)

MODEL_DIR = (
    PROJECT_DIR
    / "checkpoints_corpus_v2"
    / "maia_lite_equivalent_140k"
)

VALIDATION_DIR = (
    PROJECT_DIR
    / "validation_corpus_v2"
    / "data"
)

# ============================================================
# 3. CONFIGURATION
# ============================================================

SEQUENCE_LENGTH = 1024

# Conservative validation batch.
# Increase only if desired; this does not affect the result.
BATCH_SIZE = 16

DEVICE = "cuda"

EXPECTED_TOTAL_RAW_TOKENS = 19_999_744


# ============================================================
# 4. OFFICIAL 130K BASELINE
# ============================================================

BASELINE_130K = {

    "fineweb_edu_en": {
        "loss": 3.89186480,
        "ppl": 49.002180,
        "raw_tokens": 8_999_936,
        "pred_tokens": 8_991_147,
    },

    "fineweb2_hq_pt": {
        "loss": 3.95476403,
        "ppl": 52.183379,
        "raw_tokens": 4_499_456,
        "pred_tokens": 4_495_062,
    },

    "fineweb2_hq_es": {
        "loss": 3.70961940,
        "ppl": 40.838260,
        "raw_tokens": 4_499_456,
        "pred_tokens": 4_495_062,
    },

    "opencoder": {
        "loss": 4.31978168,
        "ppl": 75.172215,
        "raw_tokens": 999_424,
        "pred_tokens": 998_448,
    },

    "finemath": {
        "loss": 3.45431165,
        "ppl": 31.636504,
        "raw_tokens": 599_040,
        "pred_tokens": 598_455,
    },

    "pes2o": {
        "loss": 3.72731316,
        "ppl": 41.567273,
        "raw_tokens": 402_432,
        "pred_tokens": 402_039,
    },

    "GLOBAL": {
        "loss": 3.86998176,
        "ppl": 47.941512,
        "raw_tokens": 19_999_744,
        "pred_tokens": 19_980_213,
    },
}


# ============================================================
# 5. VALIDATION SOURCES
#
# Expected raw token counts are frozen.
# ============================================================

SOURCES = {

    "fineweb_edu_en": {
        "label": "FineWeb-Edu EN",
        "expected_tokens": 8_999_936,
    },

    "fineweb2_hq_pt": {
        "label": "FineWeb2-HQ PT",
        "expected_tokens": 4_499_456,
    },

    "fineweb2_hq_es": {
        "label": "FineWeb2-HQ ES",
        "expected_tokens": 4_499_456,
    },

    "opencoder": {
        "label": "OpenCoder",
        "expected_tokens": 999_424,
    },

    "finemath": {
        "label": "FineMath",
        "expected_tokens": 599_040,
    },

    "pes2o": {
        "label": "peS2o",
        "expected_tokens": 402_432,
    },
}


# ============================================================
# 6. CLEAN GPU MEMORY
# ============================================================

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()


# ============================================================
# 7. SYSTEM INFORMATION
# ============================================================

print("=" * 90)
print("MAIA LITE - OFFICIAL EQUIVALENT-140K VALIDATION")
print("=" * 90)

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU not available.")

gpu_name = torch.cuda.get_device_name(0)

gpu_memory = (
    torch.cuda.get_device_properties(0).total_memory
    / 1024**3
)

print(f"GPU:                 {gpu_name}")
print(f"GPU memory:          {gpu_memory:.1f} GB")
print(f"PyTorch:             {torch.__version__}")
print(f"CUDA:                {torch.version.cuda}")

print()
print(f"Model:               {MODEL_DIR}")
print(f"Validation corpus:   {VALIDATION_DIR}")
print(f"Context:             {SEQUENCE_LENGTH}")
print(f"Batch size:          {BATCH_SIZE}")
print()


# ============================================================
# 8. BASIC PATH VALIDATION
# ============================================================

if not MODEL_DIR.exists():

    raise RuntimeError(
        f"140k model not found:\n{MODEL_DIR}"
    )


if not VALIDATION_DIR.exists():

    raise RuntimeError(
        f"Validation Corpus V2 not found:\n"
        f"{VALIDATION_DIR}"
    )


# ============================================================
# 9. FIND SOURCE SHARDS
#
# Supports:
#
# validation_corpus_v2/<source>/*.bin
#
# and also recursively searches below source directories.
# ============================================================

def find_source_shards(source_id):

    source_dir = (
        VALIDATION_DIR
        / source_id
    )

    if not source_dir.exists():

        raise RuntimeError(
            f"Validation source directory missing:\n"
            f"{source_dir}"
        )

    shards = sorted(
        source_dir.rglob("*.bin")
    )

    if not shards:

        raise RuntimeError(
            f"No .bin validation shards found for "
            f"{source_id}"
        )

    return shards


# ============================================================
# 10. AUDIT FROZEN VALIDATION CORPUS
# ============================================================

print("=" * 90)
print("VALIDATION CORPUS AUDIT")
print("=" * 90)

source_shards = {}

grand_total_tokens = 0

for source_id, config in SOURCES.items():

    shards = find_source_shards(
        source_id
    )

    source_shards[source_id] = shards

    source_bytes = sum(
        shard.stat().st_size
        for shard in shards
    )

    if source_bytes % 2 != 0:

        raise RuntimeError(
            f"Invalid uint16 byte count in "
            f"{source_id}"
        )

    source_tokens = (
        source_bytes // 2
    )

    expected_tokens = (
        config["expected_tokens"]
    )

    status = (
        "PASS"
        if source_tokens == expected_tokens
        else "FAIL"
    )

    print(
        f"{config['label']:<20} "
        f"shards={len(shards):>2}  "
        f"tokens={source_tokens:>10,}  "
        f"expected={expected_tokens:>10,}  "
        f"{status}"
    )

    if source_tokens != expected_tokens:

        raise RuntimeError(
            f"Frozen validation token count mismatch "
            f"for {source_id}."
        )

    grand_total_tokens += (
        source_tokens
    )


print("-" * 90)

print(
    f"{'TOTAL':<20} "
    f"tokens={grand_total_tokens:>10,}  "
    f"expected={EXPECTED_TOTAL_RAW_TOKENS:>10,}"
)


if grand_total_tokens != EXPECTED_TOTAL_RAW_TOKENS:

    raise RuntimeError(
        "Global Validation Corpus V2 token "
        "count mismatch."
    )


print()
print("Validation Corpus V2 audit: PASS")
print()


# ============================================================
# 11. TOKENIZER
# ============================================================

print("=" * 90)
print("LOADING TOKENIZER")
print("=" * 90)

tokenizer = (
    GPT2TokenizerFast.from_pretrained(
        str(TOKENIZER_DIR)
    )
)

print(
    f"Tokenizer vocabulary: "
    f"{len(tokenizer):,}"
)

print(
    f"EOS token:            "
    f"{tokenizer.eos_token_id}"
)

print(
    f"PAD token:            "
    f"{tokenizer.pad_token_id}"
)


if len(tokenizer) != 50_257:

    raise RuntimeError(
        "Unexpected tokenizer vocabulary."
    )


# ============================================================
# 12. LOAD 140K MODEL
# ============================================================

print()
print("=" * 90)
print("LOADING EQUIVALENT-140K MODEL")
print("=" * 90)

model = (
    GPT2LMHeadModel.from_pretrained(
        str(MODEL_DIR),
        torch_dtype=torch.bfloat16
    )
)

model.to(DEVICE)

model.eval()

model.config.use_cache = False


parameter_count = sum(
    p.numel()
    for p in model.parameters()
)


print(
    f"Parameters:           "
    f"{parameter_count:,}"
)

print(
    "Precision:            BF16"
)

print(
    "Mode:                 EVAL"
)

print(
    "Gradients:            DISABLED"
)


# ============================================================
# 13. SHARD READER
# ============================================================

def read_shard(path):

    data = np.memmap(
        path,
        dtype=np.uint16,
        mode="r"
    )

    if len(data) % SEQUENCE_LENGTH != 0:

        raise RuntimeError(
            f"Shard is not aligned to "
            f"{SEQUENCE_LENGTH} tokens:\n"
            f"{path}"
        )

    return data


# ============================================================
# 14. EVALUATE ONE SOURCE
#
# We calculate causal LM cross entropy manually.
#
# For each independent 1024-token sequence:
#
# input:
#   token[0 ... 1022]
#
# predicts:
#   token[1 ... 1023]
#
# Therefore:
#
# prediction tokens =
# raw tokens - number of sequences
#
# This reproduces the official baseline accounting.
# ============================================================

@torch.inference_mode()
def evaluate_source(
    source_id,
    config,
    shards
):

    total_nll = 0.0
    total_pred_tokens = 0
    total_raw_tokens = 0
    total_sequences = 0

    start_time = time.time()


    for shard_path in shards:

        data = read_shard(
            shard_path
        )

        num_sequences = (
            len(data)
            // SEQUENCE_LENGTH
        )

        total_raw_tokens += (
            len(data)
        )

        total_sequences += (
            num_sequences
        )


        for start_seq in range(
            0,
            num_sequences,
            BATCH_SIZE
        ):

            end_seq = min(
                start_seq + BATCH_SIZE,
                num_sequences
            )

            batch_size_actual = (
                end_seq - start_seq
            )

            token_start = (
                start_seq
                * SEQUENCE_LENGTH
            )

            token_end = (
                end_seq
                * SEQUENCE_LENGTH
            )

            batch_np = np.array(
                data[token_start:token_end],
                dtype=np.int64,
                copy=True
            )

            batch_np = batch_np.reshape(
                batch_size_actual,
                SEQUENCE_LENGTH
            )

            input_ids = torch.from_numpy(
                batch_np
            ).to(
                DEVICE,
                non_blocking=True
            )


            # --------------------------------------------
            # Forward pass
            # --------------------------------------------

            with torch.autocast(
                device_type="cuda",
                dtype=torch.bfloat16
            ):

                outputs = model(
                    input_ids=input_ids,
                    use_cache=False
                )

                logits = outputs.logits


            # --------------------------------------------
            # Causal shift
            # --------------------------------------------

            shift_logits = (
                logits[:, :-1, :]
                .contiguous()
                .float()
            )

            shift_labels = (
                input_ids[:, 1:]
                .contiguous()
            )


            # --------------------------------------------
            # Sum NLL over ALL prediction tokens
            # --------------------------------------------

            loss_sum = (
                torch.nn.functional.cross_entropy(
                    shift_logits.view(
                        -1,
                        shift_logits.size(-1)
                    ),
                    shift_labels.view(-1),
                    reduction="sum"
                )
            )


            batch_pred_tokens = (
                batch_size_actual
                * (SEQUENCE_LENGTH - 1)
            )


            total_nll += (
                loss_sum.item()
            )

            total_pred_tokens += (
                batch_pred_tokens
            )


            del (
                input_ids,
                outputs,
                logits,
                shift_logits,
                shift_labels,
                loss_sum
            )


    mean_loss = (
        total_nll
        / total_pred_tokens
    )

    perplexity = math.exp(
        mean_loss
    )

    elapsed = (
        time.time()
        - start_time
    )


    return {

        "source_id": source_id,

        "label": (
            config["label"]
        ),

        "raw_tokens": (
            total_raw_tokens
        ),

        "sequences": (
            total_sequences
        ),

        "pred_tokens": (
            total_pred_tokens
        ),

        "nll": (
            total_nll
        ),

        "loss": (
            mean_loss
        ),

        "ppl": (
            perplexity
        ),

        "elapsed": (
            elapsed
        ),
    }


# ============================================================
# 15. RUN OFFICIAL VALIDATION
# ============================================================

print()
print("=" * 90)
print("STARTING OFFICIAL 140K VALIDATION")
print("=" * 90)

print(
    "NO gradients | NO optimizer | NO weight updates"
)

print()


results = {}

global_nll = 0.0
global_pred_tokens = 0
global_raw_tokens = 0
global_sequences = 0

validation_start = time.time()


for source_id, config in SOURCES.items():

    print(
        f"Evaluating "
        f"{config['label']}..."
    )

    result = evaluate_source(
        source_id,
        config,
        source_shards[source_id]
    )

    results[source_id] = result

    global_nll += (
        result["nll"]
    )

    global_pred_tokens += (
        result["pred_tokens"]
    )

    global_raw_tokens += (
        result["raw_tokens"]
    )

    global_sequences += (
        result["sequences"]
    )


    print(
        f"  raw tokens:   "
        f"{result['raw_tokens']:,}"
    )

    print(
        f"  sequences:    "
        f"{result['sequences']:,}"
    )

    print(
        f"  pred. tokens: "
        f"{result['pred_tokens']:,}"
    )

    print(
        f"  loss:         "
        f"{result['loss']:.8f}"
    )

    print(
        f"  PPL:          "
        f"{result['ppl']:.6f}"
    )

    print(
        f"  time:         "
        f"{result['elapsed']:.2f} s"
    )

    print()


validation_elapsed = (
    time.time()
    - validation_start
)


# ============================================================
# 16. GLOBAL RESULT
# ============================================================

global_loss = (
    global_nll
    / global_pred_tokens
)

global_ppl = math.exp(
    global_loss
)


results["GLOBAL"] = {

    "label": "GLOBAL",

    "raw_tokens": (
        global_raw_tokens
    ),

    "sequences": (
        global_sequences
    ),

    "pred_tokens": (
        global_pred_tokens
    ),

    "nll": (
        global_nll
    ),

    "loss": (
        global_loss
    ),

    "ppl": (
        global_ppl
    ),
}


# ============================================================
# 17. ACCOUNTING CHECK
# ============================================================

expected_pred_tokens = (
    global_raw_tokens
    - global_sequences
)


if (
    global_pred_tokens
    != expected_pred_tokens
):

    raise RuntimeError(
        "Prediction-token accounting mismatch."
    )


if (
    global_pred_tokens
    != BASELINE_130K["GLOBAL"]["pred_tokens"]
):

    raise RuntimeError(
        "Validation prediction-token count differs "
        "from official 130k baseline."
    )


# ============================================================
# 18. 130K -> 140K COMPARISON
# ============================================================

print()
print("=" * 108)
print("OFFICIAL COMPARISON: CONTROLLED 130K -> CORPUS V2 140K")
print("=" * 108)

header = (
    f"{'Domain':<20}"
    f"{'130k Loss':>12}"
    f"{'140k Loss':>12}"
    f"{'Δ Loss':>12}"
    f"{'130k PPL':>13}"
    f"{'140k PPL':>13}"
    f"{'Δ PPL %':>12}"
)

print(header)
print("-" * 108)


ordered_sources = list(
    SOURCES.keys()
) + ["GLOBAL"]


for source_id in ordered_sources:

    old = (
        BASELINE_130K[source_id]
    )

    new = (
        results[source_id]
    )

    delta_loss = (
        new["loss"]
        - old["loss"]
    )

    delta_ppl_percent = (
        (
            new["ppl"]
            / old["ppl"]
        )
        - 1.0
    ) * 100.0


    label = (
        "GLOBAL"
        if source_id == "GLOBAL"
        else SOURCES[source_id]["label"]
    )


    print(
        f"{label:<20}"
        f"{old['loss']:>12.6f}"
        f"{new['loss']:>12.6f}"
        f"{delta_loss:>+12.6f}"
        f"{old['ppl']:>13.3f}"
        f"{new['ppl']:>13.3f}"
        f"{delta_ppl_percent:>+11.2f}%"
    )


# ============================================================
# 19. FINAL OFFICIAL 140K RESULT
# ============================================================

print()
print("=" * 90)
print("OFFICIAL EQUIVALENT-140K VALIDATION RESULT")
print("=" * 90)

for source_id in SOURCES:

    result = (
        results[source_id]
    )

    print(
        f"{result['label']:<20} "
        f"loss={result['loss']:.8f}  "
        f"PPL={result['ppl']:.6f}  "
        f"pred.tokens={result['pred_tokens']:,}"
    )


print("-" * 90)

print(
    f"{'GLOBAL':<20} "
    f"loss={global_loss:.8f}  "
    f"PPL={global_ppl:.6f}  "
    f"pred.tokens={global_pred_tokens:,}"
)

print()

print(
    f"Raw validation tokens: "
    f"{global_raw_tokens:,}"
)

print(
    f"Validation sequences:  "
    f"{global_sequences:,}"
)

print(
    f"Evaluation time:       "
    f"{validation_elapsed / 60:.2f} min"
)

print()

print(
    "Model weights were NOT modified."
)

print(
    "Validation Corpus V2 remains frozen."
)

==========================================================================================
MAIA LITE - OFFICIAL EQUIVALENT-140K VALIDATION
==========================================================================================
GPU:                 NVIDIA A100-SXM4-80GB
GPU memory:          79.3 GB
PyTorch:             2.11.0+cu128
CUDA:                12.8

Model:               /content/drive/MyDrive/Colab_LLMs/Maia_Lite/checkpoints_corpus_v2/maia_lite_equivalent_140k
Validation corpus:   /content/drive/MyDrive/Colab_LLMs/Maia_Lite/validation_corpus_v2/data
Context:             1024
Batch size:          16

==========================================================================================
VALIDATION CORPUS AUDIT
==========================================================================================
FineWeb-Edu EN       shards= 3  tokens= 8,999,936  expected= 8,999,936  PASS
FineWeb2-HQ PT       shards= 2  tokens= 4,499,456  expected= 4,499,456  PASS
FineWeb2-HQ ES       shards= 2  tokens= 4,499,456  expected= 4,499,456  PASS
OpenCoder            shards= 1  tokens=   999,424  expected=   999,424  PASS
FineMath             shards= 1  tokens=   599,040  expected=   599,040  PASS
peS2o                shards= 1  tokens=   402,432  expected=   402,432  PASS
------------------------------------------------------------------------------------------
TOTAL                tokens=19,999,744  expected=19,999,744

Validation Corpus V2 audit: PASS

==========================================================================================
LOADING TOKENIZER
==========================================================================================
Tokenizer vocabulary: 50,257
EOS token:            2
PAD token:            1

==========================================================================================
LOADING EQUIVALENT-140K MODEL
==========================================================================================

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

Parameters:           354,823,168
Precision:            BF16
Mode:                 EVAL
Gradients:            DISABLED

==========================================================================================
STARTING OFFICIAL 140K VALIDATION
==========================================================================================
NO gradients | NO optimizer | NO weight updates

Evaluating FineWeb-Edu EN...
  raw tokens:   8,999,936
  sequences:    8,789
  pred. tokens: 8,991,147
  loss:         3.62804279
  PPL:          37.639077
  time:         101.13 s

Evaluating FineWeb2-HQ PT...
  raw tokens:   4,499,456
  sequences:    4,394
  pred. tokens: 4,495,062
  loss:         3.68948963
  PPL:          40.024414
  time:         50.58 s

Evaluating FineWeb2-HQ ES...
  raw tokens:   4,499,456
  sequences:    4,394
  pred. tokens: 4,495,062
  loss:         3.48526698
  PPL:          32.631138
  time:         50.60 s

Evaluating OpenCoder...
  raw tokens:   999,424
  sequences:    976
  pred. tokens: 998,448
  loss:         3.97726072
  PPL:          53.370636
  time:         11.60 s

Evaluating FineMath...
  raw tokens:   599,040
  sequences:    585
  pred. tokens: 598,455
  loss:         3.07310480
  PPL:          21.608890
  time:         7.16 s

Evaluating peS2o...
  raw tokens:   402,432
  sequences:    393
  pred. tokens: 402,039
  loss:         3.49977354
  PPL:          33.107953
  time:         4.99 s


============================================================================================================
OFFICIAL COMPARISON: CONTROLLED 130K -> CORPUS V2 140K
============================================================================================================
Domain                 130k Loss   140k Loss      Δ Loss     130k PPL     140k PPL     Δ PPL %
------------------------------------------------------------------------------------------------------------
FineWeb-Edu EN          3.891865    3.628043   -0.263822       49.002       37.639     -23.19%
FineWeb2-HQ PT          3.954764    3.689490   -0.265274       52.183       40.024     -23.30%
FineWeb2-HQ ES          3.709619    3.485267   -0.224352       40.838       32.631     -20.10%
OpenCoder               4.319782    3.977261   -0.342521       75.172       53.371     -29.00%
FineMath                3.454312    3.073105   -0.381207       31.637       21.609     -31.70%
peS2o                   3.727313    3.499774   -0.227540       41.567       33.108     -20.35%
GLOBAL                  3.869982    3.607994   -0.261988       47.942       36.892     -23.05%

==========================================================================================
OFFICIAL EQUIVALENT-140K VALIDATION RESULT
==========================================================================================
FineWeb-Edu EN       loss=3.62804279  PPL=37.639077  pred.tokens=8,991,147
FineWeb2-HQ PT       loss=3.68948963  PPL=40.024414  pred.tokens=4,495,062
FineWeb2-HQ ES       loss=3.48526698  PPL=32.631138  pred.tokens=4,495,062
OpenCoder            loss=3.97726072  PPL=53.370636  pred.tokens=998,448
FineMath             loss=3.07310480  PPL=21.608890  pred.tokens=598,455
peS2o                loss=3.49977354  PPL=33.107953  pred.tokens=402,039
------------------------------------------------------------------------------------------
GLOBAL               loss=3.60799408  PPL=36.891976  pred.tokens=19,980,213

Raw validation tokens: 19,999,744
Validation sequences:  19,531
Evaluation time:       3.77 min

Model weights were NOT modified.
Validation Corpus V2 remains frozen.